from fastapi import APIRouter, UploadFile, File
from routers.upload_router import upload_anfir_seguro
from routers.product_catalog_router import router as product_catalog_router
from routers.auth_router import router as auth_router
from routers.access_diagnostics_router import router as access_diagnostics_router
from routers.governanca_usuarios_router import router as governanca_usuarios_router
from routers.crm_visao_router import router as crm_visao_router
from routers.propostas_pedidos_router import router as propostas_pedidos_router
from routers.propostas_consulta_router import router as propostas_consulta_router
from routers.propostas_primeira_pagina_router import router as propostas_primeira_pagina_router
from routers.pedidos_operacionais_router import router as pedidos_operacionais_router
from routers.pedidos_documentos_oficiais_router import router as pedidos_documentos_oficiais_router
from routers.documentos_comerciais_listagem_router import router as documentos_comerciais_listagem_router
from routers.carrier_operacional_router import router as carrier_operacional_router
from routers.pedidos_ciclo_router import router as pedidos_ciclo_router
from routers.catalogo_comercial_router import router as catalogo_comercial_router
from routers.modelos_proposta_storage_router import router as modelos_proposta_storage_router
from routers.modelos_proposta_importacao_router import router as modelos_proposta_importacao_router
from routers.modelos_proposta_homologacao_router import router as modelos_proposta_homologacao_router
from routers.modelos_proposta_reconciliacao_router import router as modelos_proposta_reconciliacao_router
from routers.propostas_documentos_oficiais_router import router as propostas_documentos_oficiais_router
from routers.validacao_operacional_documentos_router import router as validacao_operacional_documentos_router
from routers.testes_campo_master_router import router as testes_campo_master_router
from routers.ia_comercial_cti_router import router as ia_comercial_cti_router
from routers.ia_comercial_acoes_router import router as ia_comercial_acoes_router
from routers.ia_comercial_artefatos_router import router as ia_comercial_artefatos_router
from routers.crm_app_clientes_edicao_router import router as crm_app_clientes_edicao_router
from routers.crm_app_proposta_envio_router import router as crm_app_proposta_envio_router
from routers.crm_app_oportunidade_propostas_envio_router import router as crm_app_oportunidade_propostas_envio_router
from routers.crm_app_oportunidades_teste_router import router as crm_app_oportunidades_teste_router

router = APIRouter()
router.include_router(product_catalog_router)
router.include_router(auth_router)
router.include_router(access_diagnostics_router)
router.include_router(governanca_usuarios_router)
router.include_router(crm_visao_router)
router.include_router(propostas_pedidos_router)
router.include_router(propostas_consulta_router)
router.include_router(propostas_primeira_pagina_router)
router.include_router(pedidos_operacionais_router)
router.include_router(pedidos_documentos_oficiais_router)
router.include_router(documentos_comerciais_listagem_router)
router.include_router(carrier_operacional_router)
router.include_router(pedidos_ciclo_router)
router.include_router(catalogo_comercial_router)
router.include_router(modelos_proposta_storage_router)
router.include_router(modelos_proposta_importacao_router)
router.include_router(modelos_proposta_homologacao_router)
router.include_router(modelos_proposta_reconciliacao_router)
router.include_router(propostas_documentos_oficiais_router)
router.include_router(validacao_operacional_documentos_router)
router.include_router(testes_campo_master_router)
router.include_router(ia_comercial_cti_router)
router.include_router(ia_comercial_acoes_router)
router.include_router(ia_comercial_artefatos_router)
router.include_router(crm_app_clientes_edicao_router)
router.include_router(crm_app_proposta_envio_router)
router.include_router(crm_app_oportunidade_propostas_envio_router)
router.include_router(crm_app_oportunidades_teste_router)


@router.post("/upload")
async def upload(file: UploadFile = File(...)):
    return await upload_anfir_seguro(file)