"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import JornadaComercialNav from "@/components/crm/JornadaComercialNav"
import { API_URL } from "@/lib/api"

type LinhaNucleo = { oportunidade_id:string; titulo:string; cliente_nome:string; responsavel_id?:string|null; competencia:string; etapa:string; valor:number; valor_ponderado:number; probabilidade:number; encerrada:boolean }
function mesAtual(){return new Date().toISOString().slice(0,7)}

export default function ForecastPage(){
 const[linhas,setLinhas]=useState<LinhaNucleo[]>([]),[loading,setLoading]=useState(true),[erro,setErro]=useState(""),[competencia,setCompetencia]=useState(mesAtual()),[etapa,setEtapa]=useState("TODAS")
 useEffect(()=>{void(async()=>{try{const resposta=await fetch(`${API_URL}/crm/nucleo-comercial`,{cache:"no-store"});const payload=await resposta.json().catch(()=>[]);if(!resposta.ok)throw new Error(payload?.detail||"Não foi possível carregar o núcleo comercial.");setLinhas(Array.isArray(payload)?payload:[])}catch(falha){setErro(falha instanceof Error?falha.message:"Não foi possível carregar o Forecast.")}finally{setLoading(false)}})()},[])
 const abertas=useMemo(()=>linhas.filter(item=>!item.encerrada),[linhas])
 const competencias=useMemo(()=>Array.from(new Set(abertas.map(item=>item.competencia).filter(Boolean))).sort(),[abertas])
 const etapas=useMemo(()=>Array.from(new Set(abertas.map(item=>item.etapa))).sort(),[abertas])
 const filtradas=useMemo(()=>abertas.filter(item=>(!competencia||item.competencia===competencia)&&(etapa==="TODAS"||item.etapa===etapa)),[abertas,competencia,etapa])
 const pipelineTotal=filtradas.reduce((t,i)=>t+Number(i.valor||0),0),pipelinePonderado=filtradas.reduce((t,i)=>t+Number(i.valor_ponderado||0),0)
 const cobertura=pipelineTotal>0?(pipelinePonderado/pipelineTotal)*100:0
 return <main className="flex min-h-screen bg-[#020817]"><Sidebar/><section className="flex-1"><Topbar/><div className="space-y-6 p-8">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400">Projeção futura</p><h1 className="mt-2 text-4xl font-bold text-white">CRM • Forecast Comercial</h1><p className="mt-2 text-gray-400">Transforma as oportunidades abertas em projeção por competência. Não é uma segunda lista de negócios e não altera status, valor ou probabilidade.</p></div><Link href="/relatorios" className="rounded-xl border border-cyan-700 px-5 py-3 text-center font-semibold text-cyan-300">Abrir realizado e relatórios</Link></div>
  <JornadaComercialNav/>
  {erro&&<div className="rounded-xl border border-red-500 p-4 text-red-300">{erro}</div>}
  <section className="rounded-2xl border border-[#13203f] bg-[#071226] p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end"><div><h2 className="font-semibold text-white">Cenário projetado</h2><p className="mt-1 text-sm text-gray-400">Selecione a competência e, quando necessário, isole uma etapa do pipeline.</p></div><label className="text-sm text-gray-300">Competência<select value={competencia} onChange={e=>setCompetencia(e.target.value)} className="ml-3 rounded-lg border border-[#24466f] bg-[#020817] px-3 py-2 text-white"><option value="">Todas</option>{competencias.map(item=><option key={item} value={item}>{item}</option>)}</select></label><label className="text-sm text-gray-300">Etapa<select value={etapa} onChange={e=>setEtapa(e.target.value)} className="ml-3 rounded-lg border border-[#24466f] bg-[#020817] px-3 py-2 text-white"><option value="TODAS">Todas</option>{etapas.map(item=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select></label></div></section>
  <section className="grid grid-cols-1 gap-4 md:grid-cols-4"><Kpi titulo="Pipeline da competência" valor={`R$ ${pipelineTotal.toLocaleString("pt-BR")}`} href="#composicao-forecast"/><Kpi titulo="Forecast ponderado" valor={`R$ ${pipelinePonderado.toLocaleString("pt-BR")}`} destaque="verde" href="#composicao-forecast"/><Kpi titulo="Cobertura ponderada" valor={`${cobertura.toFixed(1)}%`} href="#composicao-forecast"/><Kpi titulo="Oportunidades consideradas" valor={filtradas.length} href="#composicao-forecast"/></section>
  <div id="composicao-forecast" className="scroll-mt-24 overflow-hidden rounded-2xl border border-[#13203f] bg-[#091a33]"><div className="border-b border-[#13203f] p-6"><h2 className="text-xl font-semibold text-white">Composição do Forecast</h2><p className="mt-1 text-sm text-slate-400">Cada linha explica quais oportunidades formam a projeção selecionada.</p></div>{loading?<div className="p-10 text-gray-400">Carregando...</div>:filtradas.length===0?<div className="p-10 text-gray-400">Nenhuma oportunidade aberta na competência e etapa selecionadas.</div>:<div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-[#13203f]"><Th>Cliente</Th><Th>Oportunidade</Th><Th>Competência</Th><Th>Etapa</Th><Th>Pipeline</Th><Th>Probabilidade</Th><Th>Forecast</Th><Th>Ação</Th></tr></thead><tbody>{filtradas.map(item=><tr key={item.oportunidade_id} className="border-b border-[#13203f]"><Td>{item.cliente_nome}</Td><Td>{item.titulo}</Td><Td>{item.competencia||"Não definida"}</Td><td className="p-4 text-cyan-400">{item.etapa.replaceAll("_"," ")}</td><td className="p-4 text-cyan-400">R$ {Number(item.valor||0).toLocaleString("pt-BR")}</td><Td>{Math.round(Number(item.probabilidade||0)*100)}%</Td><td className="p-4 text-green-400">R$ {Number(item.valor_ponderado||0).toLocaleString("pt-BR")}</td><td className="p-4"><Link href={`/oportunidades/${item.oportunidade_id}`} className="rounded-lg border border-cyan-700 px-3 py-2 text-xs font-semibold text-cyan-300">Abrir negócio</Link></td></tr>)}</tbody></table></div>}</div>
 </div></section></main>
}
function Kpi({titulo,valor,destaque="ciano",href}:{titulo:string;valor:string|number;destaque?:"ciano"|"verde";href?:string}){const body=<><p className="text-sm text-gray-400">{titulo}</p><h2 className={`mt-2 text-3xl font-bold ${destaque==="verde"?"text-green-400":"text-cyan-400"}`}>{valor}</h2>{href&&<p className="mt-2 text-[11px] text-cyan-400">Clique para ver a composição</p>}</>;return href?<Link href={href} className="rounded-2xl border border-[#13203f] bg-[#091a33] p-6 transition hover:border-cyan-500/70 hover:bg-[#0b1d38]">{body}</Link>:<div className="rounded-2xl border border-[#13203f] bg-[#091a33] p-6">{body}</div>}
function Th({children}:{children:React.ReactNode}){return <th className="p-4 text-left text-gray-400">{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td className="p-4 text-white">{children}</td>}