"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import JornadaComercialNav from "@/components/crm/JornadaComercialNav"
import { useAuth } from "@/core/auth/AuthContext"
import { useOperationalI18n } from "@/core/i18n/operational"
import { pertenceAoEscopoDoUsuario, possuiVisaoConsolidada } from "@/core/rbac/commercial-scope"
import { API_URL } from "@/lib/api"
import { listarUsuarios } from "@/modules/usuarios/services/usuarios.service"
import type { UsuarioCTI as UsuarioGovernanca } from "@/modules/usuarios/types/usuario.types"

type LinhaNucleo = { oportunidade_id:string; titulo:string; cliente_nome:string; responsavel_id?:string|null; competencia:string; etapa:string; valor:number; valor_ponderado:number; probabilidade:number; encerrada:boolean }
type Locale = "pt-BR" | "en" | "es"

const textos = {
 "pt-BR": {
  eyebrow:"Projeção futura", title:"CRM • Forecast Comercial", subtitle:"Transforma as oportunidades abertas em projeção por competência. Não é uma segunda lista de negócios e não altera status, valor ou probabilidade.", report:"Abrir realizado e relatórios", scope:"Escopo comercial", session:"Sessão", consolidated:"Consolidado geral", selectedOwner:"Responsável selecionado", only:"Somente", authenticated:"Usuário autenticado", loadCore:"Não foi possível carregar o núcleo comercial.", loadForecast:"Não foi possível carregar o Forecast.", unidentified:"Responsável não identificado", scenario:"Cenário projetado", scenarioHelp:"Selecione a competência, a etapa e, no acesso de gestão, o responsável comercial.", competence:"Competência", all:"Todas", stage:"Etapa", owner:"Responsável", pipeline:"Pipeline da competência", weighted:"Forecast ponderado", coverage:"Cobertura ponderada", opportunities:"Oportunidades consideradas", composition:"Composição do Forecast", compositionHelp:"Cada linha explica quais oportunidades formam a projeção selecionada e a quem cada negócio está atribuído.", loading:"Carregando...", empty:"Nenhuma oportunidade aberta no recorte selecionado.", account:"Cliente", opportunity:"Oportunidade", noOwner:"Sem responsável", undefined:"Não definida", probability:"Probabilidade", forecast:"Forecast", action:"Ação", openDeal:"Abrir negócio", click:"Clique para ver a composição"
 },
 en: {
  eyebrow:"Forward projection", title:"CRM • Sales Forecast", subtitle:"Turns open opportunities into a period-based projection. It is not a second deal list and does not change stage, value or win probability.", report:"Open actuals and reports", scope:"Sales scope", session:"Session", consolidated:"Consolidated view", selectedOwner:"Selected sales owner", only:"Only", authenticated:"Authenticated user", loadCore:"We couldn't load the commercial core.", loadForecast:"We couldn't load the sales forecast.", unidentified:"Unidentified sales owner", scenario:"Projected scenario", scenarioHelp:"Select the forecast period, stage and, for management access, the sales owner.", competence:"Forecast period", all:"All", stage:"Stage", owner:"Sales owner", pipeline:"Pipeline for the period", weighted:"Weighted forecast", coverage:"Weighted coverage", opportunities:"Opportunities included", composition:"Forecast composition", compositionHelp:"Each row shows which opportunities make up the selected projection and who owns each deal.", loading:"Loading...", empty:"No open opportunities in the selected view.", account:"Account", opportunity:"Opportunity", noOwner:"No sales owner", undefined:"Not defined", probability:"Win probability", forecast:"Forecast", action:"Action", openDeal:"Open deal", click:"Click to view composition"
 },
 es: {
  eyebrow:"Proyección futura", title:"CRM • Forecast Comercial", subtitle:"Convierte las oportunidades abiertas en una proyección por período. No es una segunda lista de negocios y no modifica etapa, valor ni probabilidad de cierre.", report:"Abrir realizado e informes", scope:"Alcance comercial", session:"Sesión", consolidated:"Vista consolidada", selectedOwner:"Responsable seleccionado", only:"Solo", authenticated:"Usuario autenticado", loadCore:"No fue posible cargar el núcleo comercial.", loadForecast:"No fue posible cargar el forecast comercial.", unidentified:"Responsable no identificado", scenario:"Escenario proyectado", scenarioHelp:"Seleccione el período previsto, la etapa y, para accesos de gestión, el responsable comercial.", competence:"Período previsto", all:"Todas", stage:"Etapa", owner:"Responsable", pipeline:"Pipeline del período", weighted:"Forecast ponderado", coverage:"Cobertura ponderada", opportunities:"Oportunidades consideradas", composition:"Composición del Forecast", compositionHelp:"Cada fila explica qué oportunidades forman la proyección seleccionada y a quién está asignado cada negocio.", loading:"Cargando...", empty:"No hay oportunidades abiertas en el recorte seleccionado.", account:"Cliente", opportunity:"Oportunidad", noOwner:"Sin responsable", undefined:"No definida", probability:"Probabilidad", forecast:"Forecast", action:"Acción", openDeal:"Abrir negocio", click:"Haga clic para ver la composición"
 }
} satisfies Record<Locale, Record<string,string>>

function mesAtual(){return new Date().toISOString().slice(0,7)}
function etapaLegivel(valor:string, locale:Locale){
 const chave=valor.toUpperCase()
 const mapas:Record<Locale,Record<string,string>>={
  "pt-BR":{QUALIFICACAO:"Qualificação",PROPOSTA:"Proposta",NEGOCIACAO:"Negociação",FECHAMENTO:"Fechamento",GANHO:"Ganho",PERDIDO:"Perdido"},
  en:{QUALIFICACAO:"Qualification",PROPOSTA:"Proposal",NEGOCIACAO:"Negotiation",FECHAMENTO:"Closing",GANHO:"Won",PERDIDO:"Lost"},
  es:{QUALIFICACAO:"Calificación",PROPOSTA:"Propuesta",NEGOCIACAO:"Negociación",FECHAMENTO:"Cierre",GANHO:"Ganado",PERDIDO:"Perdido"},
 }
 return mapas[locale][chave]||valor.replaceAll("_"," ")
}

export default function ForecastPage(){
 const { usuario } = useAuth()
 const { locale, formatCurrency, formatNumber } = useOperationalI18n()
 const idioma=locale as Locale
 const t=textos[idioma]||textos["pt-BR"]
 const[linhas,setLinhas]=useState<LinhaNucleo[]>([]),[usuarios,setUsuarios]=useState<UsuarioGovernanca[]>([]),[loading,setLoading]=useState(true),[erro,setErro]=useState(""),[competencia,setCompetencia]=useState(mesAtual()),[etapa,setEtapa]=useState("TODAS"),[responsavel,setResponsavel]=useState("TODOS")
 const gestaoComercial=possuiVisaoConsolidada(usuario)
 useEffect(()=>{void(async()=>{try{const resposta=await fetch(`${API_URL}/crm/nucleo-comercial`,{cache:"no-store"});const payload=await resposta.json().catch(()=>[]);if(!resposta.ok)throw new Error(payload?.detail||t.loadCore);setLinhas(Array.isArray(payload)?payload:[])}catch(falha){setErro(falha instanceof Error?falha.message:t.loadForecast)}finally{setLoading(false)}})()},[t.loadCore,t.loadForecast])
 useEffect(()=>{if(!gestaoComercial)return;void listarUsuarios().then(setUsuarios).catch(()=>setUsuarios([]))},[gestaoComercial])
 const nomesResponsaveis=useMemo(()=>{const mapa=new Map<string,string>();usuarios.forEach(item=>mapa.set(item.id,item.nome));if(usuario?.id)mapa.set(usuario.id,usuario.nome);return mapa},[usuarios,usuario])
 const abertas=useMemo(()=>linhas.filter(item=>!item.encerrada&&pertenceAoEscopoDoUsuario(item.responsavel_id,usuario)),[linhas,usuario])
 const competencias=useMemo(()=>Array.from(new Set(abertas.map(item=>item.competencia).filter(Boolean))).sort(),[abertas])
 const etapas=useMemo(()=>Array.from(new Set(abertas.map(item=>item.etapa))).sort(),[abertas])
 const responsaveisDisponiveis=useMemo(()=>Array.from(new Set(abertas.map(item=>item.responsavel_id).filter((id):id is string=>Boolean(id)))).map(id=>({id,nome:nomesResponsaveis.get(id)||t.unidentified})).sort((a,b)=>a.nome.localeCompare(b.nome,idioma)),[abertas,nomesResponsaveis,t.unidentified,idioma])
 const filtradas=useMemo(()=>abertas.filter(item=>(!competencia||item.competencia===competencia)&&(etapa==="TODAS"||item.etapa===etapa)&&(responsavel==="TODOS"||item.responsavel_id===responsavel)),[abertas,competencia,etapa,responsavel])
 const pipelineTotal=filtradas.reduce((total,item)=>total+Number(item.valor||0),0),pipelinePonderado=filtradas.reduce((total,item)=>total+Number(item.valor_ponderado||0),0)
 const cobertura=pipelineTotal>0?(pipelinePonderado/pipelineTotal)*100:0
 const escopo=gestaoComercial?(responsavel==="TODOS"?t.consolidated:(nomesResponsaveis.get(responsavel)||t.selectedOwner)):`${t.only} ${usuario?.nome||t.authenticated}`
 return <main className="flex min-h-screen bg-[#020817]"><Sidebar/><section className="min-w-0 flex-1"><Topbar/><div className="space-y-6 p-4 sm:p-6 lg:p-8">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-bold text-white sm:text-4xl">{t.title}</h1><p className="mt-2 text-gray-400">{t.subtitle}</p><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full border border-cyan-700/70 bg-cyan-950/30 px-3 py-1.5 text-cyan-200">{t.scope}: {escopo}</span><span className="rounded-full border border-slate-700 bg-slate-900/70 px-3 py-1.5 text-slate-300">{t.session}: {usuario?.nome||t.authenticated}</span></div></div><Link href="/relatorios" className="rounded-xl border border-cyan-700 px-5 py-3 text-center font-semibold text-cyan-300">{t.report}</Link></div>
  <JornadaComercialNav/>
  {erro&&<div className="rounded-xl border border-red-500 p-4 text-red-300">{erro}</div>}
  <section className="rounded-2xl border border-[#13203f] bg-[#071226] p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-end"><div><h2 className="font-semibold text-white">{t.scenario}</h2><p className="mt-1 text-sm text-gray-400">{t.scenarioHelp}</p></div><label className="flex flex-col gap-1 text-sm text-gray-300">{t.competence}<select value={competencia} onChange={e=>setCompetencia(e.target.value)} className="rounded-lg border border-[#24466f] bg-[#020817] px-3 py-2 text-white"><option value="">{t.all}</option>{competencias.map(item=><option key={item} value={item}>{item}</option>)}</select></label><label className="flex flex-col gap-1 text-sm text-gray-300">{t.stage}<select value={etapa} onChange={e=>setEtapa(e.target.value)} className="rounded-lg border border-[#24466f] bg-[#020817] px-3 py-2 text-white"><option value="TODAS">{t.all}</option>{etapas.map(item=><option key={item} value={item}>{etapaLegivel(item,idioma)}</option>)}</select></label>{gestaoComercial&&<label className="flex min-w-56 flex-col gap-1 text-sm text-gray-300">{t.owner}<select value={responsavel} onChange={e=>setResponsavel(e.target.value)} className="rounded-lg border border-[#24466f] bg-[#020817] px-3 py-2 text-white"><option value="TODOS">{t.consolidated}</option>{responsaveisDisponiveis.map(item=><option key={item.id} value={item.id}>{item.nome}</option>)}</select></label>}</div></section>
  <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi titulo={t.pipeline} valor={formatCurrency(pipelineTotal)} href="#composicao-forecast" click={t.click}/><Kpi titulo={t.weighted} valor={formatCurrency(pipelinePonderado)} destaque="verde" href="#composicao-forecast" click={t.click}/><Kpi titulo={t.coverage} valor={`${formatNumber(cobertura,{maximumFractionDigits:1})}%`} href="#composicao-forecast" click={t.click}/><Kpi titulo={t.opportunities} valor={formatNumber(filtradas.length)} href="#composicao-forecast" click={t.click}/></section>
  <div id="composicao-forecast" className="scroll-mt-24 overflow-hidden rounded-2xl border border-[#13203f] bg-[#091a33]"><div className="border-b border-[#13203f] p-5 sm:p-6"><h2 className="text-xl font-semibold text-white">{t.composition}</h2><p className="mt-1 text-sm text-slate-400">{t.compositionHelp}</p></div>{loading?<div className="p-10 text-gray-400">{t.loading}</div>:filtradas.length===0?<div className="p-10 text-gray-400">{t.empty}</div>:<div className="overflow-x-auto"><table className="min-w-[980px] w-full"><thead><tr className="border-b border-[#13203f]"><Th>{t.account}</Th><Th>{t.opportunity}</Th><Th>{t.owner}</Th><Th>{t.competence}</Th><Th>{t.stage}</Th><Th>Pipeline</Th><Th>{t.probability}</Th><Th>{t.forecast}</Th><Th>{t.action}</Th></tr></thead><tbody>{filtradas.map(item=><tr key={item.oportunidade_id} className="border-b border-[#13203f]"><Td>{item.cliente_nome}</Td><Td>{item.titulo}</Td><Td>{item.responsavel_id?(nomesResponsaveis.get(item.responsavel_id)||usuario?.nome||t.unidentified):t.noOwner}</Td><Td>{item.competencia||t.undefined}</Td><td className="p-4 text-cyan-400">{etapaLegivel(item.etapa,idioma)}</td><td className="p-4 text-cyan-400">{formatCurrency(Number(item.valor||0))}</td><Td>{formatNumber(Math.round(Number(item.probabilidade||0)*100))}%</Td><td className="p-4 text-green-400">{formatCurrency(Number(item.valor_ponderado||0))}</td><td className="p-4"><Link href={`/oportunidades/${item.oportunidade_id}`} className="rounded-lg border border-cyan-700 px-3 py-2 text-xs font-semibold text-cyan-300">{t.openDeal}</Link></td></tr>)}</tbody></table></div>}</div>
 </div></section></main>
}
function Kpi({titulo,valor,destaque="ciano",href,click}:{titulo:string;valor:string|number;destaque?:"ciano"|"verde";href?:string;click:string}){const body=<><p className="text-sm text-gray-400">{titulo}</p><h2 className={`mt-2 text-2xl font-bold sm:text-3xl ${destaque==="verde"?"text-green-400":"text-cyan-400"}`}>{valor}</h2>{href&&<p className="mt-2 text-[11px] text-cyan-400">{click}</p>}</>;return href?<Link href={href} className="rounded-2xl border border-[#13203f] bg-[#091a33] p-5 transition hover:border-cyan-500/70 hover:bg-[#0b1d38] sm:p-6">{body}</Link>:<div className="rounded-2xl border border-[#13203f] bg-[#091a33] p-5 sm:p-6">{body}</div>}
function Th({children}:{children:React.ReactNode}){return <th className="p-4 text-left text-gray-400">{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td className="p-4 text-white">{children}</td>}
