"use client"

import { useEffect, useState } from "react"
import { useI18n } from "@/core/i18n"

type Segmento = { codigo:string; segmento:string; mercado:number; carrier:number; carrier_percentual_observado:number; tk:number; nacional:number; usado_concorrente:number; usado_carrier:number; sem_contato:number; nao_classificado:number; nao_participou:number; q1:number; q2:number; q2_vs_q1_percentual:number|null }
type Mensal = { mes:string; competencia:string; trailer:number; diesel_truck:number; direct_drive:number; total:number }
type Territorio = { ddd:string; mercado:number; trailer:number; diesel_truck:number; direct_drive:number; responsavel:string }
type Prioridade = { prioridade:string; cliente:string; score_transparente:number; mercado:number; nao_carrier:number; carrier:number; nao_participou:number; sem_contato:number; tk:number; nacional:number; preco:number; relacionamento:number; gap_tecnico:number; leitura_sugerida:string; criterio_score:string }
type Implementadora = { implementadora:string; mercado_elegivel:number; trailer:number; diesel_truck:number; direct_drive:number; leitura:string }
type Tema = { tema:string; ocorrencias:number; clientes_unicos:number; observacoes_unicas:number; leitura_comercial:string; uso_no_cti:string }
type Payload = {
 metadata:{nome_contrato:string;competencia:string;natureza:string;market_share_oficial:boolean}
 inteligencia_viena:{mercado_elegivel:number;carrier_observada:number;carrier_presenca_percentual:number;sem_contato:number;nao_participamos_proposta:number;dados_status_a_qualificar:number;q1:number;q2:number;q2_vs_q1_percentual:number|null;segmentos:Segmento[];mensal:Mensal[];territorio:Territorio[];leituras_estrategicas:string[]}
 oportunidades_prioritarias:Prioridade[]
 implementadoras_mercado:Implementadora[]
 inteligencia_observacoes:{temas:Tema[];registros_elegiveis:number;com_observacao_util:number;cobertura_observacoes_percentual:number;sem_observacao_util:number;regra:string}
}

type Tab = "viena"|"prioridades"|"implementadoras"|"observacoes"
const text={
 "pt-BR":{title:"ANFIR 2026 · Leitura estratégica Viena",subtitle:"Contrato funcional da auditoria Carrier/JOV. Esta leitura é fixa em 2026 e não obedece aos filtros históricos do topo.",viena:"Inteligência Viena",priorities:"Oportunidades Prioritárias",bodyBuilders:"Implementadoras Mercado",notes:"Inteligência Observações",loading:"Carregando leitura ANFIR 2026...",error:"Não foi possível carregar a leitura ANFIR 2026.",market:"Mercado elegível Viena",carrier:"Presença Carrier observada",coverage:"Sem contato",noParticipation:"Não participamos da proposta",qualify:"Status a qualificar",trend:"Q2 vs Q1",segment:"Segmento",marketCol:"Mercado",carrierCol:"Carrier",tk:"TK",national:"Nacional",noContact:"Sem contato",notParticipated:"Não participou",month:"Mês",trailer:"Trailer",diesel:"Diesel Truck",direct:"Direct Drive",total:"Total",territory:"Território por DDD",owner:"Responsável",readings:"Leituras estratégicas — base atual",priority:"Prioridade",account:"Cliente",score:"Score transparente",nonCarrier:"Não Carrier",price:"Preço",relationship:"Relacionamento",technical:"Gap técnico",reading:"Leitura sugerida",builder:"Implementadora normalizada",observations:"Ocorrências",clients:"Clientes únicos",uniqueNotes:"Observações únicas",commercialReading:"Leitura comercial",use:"Uso no CTI",useful:"Com observação útil",coverageNotes:"Cobertura de observações",without:"Sem observação útil",rule:"Regra",observed:"Indicador observado na ANFIR; não é market share contábil definitivo."},
 en:{title:"ANFIR 2026 · Viena strategic reading",subtitle:"Functional contract from the Carrier/JOV audit. This reading is fixed to 2026 and does not follow historical top filters.",viena:"Viena Intelligence",priorities:"Priority Accounts",bodyBuilders:"Body Builder Market",notes:"Notes Intelligence",loading:"Loading ANFIR 2026 reading...",error:"ANFIR 2026 reading could not be loaded.",market:"Eligible Viena market",carrier:"Observed Carrier presence",coverage:"No contact",noParticipation:"We did not participate",qualify:"Status to qualify",trend:"Q2 vs Q1",segment:"Segment",marketCol:"Market",carrierCol:"Carrier",tk:"TK",national:"Domestic",noContact:"No contact",notParticipated:"No participation",month:"Month",trailer:"Trailer",diesel:"Diesel Truck",direct:"Direct Drive",total:"Total",territory:"Territory by area code",owner:"Owner",readings:"Strategic readings — current base",priority:"Priority",account:"Account",score:"Transparent score",nonCarrier:"Non Carrier",price:"Price",relationship:"Relationship",technical:"Technical gap",reading:"Suggested reading",builder:"Normalized body builder",observations:"Occurrences",clients:"Unique accounts",uniqueNotes:"Unique notes",commercialReading:"Commercial reading",use:"Use in CTI",useful:"With useful note",coverageNotes:"Notes coverage",without:"Without useful note",rule:"Rule",observed:"Observed ANFIR indicator; not reconciled accounting market share."},
 es:{title:"ANFIR 2026 · Lectura estratégica Viena",subtitle:"Contrato funcional de la auditoría Carrier/JOV. Esta lectura está fija en 2026 y no sigue los filtros históricos superiores.",viena:"Inteligencia Viena",priorities:"Cuentas Prioritarias",bodyBuilders:"Mercado de Carroceros",notes:"Inteligencia de Observaciones",loading:"Cargando lectura ANFIR 2026...",error:"No fue posible cargar la lectura ANFIR 2026.",market:"Mercado elegible Viena",carrier:"Presencia Carrier observada",coverage:"Sin contacto",noParticipation:"No participamos",qualify:"Status a calificar",trend:"Q2 vs Q1",segment:"Segmento",marketCol:"Mercado",carrierCol:"Carrier",tk:"TK",national:"Nacional",noContact:"Sin contacto",notParticipated:"Sin participación",month:"Mes",trailer:"Trailer",diesel:"Diesel Truck",direct:"Direct Drive",total:"Total",territory:"Territorio por DDD",owner:"Responsable",readings:"Lecturas estratégicas — base actual",priority:"Prioridad",account:"Cliente",score:"Score transparente",nonCarrier:"No Carrier",price:"Precio",relationship:"Relación",technical:"Gap técnico",reading:"Lectura sugerida",builder:"Carrocero normalizado",observations:"Ocurrencias",clients:"Clientes únicos",uniqueNotes:"Observaciones únicas",commercialReading:"Lectura comercial",use:"Uso en CTI",useful:"Con observación útil",coverageNotes:"Cobertura de observaciones",without:"Sin observación útil",rule:"Regla",observed:"Indicador observado en ANFIR; no es market share contable reconciliado."}
} as const

export default function AnfirWorkbookPanel(){
 const{locale,formatNumber}=useI18n();const tx=text[locale]
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false),[tab,setTab]=useState<Tab>("viena")
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;setLoading(true);setError(false);fetch("/api/cti/analytics/anfir-workbook-2026",{cache:"no-store"}).then(async response=>{if(!response.ok)throw new Error(String(response.status));return response.json() as Promise<Payload>}).then(payload=>{if(active)setData(payload)}).catch(()=>{if(active)setError(true)}).finally(()=>{if(active)setLoading(false)})});return()=>{active=false}},[])
 if(loading)return <section className="rounded-3xl border border-[#17304d] bg-[#071427] p-6 text-sm text-slate-400">{tx.loading}</section>
 if(error||!data)return <section className="rounded-3xl border border-amber-700/60 bg-amber-950/10 p-6 text-sm text-amber-200">{tx.error}</section>
 const v=data.inteligencia_viena,o=data.inteligencia_observacoes
 return <section className="rounded-3xl border border-cyan-500/30 bg-[#061126] p-5 sm:p-6">
  <header><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-400">{data.metadata.competencia} · Carrier/JOV</p><h2 className="mt-2 text-2xl font-bold">{tx.title}</h2><p className="mt-2 max-w-5xl text-sm text-slate-400">{tx.subtitle}</p><p className="mt-2 text-xs text-cyan-300">{tx.observed}</p></header>
  <div className="mt-5 flex flex-wrap gap-2">{([["viena",tx.viena],["prioridades",tx.priorities],["implementadoras",tx.bodyBuilders],["observacoes",tx.notes]] as [Tab,string][]).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-xl px-4 py-2 text-sm font-semibold transition ${tab===key?"bg-cyan-400 text-slate-950":"border border-[#29456f] bg-[#09182e] text-slate-300 hover:border-cyan-500"}`}>{label}</button>)}</div>
  {tab==="viena"&&<div className="mt-6 space-y-6">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric title={tx.market} value={formatNumber(v.mercado_elegivel)}/><Metric title={tx.carrier} value={`${formatNumber(v.carrier_observada)} · ${v.carrier_presenca_percentual.toFixed(1)}%`}/><Metric title={tx.coverage} value={formatNumber(v.sem_contato)}/><Metric title={tx.noParticipation} value={formatNumber(v.nao_participamos_proposta)}/><Metric title={tx.qualify} value={formatNumber(v.dados_status_a_qualificar)}/><Metric title={tx.trend} value={`${v.q2_vs_q1_percentual&&v.q2_vs_q1_percentual>0?"+":""}${Number(v.q2_vs_q1_percentual||0).toFixed(1)}%`} detail={`${formatNumber(v.q2)} × ${formatNumber(v.q1)}`}/></div>
    <Table headers={[tx.segment,tx.marketCol,tx.carrierCol,"Carrier %",tx.tk,tx.national,tx.noContact,tx.notParticipated,tx.trend]} rows={v.segmentos.map(s=>[s.segmento,formatNumber(s.mercado),formatNumber(s.carrier),`${s.carrier_percentual_observado.toFixed(1)}%`,formatNumber(s.tk),formatNumber(s.nacional),formatNumber(s.sem_contato),formatNumber(s.nao_participou),s.q2_vs_q1_percentual===null?"—":`${s.q2_vs_q1_percentual>0?"+":""}${s.q2_vs_q1_percentual.toFixed(1)}%`])}/>
    <div className="grid gap-5 xl:grid-cols-2"><Card title="Evolução mensal 2026"><Table compact headers={[tx.month,tx.trailer,tx.diesel,tx.direct,tx.total]} rows={v.mensal.map(m=>[m.mes,formatNumber(m.trailer),formatNumber(m.diesel_truck),formatNumber(m.direct_drive),formatNumber(m.total)])}/></Card><Card title={tx.territory}><Table compact headers={["DDD",tx.marketCol,tx.trailer,tx.diesel,tx.direct,tx.owner]} rows={v.territorio.map(d=>[d.ddd,formatNumber(d.mercado),formatNumber(d.trailer),formatNumber(d.diesel_truck),formatNumber(d.direct_drive),d.responsavel])}/></Card></div>
    <Card title={tx.readings}><ol className="space-y-3">{v.leituras_estrategicas.map((r,i)=><li key={r} className="flex gap-3 text-sm leading-6 text-slate-300"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-cyan-500/15 text-xs font-bold text-cyan-300">{i+1}</span><span>{r}</span></li>)}</ol></Card>
  </div>}
  {tab==="prioridades"&&<div className="mt-6"><Table headers={[tx.priority,tx.account,tx.score,tx.marketCol,tx.nonCarrier,tx.carrierCol,tx.notParticipated,tx.noContact,tx.tk,tx.national,tx.price,tx.relationship,tx.technical,tx.reading]} rows={data.oportunidades_prioritarias.map(r=>[r.prioridade,r.cliente,formatNumber(r.score_transparente),formatNumber(r.mercado),formatNumber(r.nao_carrier),formatNumber(r.carrier),formatNumber(r.nao_participou),formatNumber(r.sem_contato),formatNumber(r.tk),formatNumber(r.nacional),formatNumber(r.preco),formatNumber(r.relacionamento),formatNumber(r.gap_tecnico),r.leitura_sugerida])}/></div>}
  {tab==="implementadoras"&&<div className="mt-6"><Table headers={[tx.builder,tx.marketCol,tx.trailer,tx.diesel,tx.direct,tx.reading]} rows={data.implementadoras_mercado.map(r=>[r.implementadora,formatNumber(r.mercado_elegivel),formatNumber(r.trailer),formatNumber(r.diesel_truck),formatNumber(r.direct_drive),r.leitura])}/></div>}
  {tab==="observacoes"&&<div className="mt-6 space-y-5"><div className="grid gap-3 sm:grid-cols-4"><Metric title={tx.market} value={formatNumber(o.registros_elegiveis)}/><Metric title={tx.useful} value={formatNumber(o.com_observacao_util)}/><Metric title={tx.coverageNotes} value={`${o.cobertura_observacoes_percentual.toFixed(1)}%`}/><Metric title={tx.without} value={formatNumber(o.sem_observacao_util)}/></div><Table headers={["Tema",tx.observations,tx.clients,tx.uniqueNotes,tx.commercialReading,tx.use]} rows={o.temas.map(r=>[r.tema,formatNumber(r.ocorrencias),formatNumber(r.clientes_unicos),formatNumber(r.observacoes_unicas),r.leitura_comercial,r.uso_no_cti])}/><div className="rounded-xl border border-cyan-900 bg-cyan-950/10 p-4 text-xs text-cyan-100/80"><strong>{tx.rule}:</strong> {o.regra}</div></div>}
 </section>
}
function Metric({title,value,detail}:{title:string;value:string;detail?:string}){return <div className="rounded-xl border border-[#193354] bg-[#08162d] p-4"><p className="text-[11px] uppercase tracking-wide text-slate-500">{title}</p><p className="mt-2 text-xl font-bold text-cyan-300">{value}</p>{detail&&<p className="mt-1 text-xs text-slate-500">{detail}</p>}</div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-[#17304d] bg-[#071427] p-4"><h3 className="mb-3 font-semibold">{title}</h3>{children}</div>}
function Table({headers,rows,compact=false}:{headers:string[];rows:string[][];compact?:boolean}){return <div className="overflow-x-auto rounded-2xl border border-[#17304d] bg-[#071427]"><table className={`w-full text-left ${compact?"min-w-[650px]":"min-w-[950px]"}`}><thead className="bg-[#091a33] text-[11px] uppercase text-slate-400"><tr>{headers.map(h=><th key={h} className="px-3 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={`${i}-${row[0]}`} className="border-t border-[#142944] text-sm text-slate-300">{row.map((cell,j)=><td key={`${j}-${cell}`} className={`px-3 py-3 ${j===0?"font-medium text-white":""}`}>{cell}</td>)}</tr>)}</tbody></table></div>}
