"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import { useOperationalContext } from "@/context/OperationalContext"
import { getClientes, getClientesCanonicosSeguros, getCrmResumoEmpresasSeguro, type ClienteCanonicoSeguro, type CrmResumoEmpresaSeguro, type EmpresaResumoItem } from "@/services/modulos-api"
import { useClosureI18n } from "@/core/i18n/closure"

type Oportunidade={id?:string;cliente_id?:string;titulo?:string;status?:string;valor_estimado?:number}
type Proposta={id?:string;cliente_id?:string;numero?:string;status?:string;valor?:number}
type Pedido={id?:string;cliente_id?:string;numero?:string;status?:string;status_ciclo?:string;valor?:number}
type Atividade={id?:string;cliente_id?:string;titulo?:string;status?:string;data?:string;data_atividade?:string}
const ENCERRADOS=new Set(["GANHO","PERDIDO","CANCELADO","ENCERRADO"])
const CRM_VAZIO:CrmResumoEmpresaSeguro={oportunidades:[],propostas:[],pedidos:[],atividades:[]}
function normalizar(valor?:string){return String(valor||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim()}
function digitos(valor?:string){return String(valor||"").replace(/\D/g,"")}
function cnpj(valor?:string){const d=digitos(valor);return d.length===14?d.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,"$1.$2.$3/$4-$5"):String(valor||"")}

export default function EmpresasSegurasPage(){
 const {contextoAtual,queryString}=useOperationalContext();const {locale,tc,formatCurrency,formatNumber}=useClosureI18n()
 const abrirEmpresa=locale==="en"?"Open company":locale==="es"?"Abrir empresa":"Abrir empresa"
 const[historico,setHistorico]=useState<EmpresaResumoItem[]>([]),[clientes,setClientes]=useState<ClienteCanonicoSeguro[]>([]),[crm,setCrm]=useState<CrmResumoEmpresaSeguro>(CRM_VAZIO),[busca,setBusca]=useState(""),[selecionada,setSelecionada]=useState<string|null>(null),[loadingHistorico,setLoadingHistorico]=useState(true),[loadingClientes,setLoadingClientes]=useState(true),[loadingCrm,setLoadingCrm]=useState(true),[avisos,setAvisos]=useState<string[]>([])
 useEffect(()=>{let ativo=true;setAvisos([]);setLoadingHistorico(true);setLoadingClientes(true);setLoadingCrm(true)
  void getClientes(queryString).then(h=>{if(ativo)setHistorico(Array.isArray(h)?h:[])}).catch(()=>{if(ativo)setAvisos(v=>[...v,"O histórico de mercado demorou mais que o esperado; os clientes cadastrados continuam disponíveis."])}).finally(()=>{if(ativo)setLoadingHistorico(false)})
  void getClientesCanonicosSeguros().then(c=>{if(ativo)setClientes(Array.isArray(c)?c:[])}).catch(()=>{if(ativo)setAvisos(v=>[...v,"A base cadastral de clientes não respondeu. Atualize a tela para tentar novamente."])}).finally(()=>{if(ativo)setLoadingClientes(false)})
  void getCrmResumoEmpresasSeguro().then(r=>{if(ativo)setCrm(r||CRM_VAZIO)}).catch(()=>{if(ativo)setAvisos(v=>[...v,"O resumo comercial está temporariamente indisponível; a relação cadastral permanece acessível."])}).finally(()=>{if(ativo)setLoadingCrm(false)})
  return()=>{ativo=false}},[queryString])
 const clientePorId=useMemo(()=>new Map(clientes.map(i=>[String(i.id),i])),[clientes]),clientePorNome=useMemo(()=>new Map(clientes.map(i=>[normalizar(i.nome),i])),[clientes])
 const oportunidades=(crm.oportunidades||[]) as Oportunidade[],propostas=(crm.propostas||[]) as Proposta[],pedidos=(crm.pedidos||[]) as Pedido[],atividades=(crm.atividades||[]) as Atividade[]
 const mapaCrm=useMemo(()=>{const m=new Map<string,{oportunidades:Oportunidade[];propostas:Proposta[];pedidos:Pedido[];atividades:Atividade[]}>();const obter=(id?:string)=>{const c=id?clientePorId.get(String(id)):undefined;if(!c)return null;const k=normalizar(c.nome);if(!m.has(k))m.set(k,{oportunidades:[],propostas:[],pedidos:[],atividades:[]});return m.get(k)!};oportunidades.forEach(i=>obter(i.cliente_id)?.oportunidades.push(i));propostas.forEach(i=>obter(i.cliente_id)?.propostas.push(i));pedidos.forEach(i=>obter(i.cliente_id)?.pedidos.push(i));atividades.forEach(i=>obter(i.cliente_id)?.atividades.push(i));return m},[atividades,clientePorId,oportunidades,pedidos,propostas])
 const baseEmpresas=useMemo(()=>{const porNome=new Map<string,EmpresaResumoItem>();historico.forEach(i=>porNome.set(normalizar(i.nome),i));clientes.forEach(c=>{const k=normalizar(c.nome);if(!porNome.has(k))porNome.set(k,{nome:c.nome,quantidade_registros:0,valor_total:0,status:{},estados:c.estado?[c.estado]:[],municipios:c.cidade?[c.cidade]:[],linhas:[],chassis:[],placas:[],implementadoras:[],equipamentos:[],quantidade_chassis:0,quantidade_placas:0})});return [...porNome.values()]},[clientes,historico])
 const lista=useMemo(()=>baseEmpresas.filter(item=>{const c=clientePorNome.get(normalizar(item.nome)),txt=normalizar([item.nome,c?.razao_social,c?.nome_fantasia,c?.cnpj,...(item.chassis||[]),...(item.placas||[]),...(item.implementadoras||[])].filter(Boolean).join(" ")),termo=normalizar(busca),num=digitos(busca);return txt.includes(termo)||(!!num&&digitos(c?.cnpj).includes(num))}),[baseEmpresas,busca,clientePorNome])
 const abertas=oportunidades.filter(i=>!ENCERRADOS.has(String(i.status||"").toUpperCase())),pipeline=abertas.reduce((s,i)=>s+Number(i.valor_estimado||0),0),selecionadaHistorico=selecionada?baseEmpresas.find(i=>normalizar(i.nome)===normalizar(selecionada)):undefined,selecionadaCliente=selecionada?clientePorNome.get(normalizar(selecionada)):undefined,selecionadaCrm=selecionada?mapaCrm.get(normalizar(selecionada)):undefined
 const accountLabel=locale==="en"?"Account":"Cliente",loading=loadingHistorico||loadingClientes||loadingCrm
 return <main className="flex min-h-screen bg-[#020817] text-white"><Sidebar/><section className="min-w-0 flex-1"><Topbar/><div className="space-y-6 p-4 sm:p-6 lg:p-8">
  <header><p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400">{tc("companies.eyebrow")}</p><h1 className="mt-2 text-3xl font-bold">{tc("companies.title")}</h1><p className="mt-2 text-sm text-slate-400">{tc("companies.subtitle")}</p><p className="mt-2 text-sm text-cyan-300">{tc("companies.context")}: {contextoAtual.label}</p></header>
  {avisos.map((a,i)=><div key={`${a}-${i}`} className="rounded-xl border border-amber-600/60 bg-amber-950/20 p-4 text-amber-200">{a}</div>)}
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi titulo={tc("companies.historical")} valor={loadingHistorico?"...":formatNumber(historico.length)}/><Kpi titulo={tc("companies.activeDeals")} valor={loadingCrm?"...":formatNumber(abertas.length)}/><Kpi titulo={tc("companies.pipeline")} valor={loadingCrm?"...":formatCurrency(pipeline)}/><Kpi titulo={tc("companies.registered")} valor={loadingClientes?"...":formatNumber(clientes.length)}/></section>
  <section className="rounded-2xl border border-[#13203f] bg-[#091a33] p-5 sm:p-6"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-bold">{tc("companies.marketOwnership")}</h2><p className="mt-1 text-sm text-slate-400">{tc("companies.marketOwnershipSub")}</p></div><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder={tc("companies.search")} className="rounded-xl border border-[#13203f] bg-[#071028] px-4 py-3 text-white"/></div>
   {loading&&lista.length===0?<p className="mt-8 text-slate-400">{tc("common.loading")}</p>:<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-b border-[#13203f] text-slate-400"><th className="p-3">{tc("companies.company")}</th><th className="p-3">{tc("companies.realized")}</th><th className="p-3">{tc("companies.inProgress")}</th><th className="p-3">{tc("common.action")}</th></tr></thead><tbody>{lista.map(item=>{const cliente=clientePorNome.get(normalizar(item.nome)),atual=mapaCrm.get(normalizar(item.nome)),ops=atual?.oportunidades.filter(o=>!ENCERRADOS.has(String(o.status||"").toUpperCase()))||[],valor=ops.reduce((s,o)=>s+Number(o.valor_estimado||0),0);return <tr key={item.nome} className="border-b border-[#13203f] hover:bg-cyan-500/5"><td className="p-3"><strong>{item.nome}</strong>{cliente?.cnpj&&<div className="mt-1 text-xs text-cyan-300">CNPJ {cnpj(cliente.cnpj)}</div>}<div className="text-xs text-slate-500">{cliente?.cidade||""}{cliente?.estado?` / ${cliente.estado}`:""}</div></td><td className="p-3"><div className="text-cyan-200">{tc("companies.records",{count:item.quantidade_registros})}</div><div className="text-xs text-slate-500">{formatCurrency(Number(item.valor_total||0))}</div></td><td className="p-3"><div>{tc("companies.deals",{count:ops.length})}</div><div className="text-xs text-emerald-300">{formatCurrency(valor)}</div></td><td className="p-3"><button onClick={()=>setSelecionada(item.nome)} className="rounded-lg border border-cyan-700 px-3 py-2 text-xs font-semibold text-cyan-300">{abrirEmpresa}</button></td></tr>})}</tbody></table></div>}
  </section>
  {selecionada&&<section className="rounded-2xl border border-cyan-800 bg-[#071427] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.16em] text-cyan-400">{tc("companies.selected")}</p><h2 className="mt-1 text-2xl font-bold">{selecionada}</h2>{selecionadaCliente?.cnpj&&<p className="mt-1 text-sm text-cyan-300">CNPJ {cnpj(selecionadaCliente.cnpj)}</p>}</div><button onClick={()=>setSelecionada(null)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs">{tc("common.close")}</button></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Kpi titulo={tc("companies.history")} valor={tc("companies.records",{count:selecionadaHistorico?.quantidade_registros||0})}/><Kpi titulo={tc("companies.authorizedOpportunities")} valor={formatNumber(selecionadaCrm?.oportunidades.length||0)}/><Kpi titulo={tc("companies.authorizedProposals")} valor={formatNumber(selecionadaCrm?.propostas.length||0)}/><Kpi titulo={tc("companies.ordersActivities")} valor={`${formatNumber(selecionadaCrm?.pedidos.length||0)} / ${formatNumber(selecionadaCrm?.atividades.length||0)}`}/></div><div className="mt-5 flex flex-wrap gap-3">{(selecionadaCrm?.oportunidades||[]).map(op=>op.id&&<Link key={op.id} href={`/oportunidades/${op.id}`} className="rounded-lg border border-cyan-800 px-3 py-2 text-xs text-cyan-200">{op.titulo||`${tc("companies.openOpportunity")} · ${accountLabel}`}</Link>)}</div></section>}
 </div></section></main>
}
function Kpi({titulo,valor}:{titulo:string;valor:string}){return <div className="rounded-2xl border border-[#16325c] bg-[#091a33] p-4"><p className="text-sm text-slate-400">{titulo}</p><p className="mt-2 text-xl font-bold text-cyan-300">{valor}</p></div>}
