"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import AnfirCompetitiveDecision from "@/components/AnfirCompetitiveDecision"
import { useOperationalContext } from "@/context/OperationalContext"
import { useStrategicI18n } from "@/core/i18n/strategic"
import { getEquipamento, type EquipamentoEstrategico, type RankingItem } from "@/services/modulos-api"

export default function EquipamentoPage({slug,fallbackTitulo}:{slug:string;fallbackTitulo:string}){
 const {contextoAtual,periodo,dataInicio,dataFim,queryString}=useOperationalContext(); const {t,formatNumber,formatCurrency,formatDate}=useStrategicI18n()
 const[dados,setDados]=useState<EquipamentoEstrategico|null>(null),[loading,setLoading]=useState(true),[erro,setErro]=useState("")
 useEffect(()=>{let ativo=true;queueMicrotask(()=>{if(!ativo)return;setLoading(true);setErro("");getEquipamento(slug,queryString).then(r=>{if(ativo)setDados(r)}).catch(()=>{if(ativo)setErro(t("equipment.loadError"))}).finally(()=>{if(ativo)setLoading(false)})});return()=>{ativo=false}},[slug,queryString,t])
 const periodoExibido=periodo==="TODO_HISTORICO"?t("common.allHistory"):periodo==="PERSONALIZADO"?`${dataInicio?formatDate(new Date(`${dataInicio}T12:00:00`)):"?"} — ${dataFim?formatDate(new Date(`${dataFim}T12:00:00`)):"?"}`:periodo.replaceAll("_"," ").toLowerCase(), tituloFamilia=dados?.nome??fallbackTitulo
 const numero=(v:number)=>formatNumber(Number(v||0)),moeda=(v:number)=>formatCurrency(Number(v||0),{maximumFractionDigits:0}),drill=(camada:"anfir"|"historico"|"crm",campo:string|undefined,valor:string|undefined,titulo:string)=>hrefDrill(camada,campo,valor,titulo,queryString,slug,t("equipment.drillSub"))
 return <main className="flex min-h-screen bg-[#020817] text-white"><Sidebar/><section className="min-w-0 flex-1"><Topbar/><div className="space-y-7 p-4 sm:p-6 lg:p-8"><header><h1 className="text-3xl font-bold sm:text-4xl">{tituloFamilia}</h1><p className="mt-2 text-sm text-slate-400">{t("equipment.subtitle")}</p><p className="mt-2 text-sm text-cyan-300">{t("common.context")}: {contextoAtual.label} • {t("common.period")}: {periodoExibido}</p></header>
 {erro&&<div className="rounded-xl border border-red-500/60 bg-red-950/20 p-4 text-red-200">{erro}</div>}
 {loading?<div className="rounded-2xl border border-[#17304d] bg-[#071226] p-6 text-slate-400">{t("equipment.loading")}</div>:dados&&<><section className="grid gap-4 xl:grid-cols-3"><Camada titulo={t("equipment.realized")} descricao={t("equipment.realizedDesc")} tom="cyan" href={drill("anfir",undefined,undefined,`${tituloFamilia} · ${t("equipment.realized")}`)} detalhe={t("equipment.layerDetail")} kpis={[[t("common.records"),numero(dados.realizado.total_registros)],[t("common.value"),moeda(dados.realizado.valor_total)],[t("common.states"),numero(dados.realizado.estados.length)]]}/><Camada titulo={t("equipment.history")} descricao={t("equipment.historyDesc")} tom="amber" href={drill("historico",undefined,undefined,`${tituloFamilia} · ${t("equipment.history")}`)} detalhe={t("equipment.layerDetail")} kpis={[[t("common.records"),numero(dados.historico_comercial.total_registros)],[t("common.units"),numero(dados.historico_comercial.total_unidades)],[t("equipment.nominalValue"),moeda(dados.historico_comercial.valor_nominal)]]}/><Camada titulo={t("equipment.live")} descricao={t("equipment.liveDesc")} tom="emerald" href={drill("crm",undefined,undefined,`${tituloFamilia} · ${t("equipment.live")}`)} detalhe={t("equipment.layerDetail")} kpis={[[t("equipment.opportunities"),numero(dados.em_curso.total_registros)],[t("equipment.pipeline"),moeda(dados.em_curso.valor_pipeline)],[t("common.states"),numero(dados.em_curso.estados.length)]]}/></section>
 <div className="rounded-xl border border-cyan-500/25 bg-cyan-950/10 p-4 text-sm text-cyan-100/80">{t("equipment.separation")}</div>
 <AnfirCompetitiveDecision slug={slug}/>
 <section className="grid gap-5 xl:grid-cols-3"><div className="space-y-5"><Ranking titulo={t("equipment.anfirStates")} itens={dados.realizado.estados} vazio={t("equipment.noRealizedState")} camada="anfir" campo="estado" queryString={queryString} familia={slug} subtitulo={t("equipment.drillSub")} formatNumber={formatNumber}/><Ranking titulo={t("equipment.anfirBodyBuilders")} itens={dados.realizado.implementadoras} vazio={t("equipment.noRealizedBodyBuilder")} camada="anfir" campo="implementadora" queryString={queryString} familia={slug} subtitulo={t("equipment.drillSub")} formatNumber={formatNumber}/><Ranking titulo={t("equipment.anfirCompanies")} itens={dados.realizado.empresas} vazio={t("equipment.noRealizedCompany")} camada="anfir" campo="empresa" queryString={queryString} familia={slug} subtitulo={t("equipment.drillSub")} formatNumber={formatNumber}/></div><div className="space-y-5"><Ranking titulo={t("equipment.histEquipment")} itens={dados.historico_comercial.equipamentos} vazio={t("equipment.noHistory")} camada="historico" campo="equipamento" queryString={queryString} familia={slug} subtitulo={t("equipment.drillSub")} formatNumber={formatNumber}/><Ranking titulo={t("equipment.histStatus")} itens={dados.historico_comercial.status} vazio={t("equipment.noHistStatus")} camada="historico" campo="status" queryString={queryString} familia={slug} subtitulo={t("equipment.drillSub")} formatNumber={formatNumber}/><Ranking titulo={t("equipment.histBodyBuilders")} itens={dados.historico_comercial.implementadoras} vazio={t("equipment.noHistBodyBuilder")} camada="historico" campo="implementadora" queryString={queryString} familia={slug} subtitulo={t("equipment.drillSub")} formatNumber={formatNumber}/></div><div className="space-y-5"><Ranking titulo={t("equipment.crmEquipment")} itens={dados.em_curso.equipamentos} vazio={t("equipment.noLive")} camada="crm" campo="equipamento" queryString={queryString} familia={slug} subtitulo={t("equipment.drillSub")} formatNumber={formatNumber}/><Ranking titulo={t("equipment.crmStatus")} itens={dados.em_curso.status} vazio={t("equipment.noLive")} camada="crm" campo="status" queryString={queryString} familia={slug} subtitulo={t("equipment.drillSub")} formatNumber={formatNumber}/><Ranking titulo={t("equipment.crmTerritory")} itens={dados.em_curso.estados.length?dados.em_curso.estados:dados.em_curso.ddds} vazio={t("equipment.noTerritory")} camada="crm" campo={dados.em_curso.estados.length?"estado":"ddd"} queryString={queryString} familia={slug} subtitulo={t("equipment.drillSub")} formatNumber={formatNumber}/></div></section>
 {dados.historico_comercial.nota_territorial&&<p className="text-xs leading-5 text-slate-500">{dados.historico_comercial.nota_territorial}</p>}</>}</div></section></main>
}
function hrefDrill(camada:"anfir"|"historico"|"crm",campo:string|undefined,valor:string|undefined,titulo:string,base:string,familia:string,subtitulo:string){const q=new URLSearchParams(base||"");q.set("camada",camada);q.set("titulo",titulo);q.set("subtitulo",subtitulo);if(campo)q.set("campo",campo);if(valor)q.set("valor",valor);if(familia)q.set("familia",familia);return `/detalhamento?${q.toString()}`}
function Camada({titulo,descricao,kpis,tom,href,detalhe}:{titulo:string;descricao:string;kpis:[string,string][];tom:"cyan"|"amber"|"emerald";href:string;detalhe:string}){const cor=tom==="amber"?"text-amber-300":tom==="emerald"?"text-emerald-300":"text-cyan-300";return <Link href={href} className="rounded-2xl border border-[#17304d] bg-[#071226] p-5 transition hover:border-cyan-500/70 hover:bg-[#0a1a31]"><p className={`text-xs font-semibold uppercase tracking-[.16em] ${cor}`}>{titulo}</p><p className="mt-2 text-sm text-slate-400">{descricao}</p><div className="mt-5 grid grid-cols-3 gap-2">{kpis.map(([r,v])=><div key={r} className="min-w-0 rounded-xl bg-[#08162d] p-3"><p className="text-[11px] text-slate-500">{r}</p><strong className="mt-1 block break-words text-lg text-white">{v}</strong></div>)}</div><p className="mt-3 text-[11px] text-slate-500">{detalhe}</p></Link>}
function Ranking({titulo,itens,vazio,camada,campo,queryString,familia,subtitulo,formatNumber}:{titulo:string;itens:RankingItem[];vazio:string;camada:"anfir"|"historico"|"crm";campo:string;queryString:string;familia:string;subtitulo:string;formatNumber:(v:number)=>string}){return <section className="rounded-2xl border border-[#17304d] bg-[#071226] p-5"><h2 className="font-semibold">{titulo}</h2>{itens.length===0?<p className="mt-4 text-sm text-slate-500">{vazio}</p>:<div className="mt-4 space-y-2">{itens.slice(0,10).map(item=><Link href={hrefDrill(camada,campo,item.nome,`${titulo} · ${item.nome}`,queryString,familia,subtitulo)} key={item.nome} className="flex items-center justify-between gap-4 rounded-xl bg-[#08162d] px-3 py-2.5 text-sm transition hover:bg-[#0b1d38] hover:ring-1 hover:ring-cyan-500/50"><span className="min-w-0 truncate text-slate-300">{item.nome}</span><strong className="shrink-0 text-cyan-300">{formatNumber(item.quantidade_registros)}</strong></Link>)}</div>}</section>}
