/* eslint-disable react-hooks/set-state-in-effect */
"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import JornadaComercialNav from "@/components/crm/JornadaComercialNav"
import { useAuth } from "@/core/auth/AuthContext"
import { useOperationalI18n } from "@/core/i18n/operational"
import { pertenceAoEscopoDoUsuario } from "@/core/rbac/commercial-scope"
import { API_URL } from "@/lib/api"

type RegistroNucleo={oportunidade_id:string;responsavel_id?:string|null;cliente_nome?:string;etapa?:string;valor?:number;proposta_numero?:string;pedido_id?:string;pedido_numero?:string;status_pedido?:string}
type PedidoOperacional={id:string;numero?:string;cliente_nome?:string;valor?:number;status?:string;data_pedido?:string;linha_produto?:string;equipamento?:string;quantidade?:number;proposta_numero?:string;status_envio_carrier?:string;status_ciclo?:string;enviado_carrier_em?:string;aceite?:{nome_signatario?:string;metodo?:string;aceito_em?:string;status?:string}}
type Pedido=PedidoOperacional&{oportunidade_id?:string;etapa_comercial?:string}
type FiltroPedido="TODOS"|"PENDENTES"|"ENVIADOS"|"FALHAS"
function statusPedido(item:Pedido){return String(item.status_envio_carrier||item.status||item.etapa_comercial||"NAO_ENVIADO").toUpperCase()}
function statusCiclo(item:Pedido){return String(item.status_ciclo||"PEDIDO").toUpperCase()}
function grupoPedido(item:Pedido):Exclude<FiltroPedido,"TODOS">{const status=statusPedido(item);if(["ENVIADO","REENVIADO","CONFIRMADO","ENVIADO_CARRIER","APROVADO_CARRIER"].includes(status))return"ENVIADOS";if(["FALHA","ERRO","REJEITADO","REJEITADO_CARRIER"].includes(status))return"FALHAS";return"PENDENTES"}
async function buscarLista<T>(url:string,mensagem:string):Promise<T[]>{const response=await fetch(url,{cache:"no-store"}),contentType=response.headers.get("content-type")||"";if(!contentType.includes("application/json")){const trecho=(await response.text()).slice(0,100).replace(/\s+/g," ");throw new Error(`${mensagem} (${response.status}): ${trecho||"-"}`)}const payload=await response.json();if(!response.ok){const detalhe=payload&&typeof payload==="object"&&"detail" in payload?String(payload.detail):mensagem;throw new Error(detalhe)}if(payload==null)return[];if(!Array.isArray(payload))throw new Error(mensagem);return payload as T[]}

const textos={
 "pt-BR":{eyebrow:"Execução pós-aceite",title:"Acompanhamento de pedidos",subtitle:"O pedido segue até CARRIER, faturamento, entrega, instalação e encerramento. Entrega não encerra o ciclo: a instalação precisa ser confirmada.",carrierFunnel:"Abrir Funil Carrier",orders:"Pedidos",totalVolume:"volume total",follow:"A acompanhar",awaiting:"aguardando avanço",sent:"Enviados",sentRegistered:"envio registrado",orderValue:"Valor em pedidos",sendFailures:"{count} com falha de envio",noFailures:"sem falhas de envio",management:"Gestão de pedidos",managementSub:"Acompanhamento operacional do pedido até a instalação efetiva do equipamento. O filtro selecionado é a composição exata do KPI correspondente.",search:"Buscar cliente, pedido, equipamento ou status",all:"Todos",failures:"Falhas",loading:"Carregando pedidos...",empty:"Nenhum pedido encontrado para o filtro selecionado.",composition:"Composição atual: {count} pedido(s).",client:"Cliente",order:"Pedido",equipment:"Equipamento",value:"Valor",carrier:"CARRIER",cycle:"Ciclo atual",action:"Ação",unidentified:"Cliente não identificado",proposal:"Proposta",unit:"un.",dossier:"Dossiê",track:"Acompanhar ciclo",click:"Clique para detalhar",loadCore:"Não foi possível carregar o núcleo comercial.",loadOrders:"Não foi possível carregar os pedidos operacionais.",loadFail:"Falha ao carregar pedidos."},
 en:{eyebrow:"Post-acceptance execution",title:"Order tracking",subtitle:"The order continues through CARRIER processing, invoicing, delivery, installation and closure. Delivery does not close the cycle: installation must be confirmed.",carrierFunnel:"Open CARRIER Funnel",orders:"Orders",totalVolume:"total volume",follow:"To follow up",awaiting:"awaiting progress",sent:"Sent",sentRegistered:"submission recorded",orderValue:"Order value",sendFailures:"{count} with submission failure",noFailures:"no submission failures",management:"Order management",managementSub:"Operational follow-up through actual equipment installation. The selected filter is the exact composition of its corresponding KPI.",search:"Search account, order, equipment or status",all:"All",failures:"Failures",loading:"Loading orders...",empty:"No orders found for the selected filter.",composition:"Current composition: {count} order(s).",client:"Account",order:"Order",equipment:"Equipment",value:"Value",carrier:"CARRIER",cycle:"Current cycle",action:"Action",unidentified:"Account not identified",proposal:"Proposal",unit:"unit(s)",dossier:"Dossier",track:"Track cycle",click:"Click to view details",loadCore:"We couldn't load the commercial core.",loadOrders:"We couldn't load operational orders.",loadFail:"We couldn't load orders."},
 es:{eyebrow:"Ejecución posterior a la aceptación",title:"Seguimiento de pedidos",subtitle:"El pedido continúa por CARRIER, facturación, entrega, instalación y cierre. La entrega no cierra el ciclo: la instalación debe confirmarse.",carrierFunnel:"Abrir Embudo CARRIER",orders:"Pedidos",totalVolume:"volumen total",follow:"A seguir",awaiting:"pendientes de avance",sent:"Enviados",sentRegistered:"envío registrado",orderValue:"Valor de pedidos",sendFailures:"{count} con falla de envío",noFailures:"sin fallas de envío",management:"Gestión de pedidos",managementSub:"Seguimiento operativo del pedido hasta la instalación efectiva del equipo. El filtro seleccionado es la composición exacta del KPI correspondiente.",search:"Buscar cliente, pedido, equipo o estado",all:"Todos",failures:"Fallas",loading:"Cargando pedidos...",empty:"No se encontraron pedidos para el filtro seleccionado.",composition:"Composición actual: {count} pedido(s).",client:"Cliente",order:"Pedido",equipment:"Equipo",value:"Valor",carrier:"CARRIER",cycle:"Ciclo actual",action:"Acción",unidentified:"Cliente no identificado",proposal:"Propuesta",unit:"un.",dossier:"Expediente",track:"Acompañar ciclo",click:"Haga clic para ver detalles",loadCore:"No fue posible cargar el núcleo comercial.",loadOrders:"No fue posible cargar los pedidos operativos.",loadFail:"No fue posible cargar los pedidos."}
} as const
function interpolate(text:string,count:number){return text.replace("{count}",String(count))}

export default function PedidosPage(){
 const { usuario } = useAuth()
 const { locale, formatCurrency, formatDate, formatNumber }=useOperationalI18n()
 const tx=textos[locale]
 const[dados,setDados]=useState<Pedido[]>([]),[loading,setLoading]=useState(true),[erro,setErro]=useState(""),[busca,setBusca]=useState(""),[filtro,setFiltro]=useState<FiltroPedido>("TODOS")
 useEffect(()=>{let ativo=true;setLoading(true);setErro("");Promise.all([buscarLista<RegistroNucleo>(`${API_URL}/crm/nucleo-comercial`,tx.loadCore),buscarLista<PedidoOperacional>(`${API_URL}/carrier-operacional/pedidos`,tx.loadOrders).catch(()=>[])]).then(([nucleo,operacionais])=>{if(!ativo)return;const operacionalPorId=new Map(operacionais.map(item=>[String(item.id),item]));const pedidos=nucleo.filter(item=>pertenceAoEscopoDoUsuario(item.responsavel_id,usuario)).filter(item=>Boolean(item.pedido_id)).map(item=>{const operacional=operacionalPorId.get(String(item.pedido_id));return{...(operacional||{id:String(item.pedido_id)}),id:String(item.pedido_id),numero:item.pedido_numero||operacional?.numero,cliente_nome:item.cliente_nome||operacional?.cliente_nome,valor:Number(item.valor||0),status:item.status_pedido||operacional?.status,proposta_numero:item.proposta_numero||operacional?.proposta_numero,oportunidade_id:item.oportunidade_id,etapa_comercial:item.etapa}});setDados(pedidos)}).catch(falha=>{if(ativo)setErro(falha instanceof Error?falha.message:tx.loadFail)}).finally(()=>{if(ativo)setLoading(false)});return()=>{ativo=false}},[tx.loadCore,tx.loadFail,tx.loadOrders,usuario])
 const resumo=useMemo(()=>{const enviados=dados.filter(i=>grupoPedido(i)==="ENVIADOS").length,falhas=dados.filter(i=>grupoPedido(i)==="FALHAS").length,pendentes=dados.filter(i=>grupoPedido(i)==="PENDENTES").length,valor=dados.reduce((t,i)=>t+Number(i.valor||0),0);return{total:dados.length,enviados,falhas,pendentes,valor}},[dados])
 const filtrados=useMemo(()=>{const loc=locale==="pt-BR"?"pt-BR":locale==="es"?"es":"en";const termo=busca.trim().toLocaleLowerCase(loc);return dados.filter(item=>{if(filtro!=="TODOS"&&grupoPedido(item)!==filtro)return false;if(!termo)return true;return`${item.numero||""} ${item.cliente_nome||""} ${item.equipamento||""} ${statusPedido(item)} ${statusCiclo(item)}`.toLocaleLowerCase(loc).includes(termo)})},[busca,dados,filtro,locale])
 const filtros:Array<{id:FiltroPedido;label:string;valor:number}>=[{id:"TODOS",label:tx.all,valor:resumo.total},{id:"PENDENTES",label:tx.follow,valor:resumo.pendentes},{id:"ENVIADOS",label:tx.sent,valor:resumo.enviados},{id:"FALHAS",label:tx.failures,valor:resumo.falhas}]
 const data=(valor?:string)=>{if(!valor)return"-";return formatDate(valor)}
 function abrirComposicao(novoFiltro:FiltroPedido){setFiltro(novoFiltro);setBusca("");window.setTimeout(()=>document.getElementById("gestao-pedidos")?.scrollIntoView({behavior:"smooth",block:"start"}),0)}
 return <main className="flex min-h-screen bg-[#020817] text-white"><Sidebar/><section className="min-w-0 flex-1"><Topbar/><div className="space-y-6 p-4 sm:p-6 lg:p-8">
  <header className="rounded-3xl border border-[#13203f] bg-[#091a33] p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400">{tx.eyebrow}</p><h1 className="mt-2 text-3xl font-bold">{tx.title}</h1><p className="mt-2 text-sm text-slate-400">{tx.subtitle}</p></div><Link href="/funil-carrier" className="rounded-xl border border-cyan-700 px-4 py-3 text-sm font-semibold text-cyan-300">{tx.carrierFunnel}</Link></div></header>
  <JornadaComercialNav/>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi titulo={tx.orders} valor={formatNumber(resumo.total)} detalhe={tx.totalVolume} onOpen={()=>abrirComposicao("TODOS")} click={tx.click}/><Kpi titulo={tx.follow} valor={formatNumber(resumo.pendentes)} detalhe={tx.awaiting} onOpen={()=>abrirComposicao("PENDENTES")} click={tx.click}/><Kpi titulo={tx.sent} valor={formatNumber(resumo.enviados)} detalhe={tx.sentRegistered} onOpen={()=>abrirComposicao("ENVIADOS")} click={tx.click}/><Kpi titulo={tx.orderValue} valor={formatCurrency(resumo.valor)} detalhe={resumo.falhas?interpolate(tx.sendFailures,resumo.falhas):tx.noFailures} onOpen={()=>abrirComposicao("TODOS")} click={tx.click}/></section>
  <section id="gestao-pedidos" className="scroll-mt-24 rounded-3xl border border-[#13203f] bg-[#071427] p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h2 className="text-xl font-bold">{tx.management}</h2><p className="mt-1 text-sm text-slate-400">{tx.managementSub}</p></div><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder={tx.search} className="w-full rounded-xl border border-[#24466f] bg-[#020817] px-4 py-3 text-sm text-white xl:max-w-md"/></div>
   <div className="mt-5 flex flex-wrap gap-2">{filtros.map(item=><button key={item.id} type="button" onClick={()=>setFiltro(item.id)} className={`rounded-full border px-4 py-2 text-sm ${filtro===item.id?"border-cyan-500 bg-cyan-950/50 text-cyan-200":"border-[#24466f] bg-[#020817] text-slate-400"}`}>{item.label} <strong className="ml-1">{formatNumber(item.valor)}</strong></button>)}</div>
   {erro&&<div className="mt-5 rounded-xl border border-red-900 bg-red-950/30 p-4 text-sm text-red-200">{erro}</div>}
   {loading?<p className="mt-6 text-slate-400">{tx.loading}</p>:filtrados.length===0?<p className="mt-6 text-slate-500">{tx.empty}</p>:<div className="mt-6 overflow-x-auto"><div className="mb-3 text-xs text-cyan-300">{interpolate(tx.composition,filtrados.length)}</div><table className="min-w-full text-sm"><thead><tr className="border-b border-[#16325c] text-left text-slate-400"><th className="p-3">{tx.client}</th><th className="p-3">{tx.order}</th><th className="p-3">{tx.equipment}</th><th className="p-3">{tx.value}</th><th className="p-3">{tx.carrier}</th><th className="p-3">{tx.cycle}</th><th className="p-3">{tx.action}</th></tr></thead><tbody>{filtrados.map(item=>{const grupo=grupoPedido(item),falha=grupo==="FALHAS",enviadoEm=item.enviado_carrier_em;return <tr key={item.id} className={`border-b border-[#13203f] align-top ${falha?"bg-red-950/10":""}`}><td className="p-3"><p className="font-semibold text-white">{item.cliente_nome||tx.unidentified}</p><p className="mt-1 text-xs text-slate-500">{data(item.data_pedido)}</p></td><td className="p-3"><p className="text-cyan-300">{item.numero||tx.order}</p><p className="mt-1 text-xs text-slate-500">{tx.proposal} {item.proposta_numero||"-"}</p></td><td className="p-3"><p>{item.equipamento||"-"}</p><p className="mt-1 text-xs text-slate-500">{item.linha_produto||"-"} • {formatNumber(item.quantidade||1)} {tx.unit}</p></td><td className="p-3 font-semibold text-emerald-300">{formatCurrency(Number(item.valor||0))}</td><td className="p-3"><span className={`rounded-full border px-3 py-1 text-xs ${falha?"border-red-800 text-red-300":grupo==="ENVIADOS"?"border-emerald-800 text-emerald-300":"border-cyan-800 text-cyan-200"}`}>{statusPedido(item).replaceAll("_"," ")}</span>{enviadoEm&&<p className="mt-2 text-xs text-slate-500">{data(enviadoEm)}</p>}</td><td className="p-3"><span className="rounded-full border border-violet-800 bg-violet-950/20 px-3 py-1 text-xs text-violet-200">{statusCiclo(item).replaceAll("_"," ")}</span></td><td className="p-3"><div className="flex flex-wrap gap-2"><Link href={`/pedidos/${item.id}`} className="rounded-lg border border-slate-600 px-3 py-2 text-xs text-slate-200">{tx.dossier}</Link><Link href={`/pedidos/${item.id}/ciclo`} className="rounded-lg border border-cyan-700 px-3 py-2 text-xs font-semibold text-cyan-300">{tx.track}</Link></div></td></tr>})}</tbody></table></div>}
  </section>
 </div></section></main>
}
function Kpi({titulo,valor,detalhe,onOpen,click}:{titulo:string;valor:string;detalhe:string;onOpen?:()=>void;click:string}){const body=<><p className="text-sm text-slate-400">{titulo}</p><p className="mt-2 text-2xl font-bold text-cyan-300">{valor}</p><p className="mt-1 text-xs text-slate-500">{detalhe}</p>{onOpen&&<p className="mt-2 text-[11px] text-cyan-400">{click}</p>}</>;return onOpen?<button type="button" onClick={onOpen} className="rounded-2xl border border-[#13203f] bg-[#091a33] p-5 text-left transition hover:border-cyan-500/70 hover:bg-[#0b1d38]">{body}</button>:<div className="rounded-2xl border border-[#13203f] bg-[#091a33] p-5">{body}</div>}
