/* eslint-disable react-hooks/set-state-in-effect */
"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import JornadaComercialNav from "@/components/crm/JornadaComercialNav"
import { API_URL } from "@/lib/api"

type RegistroNucleo={oportunidade_id:string;cliente_nome?:string;etapa?:string;valor?:number;proposta_numero?:string;pedido_id?:string;pedido_numero?:string;status_pedido?:string}
type PedidoOperacional={id:string;numero?:string;cliente_nome?:string;valor?:number;status?:string;data_pedido?:string;linha_produto?:string;equipamento?:string;quantidade?:number;proposta_numero?:string;status_envio_carrier?:string;status_ciclo?:string;enviado_carrier_em?:string;aceite?:{nome_signatario?:string;metodo?:string;aceito_em?:string;status?:string}}
type Pedido=PedidoOperacional&{oportunidade_id?:string;etapa_comercial?:string}
type FiltroPedido="TODOS"|"PENDENTES"|"ENVIADOS"|"FALHAS"
function moeda(valor:unknown){return Number(valor||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function data(valor?:string){if(!valor)return"-";const d=new Date(valor);return Number.isNaN(d.getTime())?valor:d.toLocaleDateString("pt-BR")}
function statusPedido(item:Pedido){return String(item.status_envio_carrier||item.status||item.etapa_comercial||"NAO_ENVIADO").toUpperCase()}
function statusCiclo(item:Pedido){return String(item.status_ciclo||"PEDIDO").toUpperCase()}
function grupoPedido(item:Pedido):Exclude<FiltroPedido,"TODOS">{const status=statusPedido(item);if(["ENVIADO","REENVIADO","CONFIRMADO","ENVIADO_CARRIER","APROVADO_CARRIER"].includes(status))return"ENVIADOS";if(["FALHA","ERRO","REJEITADO","REJEITADO_CARRIER"].includes(status))return"FALHAS";return"PENDENTES"}
async function buscarLista<T>(url:string,mensagem:string):Promise<T[]>{const response=await fetch(url,{cache:"no-store"}),contentType=response.headers.get("content-type")||"";if(!contentType.includes("application/json")){const trecho=(await response.text()).slice(0,100).replace(/\s+/g," ");throw new Error(`API retornou conteúdo inválido (${response.status}): ${trecho||"sem conteúdo"}`)}const payload=await response.json();if(!response.ok){const detalhe=payload&&typeof payload==="object"&&"detail" in payload?String(payload.detail):mensagem;throw new Error(detalhe)}if(payload==null)return[];if(!Array.isArray(payload))throw new Error("A API de pedidos retornou um formato inesperado.");return payload as T[]}

export default function PedidosPage(){
 const[dados,setDados]=useState<Pedido[]>([]),[loading,setLoading]=useState(true),[erro,setErro]=useState(""),[busca,setBusca]=useState(""),[filtro,setFiltro]=useState<FiltroPedido>("TODOS")
 useEffect(()=>{let ativo=true;setLoading(true);setErro("");Promise.all([buscarLista<RegistroNucleo>(`${API_URL}/crm/nucleo-comercial`,"Não foi possível carregar o núcleo comercial."),buscarLista<PedidoOperacional>(`${API_URL}/carrier-operacional/pedidos`,"Não foi possível carregar os pedidos operacionais.").catch(()=>[])]).then(([nucleo,operacionais])=>{if(!ativo)return;const operacionalPorId=new Map(operacionais.map(item=>[String(item.id),item]));const pedidos=nucleo.filter(item=>Boolean(item.pedido_id)).map(item=>{const operacional=operacionalPorId.get(String(item.pedido_id));return{...(operacional||{id:String(item.pedido_id)}),id:String(item.pedido_id),numero:item.pedido_numero||operacional?.numero,cliente_nome:item.cliente_nome||operacional?.cliente_nome,valor:Number(item.valor||0),status:item.status_pedido||operacional?.status,proposta_numero:item.proposta_numero||operacional?.proposta_numero,oportunidade_id:item.oportunidade_id,etapa_comercial:item.etapa}});setDados(pedidos)}).catch(falha=>{if(ativo)setErro(falha instanceof Error?falha.message:"Falha ao carregar pedidos.")}).finally(()=>{if(ativo)setLoading(false)});return()=>{ativo=false}},[])
 const resumo=useMemo(()=>{const enviados=dados.filter(i=>grupoPedido(i)==="ENVIADOS").length,falhas=dados.filter(i=>grupoPedido(i)==="FALHAS").length,pendentes=dados.filter(i=>grupoPedido(i)==="PENDENTES").length,valor=dados.reduce((t,i)=>t+Number(i.valor||0),0);return{total:dados.length,enviados,falhas,pendentes,valor}},[dados])
 const filtrados=useMemo(()=>{const termo=busca.trim().toLocaleLowerCase("pt-BR");return dados.filter(item=>{if(filtro!=="TODOS"&&grupoPedido(item)!==filtro)return false;if(!termo)return true;return`${item.numero||""} ${item.cliente_nome||""} ${item.equipamento||""} ${statusPedido(item)} ${statusCiclo(item)}`.toLocaleLowerCase("pt-BR").includes(termo)})},[busca,dados,filtro])
 const filtros:Array<{id:FiltroPedido;label:string;valor:number}>=[{id:"TODOS",label:"Todos",valor:resumo.total},{id:"PENDENTES",label:"A acompanhar",valor:resumo.pendentes},{id:"ENVIADOS",label:"Enviados",valor:resumo.enviados},{id:"FALHAS",label:"Falhas",valor:resumo.falhas}]
 function abrirComposicao(novoFiltro:FiltroPedido){setFiltro(novoFiltro);setBusca("");window.setTimeout(()=>document.getElementById("gestao-pedidos")?.scrollIntoView({behavior:"smooth",block:"start"}),0)}
 return <main className="flex min-h-screen bg-[#020817] text-white"><Sidebar/><section className="min-w-0 flex-1"><Topbar/><div className="space-y-6 p-4 sm:p-6 lg:p-8">
  <header className="rounded-3xl border border-[#13203f] bg-[#091a33] p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400">Execução pós-aceite</p><h1 className="mt-2 text-3xl font-bold">Acompanhamento de pedidos</h1><p className="mt-2 text-sm text-slate-400">O pedido segue até CARRIER, faturamento, entrega, instalação e encerramento. Entrega não encerra o ciclo: a instalação precisa ser confirmada.</p></div><Link href="/funil-carrier" className="rounded-xl border border-cyan-700 px-4 py-3 text-sm font-semibold text-cyan-300">Abrir Funil Carrier</Link></div></header>
  <JornadaComercialNav/>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi titulo="Pedidos" valor={String(resumo.total)} detalhe="volume total" onOpen={()=>abrirComposicao("TODOS")}/><Kpi titulo="A acompanhar" valor={String(resumo.pendentes)} detalhe="aguardando avanço" onOpen={()=>abrirComposicao("PENDENTES")}/><Kpi titulo="Enviados" valor={String(resumo.enviados)} detalhe="envio registrado" onOpen={()=>abrirComposicao("ENVIADOS")}/><Kpi titulo="Valor em pedidos" valor={moeda(resumo.valor)} detalhe={resumo.falhas?`${resumo.falhas} com falha de envio`:"sem falhas de envio"} onOpen={()=>abrirComposicao("TODOS")}/></section>
  <section id="gestao-pedidos" className="scroll-mt-24 rounded-3xl border border-[#13203f] bg-[#071427] p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h2 className="text-xl font-bold">Gestão de pedidos</h2><p className="mt-1 text-sm text-slate-400">Acompanhamento operacional do pedido até a instalação efetiva do equipamento. O filtro selecionado é a composição exata do KPI correspondente.</p></div><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar cliente, pedido, equipamento ou status" className="w-full rounded-xl border border-[#24466f] bg-[#020817] px-4 py-3 text-sm text-white xl:max-w-md"/></div>
   <div className="mt-5 flex flex-wrap gap-2">{filtros.map(item=><button key={item.id} type="button" onClick={()=>setFiltro(item.id)} className={`rounded-full border px-4 py-2 text-sm ${filtro===item.id?"border-cyan-500 bg-cyan-950/50 text-cyan-200":"border-[#24466f] bg-[#020817] text-slate-400"}`}>{item.label} <strong className="ml-1">{item.valor}</strong></button>)}</div>
   {erro&&<div className="mt-5 rounded-xl border border-red-900 bg-red-950/30 p-4 text-sm text-red-200">{erro}</div>}
   {loading?<p className="mt-6 text-slate-400">Carregando pedidos...</p>:filtrados.length===0?<p className="mt-6 text-slate-500">Nenhum pedido encontrado para o filtro selecionado.</p>:<div className="mt-6 overflow-x-auto"><div className="mb-3 text-xs text-cyan-300">Composição atual: {filtrados.length.toLocaleString("pt-BR")} pedido(s).</div><table className="min-w-full text-sm"><thead><tr className="border-b border-[#16325c] text-left text-slate-400"><th className="p-3">Cliente</th><th className="p-3">Pedido</th><th className="p-3">Equipamento</th><th className="p-3">Valor</th><th className="p-3">CARRIER</th><th className="p-3">Ciclo atual</th><th className="p-3">Ação</th></tr></thead><tbody>{filtrados.map(item=>{const grupo=grupoPedido(item),falha=grupo==="FALHAS",enviadoEm=item.enviado_carrier_em;return <tr key={item.id} className={`border-b border-[#13203f] align-top ${falha?"bg-red-950/10":""}`}><td className="p-3"><p className="font-semibold text-white">{item.cliente_nome||"Cliente não identificado"}</p><p className="mt-1 text-xs text-slate-500">{data(item.data_pedido)}</p></td><td className="p-3"><p className="text-cyan-300">{item.numero||"Pedido"}</p><p className="mt-1 text-xs text-slate-500">Proposta {item.proposta_numero||"-"}</p></td><td className="p-3"><p>{item.equipamento||"-"}</p><p className="mt-1 text-xs text-slate-500">{item.linha_produto||"-"} • {item.quantidade||1} un.</p></td><td className="p-3 font-semibold text-emerald-300">{moeda(item.valor)}</td><td className="p-3"><span className={`rounded-full border px-3 py-1 text-xs ${falha?"border-red-800 text-red-300":grupo==="ENVIADOS"?"border-emerald-800 text-emerald-300":"border-cyan-800 text-cyan-200"}`}>{statusPedido(item).replaceAll("_"," ")}</span>{enviadoEm&&<p className="mt-2 text-xs text-slate-500">{data(enviadoEm)}</p>}</td><td className="p-3"><span className="rounded-full border border-violet-800 bg-violet-950/20 px-3 py-1 text-xs text-violet-200">{statusCiclo(item)}</span></td><td className="p-3"><div className="flex flex-wrap gap-2"><Link href={`/pedidos/${item.id}`} className="rounded-lg border border-slate-600 px-3 py-2 text-xs text-slate-200">Dossiê</Link><Link href={`/pedidos/${item.id}/ciclo`} className="rounded-lg border border-cyan-700 px-3 py-2 text-xs font-semibold text-cyan-300">Acompanhar ciclo</Link></div></td></tr>})}</tbody></table></div>}
  </section>
 </div></section></main>
}
function Kpi({titulo,valor,detalhe,onOpen}:{titulo:string;valor:string;detalhe:string;onOpen?:()=>void}){const body=<><p className="text-sm text-slate-400">{titulo}</p><p className="mt-2 text-2xl font-bold text-cyan-300">{valor}</p><p className="mt-1 text-xs text-slate-500">{detalhe}</p>{onOpen&&<p className="mt-2 text-[11px] text-cyan-400">Clique para detalhar</p>}</>;return onOpen?<button type="button" onClick={onOpen} className="rounded-2xl border border-[#13203f] bg-[#091a33] p-5 text-left transition hover:border-cyan-500/70 hover:bg-[#0b1d38]">{body}</button>:<div className="rounded-2xl border border-[#13203f] bg-[#091a33] p-5">{body}</div>}