"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { fetchCrmSeguroProxy } from "@/services/crm-secure"

type Registro=Record<string,unknown>
type Item={id:string;cliente:string;titulo:string;responsavel:string;status:string;motivo:string;observacao:string;valor:number;encerradoEm:string}
const ENCERRADOS=new Set(["GANHO","PERDIDO","CANCELADO","CANCELADA","ENCERRADO","ENCERRADA"])
const LABELS:Record<string,string>={VENDA_CONCLUIDA:"Venda concluída",PERDA_CONCORRENCIA:"Perda para concorrência",COMPRA_INDIRETA:"Compra indireta",DESISTENCIA_CLIENTE:"Desistência do cliente",SEM_CONTINUIDADE:"Sem continuidade",SOLUCAO_GARANTIA_FABRICANTE:"Garantia/troca do fabricante",PROJETO_ADIADO:"Projeto adiado",PRECO_CONDICAO_COMERCIAL:"Preço/condição comercial",PRODUTO_INADEQUADO_INDISPONIVEL:"Produto inadequado/indisponível",OUTRO:"Outro"}
function texto(v:unknown,p=""){const s=String(v??"").trim();return s||p}
function lista(p:unknown):Registro[]{if(Array.isArray(p))return p as Registro[];if(p&&typeof p==="object"){const r=p as Registro;for(const k of ["dados","itens","oportunidades","resultado"])if(Array.isArray(r[k]))return r[k] as Registro[]}return[]}
function moeda(v:number){return v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function data(v:string){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("pt-BR")}

export default function HistoricoNegociacoesEncerradas({modo="web"}:{modo?:"web"|"app"}){
 const[itens,setItens]=useState<Item[]>([]),[loading,setLoading]=useState(true),[erro,setErro]=useState("")
 const[busca,setBusca]=useState(""),[motivo,setMotivo]=useState(""),[resultado,setResultado]=useState(""),[de,setDe]=useState(""),[ate,setAte]=useState("")
 useEffect(()=>{let ativo=true;async function carregar(){setLoading(true);setErro("");try{const nr=await fetchCrmSeguroProxy("crm-seguro/nucleo-comercial",{cache:"no-store"});const np=await nr.json().catch(()=>[]);if(!nr.ok)throw new Error(texto((np as Registro).detail,"Não foi possível carregar o histórico."));const fechadas=lista(np).filter(r=>ENCERRADOS.has(texto(r.status||r.status_oportunidade).toUpperCase()));const saida=await Promise.all(fechadas.map(async r=>{const id=texto(r.oportunidade_id||r.id);let d:Registro={};try{const dr=await fetchCrmSeguroProxy(`crm-visao/oportunidades/${encodeURIComponent(id)}/detalhes`,{cache:"no-store"});const dp=await dr.json().catch(()=>({}));if(dr.ok)d=(dp as Registro).oportunidade as Registro||{}}catch{}return{id,cliente:texto(d.cliente_nome||r.cliente_nome||r.razao_social,"Cliente"),titulo:texto(d.titulo||r.titulo||r.oportunidade_titulo,"Negociação"),responsavel:texto(r.responsavel_nome||r.responsavel,"—"),status:texto(d.status||r.status||r.status_oportunidade).toUpperCase(),motivo:texto(d.motivo_encerramento,"OUTRO").toUpperCase(),observacao:texto(d.observacao_encerramento,"Sem observação registrada"),valor:Number(d.valor_estimado||r.valor||r.valor_estimado||0),encerradoEm:texto(d.data_fechamento_real||r.data_fechamento_real||r.updated_at)}}));if(ativo)setItens(saida)}catch(e){if(ativo)setErro(e instanceof Error?e.message:"Falha ao carregar histórico.")}finally{if(ativo)setLoading(false)}}void carregar();return()=>{ativo=false}},[])
 const filtrados=useMemo(()=>itens.filter(i=>{const termo=busca.trim().toLowerCase();if(termo&&!`${i.cliente} ${i.titulo} ${i.responsavel} ${i.observacao}`.toLowerCase().includes(termo))return false;if(motivo&&i.motivo!==motivo)return false;if(resultado&&i.status!==resultado)return false;const dia=i.encerradoEm?i.encerradoEm.slice(0,10):"";if(de&&(!dia||dia<de))return false;if(ate&&(!dia||dia>ate))return false;return true}),[itens,busca,motivo,resultado,de,ate])
 const total=filtrados.reduce((s,i)=>s+i.valor,0);const porMotivo=useMemo(()=>{const m=new Map<string,number>();for(const i of filtrados)m.set(i.motivo,(m.get(i.motivo)||0)+1);return [...m.entries()].sort((a,b)=>b[1]-a[1])},[filtrados]);const max=Math.max(1,...porMotivo.map(x=>x[1]));const base=modo==="app"?"/crm-app/historico":"/oportunidades/encerradas"
 return <div className="space-y-5">
  <header><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-400">Histórico comercial</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Negociações encerradas</h1><p className="mt-2 text-sm text-slate-400">Processos fora da carteira aberta, preservados para análise de resultado e motivo.</p></header>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Cliente, negócio ou observação" className="rounded-xl border border-[#24466f] bg-[#020817] px-3 py-3"/><select value={resultado} onChange={e=>setResultado(e.target.value)} className="rounded-xl border border-[#24466f] bg-[#020817] px-3 py-3"><option value="">Todos os resultados</option><option value="GANHO">Ganho</option><option value="PERDIDO">Perdido</option><option value="ENCERRADO">Encerrado</option></select><select value={motivo} onChange={e=>setMotivo(e.target.value)} className="rounded-xl border border-[#24466f] bg-[#020817] px-3 py-3"><option value="">Todos os motivos</option>{Object.entries(LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input type="date" value={de} onChange={e=>setDe(e.target.value)} className="rounded-xl border border-[#24466f] bg-[#020817] px-3 py-3"/><input type="date" value={ate} onChange={e=>setAte(e.target.value)} className="rounded-xl border border-[#24466f] bg-[#020817] px-3 py-3"/></section>
  <section className="grid gap-3 sm:grid-cols-3"><Kpi t="Encerradas" v={String(filtrados.length)}/><Kpi t="Valor relacionado" v={moeda(total)}/><Kpi t="Motivos diferentes" v={String(porMotivo.length)}/></section>
  {porMotivo.length>0&&<section className="rounded-3xl border border-[#16325c] bg-[#07162b] p-5"><h2 className="text-lg font-bold">Motivos de encerramento</h2><div className="mt-4 space-y-3">{porMotivo.map(([m,q])=><div key={m}><div className="mb-1 flex justify-between gap-3 text-sm"><span>{LABELS[m]||m.replaceAll("_"," ")}</span><strong>{q}</strong></div><div className="h-2 overflow-hidden rounded-full bg-[#102442]"><div className="h-full rounded-full bg-cyan-400" style={{width:`${Math.max(4,(q/max)*100)}%`}}/></div></div>)}</div></section>}
  {loading&&<Aviso>Carregando histórico...</Aviso>}{erro&&<div className="rounded-2xl border border-red-900 bg-red-950/30 p-4 text-red-200">{erro}</div>}{!loading&&!erro&&filtrados.length===0&&<Aviso>Nenhuma negociação encerrada para os filtros selecionados.</Aviso>}
  <div className="space-y-3">{filtrados.map(i=><article key={i.id} className="rounded-2xl border border-[#16325c] bg-[#07162b] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-400">{LABELS[i.motivo]||i.motivo}</p><h3 className="mt-1 font-bold">{i.cliente}</h3><p className="text-sm text-slate-400">{i.titulo}</p></div><div className="text-sm sm:text-right"><strong className={i.status==="GANHO"?"text-emerald-300":i.status==="PERDIDO"?"text-red-300":"text-amber-200"}>{i.status}</strong><p className="mt-1 text-slate-400">{data(i.encerradoEm)} · {moeda(i.valor)}</p></div></div><p className="mt-3 rounded-xl bg-[#020817] p-3 text-sm leading-6 text-slate-300">{i.observacao}</p><div className="mt-3 flex items-center justify-between gap-3 text-xs text-slate-500"><span>{i.responsavel}</span><Link href={`${base}/${i.id}`} className="font-semibold text-cyan-300">Abrir histórico completo</Link></div></article>)}</div>
 </div>
}
function Kpi({t,v}:{t:string;v:string}){return <div className="rounded-2xl border border-[#16325c] bg-[#07162b] p-4"><p className="text-xs text-slate-500">{t}</p><p className="mt-2 text-xl font-bold text-cyan-300">{v}</p></div>}
function Aviso({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-[#16325c] bg-[#07162b] p-6 text-slate-300">{children}</div>}
