"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { ArrowLeft, CheckCircle2, Eye, FileText, Loader2, Mail, PackageCheck, Send } from "lucide-react"
import { useParams, useRouter } from "next/navigation"
import { useAuth } from "@/core/auth"
import { fetchCrmSeguroProxy } from "@/services/crm-secure"
import { useClosureI18n } from "@/core/i18n/closure"

type Registro=Record<string,unknown>
type Pacote={proposta:Registro;item:Registro|null;oportunidade:Registro|null;cliente:Registro|null;aceites:Registro[];pedidos:Registro[]}
type Locale="pt-BR"|"en"|"es"
function texto(v:unknown,p="—"){const s=String(v??"").trim();return s||p}
function emails(v:string){return v.split(/[;,\n]+/).map(i=>i.trim()).filter(Boolean)}
const copy={
 "pt-BR":{defaultMessage:"Segue a proposta comercial para sua análise.",load:"Não foi possível carregar a proposta.",opFail:"Operação não concluída.",sent:"Proposta enviada por e-mail. Protocolo: {id}.",sendFail:"Não foi possível enviar a proposta.",needTo:"Informe ao menos um endereço no campo Para.",confirmAcceptance:"Confirmar que {name} aceitou presencialmente os termos desta proposta?",acceptFail:"Não foi possível registrar o aceite.",acceptId:"A solicitação de aceite foi criada sem identificação válida.",acceptConfirmFail:"Não foi possível confirmar o aceite.",acceptConfirmed:"Aceite presencial confirmado. A proposta está liberada para conversão em pedido.",tokenFail:"O link de aceite foi criado sem token válido.",needOrderTo:"Informe ao menos um endereço no campo Para do pedido.",orderFail:"Não foi possível gerar o pedido.",orderIdFail:"Pedido gerado sem identificação válida.",message:"Mensagem",cancel:"Cancelar",sendPdf:"Enviar PDF oficial",viewPdf:"Visualizar proposta",viewFail:"Não foi possível abrir a proposta oficial.",orderReview:"Revisão e endereçamento do pedido",orderReviewSub:"Defina agora Para, CC e CCO. O pedido será criado já com esse envelope registrado.",orderNotes:"Observações do pedido",multiple:"Separe múltiplos endereços por vírgula, ponto e vírgula ou nova linha.",to:"Para",cc:"CC — cópia",bcc:"CCO — cópia oculta"},
 en:{defaultMessage:"Please find the sales proposal attached for your review.",load:"We couldn't load the proposal.",opFail:"The operation could not be completed.",sent:"Proposal sent by email. Protocol: {id}.",sendFail:"We couldn't send the proposal.",needTo:"Enter at least one address in the To field.",confirmAcceptance:"Confirm that {name} accepted the terms of this proposal in person?",acceptFail:"We couldn't record the acceptance.",acceptId:"The acceptance request was created without a valid identifier.",acceptConfirmFail:"We couldn't confirm the acceptance.",acceptConfirmed:"In-person acceptance confirmed. The proposal is now available for order conversion.",tokenFail:"The acceptance link was created without a valid token.",needOrderTo:"Enter at least one address in the order To field.",orderFail:"We couldn't create the order.",orderIdFail:"The order was created without a valid identifier.",message:"Message",cancel:"Cancel",sendPdf:"Send official PDF",viewPdf:"View proposal",viewFail:"We couldn't open the official proposal.",orderReview:"Order review and recipients",orderReviewSub:"Set To, CC and BCC now. The order will be created with this delivery envelope already recorded.",orderNotes:"Order notes",multiple:"Separate multiple addresses with commas, semicolons or new lines.",to:"To",cc:"CC",bcc:"BCC"},
 es:{defaultMessage:"Adjuntamos la propuesta comercial para su análisis.",load:"No fue posible cargar la propuesta.",opFail:"No fue posible completar la operación.",sent:"Propuesta enviada por correo. Protocolo: {id}.",sendFail:"No fue posible enviar la propuesta.",needTo:"Ingrese al menos una dirección en el campo Para.",confirmAcceptance:"¿Confirma que {name} aceptó presencialmente los términos de esta propuesta?",acceptFail:"No fue posible registrar la aceptación.",acceptId:"La solicitud de aceptación fue creada sin identificación válida.",acceptConfirmFail:"No fue posible confirmar la aceptación.",acceptConfirmed:"Aceptación presencial confirmada. La propuesta está disponible para convertirse en pedido.",tokenFail:"El enlace de aceite fue creado sin token válido.",needOrderTo:"Ingrese al menos una dirección en el campo Para del pedido.",orderFail:"No fue posible generar el pedido.",orderIdFail:"El pedido fue generado sin identificación válida.",message:"Mensaje",cancel:"Cancelar",sendPdf:"Enviar PDF oficial",viewPdf:"Visualizar proposta",viewFail:"No fue posible abrir la propuesta oficial.",orderReview:"Revisión y destinatarios del pedido",orderReviewSub:"Defina ahora Para, CC y CCO. El pedido se creará con este direccionamiento ya registrado.",orderNotes:"Observaciones del pedido",multiple:"Separe varias direcciones con coma, punto y coma o una nueva línea.",to:"Para",cc:"CC — copia",bcc:"CCO — copia oculta"}
} satisfies Record<Locale,Record<string,string>>
const fill=(s:string,k:string,v:string)=>s.replace(`{${k}}`,v)

export default function PropostaCrmAppPage(){
 const params=useParams<{id:string}>(),router=useRouter(),{usuario}=useAuth(),id=String(params.id||"");const {locale,tc,formatCurrency,formatNumber}=useClosureI18n(),t=copy[locale as Locale]||copy["pt-BR"]
 const[dados,setDados]=useState<Pacote|null>(null),[carregando,setCarregando]=useState(true),[processando,setProcessando]=useState(false),[erro,setErro]=useState(""),[mensagem,setMensagem]=useState(""),[revisaoAberta,setRevisaoAberta]=useState(false),[envioAberto,setEnvioAberto]=useState(false),[paraPedido,setParaPedido]=useState(""),[ccPedido,setCcPedido]=useState(""),[ccoPedido,setCcoPedido]=useState(""),[observacoes,setObservacoes]=useState(""),[paraProposta,setParaProposta]=useState(""),[ccProposta,setCcProposta]=useState(""),[ccoProposta,setCcoProposta]=useState(""),[mensagemEmail,setMensagemEmail]=useState(t.defaultMessage)
 const moeda=(v:unknown)=>formatCurrency(Number(v||0))
 async function carregar(){setCarregando(true);setErro("");try{const r=await fetchCrmSeguroProxy(`crm-seguro/propostas/${encodeURIComponent(id)}/pacote`,{cache:"no-store"}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p.detail||t.load));setDados(p);const e=texto(p?.cliente?.email,"");if(e){setParaProposta(a=>a||e);setParaPedido(a=>a||e)}}catch(e){setErro(e instanceof Error?e.message:t.load)}finally{setCarregando(false)}}
 useEffect(()=>{if(id)void carregar()},[id])
 useEffect(()=>{setMensagemEmail(a=>a||t.defaultMessage)},[t.defaultMessage])
 async function executar(sufixo:string,body:Registro={}){setProcessando(true);setErro("");setMensagem("");try{const r=await fetchCrmSeguroProxy(`crm-seguro/propostas/${encodeURIComponent(id)}${sufixo}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p.detail||t.opFail));setMensagem(tc("common.success"));await carregar();return p}catch(e){setErro(e instanceof Error?e.message:t.opFail)}finally{setProcessando(false)}}
 function visualizarProposta(){setErro("");setEnvioAberto(false);router.push(`/crm-app/propostas/${encodeURIComponent(id)}/visualizar`)}
 async function enviarProposta(){const d=emails(paraProposta);if(!d.length)return setErro(t.needTo);setProcessando(true);setErro("");setMensagem("");try{const r=await fetchCrmSeguroProxy(`crm-seguro/propostas/${encodeURIComponent(id)}/enviar-email`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({destinatarios:d,cc:emails(ccProposta),cco:emails(ccoProposta),mensagem:mensagemEmail.trim()||null})}),p=await r.json().catch(()=>({})) as Registro;if(!r.ok)throw new Error(texto(p.detail,t.sendFail));setMensagem(fill(t.sent,"id",texto(p.message_id,"OK")));setEnvioAberto(false);await carregar()}catch(e){setErro(e instanceof Error?e.message:t.sendFail)}finally{setProcessando(false)}}
 async function aceite(metodo:"PRESENCIAL_TELA"|"REMOTO_LINK"){const nome=window.prompt(tc("proposal.signerName"))?.trim();if(!nome)return;const email=window.prompt(tc("proposal.signerEmail"))?.trim()||null;if(metodo==="PRESENCIAL_TELA"&&!window.confirm(fill(t.confirmAcceptance,"name",nome)))return;setProcessando(true);setErro("");setMensagem("");try{const r=await fetchCrmSeguroProxy(`crm-seguro/propostas/${encodeURIComponent(id)}/aceites`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({metodo,nome_signatario:nome,email_signatario:email})}),p=await r.json().catch(()=>({})) as Registro;if(!r.ok)throw new Error(String(p.detail||t.acceptFail));const ac=p.aceite&&typeof p.aceite==="object"?p.aceite as Registro:null,aid=texto(ac?.id,"");if(metodo==="PRESENCIAL_TELA"){if(!aid)throw new Error(t.acceptId);const c=await fetch(`/api/crm-proxy/crm-documentos/aceites/${encodeURIComponent(aid)}/confirmar`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({aceite_termos:true,user_agent:navigator.userAgent,evidencias:{origem:"CRM_APP",modalidade:"PRESENCIAL_TELA"}})}),cp=await c.json().catch(()=>({})) as Registro;if(!c.ok)throw new Error(String(cp.detail||t.acceptConfirmFail));setMensagem(t.acceptConfirmed)}else{const token=String(p.link_token||"");if(!token)throw new Error(t.tokenFail);const link=`${window.location.origin}/aceite/${token}`;await navigator.clipboard?.writeText(link);setMensagem(tc("proposal.linkCopied",{link}))}await carregar()}catch(e){setErro(e instanceof Error?e.message:t.acceptFail)}finally{setProcessando(false)}}
 async function converterPedido(){const d=emails(paraPedido);if(!d.length){setErro(t.needOrderTo);return}setProcessando(true);setErro("");setMensagem("");try{const r=await fetchCrmSeguroProxy(`crm-seguro/propostas/${encodeURIComponent(id)}/converter-pedido-operacional`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({destinatarios:d,cc:emails(ccPedido),cco:emails(ccoPedido),observacoes_envio:observacoes||null,responsavel_id:usuario?.id?String(usuario.id):null})}),p=await r.json().catch(()=>({})) as Registro;if(!r.ok)throw new Error(String(p.detail||t.orderFail));const pid=String(p.id||"");if(!pid)throw new Error(t.orderIdFail);router.push(`/crm-app/pedidos/${pid}`)}catch(e){setErro(e instanceof Error?e.message:t.orderFail)}finally{setProcessando(false)}}
 const status=texto(dados?.proposta.status_documento,"RASCUNHO").toUpperCase(),podeEmitir=["RASCUNHO","EM_REVISAO","APROVADA_INTERNA"].includes(status),podeVisualizar=["EMITIDA","ENVIADA","VISUALIZADA","EM_NEGOCIACAO","ACEITA"].includes(status),podeEnviar=["RASCUNHO","EM_REVISAO","APROVADA_INTERNA","EMITIDA","ENVIADA","VISUALIZADA","EM_NEGOCIACAO"].includes(status),podeAceite=["EMITIDA","ENVIADA","VISUALIZADA","EM_NEGOCIACAO"].includes(status),podePedido=status==="ACEITA",pedido=dados?.pedidos?.[0],precoTabela=dados?.item?.preco_tabela??dados?.item?.preco_unitario,desconto=Number(dados?.item?.desconto_percentual||0)
 return <main className="min-h-[100dvh] bg-[#020817] px-4 py-5 pb-28 text-white sm:px-6"><div className="mx-auto max-w-4xl"><header className="mb-5 flex items-center gap-3"><Link href="/crm-app/propostas" className="grid size-11 place-items-center rounded-2xl border border-[#16325c] bg-[#091a33] text-cyan-300"><ArrowLeft size={20}/></Link><div><p className="text-xs uppercase tracking-[0.24em] text-cyan-400">CTI CRM</p><h1 className="text-2xl font-bold">{tc("crmProposal.title")}</h1></div></header>
 {carregando&&<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-cyan-300"/></div>}{erro&&<div className="mb-4 rounded-2xl border border-red-900 bg-red-950/40 p-4 text-red-200">{erro}</div>}{mensagem&&<div className="mb-4 rounded-2xl border border-emerald-900 bg-emerald-950/30 p-4 text-emerald-200">{mensagem}</div>}
 {dados&&<div className="space-y-4"><section className="rounded-3xl border border-[#16325c] bg-gradient-to-br from-[#0a2242] to-[#07162b] p-5"><p className="text-sm text-slate-400">{tc("proposal.title")}</p><h2 className="mt-1 text-xl font-bold">{texto(dados.proposta.numero,tc("proposal.draft"))}</h2><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded-full border border-cyan-800 px-3 py-1 text-cyan-200">{status.replaceAll("_"," ")}</span><span className="rounded-full border border-[#24466f] px-3 py-1 text-slate-300">{moeda(dados.proposta.valor)}</span></div></section>
 <section className="grid gap-3 sm:grid-cols-2"><Info label={locale==="en"?"Account":"Cliente"} valor={texto(dados.cliente?.razao_social||dados.cliente?.nome||dados.oportunidade?.cliente_nome)}/><Info label={tc("proposal.equipment")} valor={texto(dados.item?.equipamento)}/><Info label={tc("common.quantity")} valor={texto(dados.item?.quantidade,"1")}/><Info label={tc("crmProposal.tablePrice")} valor={moeda(precoTabela)}/><Info label={tc("proposal.discount")} valor={`${formatNumber(desconto,{maximumFractionDigits:2})}%`}/><Info label={tc("crmProposal.negotiatedValue")} valor={moeda(dados.proposta.valor)}/></section>
 <section className="rounded-3xl border border-[#16325c] bg-[#07162b] p-5"><h3 className="font-bold">{tc("crmProposal.commercialActions")}</h3><p className="mt-1 text-sm text-slate-400">{tc("crmProposal.actionsSub")}</p><div className="mt-4 grid gap-3">{podeEmitir&&<button type="button" disabled={processando} onClick={()=>void executar("/emitir")} className="rounded-xl border border-cyan-700 px-4 py-3 text-cyan-200 disabled:opacity-40"><FileText className="mr-2 inline" size={18}/>{tc("proposal.issue")}</button>}{podeVisualizar&&<button type="button" onClick={visualizarProposta} className="rounded-xl border border-cyan-700 px-4 py-3 font-semibold text-cyan-200"><Eye className="mr-2 inline" size={18}/>{t.viewPdf}</button>}{podeEnviar&&!envioAberto&&<button type="button" disabled={processando} onClick={()=>setEnvioAberto(true)} className="rounded-xl border border-cyan-700 px-4 py-3 font-semibold text-cyan-200 disabled:opacity-40"><Mail className="mr-2 inline" size={18}/>{tc("crmProposal.sendEmail")}</button>}{podeAceite&&<><button type="button" disabled={processando} onClick={()=>void aceite("PRESENCIAL_TELA")} className="rounded-xl border border-cyan-700 px-4 py-3 text-cyan-200"><CheckCircle2 className="mr-2 inline" size={18}/>{tc("proposal.inPersonAcceptance")}</button><button type="button" disabled={processando} onClick={()=>void aceite("REMOTO_LINK")} className="rounded-xl border border-cyan-700 px-4 py-3 text-cyan-200">{tc("proposal.acceptanceLink")}</button></>}{podePedido&&!revisaoAberta&&<button type="button" disabled={processando} onClick={()=>setRevisaoAberta(true)} className="rounded-xl border border-emerald-700 px-4 py-3 text-emerald-300"><PackageCheck className="mr-2 inline" size={18}/>{tc("crmProposal.reviewOrder")}</button>}{pedido&&<Link href={`/crm-app/pedidos/${String(pedido.id)}`} className="rounded-xl border border-emerald-700 px-4 py-3 text-center font-semibold text-emerald-300">{tc("crmProposal.openOrder")}</Link>}</div></section>
 {envioAberto&&<section className="rounded-3xl border border-cyan-800 bg-cyan-950/15 p-5"><h3 className="text-lg font-bold">{tc("crmProposal.sendToAccount")}</h3><p className="mt-1 text-sm text-slate-400">{tc("crmProposal.sendToAccountSub")}</p><div className="mt-4 space-y-3"><CampoEmail titulo={t.to} valor={paraProposta} alterar={setParaProposta} obrigatorio/><CampoEmail titulo={t.cc} valor={ccProposta} alterar={setCcProposta}/><CampoEmail titulo={t.bcc} valor={ccoProposta} alterar={setCcoProposta}/><label className="block"><span className="mb-2 block text-sm">{t.message}</span><textarea value={mensagemEmail} onChange={e=>setMensagemEmail(e.target.value)} rows={4} className="w-full rounded-2xl border border-[#24466f] bg-[#020817] px-4 py-3"/></label></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><button type="button" onClick={()=>setEnvioAberto(false)} className="rounded-xl border border-[#24466f] px-4 py-3">{t.cancel}</button><button type="button" disabled={processando||!emails(paraProposta).length} onClick={()=>void enviarProposta()} className="rounded-xl bg-cyan-500 px-4 py-3 font-bold text-slate-950 disabled:opacity-40">{processando?<Loader2 className="mr-2 inline animate-spin" size={18}/>:<Send className="mr-2 inline" size={18}/>} {t.sendPdf}</button></div></section>}
 {podePedido&&revisaoAberta&&<section className="rounded-3xl border border-emerald-800 bg-emerald-950/20 p-5"><h3 className="text-lg font-bold">{t.orderReview}</h3><p className="mt-1 text-sm text-slate-400">{t.orderReviewSub}</p><div className="mt-4 space-y-3"><CampoEmail titulo={t.to} valor={paraPedido} alterar={setParaPedido} obrigatorio/><CampoEmail titulo={t.cc} valor={ccPedido} alterar={setCcPedido}/><CampoEmail titulo={t.bcc} valor={ccoPedido} alterar={setCcoPedido}/><label className="block"><span className="mb-2 block text-sm">{t.orderNotes}</span><textarea value={observacoes} onChange={e=>setObservacoes(e.target.value)} rows={3} className="w-full rounded-2xl border border-[#24466f] bg-[#020817] px-4 py-3"/></label></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><button type="button" onClick={()=>setRevisaoAberta(false)} className="rounded-xl border border-[#24466f] px-4 py-3">{t.cancel}</button><button type="button" disabled={processando||!emails(paraPedido).length} onClick={()=>void converterPedido()} className="rounded-xl bg-emerald-600 px-4 py-3 font-bold disabled:opacity-40"><Send className="mr-2 inline" size={18}/> {tc("proposal.generateOrder")}</button></div></section>}</div>}
 </div></main>
}
function CampoEmail({titulo,valor,alterar,obrigatorio=false}:{titulo:string;valor:string;alterar:(v:string)=>void;obrigatorio?:boolean}){return <label className="block"><span className="mb-2 block text-sm">{titulo}{obrigatorio?" *":""}</span><textarea value={valor} onChange={e=>alterar(e.target.value)} rows={2} className="w-full rounded-2xl border border-[#24466f] bg-[#020817] px-4 py-3"/></label>}
function Info({label,valor}:{label:string;valor:string}){return <div className="rounded-2xl border border-[#16325c] bg-[#091a33] p-4"><p className="text-xs text-slate-400">{label}</p><strong className="mt-1 block">{valor}</strong></div>}
