"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import JornadaComercialNav from "@/components/crm/JornadaComercialNav"
import CrmFiltrosComerciais from "@/components/crm-app/CrmFiltrosComerciais"
import { useAuth } from "@/core/auth/AuthContext"
import { useOperationalI18n } from "@/core/i18n/operational"
import { pertenceAoEscopoDoUsuario, possuiEscopoProprio } from "@/core/rbac/commercial-scope"
import { API_URL } from "@/lib/api"
import { aplicarFiltrosComerciais, calcularMetricasPrazo, FILTROS_CRM_VAZIOS, montarRegistroAnalitico, opcoesUnicas, type CrmFiltrosComerciais as FiltrosComerciais } from "@/lib/crm-analise-comercial"
import { exportarRelatorioCrmPdf } from "@/lib/crm-relatorio-pdf"

type Snapshot = { validade?: string | null; oportunidade?: { titulo?: string; cliente_nome?: string; empresa_nome?: string } }
type Proposta = { id: string; numero?: string; cliente_id?: string; oportunidade_id?: string; item_oportunidade_id?: string; valor?: number; status?: string; status_documento?: string; validade?: string; versao?: number; created_at?: string; snapshot_dados?: Snapshot }
type LinhaNucleo = { oportunidade_id?: string; proposta_id?: string; proposta_vigente_id?: string; cliente_nome?: string; titulo?: string; responsavel_id?:string|null; responsavel_nome?:string|null; linha_equipamentos?:string|null; equipamento?:string|null; data_fechamento_prevista?:string|null }
type LinhaProposta = { proposta: Proposta; cliente: string; oportunidade: string; validade: string; nucleo?:LinhaNucleo }
type FiltroProposta = "TODOS" | "ACEITAS" | "ELABORACAO" | "EMITIDA" | "ENVIADA" | "EM_NEGOCIACAO" | "ACEITA" | "CANCELADA"
type UsuarioOpcao={id:string;nome:string}

const textos = {
  "pt-BR": { subtitle:"Documento comercial da negociação: versão, emissão e aceite. Após a conversão, o registro segue para Pedidos.", dealsWithProposal:"Propostas ativas", consolidatedValue:"Valor comercial consolidado", acceptedConverted:"Aceitas", status:"Status", all:"Todos", title:"Propostas comerciais", explanation:"Aqui se administra cada proposta até o aceite; após a conversão, ela sai desta etapa e o pedido aparece em Pedidos.", currentFilter:"Filtro atual", loading:"Carregando...", client:"Cliente", currentProposal:"Proposta", opportunity:"Oportunidade", value:"Valor", validity:"Validade", versions:"Versão", action:"Ação", noNumber:"Proposta sem número", data:"Dados", view:"Visualizar proposta", unidentifiedClient:"Cliente não identificado", genericOpportunity:"Oportunidade comercial", notProvided:"Não informada", click:"Clique para detalhar", responsible:"Responsável", line:"Linha", includedAt:"Inclusão", forecastAt:"Previsão", planned:"Prazo previsto", elapsed:"Decorrido", overdue:"Atraso", statuses:{ RASCUNHO:"Em elaboração", ELABORACAO:"Em elaboração", EM_REVISAO:"Em revisão", APROVADA_INTERNA:"Aprovada internamente", EMITIDA:"Emitida", ENVIADA:"Enviada", VISUALIZADA:"Visualizada", EM_NEGOCIACAO:"Em negociação", APROVADA:"Aceita", ACEITA:"Aceita", CONVERTIDA_PEDIDO:"Convertida em pedido", SUBSTITUIDA:"Substituída", REJEITADA:"Rejeitada", EXPIRADA:"Expirada", CANCELADA:"Cancelada" } },
  en: { subtitle:"Commercial document for the deal: versioning, issuance and acceptance. After conversion, the record moves to Orders.", dealsWithProposal:"Active proposals", consolidatedValue:"Consolidated proposal value", acceptedConverted:"Accepted", status:"Status", all:"All", title:"Sales proposals", explanation:"Each proposal is managed here through acceptance; after conversion, it leaves this stage and the order appears in Orders.", currentFilter:"Current filter", loading:"Loading...", client:"Account", currentProposal:"Proposal", opportunity:"Opportunity", value:"Value", validity:"Valid until", versions:"Version", action:"Action", noNumber:"Proposal without number", data:"Details", view:"View proposal", unidentifiedClient:"Account not identified", genericOpportunity:"Commercial opportunity", notProvided:"Not provided", click:"Click to view details", responsible:"Owner", line:"Line", includedAt:"Created", forecastAt:"Forecast", planned:"Planned", elapsed:"Elapsed", overdue:"Overdue", statuses:{ RASCUNHO:"Draft", ELABORACAO:"Draft", EM_REVISAO:"Under review", APROVADA_INTERNA:"Internally approved", EMITIDA:"Issued", ENVIADA:"Sent", VISUALIZADA:"Viewed", EM_NEGOCIACAO:"In negotiation", APROVADA:"Accepted", ACEITA:"Accepted", CONVERTIDA_PEDIDO:"Converted to order", SUBSTITUIDA:"Superseded", REJEITADA:"Rejected", EXPIRADA:"Expired", CANCELADA:"Cancelled" } },
  es: { subtitle:"Documento comercial de la negociación: versión, emisión y aceptación. Después de la conversión, el registro pasa a Pedidos.", dealsWithProposal:"Propuestas activas", consolidatedValue:"Valor comercial consolidado", acceptedConverted:"Aceptadas", status:"Estado", all:"Todos", title:"Propuestas comerciales", explanation:"Aquí se administra cada propuesta hasta la aceptación; después de la conversión, sale de esta etapa y el pedido aparece en Pedidos.", currentFilter:"Filtro actual", loading:"Cargando...", client:"Cliente", currentProposal:"Propuesta", opportunity:"Oportunidad", value:"Valor", validity:"Vigencia", versions:"Versión", action:"Acción", noNumber:"Propuesta sin número", data:"Datos", view:"Ver propuesta", unidentifiedClient:"Cliente no identificado", genericOpportunity:"Oportunidad comercial", notProvided:"No informado", click:"Haga clic para detallar", responsible:"Responsable", line:"Línea", includedAt:"Inclusión", forecastAt:"Previsión", planned:"Plazo previsto", elapsed:"Transcurrido", overdue:"Atraso", statuses:{ RASCUNHO:"En elaboración", ELABORACAO:"En elaboración", EM_REVISAO:"En revisión", APROVADA_INTERNA:"Aprobada internamente", EMITIDA:"Emitida", ENVIADA:"Enviada", VISUALIZADA:"Visualizada", EM_NEGOCIACAO:"En negociación", APROVADA:"Aceptada", ACEITA:"Aceptada", CONVERTIDA_PEDIDO:"Convertida en pedido", SUBSTITUIDA:"Sustituida", REJEITADA:"Rechazada", EXPIRADA:"Vencida", CANCELADA:"Cancelada" } }
} as const

function statusCodigo(item: Proposta) { return String(item.status_documento || item.status || "RASCUNHO").toUpperCase() }
function aceita(item: Proposta){return ["ACEITA","APROVADA"].includes(statusCodigo(item))}
function correspondeFiltro(item: Proposta, filtro: FiltroProposta) { const codigo=statusCodigo(item); if(filtro==="TODOS")return true;if(filtro==="ACEITAS")return aceita(item);if(filtro==="ELABORACAO")return ["RASCUNHO","ELABORACAO"].includes(codigo);if(filtro==="ACEITA")return ["ACEITA","APROVADA"].includes(codigo);return codigo===filtro }
function listaUsuarios(payload:unknown):UsuarioOpcao[]{if(!Array.isArray(payload))return[];return payload.map(item=>{const i=item as Record<string,unknown>;return{id:String(i.id||"").trim(),nome:String(i.nome||i.email||"").trim()}}).filter(i=>i.id&&i.nome)}
function dias(v:number|null){return v===null?"—":`${v}d`}

export default function PropostasPage() {
  const { usuario } = useAuth()
  const { locale, tOp, formatCurrency, formatNumber, formatDate } = useOperationalI18n()
  const tx=textos[locale], master=String(usuario?.tipo_usuario||"").toUpperCase()==="ADMIN_MASTER"
  const [dados,setDados]=useState<Proposta[]>([]),[nucleo,setNucleo]=useState<LinhaNucleo[]>([]),[loading,setLoading]=useState(true),[erro,setErro]=useState(""),[filtro,setFiltro]=useState<FiltroProposta>("TODOS"),[filtrosComerciais,setFiltrosComerciais]=useState<FiltrosComerciais>(FILTROS_CRM_VAZIOS),[usuarios,setUsuarios]=useState<UsuarioOpcao[]>([])
  useEffect(()=>{void(async()=>{try{const [rp,rn]=await Promise.all([fetch(`${API_URL}/crm/propostas`,{cache:"no-store"}),fetch(`${API_URL}/crm/nucleo-comercial`,{cache:"no-store"})]);const pp=await rp.json().catch(()=>[]),np=await rn.json().catch(()=>[]);if(!rp.ok)throw new Error(pp?.detail||tx.loading);setDados(Array.isArray(pp)?pp:[]);setNucleo(rn.ok&&Array.isArray(np)?np:[])}catch(e){setErro(e instanceof Error?e.message:tx.loading)}finally{setLoading(false)}})()},[tx.loading])
  useEffect(()=>{if(!master){const id=String(usuario?.id||"").trim(),nome=String(usuario?.nome||usuario?.email||"").trim();setUsuarios(id&&nome?[{id,nome}]:[]);return}fetch("/api/crm-proxy/governanca/usuarios",{cache:"no-store"}).then(async r=>r.ok?listaUsuarios(await r.json().catch(()=>[])):[]).then(setUsuarios).catch(()=>setUsuarios([]))},[master,usuario?.id,usuario?.nome,usuario?.email])
  const nucleoEscopado=useMemo(()=>nucleo.filter(item=>pertenceAoEscopoDoUsuario(item.responsavel_id,usuario)),[nucleo,usuario])
  const oportunidadesPermitidas=useMemo(()=>new Set(nucleoEscopado.map(item=>String(item.oportunidade_id||"")).filter(Boolean)),[nucleoEscopado])
  const dadosEscopados=useMemo(()=>possuiEscopoProprio(usuario)?dados.filter(item=>Boolean(item.oportunidade_id)&&oportunidadesPermitidas.has(String(item.oportunidade_id))):dados,[dados,oportunidadesPermitidas,usuario])
  const propostasAtivas=useMemo(()=>dadosEscopados.filter(item=>statusCodigo(item)!=="CONVERTIDA_PEDIDO"),[dadosEscopados])
  const linhas=useMemo<LinhaProposta[]>(()=>{const mapaNucleo=new Map<string,LinhaNucleo>();for(const item of nucleoEscopado){for(const chave of [item.proposta_id,item.proposta_vigente_id,item.oportunidade_id])if(chave)mapaNucleo.set(chave,item)}return propostasAtivas.map(proposta=>{const snap=proposta.snapshot_dados,linha=mapaNucleo.get(proposta.id)||mapaNucleo.get(proposta.oportunidade_id||"");return{proposta,cliente:linha?.cliente_nome||snap?.oportunidade?.cliente_nome||snap?.oportunidade?.empresa_nome||tx.unidentifiedClient,oportunidade:linha?.titulo||snap?.oportunidade?.titulo||tx.genericOpportunity,validade:proposta.validade||snap?.validade||tx.notProvided,nucleo:linha}}).sort((a,b)=>String(b.proposta.created_at||"").localeCompare(String(a.proposta.created_at||"")))},[propostasAtivas,nucleoEscopado,tx.genericOpportunity,tx.notProvided,tx.unidentifiedClient])
  const nomesPorId=useMemo(()=>Object.fromEntries(usuarios.map(i=>[i.id,i.nome])),[usuarios])
  const analiticos=useMemo(()=>linhas.map(l=>{const n=l.nucleo||{};const a=montarRegistroAnalitico({...l.proposta,responsavel_id:n.responsavel_id,responsavel_nome:n.responsavel_nome,linha_equipamentos:n.linha_equipamentos,equipamento:n.equipamento,data_fechamento_prevista:n.data_fechamento_prevista},nomesPorId);return{...a,linhaProposta:l}}),[linhas,nomesPorId])
  const linhasFiltro=useMemo(()=>opcoesUnicas(analiticos.map(i=>i.linha),"Não informada"),[analiticos])
  const responsaveis=useMemo(()=>{const base=[...usuarios];for(const i of analiticos)if(i.responsavelId&&!base.some(u=>u.id===i.responsavelId))base.push({id:i.responsavelId,nome:i.responsavelNome});return base.sort((a,b)=>a.nome.localeCompare(b.nome,locale))},[usuarios,analiticos,locale])
  const comercial=useMemo(()=>aplicarFiltrosComerciais(analiticos,filtrosComerciais,master,String(usuario?.id||"")),[analiticos,filtrosComerciais,master,usuario?.id])
  const filtrados=comercial.filter(a=>correspondeFiltro(a.linhaProposta.proposta,filtro))
  const valor=comercial.reduce((s,a)=>s+Number(a.linhaProposta.proposta.valor||0),0),aceitas=comercial.filter(a=>aceita(a.linhaProposta.proposta)).length
  const statusLabel=(item:Proposta)=>tx.statuses[statusCodigo(item) as keyof typeof tx.statuses] || statusCodigo(item).replaceAll("_"," ")
  const filtroLabel=(valorFiltro:FiltroProposta)=>valorFiltro==="TODOS"?tx.all:valorFiltro==="ACEITAS"?tx.acceptedConverted:valorFiltro==="ELABORACAO"?tx.statuses.ELABORACAO:valorFiltro==="ACEITA"?tx.statuses.ACEITA:tx.statuses[valorFiltro as keyof typeof tx.statuses] || valorFiltro
  function abrirComposicao(novoFiltro:FiltroProposta){setFiltro(novoFiltro);window.setTimeout(()=>document.getElementById("lista-propostas")?.scrollIntoView({behavior:"smooth",block:"start"}),0)}
  function exportarPdf(){exportarRelatorioCrmPdf({titulo:tx.title,subtitulo:tx.subtitle,colunas:[{chave:"proposta",titulo:tx.currentProposal},{chave:"cliente",titulo:tx.client},{chave:"responsavel",titulo:tx.responsible},{chave:"linha",titulo:tx.line},{chave:"oportunidade",titulo:tx.opportunity},{chave:"status",titulo:tx.status},{chave:"valor",titulo:tx.value},{chave:"inclusao",titulo:tx.includedAt},{chave:"previsao",titulo:tx.forecastAt},{chave:"atraso",titulo:tx.overdue}],registros:filtrados.map(a=>{const l=a.linhaProposta,m=calcularMetricasPrazo(a.dataInclusao,a.dataPrevista,["ACEITA","APROVADA","CANCELADA","REJEITADA","EXPIRADA"].includes(statusCodigo(l.proposta)));return{proposta:l.proposta.numero||tx.noNumber,cliente:l.cliente,responsavel:a.responsavelNome,linha:a.linha,oportunidade:l.oportunidade,status:statusLabel(l.proposta),valor:formatCurrency(Number(l.proposta.valor||0)),inclusao:a.dataInclusao?formatDate(a.dataInclusao):"—",previsao:a.dataPrevista?formatDate(a.dataPrevista):"—",atraso:m.atrasado?`${m.diasAtraso} dias`:"—"}})})}
  return <main className="flex min-h-screen bg-[#020817]"><Sidebar/><section className="flex-1"><Topbar/><div className="space-y-6 p-8">
    <div><h1 className="text-4xl font-bold text-white">CRM • {tOp("proposals.title")}</h1><p className="mt-2 text-gray-400">{tx.subtitle}</p></div><JornadaComercialNav/>
    <CrmFiltrosComerciais filtros={filtrosComerciais} onChange={setFiltrosComerciais} master={master} responsaveis={responsaveis} linhas={linhasFiltro} totalFiltrado={filtrados.length} onPdf={exportarPdf}/>
    {erro&&<div className="rounded-xl border border-red-500 p-4 text-red-300">{erro}</div>}
    <section className="grid gap-4 md:grid-cols-3"><Kpi titulo={tx.dealsWithProposal} valor={formatNumber(comercial.length)} onOpen={()=>abrirComposicao("TODOS")} detalhe={tx.click}/><Kpi titulo={tx.consolidatedValue} valor={formatCurrency(valor)} onOpen={()=>abrirComposicao("TODOS")} detalhe={tx.click}/><Kpi titulo={tx.acceptedConverted} valor={formatNumber(aceitas)} onOpen={()=>abrirComposicao("ACEITAS")} detalhe={tx.click}/></section>
    <section className="rounded-2xl border border-[#13203f] bg-[#071226] p-5"><label className="text-sm text-gray-300">{tx.status}<select value={filtro} onChange={e=>setFiltro(e.target.value as FiltroProposta)} className="ml-3 rounded-lg border border-[#24466f] bg-[#020817] px-3 py-2 text-white"><option value="TODOS">{tx.all}</option><option value="ACEITAS">{tx.acceptedConverted}</option><option value="ELABORACAO">{tx.statuses.ELABORACAO}</option><option value="EMITIDA">{tx.statuses.EMITIDA}</option><option value="ENVIADA">{tx.statuses.ENVIADA}</option><option value="EM_NEGOCIACAO">{tx.statuses.EM_NEGOCIACAO}</option><option value="ACEITA">{tx.statuses.ACEITA}</option><option value="CANCELADA">{tx.statuses.CANCELADA}</option></select></label></section>
    <div id="lista-propostas" className="scroll-mt-24 overflow-hidden rounded-2xl border border-[#13203f] bg-[#091a33]"><div className="border-b border-[#13203f] p-6"><h2 className="text-xl font-semibold text-white">{tx.title}</h2><p className="mt-1 text-sm text-slate-400">{tx.explanation} {tx.currentFilter}: {filtroLabel(filtro)} · {formatNumber(filtrados.length)}.</p></div>{loading?<div className="p-10 text-gray-400">{tx.loading}</div>:<div className="overflow-x-auto"><table className="min-w-[1400px] w-full"><thead><tr className="border-b border-[#13203f]"><Th>{tx.client}</Th><Th>{tx.currentProposal}</Th><Th>{tx.opportunity}</Th><Th>{tx.responsible}</Th><Th>{tx.line}</Th><Th>{tx.value}</Th><Th>{tx.status}</Th><Th>{tx.includedAt}</Th><Th>{tx.forecastAt}</Th><Th>{tx.planned}</Th><Th>{tx.elapsed}</Th><Th>{tx.overdue}</Th><Th>{tx.action}</Th></tr></thead><tbody>{filtrados.map(a=>{const l=a.linhaProposta,m=calcularMetricasPrazo(a.dataInclusao,a.dataPrevista,["ACEITA","APROVADA","CANCELADA","REJEITADA","EXPIRADA"].includes(statusCodigo(l.proposta)));return <tr key={l.proposta.id} className="border-b border-[#13203f]"><Td>{l.cliente}</Td><Td>{l.proposta.numero||tx.noNumber}</Td><Td>{l.oportunidade}</Td><Td>{a.responsavelNome}</Td><Td>{a.linha}</Td><td className="p-4 text-green-400">{formatCurrency(Number(l.proposta.valor||0))}</td><td className="p-4 text-cyan-400">{statusLabel(l.proposta)}</td><Td>{a.dataInclusao?formatDate(a.dataInclusao):"—"}</Td><Td>{a.dataPrevista?formatDate(a.dataPrevista):"—"}</Td><Td>{dias(m.diasPlanejados)}</Td><Td>{dias(m.diasDecorridos)}</Td><td className={`p-4 ${m.atrasado?"font-semibold text-amber-300":"text-white"}`}>{m.atrasado?`${m.diasAtraso}d`:"—"}</td><td className="p-4"><div className="flex gap-2"><Link href={`/propostas/${l.proposta.id}`} className="rounded-lg border border-slate-600 px-3 py-2 text-xs text-slate-200">{tx.data}</Link><Link href={`/propostas/${l.proposta.id}/documento`} className="rounded-lg bg-cyan-500 px-3 py-2 text-xs font-semibold text-slate-950">{tx.view}</Link></div></td></tr>})}</tbody></table></div>}</div>
  </div></section></main>
}
function Kpi({titulo,valor,onOpen,detalhe}:{titulo:string;valor:string|number;onOpen?:()=>void;detalhe:string}){const body=<><p className="text-sm text-gray-400">{titulo}</p><h2 className="mt-2 text-3xl font-bold text-cyan-400">{valor}</h2>{onOpen&&<p className="mt-2 text-[11px] text-cyan-400">{detalhe}</p>}</>;return onOpen?<button type="button" onClick={onOpen} className="rounded-2xl border border-[#13203f] bg-[#091a33] p-6 text-left transition hover:border-cyan-500/70 hover:bg-[#0b1d38]">{body}</button>:<div className="rounded-2xl border border-[#13203f] bg-[#091a33] p-6">{body}</div>}
function Th({children}:{children:React.ReactNode}){return <th className="p-4 text-left text-gray-400">{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td className="p-4 text-white">{children}</td>}
