"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import JornadaComercialNav from "@/components/crm/JornadaComercialNav"
import { useAuth } from "@/core/auth/AuthContext"
import { pertenceAoEscopoDoUsuario, possuiEscopoProprio } from "@/core/rbac/commercial-scope"
import { API_URL } from "@/lib/api"

type Snapshot = { validade?: string | null; oportunidade?: { titulo?: string; cliente_nome?: string; empresa_nome?: string } }
type Proposta = { id: string; numero?: string; cliente_id?: string; oportunidade_id?: string; item_oportunidade_id?: string; valor?: number; status?: string; status_documento?: string; validade?: string; versao?: number; created_at?: string; snapshot_dados?: Snapshot }
type LinhaNucleo = { oportunidade_id?: string; proposta_id?: string; proposta_vigente_id?: string; cliente_nome?: string; titulo?: string; responsavel_id?:string|null }
type Grupo = { chave: string; proposta: Proposta; versoes: Proposta[]; cliente: string; oportunidade: string; validade: string }
type FiltroProposta = "TODOS" | "ACEITAS_CONVERTIDAS" | string

function status(item: Proposta) {
  const valor = String(item.status_documento || item.status || "RASCUNHO").toUpperCase()
  const mapa: Record<string, string> = { RASCUNHO:"Em elaboração", ELABORACAO:"Em elaboração", EM_REVISAO:"Em revisão", APROVADA_INTERNA:"Aprovada internamente", EMITIDA:"Emitida", ENVIADA:"Enviada", VISUALIZADA:"Visualizada", EM_NEGOCIACAO:"Em negociação", APROVADA:"Aceita", ACEITA:"Aceita", CONVERTIDA_PEDIDO:"Convertida em pedido", SUBSTITUIDA:"Substituída", REJEITADA:"Rejeitada", EXPIRADA:"Expirada", CANCELADA:"Cancelada" }
  return mapa[valor] || valor.replaceAll("_", " ")
}
function aceitaOuConvertida(item: Proposta){return ["ACEITA","CONVERTIDA_PEDIDO","APROVADA"].includes(String(item.status_documento||item.status||"").toUpperCase())}
function prioridade(item: Proposta) { const valor=String(item.status_documento||item.status||"").toUpperCase(); if(valor==="CONVERTIDA_PEDIDO")return 60;if(["ACEITA","APROVADA"].includes(valor))return 50;if(["EMITIDA","ENVIADA","VISUALIZADA","EM_NEGOCIACAO"].includes(valor))return 40;if(["APROVADA_INTERNA","EM_REVISAO"].includes(valor))return 30;if(["RASCUNHO","ELABORACAO"].includes(valor))return 20;return 10 }

export default function PropostasPage() {
  const { usuario } = useAuth()
  const [dados,setDados]=useState<Proposta[]>([]),[nucleo,setNucleo]=useState<LinhaNucleo[]>([]),[loading,setLoading]=useState(true),[erro,setErro]=useState(""),[filtro,setFiltro]=useState<FiltroProposta>("TODOS")
  useEffect(()=>{void(async()=>{try{const [rp,rn]=await Promise.all([fetch(`${API_URL}/crm/propostas`,{cache:"no-store"}),fetch(`${API_URL}/crm/nucleo-comercial`,{cache:"no-store"})]);const pp=await rp.json().catch(()=>[]),np=await rn.json().catch(()=>[]);if(!rp.ok)throw new Error(pp?.detail||"Não foi possível carregar as propostas.");setDados(Array.isArray(pp)?pp:[]);setNucleo(rn.ok&&Array.isArray(np)?np:[])}catch(e){setErro(e instanceof Error?e.message:"Falha ao carregar propostas.")}finally{setLoading(false)}})()},[])
  const nucleoEscopado=useMemo(()=>nucleo.filter(item=>pertenceAoEscopoDoUsuario(item.responsavel_id,usuario)),[nucleo,usuario])
  const oportunidadesPermitidas=useMemo(()=>new Set(nucleoEscopado.map(item=>String(item.oportunidade_id||"")).filter(Boolean)),[nucleoEscopado])
  const dadosEscopados=useMemo(()=>possuiEscopoProprio(usuario)?dados.filter(item=>Boolean(item.oportunidade_id)&&oportunidadesPermitidas.has(String(item.oportunidade_id))):dados,[dados,oportunidadesPermitidas,usuario])
  const grupos=useMemo<Grupo[]>(()=>{const mapaNucleo=new Map<string,LinhaNucleo>();for(const item of nucleoEscopado){for(const chave of [item.proposta_id,item.proposta_vigente_id,item.oportunidade_id])if(chave)mapaNucleo.set(chave,item)}const mapa=new Map<string,Proposta[]>();for(const proposta of dadosEscopados){const chave=proposta.item_oportunidade_id||proposta.oportunidade_id||proposta.id;mapa.set(chave,[...(mapa.get(chave)||[]),proposta])}return[...mapa.entries()].map(([chave,versoes])=>{const ordenadas=[...versoes].sort((a,b)=>prioridade(b)-prioridade(a)||Number(b.versao||0)-Number(a.versao||0)||String(b.created_at||"").localeCompare(String(a.created_at||"")));const proposta=ordenadas[0],snap=proposta.snapshot_dados,linha=mapaNucleo.get(proposta.id)||mapaNucleo.get(proposta.oportunidade_id||"");return{chave,proposta,versoes:[...versoes].sort((a,b)=>Number(b.versao||0)-Number(a.versao||0)),cliente:linha?.cliente_nome||snap?.oportunidade?.cliente_nome||snap?.oportunidade?.empresa_nome||"Cliente não identificado",oportunidade:linha?.titulo||snap?.oportunidade?.titulo||"Oportunidade comercial",validade:proposta.validade||snap?.validade||"Não informada"}}).sort((a,b)=>String(b.proposta.created_at||"").localeCompare(String(a.proposta.created_at||"")))},[dadosEscopados,nucleoEscopado])
  const filtrados=grupos.filter(g=>filtro==="TODOS"?true:filtro==="ACEITAS_CONVERTIDAS"?aceitaOuConvertida(g.proposta):status(g.proposta)===filtro),valor=grupos.reduce((s,g)=>s+Number(g.proposta.valor||0),0),aceitas=grupos.filter(g=>aceitaOuConvertida(g.proposta)).length
  function abrirComposicao(novoFiltro:FiltroProposta){setFiltro(novoFiltro);window.setTimeout(()=>document.getElementById("lista-propostas")?.scrollIntoView({behavior:"smooth",block:"start"}),0)}
  return <main className="flex min-h-screen bg-[#020817]"><Sidebar/><section className="flex-1"><Topbar/><div className="space-y-6 p-8">
    <div><h1 className="text-4xl font-bold text-white">CRM • Propostas</h1><p className="mt-2 text-gray-400">Documento comercial da negociação: versão, emissão, aceite e conversão. O negócio continua sendo a mesma oportunidade.</p></div>
    <JornadaComercialNav/>
    {erro&&<div className="rounded-xl border border-red-500 p-4 text-red-300">{erro}</div>}
    <section className="grid gap-4 md:grid-cols-3"><Kpi titulo="Negociações com proposta" valor={grupos.length} onOpen={()=>abrirComposicao("TODOS")}/><Kpi titulo="Valor comercial consolidado" valor={`R$ ${valor.toLocaleString("pt-BR")}`} onOpen={()=>abrirComposicao("TODOS")}/><Kpi titulo="Aceitas / convertidas" valor={aceitas} onOpen={()=>abrirComposicao("ACEITAS_CONVERTIDAS")}/></section>
    <section className="rounded-2xl border border-[#13203f] bg-[#071226] p-5"><label className="text-sm text-gray-300">Status<select value={filtro} onChange={e=>setFiltro(e.target.value)} className="ml-3 rounded-lg border border-[#24466f] bg-[#020817] px-3 py-2 text-white"><option value="TODOS">Todos</option><option value="ACEITAS_CONVERTIDAS">Aceitas / convertidas</option><option>Em elaboração</option><option>Emitida</option><option>Enviada</option><option>Em negociação</option><option>Aceita</option><option>Convertida em pedido</option><option>Cancelada</option></select></label></section>
    <div id="lista-propostas" className="scroll-mt-24 overflow-hidden rounded-2xl border border-[#13203f] bg-[#091a33]"><div className="border-b border-[#13203f] p-6"><h2 className="text-xl font-semibold text-white">Propostas comerciais</h2><p className="mt-1 text-sm text-slate-400">Aqui se administra o documento; pedido e venda aparecem nas etapas seguintes da mesma jornada. Filtro atual: {filtro === "ACEITAS_CONVERTIDAS" ? "Aceitas / convertidas" : filtro} · {filtrados.length.toLocaleString("pt-BR")} negociação(ões).</p></div>{loading?<div className="p-10 text-gray-400">Carregando...</div>:<div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-[#13203f]"><Th>Cliente</Th><Th>Proposta vigente</Th><Th>Oportunidade</Th><Th>Valor</Th><Th>Status</Th><Th>Validade</Th><Th>Versões</Th><Th>Ação</Th></tr></thead><tbody>{filtrados.map(g=><tr key={g.chave} className="border-b border-[#13203f]"><Td>{g.cliente}</Td><Td>{g.proposta.numero||"Proposta sem número"}</Td><Td>{g.oportunidade}</Td><td className="p-4 text-green-400">R$ {Number(g.proposta.valor||0).toLocaleString("pt-BR")}</td><td className="p-4 text-cyan-400">{status(g.proposta)}</td><Td>{g.validade}</Td><Td>{String(g.versoes.length)}</Td><td className="p-4"><div className="flex gap-2"><Link href={`/propostas/${g.proposta.id}`} className="rounded-lg border border-slate-600 px-3 py-2 text-xs text-slate-200">Dados</Link><Link href={`/propostas/${g.proposta.id}/documento`} className="rounded-lg bg-cyan-500 px-3 py-2 text-xs font-semibold text-slate-950">Visualizar proposta</Link></div></td></tr>)}</tbody></table></div>}</div>
  </div></section></main>
}
function Kpi({titulo,valor,onOpen}:{titulo:string;valor:string|number;onOpen?:()=>void}){const body=<><p className="text-sm text-gray-400">{titulo}</p><h2 className="mt-2 text-3xl font-bold text-cyan-400">{valor}</h2>{onOpen&&<p className="mt-2 text-[11px] text-cyan-400">Clique para detalhar</p>}</>;return onOpen?<button type="button" onClick={onOpen} className="rounded-2xl border border-[#13203f] bg-[#091a33] p-6 text-left transition hover:border-cyan-500/70 hover:bg-[#0b1d38]">{body}</button>:<div className="rounded-2xl border border-[#13203f] bg-[#091a33] p-6">{body}</div>}
function Th({children}:{children:React.ReactNode}){return <th className="p-4 text-left text-gray-400">{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td className="p-4 text-white">{children}</td>}
