"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import { useAuth } from "@/core/auth/AuthContext"
import { useOperationalContext } from "@/context/OperationalContext"
import { useStrategicI18n } from "@/core/i18n/strategic"
import { getMapaEstrategico, type MapaEstrategicoResumo, type RankingItem } from "@/services/modulos-api"

export default function Page() {
  const { usuario } = useAuth(); const { contextoAtual, queryString } = useOperationalContext(); const { t, formatNumber, formatCurrency } = useStrategicI18n()
  const [dados,setDados]=useState<MapaEstrategicoResumo|null>(null),[loading,setLoading]=useState(true),[erro,setErro]=useState("")
  const queryEstrategica=(()=>{const q=new URLSearchParams(queryString||"");q.set("periodo","ANO_ATUAL");q.delete("inicio");q.delete("fim");return q.toString()})()
  useEffect(()=>{let ativo=true;queueMicrotask(()=>{if(!ativo)return;setLoading(true);setErro("");getMapaEstrategico(queryEstrategica).then((mapa)=>{if(!ativo)return;setDados(mapa)}).catch(()=>{if(ativo)setErro(t("map.loadError"))}).finally(()=>{if(ativo)setLoading(false)})});return()=>{ativo=false}},[queryEstrategica,t])
  const perfil=String(usuario?.tipo_usuario||"").toUpperCase(), gestaoComercial=perfil==="ADMIN_MASTER"||perfil==="DIRETOR_VIENA_SP", escopoExibido=gestaoComercial?t("map.consolidatedScope"):t("map.allowedScope",{name:usuario?.nome||t("map.authUser")})
  const numero=(v:number)=>formatNumber(Number(v||0)), moeda=(v:number)=>formatCurrency(Number(v||0),{maximumFractionDigits:0})
  const drill=(camada:"anfir"|"historico"|"crm",campo:string|undefined,valor:string|undefined,titulo:string)=>hrefDrill(camada,campo,valor,titulo,queryEstrategica,t("map.drillSub"))
  return <main className="flex min-h-screen bg-[#020817] text-white"><Sidebar/><section className="min-w-0 flex-1"><Topbar/><div className="space-y-7 p-4 sm:p-6 lg:p-8">
    <header><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-400">Leitura estratégica regional</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Mapa Comercial Estratégico</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-400">Leitura territorial e comercial do mercado refrigerado, preservando ANFIR, Histórico Comercial e CRM como fontes independentes e rastreáveis.</p><div className="mt-4 flex flex-wrap gap-2 text-xs"><Pill>{t("common.scope")}: {escopoExibido}</Pill><Pill>{t("common.session")}: {usuario?.nome||t("map.authUser")}</Pill><Pill>{t("common.context")}: {contextoAtual.label}</Pill><Pill>{t("common.period")}: 2026</Pill></div></header>
    <div className="rounded-xl border border-cyan-500/25 bg-cyan-950/10 p-4 text-sm leading-6 text-cyan-100/80"><strong>Base comparável 2026.</strong> ANFIR e Histórico/Funil são recortados para 2026. O CRM representa somente a operação efetivamente registrada desde sua entrada em uso e não gera crítica retroativa por períodos anteriores ao seu lançamento.</div>
    {erro&&<div className="rounded-xl border border-red-500/60 bg-red-950/20 p-4 text-red-200">{erro}</div>}{loading&&<div className="rounded-2xl border border-[#17304d] bg-[#071226] p-6 text-slate-400">{t("map.loading")}</div>}
    {!loading&&dados&&<><section className="grid gap-4 md:grid-cols-3"><Kpi titulo="ANFIR 2026 · realizado" valor={numero(dados.realizado.total_registros)} apoio={moeda(dados.realizado.valor_total)} tom="cyan" href={drill("anfir",undefined,undefined,"ANFIR 2026 · realizado")} detalhe={t("common.clickDetail")}/><Kpi titulo="Histórico / Funil 2026" valor={numero(dados.historico_comercial.total_registros)} apoio={t("map.nominalUnits",{count:numero(dados.historico_comercial.total_unidades)})} tom="amber" href={drill("historico",undefined,undefined,"Histórico / Funil 2026")} detalhe={t("common.clickDetail")}/><Kpi titulo="CRM · desde início da operação" valor={numero(dados.em_curso.total_registros)} apoio={moeda(dados.em_curso.valor_pipeline)} tom="emerald" href={drill("crm",undefined,undefined,"CRM · desde início da operação")} detalhe={t("common.clickDetail")}/></section>

    <section className="rounded-2xl border border-[#17304d] bg-[#071226] p-5">
      <div className="flex flex-col gap-2 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-cyan-300">Ciclo comercial comparável</p><h2 className="mt-1 text-xl font-semibold">CRM → Funil / Histórico 2026 → ANFIR 2026</h2></div><p className="max-w-2xl text-xs leading-5 text-slate-500">As três camadas continuam independentes. O CTI usa 2026 como janela estratégica comum, sem interpretar a ausência de registros no CRM antes de sua implantação como falha comercial.</p></div>
      <div className="mt-5 grid gap-3 lg:grid-cols-[1fr_auto_1fr_auto_1fr] lg:items-stretch">
        <EtapaCiclo titulo="1 · CRM em curso" valor={numero(dados.em_curso.total_registros)} apoio={moeda(dados.em_curso.valor_pipeline)} descricao="Negociações e oportunidades registradas desde a entrada operacional do CRM." tom="emerald" href={drill("crm",undefined,undefined,"CRM em curso")}/>
        <SetaCiclo/>
        <EtapaCiclo titulo="2 · Funil / Histórico 2026" valor={numero(dados.historico_comercial.total_registros)} apoio={t("map.nominalUnits",{count:numero(dados.historico_comercial.total_unidades)})} descricao="Registros comerciais de 2026 preservados para acompanhamento e comparação." tom="amber" href={drill("historico",undefined,undefined,"Funil / Histórico 2026")}/>
        <SetaCiclo/>
        <EtapaCiclo titulo="3 · ANFIR 2026 realizado" valor={numero(dados.realizado.total_registros)} apoio={moeda(dados.realizado.valor_total)} descricao="Mercado efetivamente observado na ANFIR dentro da janela 2026." tom="cyan" href={drill("anfir",undefined,undefined,"ANFIR 2026 realizado")}/>
      </div>
      <div className="mt-5 grid gap-4 xl:grid-cols-2">
        <div className="rounded-xl border border-[#13203f] bg-[#08162d] p-4"><h3 className="font-semibold text-slate-100">Leitura gerencial imediata</h3><div className="mt-3 space-y-2 text-sm text-slate-400"><p>• CRM mostra o que a equipe está trabalhando desde que a ferramenta entrou em operação.</p><p>• Histórico/Funil mostra somente os registros comerciais de 2026.</p><p>• ANFIR mostra somente o mercado realizado de 2026.</p></div></div>
        <div className="rounded-xl border border-[#13203f] bg-[#08162d] p-4"><h3 className="font-semibold text-slate-100">Regra de avaliação da equipe</h3><div className="mt-3 space-y-2 text-sm text-slate-400"><p>• Não gerar negativa por ausência de CRM anterior ao lançamento da ferramenta.</p><p>• Alertas de acompanhamento serão avaliados somente sobre oportunidades e eventos posteriores à entrada operacional do CRM.</p><p>• Ganhos e perdas devem ser sustentados por evidência do ciclo comercial, nunca pela simples diferença entre os totais das três camadas.</p></div></div>
      </div>
    </section>

    <section className="grid gap-5 xl:grid-cols-3"><Ranking titulo="Cobertura por estado · ANFIR 2026" itens={dados.realizado.estados} vazio={t("map.noState")} camada="anfir" campo="estado" queryString={queryEstrategica} subtitulo={t("map.drillSub")} formatNumber={formatNumber}/><Ranking titulo="Cobertura por município · ANFIR 2026" itens={dados.realizado.municipios} vazio={t("map.noCity")} camada="anfir" campo="municipio" queryString={queryEstrategica} subtitulo={t("map.drillSub")} formatNumber={formatNumber}/><Ranking titulo="Cobertura por DDD · ANFIR 2026" itens={dados.realizado.ddds} vazio={t("map.noDdd")} camada="anfir" campo="ddd" queryString={queryEstrategica} subtitulo={t("map.drillSub")} formatNumber={formatNumber}/></section>
    <section className="rounded-2xl border border-[#17304d] bg-[#071226] p-5"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-cyan-300">{t("map.familyCross")}</p><h2 className="mt-1 text-lg font-semibold">Camadas 2026</h2></div><p className="text-xs text-slate-500">{t("map.noSum")}</p></div><div className="grid gap-3 md:grid-cols-3">{familias(dados).map(item=><div key={item.nome} className="rounded-xl border border-[#13203f] bg-[#08162d] p-4"><h3 className="font-semibold">{item.nome}</h3><div className="mt-3 space-y-2 text-sm"><Linha rotulo="ANFIR 2026" valor={item.realizado} cor="text-cyan-300" href={drill("anfir","familia",item.slug,`${item.nome} · ANFIR 2026`)} formatNumber={formatNumber}/><Linha rotulo="Histórico 2026" valor={item.historico} cor="text-amber-300" href={drill("historico","familia",item.slug,`${item.nome} · Histórico 2026`)} formatNumber={formatNumber}/><Linha rotulo="CRM em curso" valor={item.emCurso} cor="text-emerald-300" href={drill("crm","familia",item.slug,`${item.nome} · CRM em curso`)} formatNumber={formatNumber}/></div></div>)}</div></section>
    <section className="grid gap-5 xl:grid-cols-3"><Ranking titulo="Empresas · ANFIR 2026" itens={dados.realizado.empresas} vazio={t("map.noCompany")} camada="anfir" campo="empresa" queryString={queryEstrategica} subtitulo={t("map.drillSub")} formatNumber={formatNumber}/><Ranking titulo="Equipamentos · Histórico 2026" itens={dados.historico_comercial.equipamentos} vazio={t("map.noHistEquipment")} camada="historico" campo="equipamento" queryString={queryEstrategica} subtitulo={t("map.drillSub")} formatNumber={formatNumber}/><Ranking titulo="Equipamentos · CRM em curso" itens={dados.em_curso.equipamentos} vazio={t("map.noLiveEquipment")} camada="crm" campo="equipamento" queryString={queryEstrategica} subtitulo={t("map.drillSub")} formatNumber={formatNumber}/></section>
    <section className="grid gap-5 xl:grid-cols-2"><Ranking titulo="Implementadoras · ANFIR 2026" itens={dados.realizado.implementadoras} vazio={t("map.noBodyBuilder")} camada="anfir" campo="implementadora" queryString={queryEstrategica} subtitulo={t("map.drillSub")} formatNumber={formatNumber}/><Ranking titulo="Implementadoras · Histórico 2026" itens={dados.historico_comercial.implementadoras} vazio={t("map.noHistBodyBuilder")} camada="historico" campo="implementadora" queryString={queryEstrategica} subtitulo={t("map.drillSub")} formatNumber={formatNumber}/></section>
    <div className="rounded-xl border border-cyan-500/25 bg-cyan-950/10 p-4 text-sm leading-6 text-cyan-100/80">A correlação é estratégica, não uma fusão de registros. O recorte 2026 torna as camadas comparáveis sem transformar diferença de cobertura temporal em avaliação negativa da equipe.</div></>}
  </div></section></main>
}
function Pill({children}:{children:React.ReactNode}){return <span className="rounded-full border border-slate-700 bg-slate-900/70 px-3 py-1.5 text-slate-300">{children}</span>}
function hrefDrill(camada:"anfir"|"historico"|"crm",campo:string|undefined,valor:string|undefined,titulo:string,base:string,subtitulo:string){const q=new URLSearchParams(base||"");q.set("camada",camada);q.set("titulo",titulo);q.set("subtitulo",subtitulo);if(campo)q.set("campo",campo);if(valor)q.set("valor",valor);return `/detalhamento?${q.toString()}`}
function Kpi({titulo,valor,apoio,tom,href,detalhe}:{titulo:string;valor:string;apoio:string;tom:"cyan"|"amber"|"emerald";href:string;detalhe:string}){const cor=tom==="amber"?"text-amber-300":tom==="emerald"?"text-emerald-300":"text-cyan-300";return <Link href={href} className="rounded-2xl border border-[#17304d] bg-[#071226] p-5 transition hover:border-cyan-500/70 hover:bg-[#0a1a31]"><p className={`text-xs font-semibold uppercase tracking-[.14em] ${cor}`}>{titulo}</p><strong className="mt-2 block text-3xl">{valor}</strong><p className="mt-1 text-sm text-slate-400">{apoio}</p><p className="mt-3 text-[11px] text-slate-500">{detalhe}</p></Link>}
function EtapaCiclo({titulo,valor,apoio,descricao,tom,href}:{titulo:string;valor:string;apoio:string;descricao:string;tom:"cyan"|"amber"|"emerald";href:string}){const cor=tom==="amber"?"text-amber-300":tom==="emerald"?"text-emerald-300":"text-cyan-300";return <Link href={href} className="rounded-xl border border-[#13203f] bg-[#08162d] p-4 transition hover:border-cyan-500/60"><p className={`text-xs font-semibold uppercase tracking-[.12em] ${cor}`}>{titulo}</p><strong className="mt-2 block text-3xl">{valor}</strong><p className="mt-1 text-sm text-slate-300">{apoio}</p><p className="mt-3 text-xs leading-5 text-slate-500">{descricao}</p></Link>}
function SetaCiclo(){return <div className="hidden items-center justify-center text-2xl text-cyan-400/70 lg:flex">→</div>}
function Ranking({titulo,itens,vazio,camada,campo,queryString,subtitulo,formatNumber}:{titulo:string;itens:RankingItem[];vazio:string;camada:"anfir"|"historico"|"crm";campo:string;queryString:string;subtitulo:string;formatNumber:(v:number)=>string}){return <section className="rounded-2xl border border-[#17304d] bg-[#071226] p-5"><h2 className="font-semibold">{titulo}</h2>{itens.length===0?<p className="mt-4 text-sm text-slate-500">{vazio}</p>:<div className="mt-4 space-y-2">{itens.slice(0,12).map(item=><Link href={hrefDrill(camada,campo,item.nome,`${titulo} · ${item.nome}`,queryString,subtitulo)} key={item.nome} className="flex items-center justify-between gap-4 rounded-xl bg-[#08162d] px-3 py-2.5 text-sm transition hover:bg-[#0b1d38] hover:ring-1 hover:ring-cyan-500/50"><span className="min-w-0 truncate text-slate-300">{item.nome}</span><strong className="shrink-0 text-cyan-300">{formatNumber(item.quantidade_registros)}</strong></Link>)}</div>}</section>}
function Linha({rotulo,valor,cor,href,formatNumber}:{rotulo:string;valor:number;cor:string;href:string;formatNumber:(v:number)=>string}){return <Link href={href} className="flex items-center justify-between gap-3 rounded-lg px-2 py-1 transition hover:bg-[#0b1d38]"><span className="text-slate-400">{rotulo}</span><strong className={cor}>{formatNumber(valor)}</strong></Link>}
function familias(dados:MapaEstrategicoResumo){const itens=[{nome:"TR • Trailer",slug:"trailer"},{nome:"DT • Diesel Truck",slug:"diesel-truck"},{nome:"DD • Direct Drive",slug:"direct-drive"}];const procurar=(lista:RankingItem[]|undefined,nome:string)=>lista?.find(i=>i.nome===nome)?.quantidade_registros??0;return itens.map(item=>({...item,realizado:procurar(dados.realizado.familias,item.nome),historico:procurar(dados.historico_comercial.familias,item.nome),emCurso:procurar(dados.em_curso.familias,item.nome)}))}