"use client"

import Link from "next/link"
import { FormEvent, useEffect, useMemo, useRef, useState } from "react"
import { ArrowLeft, Check, ClipboardCheck, Loader2, MapPinned, Search } from "lucide-react"
import { useAuth } from "@/core/auth"
import { ControlledSelect } from "@/components/crm-app/ControlledSelect"
import { useOperationalI18n } from "@/core/i18n/operational"
import { fetchCrmSeguroProxy } from "@/services/crm-secure"

type Cliente = { id: string; nome: string; cidade?: string; estado?: string }
type Negociacao = { oportunidade_id:string; cliente_id:string; cliente_nome?:string; titulo:string; etapa:string; proposta_id?:string|null; proposta_numero?:string|null; pedido_id?:string|null; pedido_numero?:string|null; encerrada?:boolean }
type Registro = Record<string, unknown>
type Locale = "pt-BR" | "en" | "es"

const textos = {
  "pt-BR": { title:"Nova atividade", banner:"Uma única criação para todas as interações", bannerHelp:"A atividade pode estar ligada a um cliente/negociação ou a um parceiro de negócio sem cadastro de cliente.", registeredAccount:"Cliente cadastrado", accountPlaceholder:"Opcional: digite pelo menos 2 letras do nome", partnerIntro:"Ou registre a atividade para parceiro de negócio / contato externo", partnerName:"Nome da pessoa ou parceiro", partnerOrg:"Empresa/organização (opcional)", selectedAccount:"Cliente selecionado", dealPreserved:"negociação preservada", partnerContact:"Parceiro/contato", relatedDeal:"Negociação relacionada", relatedHelp:"Opcional. Para parceiro/contato externo, permanece sem negociação relacionada e não bloqueia o registro.", generalAccount:"Interação geral com o cliente", noDeal:"Sem negociação relacionada", activityType:"Tipo de atividade", visitGoal:"Objetivo da visita", fieldTitle:"Título", date:"Data", time:"Horário", description:"Descrição", saving:"Salvando...", save:"Salvar atividade", load:"Não foi possível carregar clientes e negociações.", chooseContext:"Selecione um cliente ou informe um parceiro/contato externo.", auth:"Não foi possível confirmar o usuário autenticado.", success:"Atividade registrada com sucesso. Redirecionando para a Central de Atividades...", saveFail:"Não foi possível salvar a atividade.", dealFallback:"Oportunidade comercial" },
  en: { title:"New activity", banner:"One creation flow for every interaction", bannerHelp:"The activity can be linked to an account/deal or to an external business partner that is not registered as an account.", registeredAccount:"Registered account", accountPlaceholder:"Optional: type at least 2 letters of the account name", partnerIntro:"Or record the activity for a business partner / external contact", partnerName:"Person or partner name", partnerOrg:"Company/organization (optional)", selectedAccount:"Selected account", dealPreserved:"deal preserved", partnerContact:"Partner/contact", relatedDeal:"Related deal", relatedHelp:"Optional. For an external partner/contact it remains without a related deal and does not block the record.", generalAccount:"General interaction with the account", noDeal:"No related deal", activityType:"Activity type", visitGoal:"Visit objective", fieldTitle:"Title", date:"Date", time:"Time", description:"Description", saving:"Saving...", save:"Save activity", load:"We couldn't load accounts and deals.", chooseContext:"Select an account or enter an external partner/contact.", auth:"We couldn't confirm the authenticated user.", success:"Activity recorded successfully. Redirecting to Activity Center...", saveFail:"We couldn't save the activity.", dealFallback:"Sales opportunity" },
  es: { title:"Nueva actividad", banner:"Una sola creación para todas las interacciones", bannerHelp:"La actividad puede estar vinculada a un cliente/negocio o a un socio comercial externo sin registro de cliente.", registeredAccount:"Cliente registrado", accountPlaceholder:"Opcional: escriba al menos 2 letras del nombre", partnerIntro:"O registre la actividad para un socio comercial / contacto externo", partnerName:"Nombre de la persona o socio", partnerOrg:"Empresa/organización (opcional)", selectedAccount:"Cliente seleccionado", dealPreserved:"negocio preservado", partnerContact:"Socio/contacto", relatedDeal:"Negocio relacionado", relatedHelp:"Opcional. Para socio/contacto externo permanece sin negocio relacionado y no bloquea el registro.", generalAccount:"Interacción general con el cliente", noDeal:"Sin negocio relacionado", activityType:"Tipo de actividad", visitGoal:"Objetivo de la visita", fieldTitle:"Título", date:"Fecha", time:"Hora", description:"Descripción", saving:"Guardando...", save:"Guardar actividad", load:"No fue posible cargar clientes y negocios.", chooseContext:"Seleccione un cliente o informe un socio/contacto externo.", auth:"No fue posible confirmar el usuario autenticado.", success:"Actividad registrada con éxito. Redirigiendo al Centro de Actividades...", saveFail:"No fue posible guardar la actividad.", dealFallback:"Oportunidad comercial" },
} satisfies Record<Locale, Record<string,string>>

const tiposPorIdioma: Record<Locale, readonly (readonly [string,string])[]> = {
  "pt-BR": [["VISITA_PRESENCIAL","Visita presencial"],["VISITA_REMOTA","Visita remota"],["LIGACAO","Ligação"],["WHATSAPP","WhatsApp"],["EMAIL","E-mail"],["FOLLOW_UP","Follow-up"],["REUNIAO","Reunião"],["APRESENTACAO","Apresentação"],["PROSPECCAO","Prospecção"],["POS_VENDA","Pós-venda"],["OUTRO","Outro"]],
  en: [["VISITA_PRESENCIAL","On-site visit"],["VISITA_REMOTA","Remote visit"],["LIGACAO","Phone call"],["WHATSAPP","WhatsApp"],["EMAIL","Email"],["FOLLOW_UP","Follow-up"],["REUNIAO","Meeting"],["APRESENTACAO","Presentation"],["PROSPECCAO","Prospecting"],["POS_VENDA","After-sales"],["OUTRO","Other"]],
  es: [["VISITA_PRESENCIAL","Visita presencial"],["VISITA_REMOTA","Visita remota"],["LIGACAO","Llamada"],["WHATSAPP","WhatsApp"],["EMAIL","Correo electrónico"],["FOLLOW_UP","Seguimiento"],["REUNIAO","Reunión"],["APRESENTACAO","Presentación"],["PROSPECCAO","Prospección"],["POS_VENDA","Posventa"],["OUTRO","Otro"]],
}
const parceirosPorIdioma: Record<Locale, readonly (readonly [string,string])[]> = {
  "pt-BR": [["PESSOA_FISICA","Pessoa física / contato"],["EMPRESA","Empresa / parceiro de negócio"],["IMPLEMENTADORA","Implementadora"],["AUTORIZADA_CARRIER","Autorizada Carrier"],["FORNECEDOR","Fornecedor"],["OUTRO","Outro"]],
  en: [["PESSOA_FISICA","Individual / contact"],["EMPRESA","Company / business partner"],["IMPLEMENTADORA","Body builder"],["AUTORIZADA_CARRIER","Carrier authorized dealer"],["FORNECEDOR","Supplier"],["OUTRO","Other"]],
  es: [["PESSOA_FISICA","Persona física / contacto"],["EMPRESA","Empresa / socio comercial"],["IMPLEMENTADORA","Implementadora"],["AUTORIZADA_CARRIER","Autorizada Carrier"],["FORNECEDOR","Proveedor"],["OUTRO","Otro"]],
}
function texto(valor:unknown){return String(valor??"").trim()}
function chave(valor:unknown){return texto(valor).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase()}
function etapaLegivel(valor:string, locale:Locale){const m:Record<Locale,Record<string,string>>={"pt-BR":{OPORTUNIDADE:"Oportunidade",PROPOSTA:"Proposta",NEGOCIACAO:"Negociação",PEDIDO:"Pedido",GANHO:"Ganho",PERDIDO:"Perdido"},en:{OPORTUNIDADE:"Opportunity",PROPOSTA:"Proposal",NEGOCIACAO:"Negotiation",PEDIDO:"Order",GANHO:"Won",PERDIDO:"Lost"},es:{OPORTUNIDADE:"Oportunidad",PROPOSTA:"Propuesta",NEGOCIACAO:"Negociación",PEDIDO:"Pedido",GANHO:"Ganado",PERDIDO:"Perdido"}};return m[locale][valor.toUpperCase()]||valor.replaceAll("_"," ")}

export default function NovaAtividadePage(){
  const {usuario}=useAuth(); const {locale}=useOperationalI18n(); const idioma=locale as Locale; const t=textos[idioma]||textos["pt-BR"]
  const tipos=tiposPorIdioma[idioma]; const tiposParceiro=parceirosPorIdioma[idioma]
  const[clientes,setClientes]=useState<Cliente[]>([]),[negociacoes,setNegociacoes]=useState<Negociacao[]>([]),[clienteBusca,setClienteBusca]=useState(""),[cliente,setCliente]=useState<Cliente|null>(null),[parceiroNome,setParceiroNome]=useState(""),[parceiroTipo,setParceiroTipo]=useState("PESSOA_FISICA"),[parceiroOrganizacao,setParceiroOrganizacao]=useState(""),[oportunidadeId,setOportunidadeId]=useState(""),[tipo,setTipo]=useState("FOLLOW_UP"),[carregando,setCarregando]=useState(true),[salvando,setSalvando]=useState(false),[erro,setErro]=useState(""),[sucesso,setSucesso]=useState("")
  const envioEmCursoRef=useRef(false)
  useEffect(()=>{let ativo=true;void(async()=>{setCarregando(true);setErro("");try{const params=new URLSearchParams(window.location.search),clienteContexto=texto(params.get("cliente")),oportunidadeContexto=texto(params.get("oportunidade")),tipoContexto=texto(params.get("tipo")).toUpperCase();const[cr,nr]=await Promise.all([fetch("/api/crm-proxy/crm-app/clientes",{cache:"no-store"}),fetchCrmSeguroProxy("crm-seguro/nucleo-comercial",{cache:"no-store"})]);const cd=await cr.json().catch(()=>[]),nd=await nr.json().catch(()=>[]);if(!cr.ok)throw new Error(String((cd as Registro).detail||`HTTP ${cr.status}`));if(!nr.ok)throw new Error(String((nd as Registro).detail||`HTTP ${nr.status}`));if(!ativo)return;const lc=(Array.isArray(cd)?cd:[]).map((i:Registro)=>({id:texto(i.id),nome:texto(i.nome||i.razao_social||i.nome_fantasia),cidade:texto(i.cidade||i.municipio),estado:texto(i.estado||i.uf)})).filter(i=>i.id&&i.nome).sort((a,b)=>a.nome.localeCompare(b.nome,locale));const ln=(Array.isArray(nd)?nd:[]).map((i:Registro)=>({oportunidade_id:texto(i.oportunidade_id),cliente_id:texto(i.cliente_id),cliente_nome:texto(i.cliente_nome),titulo:texto(i.titulo)||t.dealFallback,etapa:texto(i.etapa)||"OPORTUNIDADE",proposta_id:texto(i.proposta_id)||null,proposta_numero:texto(i.proposta_numero)||null,pedido_id:texto(i.pedido_id)||null,pedido_numero:texto(i.pedido_numero)||null,encerrada:Boolean(i.encerrada)})).filter(i=>i.oportunidade_id);setClientes(lc);setNegociacoes(ln);if(tipoContexto&&tipos.some(([v])=>v===tipoContexto))setTipo(tipoContexto);const ni=oportunidadeContexto?ln.find(i=>i.oportunidade_id===oportunidadeContexto):undefined,idc=clienteContexto||ni?.cliente_id||"",nome=ni?.cliente_nome||"",ci=lc.find(i=>i.id===idc)||lc.find(i=>nome&&chave(i.nome)===chave(nome));if(ci){setCliente(ci);setClienteBusca(ci.nome)}if(ni)setOportunidadeId(ni.oportunidade_id)}catch(f){if(ativo)setErro(f instanceof Error?f.message:t.load)}finally{if(ativo)setCarregando(false)}})();return()=>{ativo=false}},[locale,t.load,t.dealFallback,tipos])
  const sugestoes=useMemo(()=>{const termo=clienteBusca.trim().toLocaleLowerCase(locale);if(termo.length<2||cliente)return[];return clientes.filter(i=>`${i.nome} ${i.cidade||""} ${i.estado||""}`.toLocaleLowerCase(locale).includes(termo)).slice(0,12)},[clienteBusca,cliente,clientes,locale])
  const negociacoesDoCliente=useMemo(()=>negociacoes.filter(i=>!i.encerrada&&(i.cliente_id===cliente?.id||i.cliente_nome?.toLocaleLowerCase(locale)===cliente?.nome.toLocaleLowerCase(locale))),[cliente,negociacoes,locale])
  const opcoesNegociacao=useMemo(()=>[["",cliente?t.generalAccount:t.noDeal],...negociacoesDoCliente.map(i=>[i.oportunidade_id,`${i.titulo} — ${etapaLegivel(i.etapa,idioma)}`] as const)] as const,[cliente,negociacoesDoCliente,t.generalAccount,t.noDeal,idioma])
  const negociacaoSelecionada=useMemo(()=>negociacoes.find(i=>i.oportunidade_id===oportunidadeId)||null,[negociacoes,oportunidadeId]);const visita=tipo.startsWith("VISITA"),contextoValido=Boolean(cliente||parceiroNome.trim())
  function limparParceiro(){setParceiroNome("");setParceiroOrganizacao("")}
  async function salvar(e:FormEvent<HTMLFormElement>){e.preventDefault();if(envioEmCursoRef.current)return;setErro("");setSucesso("");if(!contextoValido)return setErro(t.chooseContext);if(!usuario?.id)return setErro(t.auth);envioEmCursoRef.current=true;setSalvando(true);const d=new FormData(e.currentTarget);try{const r=await fetchCrmSeguroProxy("crm-seguro/atividades",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cliente_id:cliente?.id||null,parceiro_nome:cliente?null:parceiroNome.trim(),parceiro_tipo:cliente?null:parceiroTipo,parceiro_organizacao:cliente?null:parceiroOrganizacao.trim()||null,oportunidade_id:cliente?negociacaoSelecionada?.oportunidade_id||null:null,proposta_id:cliente?negociacaoSelecionada?.proposta_id||null:null,pedido_id:cliente?negociacaoSelecionada?.pedido_id||null:null,usuario_id:usuario.id,tipo,titulo:texto(d.get("titulo")),descricao:texto(d.get("descricao"))||null,data:texto(d.get("data"))||null,horario:texto(d.get("horario"))||null,status:"PENDENTE"})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(texto(p.detail)||`HTTP ${r.status}`);setSucesso(t.success);window.location.href="/crm-app/atividades"}catch(f){envioEmCursoRef.current=false;setErro(f instanceof Error?f.message:t.saveFail)}finally{setSalvando(false)}}
  return <main className="min-h-[100dvh] bg-[#020817] px-4 py-5 text-white sm:px-6"><div className="mx-auto max-w-3xl"><header className="mb-5 flex items-center gap-3"><Link href="/crm-app" className="grid size-11 place-items-center rounded-2xl border border-[#16325c] bg-[#091a33] text-cyan-300"><ArrowLeft size={20}/></Link><div><p className="text-xs uppercase tracking-[0.24em] text-cyan-400">CTI CRM</p><h1 className="text-2xl font-bold">{t.title}</h1></div></header><section className="mb-4 rounded-3xl border border-[#16325c] bg-gradient-to-br from-[#0a2242] to-[#07162b] p-5"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-cyan-950/60 text-cyan-300">{visita?<MapPinned/>:<ClipboardCheck/>}</span><div><strong className="block text-lg">{t.banner}</strong><span className="text-sm text-slate-400">{t.bannerHelp}</span></div></div></section>{erro&&<div className="mb-4 rounded-2xl border border-red-900 bg-red-950/40 p-4 text-sm text-red-200">{erro}</div>}{sucesso&&<div className="mb-4 rounded-2xl border border-emerald-900 bg-emerald-950/40 p-4 text-sm text-emerald-200">{sucesso}</div>}{carregando?<div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-cyan-300"/></div>:<form onSubmit={salvar} className="grid gap-4 rounded-3xl border border-[#16325c] bg-[#07162b] p-5 sm:grid-cols-2">
  <label className="relative sm:col-span-2"><span className="mb-2 block text-sm text-slate-300">{t.registeredAccount}</span><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18}/><input value={clienteBusca} onChange={e=>{setClienteBusca(e.target.value);setCliente(null);setOportunidadeId("")}} placeholder={t.accountPlaceholder} className="h-12 w-full rounded-2xl border border-[#24466f] bg-[#020817] pl-11 pr-4"/></div>{sugestoes.length>0&&<div className="absolute z-20 mt-2 max-h-64 w-full overflow-auto rounded-2xl border border-[#24466f] bg-[#07162b] shadow-2xl">{sugestoes.map(i=><button type="button" key={i.id} onClick={()=>{setCliente(i);setClienteBusca(i.nome);limparParceiro();setOportunidadeId("")}} className="flex w-full items-center justify-between border-b border-[#16325c] px-4 py-3 text-left last:border-0"><span><strong className="block">{i.nome}</strong><small className="text-slate-400">{[i.cidade,i.estado].filter(Boolean).join("/")||t.registeredAccount}</small></span><Check size={16} className="text-cyan-300"/></button>)}</div>}</label>
  <div className="sm:col-span-2 rounded-2xl border border-[#24466f] bg-[#020817]/60 p-4"><div className="mb-3 text-sm text-slate-300">{t.partnerIntro}</div><div className="grid gap-3 sm:grid-cols-2"><input value={parceiroNome} onChange={e=>{setParceiroNome(e.target.value);if(e.target.value.trim()){setCliente(null);setClienteBusca("");setOportunidadeId("")}}} placeholder={t.partnerName} className="h-12 rounded-2xl border border-[#24466f] bg-[#020817] px-4"/><ControlledSelect value={parceiroTipo} onChange={setParceiroTipo} options={tiposParceiro}/><input value={parceiroOrganizacao} onChange={e=>setParceiroOrganizacao(e.target.value)} placeholder={t.partnerOrg} className="h-12 rounded-2xl border border-[#24466f] bg-[#020817] px-4 sm:col-span-2"/></div></div>
  {cliente&&<div className="sm:col-span-2 rounded-xl border border-emerald-900 bg-emerald-950/20 p-3 text-sm text-emerald-200">{t.selectedAccount}: <strong>{cliente.nome}</strong>{oportunidadeId?` · ${t.dealPreserved}`:""}</div>}{!cliente&&parceiroNome.trim()&&<div className="sm:col-span-2 rounded-xl border border-cyan-900 bg-cyan-950/20 p-3 text-sm text-cyan-200">{t.partnerContact}: <strong>{parceiroNome.trim()}</strong>{parceiroOrganizacao.trim()?` · ${parceiroOrganizacao.trim()}`:""}</div>}
  <div className="sm:col-span-2"><span className="mb-2 block text-sm text-slate-300">{t.relatedDeal}</span><ControlledSelect value={oportunidadeId} onChange={setOportunidadeId} options={opcoesNegociacao}/><small className="mt-1 block text-slate-500">{t.relatedHelp}</small></div><div><span className="mb-2 block text-sm text-slate-300">{t.activityType}</span><ControlledSelect value={tipo} onChange={setTipo} options={tipos}/></div><Campo name="titulo" label={visita?t.visitGoal:t.fieldTitle} required/><Campo name="data" label={t.date} type="date" required/><Campo name="horario" label={t.time} type="time"/><label className="sm:col-span-2"><span className="mb-2 block text-sm text-slate-300">{t.description}</span><textarea name="descricao" rows={5} className="w-full rounded-2xl border border-[#24466f] bg-[#020817] p-4"/></label><button disabled={salvando||!contextoValido} className="sm:col-span-2 h-12 rounded-2xl bg-cyan-500 font-semibold text-slate-950 disabled:opacity-60">{salvando?t.saving:t.save}</button></form>}</div></main>
}
function Campo({name,label,type="text",required=false}:{name:string;label:string;type?:string;required?:boolean}){return <label><span className="mb-2 block text-sm text-slate-300">{label}</span><input name={name} type={type} required={required} className="h-12 w-full rounded-2xl border border-[#24466f] bg-[#020817] px-4"/></label>}
