"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { ArrowLeft, CircleDollarSign, ClipboardCheck, Loader2, PackageCheck, Search } from "lucide-react"
import JornadaDocumentalNav from "@/components/crm-app/JornadaDocumentalNav"
import { useAuth } from "@/core/auth/AuthContext"
import { useOperationalI18n } from "@/core/i18n/operational"
import { pertenceAoEscopoDoUsuario, possuiEscopoProprio } from "@/core/rbac/commercial-scope"

type Venda = { id?: string; cliente_id?: string; oportunidade_id?: string; pedido_id?: string; cliente_nome?: string; pedido_numero?: string; equipamento_nome?: string; equipamento_codigo?: string; tipo_venda?: string; valor?: number; data_venda?: string }
type LinhaNucleo={oportunidade_id?:string;pedido_id?:string|null;responsavel_id?:string|null}
type Locale="pt-BR"|"en"|"es"
const textos={
 "pt-BR":{title:"Vendas realizadas",subtitle:"Histórico dos negócios concluídos e ponto de partida do pós-venda",registered:"Vendas registradas",realized:"Valor realizado",search:"Buscar cliente, pedido, equipamento ou tipo",empty:"Nenhuma venda encontrada.",load:"Não foi possível carregar as vendas.",account:"Cliente não identificado",equipment:"Equipamento a definir",order:"Pedido",openOrder:"Abrir pedido de origem",afterSales:"Registrar pós-venda",sale:"VENDA"},
 en:{title:"Closed sales",subtitle:"Completed business history and the starting point for after-sales follow-up",registered:"Recorded sales",realized:"Realized revenue",search:"Search account, order, equipment or sale type",empty:"No sales found.",load:"We couldn't load sales.",account:"Account not identified",equipment:"Equipment to be defined",order:"Order",openOrder:"Open source order",afterSales:"Log after-sales follow-up",sale:"SALE"},
 es:{title:"Ventas realizadas",subtitle:"Historial de negocios concluidos y punto de partida del seguimiento posventa",registered:"Ventas registradas",realized:"Valor realizado",search:"Buscar cliente, pedido, equipo o tipo de venta",empty:"No se encontraron ventas.",load:"No fue posible cargar las ventas.",account:"Cliente no identificado",equipment:"Equipo por definir",order:"Pedido",openOrder:"Abrir pedido de origen",afterSales:"Registrar seguimiento posventa",sale:"VENTA"},
} satisfies Record<Locale,Record<string,string>>
function tipoVendaLegivel(valor:string|undefined,locale:Locale){const key=String(valor||"VENDA").toUpperCase();const m:Record<string,[string,string,string]>={EQUIPAMENTO:["Equipamento","Equipment","Equipo"],PECA:["Peça","Part","Repuesto"],SERVICO:["Serviço","Service","Servicio"],OUTRA:["Outra","Other","Otra"],VENDA:["Venda","Sale","Venta"]};const i=locale==="en"?1:locale==="es"?2:0;return m[key]?.[i]??String(valor||"")}

export default function VendasCrmAppPage(){
  const { usuario } = useAuth()
  const { locale, formatCurrency, formatDate, formatNumber } = useOperationalI18n()
  const idioma=locale as Locale,t=textos[idioma]||textos["pt-BR"]
  const [dados,setDados]=useState<Venda[]>([]),[busca,setBusca]=useState(""),[carregando,setCarregando]=useState(true),[erro,setErro]=useState("")
  useEffect(()=>{Promise.all([fetch("/api/crm-proxy/vendas",{cache:"no-store"}),fetch("/api/crm-proxy/crm/nucleo-comercial",{cache:"no-store"})]).then(async([rv,rn])=>{const vendas=await rv.json().catch(()=>[]),nucleo=await rn.json().catch(()=>[]);if(!rv.ok)throw new Error(String(vendas.detail||`HTTP ${rv.status}`));const listaVendas=Array.isArray(vendas)?vendas:[];if(!possuiEscopoProprio(usuario)){setDados(listaVendas);return}const permitidas=(rn.ok&&Array.isArray(nucleo)?nucleo:[]).filter((i:LinhaNucleo)=>pertenceAoEscopoDoUsuario(i.responsavel_id,usuario));const ops=new Set(permitidas.map((i:LinhaNucleo)=>String(i.oportunidade_id||"")).filter(Boolean)),pedidos=new Set(permitidas.map((i:LinhaNucleo)=>String(i.pedido_id||"")).filter(Boolean));setDados(listaVendas.filter((i:Venda)=>(Boolean(i.oportunidade_id)&&ops.has(String(i.oportunidade_id)))||(Boolean(i.pedido_id)&&pedidos.has(String(i.pedido_id)))))}).catch(f=>setErro(f instanceof Error?f.message:t.load)).finally(()=>setCarregando(false))},[usuario,t.load])
  const filtrados=useMemo(()=>{const termo=busca.trim().toLocaleLowerCase(locale);if(!termo)return dados;return dados.filter(i=>`${i.cliente_nome||""} ${i.pedido_numero||""} ${i.equipamento_nome||i.equipamento_codigo||""} ${i.tipo_venda||""}`.toLocaleLowerCase(locale).includes(termo))},[busca,dados,locale])
  const valorTotal=dados.reduce((t,i)=>t+Number(i.valor||0),0)
  const data=(valor?:string)=>valor?formatDate(new Date(`${valor}T12:00:00`)):"—"
  return <main className="min-h-[100dvh] bg-[#020817] px-4 py-5 pb-24 text-white sm:px-6"><div className="mx-auto max-w-6xl">
    <header className="mb-5 flex items-center gap-3"><Link href="/crm-app" className="grid size-11 place-items-center rounded-2xl border border-[#16325c] bg-[#091a33] text-cyan-300"><ArrowLeft size={20}/></Link><div><p className="text-xs uppercase tracking-[.24em] text-cyan-400">CTI CRM</p><h1 className="text-2xl font-bold">{t.title}</h1><p className="text-sm text-slate-400">{t.subtitle}</p></div></header>
    <JornadaDocumentalNav/>
    <section className="mb-4 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-[#16325c] bg-[#07162b] p-4"><p className="text-xs uppercase tracking-[.12em] text-slate-500">{t.registered}</p><strong className="mt-2 block text-2xl text-cyan-300">{formatNumber(dados.length)}</strong></div><div className="rounded-2xl border border-[#16325c] bg-[#07162b] p-4"><p className="text-xs uppercase tracking-[.12em] text-slate-500">{t.realized}</p><strong className="mt-2 block text-2xl text-emerald-300">{formatCurrency(valorTotal)}</strong></div></section>
    <label className="relative mb-4 block"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder={t.search} className="h-12 w-full rounded-2xl border border-[#16325c] bg-[#07162b] pl-11 pr-4"/></label>
    {erro&&<div className="rounded-2xl border border-red-900 bg-red-950/40 p-4 text-red-200">{erro}</div>}
    {carregando?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-cyan-300"/></div>:filtrados.length===0?<div className="rounded-3xl border border-dashed border-[#24466f] p-8 text-center text-slate-400">{t.empty}</div>:<div className="space-y-3">{filtrados.map((item,index)=>{const contexto=[item.cliente_id?`cliente=${encodeURIComponent(item.cliente_id)}`:"",item.oportunidade_id?`oportunidade=${encodeURIComponent(item.oportunidade_id)}`:"","tipo=POS_VENDA"].filter(Boolean).join("&");return <article key={item.id||index} className="rounded-3xl border border-[#16325c] bg-[#07162b] p-5"><div className="flex items-center gap-4"><span className="rounded-2xl bg-emerald-950/40 p-3 text-emerald-300"><CircleDollarSign size={22}/></span><span className="min-w-0 flex-1"><strong className="block truncate text-lg">{item.cliente_nome||t.account}</strong><span className="mt-1 block text-sm text-slate-300">{item.equipamento_nome||item.equipamento_codigo||t.equipment}</span><span className="mt-2 block text-xs text-slate-500">{data(item.data_venda)} · {tipoVendaLegivel(item.tipo_venda,idioma)||t.sale} · {formatCurrency(Number(item.valor||0))}</span><span className="mt-1 block text-[11px] text-slate-600">{t.order} {item.pedido_numero||"—"}</span></span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{item.pedido_id&&<Link href={`/crm-app/pedidos/${encodeURIComponent(item.pedido_id)}`} className="flex items-center justify-center gap-2 rounded-xl border border-[#24466f] px-3 py-3 text-sm font-semibold text-cyan-200"><PackageCheck size={16}/>{t.openOrder}</Link>}<Link href={`/crm-app/atividades/nova?${contexto}`} className="flex items-center justify-center gap-2 rounded-xl bg-cyan-500 px-3 py-3 text-sm font-bold text-slate-950"><ClipboardCheck size={16}/>{t.afterSales}</Link></div></article>})}</div>}
  </div></main>
}
