/* eslint-disable react-hooks/set-state-in-effect */
"use client"

import Link from "next/link"
import { FormEvent, useEffect, useState } from "react"
import { useParams } from "next/navigation"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import { fetchCrmSeguroProxy } from "@/services/crm-secure"
import { useClosureI18n } from "@/core/i18n/closure"

type Registro=Record<string,unknown>
type Destinatario={id:string;nome?:string;email?:string;cargo?:string;regiao?:string}
type Detalhes={pedido:Registro;proposta:Registro;item:Registro;aceite:Registro;destinatarios_disponiveis:Destinatario[];envios:Registro[]}
type Locale="pt-BR"|"en"|"es"
const local={
 "pt-BR":{summary:"Resumo do pedido",carrierInfo:"A etapa CARRIER só será confirmada depois do envio real pelo provedor de e-mail e da gravação do protocolo.",defaultNote:"Encaminhamento do dossiê comercial gerado pelo CTI.",subject:"Encaminhamento CARRIER",pending:"PENDENTE"},
 en:{summary:"Order summary",carrierInfo:"The CARRIER stage is confirmed only after actual email delivery and protocol registration.",defaultNote:"Commercial dossier forwarded from CTI.",subject:"CARRIER delivery",pending:"PENDING"},
 es:{summary:"Resumen del pedido",carrierInfo:"La etapa CARRIER solo se confirmará después del envío real por correo y del registro del protocolo.",defaultNote:"Envío del expediente comercial generado por CTI.",subject:"Envío CARRIER",pending:"PENDIENTE"}
} satisfies Record<Locale,Record<string,string>>

export default function PedidoDetalhesPage(){
 const params=useParams<{id:string}>(),id=String(params?.id||"");const {locale,tc,formatCurrency,formatDate}=useClosureI18n(),t=local[locale as Locale]||local["pt-BR"]
 const[dados,setDados]=useState<Detalhes|null>(null),[selecionados,setSelecionados]=useState<string[]>([]),[loading,setLoading]=useState(true),[salvando,setSalvando]=useState(false),[erro,setErro]=useState(""),[mensagem,setMensagem]=useState("")
 const moeda=(v:unknown)=>formatCurrency(Number(v||0)),dataHora=(v:unknown)=>!v?"-":formatDate(String(v),{dateStyle:"short",timeStyle:"short"})
 async function carregar(){setLoading(true);setErro("");try{const r=await fetchCrmSeguroProxy(`crm-seguro/pedidos/${encodeURIComponent(id)}/carrier-pacote`,{cache:"no-store"}),p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||tc("order.loadFailed"));setDados(p);setSelecionados((p.destinatarios_disponiveis||[]).filter((i:Destinatario)=>Boolean((i as Destinatario&{copia_obrigatoria?:boolean}).copia_obrigatoria)).map((i:Destinatario)=>i.id))}catch(e){setErro(e instanceof Error?e.message:tc("order.loadFailed"))}finally{setLoading(false)}}
 useEffect(()=>{if(id)void carregar()},[id])
 async function enviarCarrier(ev:FormEvent<HTMLFormElement>){ev.preventDefault();setSalvando(true);setErro("");setMensagem("");const form=new FormData(ev.currentTarget);try{const emails=(dados?.destinatarios_disponiveis||[]).filter(i=>selecionados.includes(i.id)).map(i=>String(i.email||"").trim()).filter(Boolean);if(!emails.length)throw new Error(tc("order.selectRecipient"));const s=await fetchCrmSeguroProxy(`crm-seguro/pedidos/${encodeURIComponent(id)}/destinatarios`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({destinatarios:emails,observacoes_envio:String(form.get("observacao")||"")||null})}),sp=await s.json().catch(()=>null);if(!s.ok)throw new Error(sp?.detail||tc("common.error"));if(!window.confirm(tc("order.confirmSend",{count:emails.length}))){setMensagem(tc("order.recipientsSaved"));return}const e=await fetchCrmSeguroProxy(`crm-seguro/pedidos/${encodeURIComponent(id)}/enviar`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmar:true})}),ep=await e.json().catch(()=>null);if(!e.ok)throw new Error(ep?.detail||tc("common.error"));setMensagem(tc("order.sent"));await carregar()}catch(f){setErro(f instanceof Error?f.message:tc("common.error"))}finally{setSalvando(false)}}
 const propostaId=String(dados?.proposta.id||dados?.pedido.proposta_id||"")
 return <main className="flex min-h-screen bg-[#020817] text-white"><Sidebar/><section className="min-w-0 flex-1"><Topbar/><div className="space-y-6 p-4 sm:p-6 lg:p-8">
  <header className="rounded-3xl border border-[#13203f] bg-[#091a33] p-6"><Link href="/pedidos" className="text-sm font-semibold text-cyan-300">← {tc("order.back")}</Link><div className="mt-4 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400">{tc("order.dossier")}</p><h1 className="mt-2 text-3xl font-bold">{String(dados?.pedido.numero||tc("proposal.order"))}</h1><p className="mt-2 text-sm text-slate-400">{tc("order.acceptedProposal")}</p></div>{dados&&<span className="w-fit rounded-full border border-cyan-800 px-4 py-2 text-sm text-cyan-200">{String(dados.pedido.status_envio_carrier||"-").replaceAll("_"," ")}</span>}</div></header>
  {loading&&<Aviso>{tc("order.loading")}</Aviso>}{erro&&<div className="rounded-xl border border-red-900 bg-red-950/30 p-4 text-red-200">{erro}</div>}{mensagem&&<div className="rounded-xl border border-emerald-900 bg-emerald-950/30 p-4 text-emerald-200">{mensagem}</div>}
  {dados&&<><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi titulo={tc("common.value")} valor={moeda(dados.pedido.valor)}/><Kpi titulo={tc("order.equipment")} valor={String(dados.item.equipamento||dados.proposta.equipamentos||"-")}/><Kpi titulo={tc("common.quantity")} valor={String(dados.item.quantidade||1)}/><Kpi titulo={tc("order.proposal")} valor={String(dados.proposta.numero||"-")}/></section>
  <section className="grid gap-3 md:grid-cols-2"><Link href={`/pedidos/${id}/documento`} className="rounded-xl bg-cyan-500 px-5 py-4 text-center font-semibold text-slate-950">{tc("order.viewDocument")}</Link>{propostaId&&<Link href={`/propostas/${propostaId}/documento`} className="rounded-xl border border-cyan-700 px-5 py-4 text-center font-semibold text-cyan-300">{tc("proposal.viewOfficial")}</Link>}</section>
  <section className="grid gap-6 xl:grid-cols-2"><article className="rounded-3xl border border-[#13203f] bg-[#071427] p-6"><h2 className="text-xl font-bold">{t.summary}</h2><dl className="mt-5 space-y-3 text-sm"><Linha label={tc("proposal.line")} valor={String(dados.item.linha_produto||dados.proposta.produtos||"-")}/><Linha label={tc("order.equipment")} valor={String(dados.item.equipamento||dados.proposta.equipamentos||"-")}/><Linha label={tc("proposal.payment")} valor={String(dados.item.condicao_pagamento||dados.proposta.condicoes||"-")}/><Linha label={tc("order.delivery")} valor={String(dados.item.prazo_entrega||"-")}/><Linha label={tc("proposal.warranty")} valor={String(dados.item.garantia||"-")}/><Linha label={tc("order.orderDate")} valor={dataHora(dados.pedido.data_pedido)}/></dl></article><article className="rounded-3xl border border-[#13203f] bg-[#071427] p-6"><h2 className="text-xl font-bold">{tc("order.acceptance")}</h2><dl className="mt-5 space-y-3 text-sm"><Linha label={tc("order.signer")} valor={String(dados.aceite.nome_signatario||"-")}/><Linha label={tc("order.document")} valor={String(dados.aceite.documento_signatario||"-")}/><Linha label={tc("order.method")} valor={String(dados.aceite.metodo||"-")}/><Linha label={tc("order.dateTime")} valor={dataHora(dados.aceite.aceito_em)}/><Linha label={tc("common.status")} valor={String(dados.aceite.status||"-")}/><Linha label={tc("order.proposalHash")} valor={String(dados.proposta.hash_documento||"-")}/></dl></article></section>
  <form onSubmit={enviarCarrier} className="rounded-3xl border border-[#13203f] bg-[#071427] p-6"><h2 className="text-xl font-bold">{tc("order.sendCarrier")}</h2><p className="mt-2 text-sm text-slate-400">{t.carrierInfo}</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{dados.destinatarios_disponiveis.length===0?<div className="md:col-span-2 xl:col-span-3 rounded-2xl border border-amber-700 bg-amber-950/20 p-4 text-sm text-amber-200"><p>{tc("order.noRecipients")}</p><Link href="/configuracoes/destinatarios-carrier" className="mt-3 inline-flex rounded-xl bg-cyan-500 px-4 py-2 font-semibold text-slate-950">{tc("order.registerRecipient")}</Link></div>:dados.destinatarios_disponiveis.map(item=><label key={item.id} className="flex gap-3 rounded-xl border border-[#16325c] bg-[#091a33] p-4 text-sm"><input type="checkbox" checked={selecionados.includes(item.id)} onChange={e=>setSelecionados(a=>e.target.checked?[...new Set([...a,item.id])]:a.filter(x=>x!==item.id))}/><span><strong className="block text-white">{item.nome||item.email}</strong><span className="text-slate-500">{item.cargo||item.regiao||item.email}</span></span></label>)}</div><label className="mt-5 block text-sm text-slate-300">{tc("order.observation")}<textarea name="observacao" defaultValue={t.defaultNote} rows={4} className="mt-2 w-full rounded-xl border border-[#24466f] bg-[#020817] px-4 py-3 text-white"/></label><button disabled={salvando||selecionados.length===0} className="mt-5 rounded-xl bg-cyan-500 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{salvando?tc("common.sending"):tc("order.sendCarrier")}</button></form>
  <section className="rounded-3xl border border-[#13203f] bg-[#071427] p-6"><h2 className="text-xl font-bold">{tc("order.forwardingHistory")}</h2><div className="mt-5 space-y-3">{dados.envios.length===0?<p className="text-sm text-slate-500">{tc("order.noForwarding")}</p>:dados.envios.map(envio=><article key={String(envio.id)} className="rounded-xl border border-[#16325c] bg-[#091a33] p-4 text-sm"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold text-white">{String(envio.assunto||t.subject)}</p><p className="mt-1 text-slate-500">{dataHora(envio.created_at)}</p></div><span className="w-fit rounded-full border border-cyan-800 px-3 py-1 text-xs text-cyan-200">{String(envio.status||t.pending).replaceAll("_"," ")}</span></div></article>)}</div></section></>}
 </div></section></main>
}
function Kpi({titulo,valor}:{titulo:string;valor:string}){return <div className="rounded-2xl border border-[#13203f] bg-[#091a33] p-5"><p className="text-sm text-slate-400">{titulo}</p><p className="mt-2 break-words text-xl font-bold text-cyan-300">{valor}</p></div>}
function Linha({label,valor}:{label:string;valor:string}){return <div className="flex items-start justify-between gap-4 border-b border-[#13203f] pb-3 last:border-0"><dt className="text-slate-500">{label}</dt><dd className="max-w-[65%] break-words text-right text-slate-200">{valor}</dd></div>}
function Aviso({children}:{children:React.ReactNode}){return <div className="rounded-3xl border border-[#13203f] bg-[#071427] p-8 text-slate-300">{children}</div>}
