"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { AlertCircle, ArrowLeft, Building2, ChevronRight, Loader2, Plus, Search, X } from "lucide-react"

type Registro = Record<string, unknown>
type Cliente = { id: string; chave: string; nome: string; razaoSocial: string; nomeFantasia: string; cnpj: string; cidade: string; estado: string; negocios: number }
const letras = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("")
function texto(valor: unknown) { return String(valor ?? "").trim() }
function chaveNome(valor: unknown) { return texto(valor).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleUpperCase("pt-BR") }
function somenteDigitos(valor: unknown) { return texto(valor).replace(/\D/g, "") }
function formatarCnpj(valor: string) { const d = somenteDigitos(valor); return d.length === 14 ? d.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/, "$1.$2.$3/$4-$5") : valor }
function normalizarBusca(valor: unknown) { return chaveNome(valor).replace(/[^A-Z0-9]/g, "") }
function inicial(nome: string) { return chaveNome(nome).charAt(0) }

export default function ClientesCrmAppPage() {
  const [clientes,setClientes]=useState<Cliente[]>([]),[busca,setBusca]=useState(""),[letra,setLetra]=useState(""),[carregando,setCarregando]=useState(true),[erro,setErro]=useState("")
  useEffect(()=>{let ativo=true;void(async()=>{setCarregando(true);setErro("");try{
    const [cadastro,nucleo]=await Promise.all([fetch("/api/crm-proxy/crm-app/clientes",{cache:"no-store"}),fetch("/api/crm-proxy/crm/nucleo-comercial",{cache:"no-store"})])
    const cadastroDados=await cadastro.json().catch(()=>[]), nucleoDados=await nucleo.json().catch(()=>[])
    if(!cadastro.ok)throw new Error(String((cadastroDados as Registro).detail||`Clientes: HTTP ${cadastro.status}`));if(!nucleo.ok)throw new Error(String((nucleoDados as Registro).detail||`Núcleo: HTTP ${nucleo.status}`));if(!ativo)return
    const mapa=new Map<string,Cliente>()
    for(const item of Array.isArray(cadastroDados)?cadastroDados:[]){const razaoSocial=texto(item.razao_social),nomeFantasia=texto(item.nome_fantasia),nome=texto(item.nome||razaoSocial||nomeFantasia);if(!nome)continue;const cnpj=texto(item.cnpj||item.cnpj_cpf||item.documento),chave=chaveNome(nome);mapa.set(chave,{id:texto(item.id)||nome,chave,nome,razaoSocial,nomeFantasia,cnpj,cidade:texto(item.cidade||item.municipio),estado:texto(item.estado||item.uf).toUpperCase(),negocios:0})}
    for(const item of Array.isArray(nucleoDados)?nucleoDados:[]){const nome=texto(item.cliente_nome);if(!nome)continue;const chave=chaveNome(nome), existente=mapa.get(chave);mapa.set(chave,{id:texto(item.cliente_id)||existente?.id||nome,chave,nome:existente?.nome||nome,razaoSocial:existente?.razaoSocial||texto(item.razao_social),nomeFantasia:existente?.nomeFantasia||texto(item.nome_fantasia),cnpj:existente?.cnpj||texto(item.cnpj||item.cnpj_cpf||item.documento),cidade:existente?.cidade||texto(item.cliente_cidade||item.municipio),estado:existente?.estado||texto(item.cliente_estado||item.uf).toUpperCase(),negocios:(existente?.negocios||0)+1})}
    setClientes([...mapa.values()].sort((a,b)=>a.nome.localeCompare(b.nome,"pt-BR")))
  }catch(falha){if(ativo)setErro(falha instanceof Error?falha.message:"Não foi possível carregar a carteira de clientes.")}finally{if(ativo)setCarregando(false)}})();return()=>{ativo=false}},[])

  const contagemLetras=useMemo(()=>{const mapa=new Map<string,number>();for(const cliente of clientes){const i=inicial(cliente.nome);if(letras.includes(i))mapa.set(i,(mapa.get(i)||0)+1)}return mapa},[clientes])
  const filtrados=useMemo(()=>{const termo=busca.trim();if(termo){const termoTexto=chaveNome(termo),termoCompacto=normalizarBusca(termo),termoCnpj=somenteDigitos(termo);return clientes.filter((item)=>{const nomes=[item.nome,item.razaoSocial,item.nomeFantasia].filter(Boolean).map(chaveNome);const nomesCompactos=[item.nome,item.razaoSocial,item.nomeFantasia].filter(Boolean).map(normalizarBusca);return nomes.some((valor)=>valor.includes(termoTexto))||nomesCompactos.some((valor)=>valor.includes(termoCompacto))||(termoCnpj.length>0&&somenteDigitos(item.cnpj).includes(termoCnpj))})}if(letra)return clientes.filter((item)=>inicial(item.nome)===letra);return []},[busca,clientes,letra])
  const modoBusca=Boolean(busca.trim()), modoLetra=Boolean(letra&&!modoBusca)

  return <main className="min-h-[100dvh] bg-[#020817] px-4 py-5 pb-24 text-white sm:px-6"><div className="mx-auto max-w-5xl">
    <header className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Link href="/crm-app" className="grid size-11 place-items-center rounded-2xl border border-[#16325c] bg-[#091a33] text-cyan-300"><ArrowLeft size={20}/></Link><div><p className="text-xs uppercase tracking-[.24em] text-cyan-400">CTI CRM</p><h1 className="text-2xl font-bold">Carteira de clientes</h1>{!carregando&&!erro&&<p className="mt-1 text-sm text-slate-400">{clientes.length} clientes cadastrados</p>}</div></div><Link href="/crm-app/clientes/nova" className="flex h-11 items-center justify-center gap-2 rounded-xl bg-cyan-500 px-4 font-bold text-slate-950"><Plus size={18}/>Novo cliente</Link></header>

    <label className="relative mb-4 block"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18}/><input value={busca} onChange={(e)=>{setBusca(e.target.value);if(e.target.value)setLetra("")}} placeholder="Buscar por nome, razão social, fantasia ou CNPJ" className="h-12 w-full rounded-2xl border border-[#16325c] bg-[#07162b] pl-11 pr-11"/>{busca&&<button type="button" onClick={()=>setBusca("")} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-2 text-slate-400"><X size={18}/></button>}</label>

    {!carregando&&!erro&&<section className="mb-5 rounded-3xl border border-[#16325c] bg-[#07162b] p-4"><div className="mb-3 flex items-center justify-between gap-3"><div><h2 className="font-semibold">Índice alfabético</h2><p className="text-xs text-slate-400">Escolha uma letra para listar somente os clientes correspondentes.</p></div>{letra&&<button type="button" onClick={()=>setLetra("")} className="text-sm font-semibold text-cyan-300">Limpar</button>}</div><div className="grid grid-cols-7 gap-2 sm:grid-cols-13">{letras.map((l)=>{const quantidade=contagemLetras.get(l)||0;return <button key={l} type="button" disabled={!quantidade} onClick={()=>{setLetra(l);setBusca("")}} className={`rounded-xl border px-2 py-2 text-sm font-bold ${letra===l?"border-cyan-400 bg-cyan-500 text-slate-950":"border-[#24466f] bg-[#020817] text-slate-300 disabled:opacity-25"}`}>{l}<span className="ml-1 text-[10px] font-normal">{quantidade||""}</span></button>})}</div></section>}

    {erro&&<div className="rounded-2xl border border-red-900 bg-red-950/40 p-4 text-red-200">{erro}</div>}
    {carregando?<div className="grid min-h-64 place-items-center gap-3 text-slate-400"><Loader2 className="animate-spin text-cyan-300"/><span>Carregando carteira comercial...</span></div>:erro?null:!modoBusca&&!modoLetra?<div className="grid min-h-64 place-items-center rounded-3xl border border-dashed border-[#24466f] p-8 text-center"><div><Building2 className="mx-auto mb-3 text-cyan-300"/><p className="font-semibold">Selecione uma letra ou use a busca</p><p className="mt-1 text-sm text-slate-400">A carteira completa permanece disponível sem carregar centenas de cartões de uma só vez.</p></div></div>:filtrados.length===0?<div className="grid min-h-64 place-items-center rounded-3xl border border-dashed border-[#24466f] p-8 text-center"><div><AlertCircle className="mx-auto mb-3 text-cyan-300"/><p className="font-semibold">Nenhum cliente encontrado</p><Link href="/crm-app/clientes/nova" className="mt-3 inline-flex text-sm font-semibold text-cyan-300">Cadastrar novo cliente</Link></div></div>:<><div className="mb-3 flex items-center justify-between text-sm text-slate-400"><span>{filtrados.length} {filtrados.length===1?"cliente encontrado":"clientes encontrados"}{modoLetra?` na letra ${letra}`:""}</span>{modoLetra&&<button type="button" onClick={()=>setLetra("")} className="font-semibold text-cyan-300">Voltar ao alfabeto</button>}</div><div className="grid gap-4 md:grid-cols-2">{filtrados.map((cliente)=><Link key={cliente.chave} href={`/crm-app/clientes/${encodeURIComponent(cliente.id)}?nome=${encodeURIComponent(cliente.nome)}`} className="group rounded-3xl border border-[#16325c] bg-[#07162b] p-5 transition hover:border-cyan-700"><div className="flex items-center gap-3"><span className="rounded-2xl bg-cyan-950/50 p-3 text-cyan-300"><Building2 size={22}/></span><div className="min-w-0 flex-1"><h2 className="truncate font-bold">{cliente.nome}</h2>{cliente.cnpj&&<p className="mt-1 text-xs text-cyan-200">CNPJ {formatarCnpj(cliente.cnpj)}</p>}<p className="text-xs text-slate-400">{cliente.cidade?`${cliente.cidade}${cliente.estado?`/${cliente.estado}`:""}`:"Cadastro comercial"}</p><p className="mt-2 text-xs font-semibold text-cyan-300">{cliente.negocios} {cliente.negocios===1?"negociação":"negociações"} · abrir dossiê</p></div><ChevronRight size={20} className="text-cyan-300"/></div></Link>)}</div></>}
  </div></main>
}
