"use client"
import { FormEvent,useState } from "react"
import { Item,dinheiro,num,clamp,texto } from "./financeiro"
export default function ItemValorEditor({item,onDone,onCancel}:{item:Item;onDone:()=>void;onCancel:()=>void}){
 const[qtd,setQtd]=useState(String(item.quantidade)),[desconto,setDesconto]=useState(String(item.desconto_percentual)),[negociado,setNegociado]=useState(String(Number((item.preco_tabela*(1-item.desconto_percentual/100)).toFixed(2)))),[saving,setSaving]=useState(false),[erro,setErro]=useState("")
 const q=Math.max(1,num(qtd)||1),d=clamp(num(desconto),0,100),unit=item.preco_tabela*(1-d/100),dr=item.preco_tabela-unit,total=unit*q
 function mudarDesconto(v:string){const x=clamp(num(v),0,100);setDesconto(v);setNegociado(String(Number((item.preco_tabela*(1-x/100)).toFixed(2))))}
 function mudarNegociado(v:string){const p=clamp(num(v),0,item.preco_tabela),x=item.preco_tabela?clamp((1-p/item.preco_tabela)*100,0,100):0;setNegociado(v);setDesconto(String(Number(x.toFixed(4))))}
 async function salvar(e:FormEvent){e.preventDefault();setSaving(true);setErro("");try{const r=await fetch(`/api/crm-proxy/crm-documentos/itens/${encodeURIComponent(item.id)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({quantidade:q,preco_unitario:item.preco_tabela,desconto_percentual:d})});const p=await r.json().catch(()=>({})) as Record<string,unknown>;if(!r.ok)throw new Error(texto(p.detail)||`Falha ${r.status}`);onDone()}catch(x){setErro(x instanceof Error?x.message:"Não foi possível atualizar o item.")}finally{setSaving(false)}}
 return <form onSubmit={salvar} className="mt-3 rounded-xl border border-cyan-800 bg-[#061326] p-3">{erro&&<p className="mb-2 text-xs text-red-300">{erro}</p>}<div className="grid grid-cols-2 gap-2"><Box l="Tabela" v={dinheiro(item.preco_tabela)}/><Box l="Desconto R$" v={dinheiro(dr)}/><Box l="Unitário negociado" v={dinheiro(unit)} hi/><Box l="Subtotal" v={dinheiro(total)} hi/></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><Fld l="Quantidade" v={qtd} on={setQtd}/><Fld l="Desconto (%)" v={desconto} on={mudarDesconto} step="0.01"/><Fld l="Preço negociado (R$)" v={negociado} on={mudarNegociado} step="0.01"/></div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={onCancel} className="rounded-lg border border-[#24466f] py-2 text-xs">Cancelar</button><button disabled={saving} className="rounded-lg bg-cyan-500 py-2 text-xs font-bold text-slate-950">{saving?"Salvando...":"Salvar valores"}</button></div></form>
}
function Box({l,v,hi=false}:{l:string;v:string;hi?:boolean}){return <div className="rounded-lg border border-[#24466f] bg-[#020817] p-2"><span className="block text-[9px] uppercase text-slate-500">{l}</span><b className={hi?"text-emerald-300":"text-slate-200"}>{v}</b></div>}
function Fld({l,v,on,step}:{l:string;v:string;on:(v:string)=>void;step?:string}){return <label className="text-xs text-slate-300">{l}<input type="number" step={step} value={v} onChange={e=>on(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[#24466f] bg-[#020817] px-2"/></label>}
