"use client"
import {useEffect,useMemo,useState} from "react"
import {dinheiro,texto} from "./financeiro"
type R=Record<string,unknown>;type E={codigo:string;nome:string;preco:number}
export default function NovoItemFinanceiro({oportunidadeId,ordem,onDone}:{oportunidadeId:string;ordem:number;onDone:()=>void}){
 const[lista,setLista]=useState<E[]>([]),[codigo,setCodigo]=useState(""),[qtd,setQtd]=useState(1),[desc,setDesc]=useState(0),[aberto,setAberto]=useState(false),[erro,setErro]=useState("")
 useEffect(()=>{fetch("/api/crm-proxy/catalogo-comercial/equipamentos",{cache:"no-store"}).then(r=>r.json()).then(p=>{const l=(Array.isArray(p)?p:[]).map((x:R)=>({codigo:texto(x.codigo),nome:texto(x.nome_comercial||x.equipamento),preco:Number((x.preco_vigente as R)?.preco_cheio||0)})).filter(x=>x.codigo);setLista(l);if(l[0])setCodigo(l[0].codigo)}).catch(()=>setErro("Falha ao carregar catálogo."))},[])
 const e=useMemo(()=>lista.find(x=>x.codigo===codigo),[lista,codigo]),unit=(e?.preco||0)*(1-desc/100),total=unit*qtd
 async function salvar(){if(!e)return;setErro("");const r=await fetch(`/api/crm-proxy/catalogo-comercial/oportunidades/${encodeURIComponent(oportunidadeId)}/itens`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({equipamento_codigo:e.codigo,quantidade:qtd,desconto_percentual:desc,ordem})});const p=await r.json().catch(()=>({}));if(!r.ok)return setErro(texto((p as R).detail)||`Falha ${r.status}`);setAberto(false);onDone()}
 if(!aberto)return <button onClick={()=>setAberto(true)} className="mt-4 w-full rounded-xl border border-cyan-700 px-4 py-3 font-semibold text-cyan-300">+ Adicionar outro item</button>
 return <div className="mt-4 rounded-2xl border border-[#24466f] bg-[#061326] p-4"><h3 className="font-bold">Novo item</h3>{erro&&<p className="mt-2 text-sm text-red-300">{erro}</p>}<select value={codigo} onChange={x=>setCodigo(x.target.value)} className="mt-3 h-12 w-full rounded-xl border border-[#24466f] bg-[#020817] px-3">{lista.map(x=><option key={x.codigo} value={x.codigo}>{x.nome}</option>)}</select><div className="mt-3 grid grid-cols-2 gap-2"><input type="number" min={1} value={qtd} onChange={x=>setQtd(Math.max(1,Number(x.target.value)||1))} className="h-12 rounded-xl border border-[#24466f] bg-[#020817] px-3" placeholder="Quantidade"/><input type="number" min={0} max={100} step="0.01" value={desc} onChange={x=>setDesc(Math.max(0,Math.min(100,Number(x.target.value)||0)))} className="h-12 rounded-xl border border-[#24466f] bg-[#020817] px-3" placeholder="Desconto %"/></div><div className="mt-3 text-sm text-slate-300">Tabela: {dinheiro(e?.preco)} · desconto: {dinheiro((e?.preco||0)-unit)} · unitário: {dinheiro(unit)} · subtotal: <strong className="text-emerald-300">{dinheiro(total)}</strong></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setAberto(false)} className="rounded-xl border border-[#24466f] py-3">Cancelar</button><button onClick={()=>void salvar()} className="rounded-xl bg-cyan-500 py-3 font-bold text-slate-950">Salvar item</button></div></div>
}
