"use client"
import Link from "next/link"
import { useCallback,useEffect,useState } from "react"
import { CheckCircle2,FilePlus2,Loader2,Send } from "lucide-react"
import { useAuth } from "@/core/auth"
import { Item,Registro,dinheiro,num,texto } from "./financeiro"
type Proposta={id:string;numero:string;valor:number;status_documento:string;versao:number}
const INATIVOS=new Set(["CANCELADA","SUBSTITUIDA","OBSOLETA","REJEITADA","EXPIRADA"])
function atual(lista:Proposta[]){return [...lista].sort((a,b)=>b.versao-a.versao).find(p=>!INATIVOS.has(p.status_documento.toUpperCase()))||null}
export default function PropostasProcessoSection({oportunidadeId}:{oportunidadeId:string}){
 const{usuario}=useAuth();const[itens,setItens]=useState<Item[]>([]),[props,setProps]=useState<Record<string,Proposta[]>>({}),[loading,setLoading]=useState(true),[proc,setProc]=useState(""),[erro,setErro]=useState(""),[msg,setMsg]=useState(""),[final,setFinal]=useState(false),[ids,setIds]=useState<string[]>([]),[emails,setEmails]=useState(""),[mensagem,setMensagem]=useState("")
 const carregar=useCallback(async()=>{setLoading(true);setErro("");try{const r=await fetch(`/api/crm-proxy/crm-documentos/oportunidades/${encodeURIComponent(oportunidadeId)}/itens`,{cache:"no-store"}),p=await r.json().catch(()=>[]);if(!r.ok)throw new Error(texto((p as Registro).detail)||`Falha ${r.status}`);const li=(Array.isArray(p)?p:[]).map((x:Registro):Item=>({id:texto(x.id),equipamento:texto(x.nome_comercial||x.equipamento)||"Equipamento",quantidade:num(x.quantidade)||1,preco_tabela:num(x.preco_tabela||x.preco_unitario),preco_unitario:num(x.preco_unitario),desconto_percentual:num(x.desconto_percentual),status:texto(x.status||"EM_NEGOCIACAO")})).filter(x=>x.id);setItens(li);const pares=await Promise.all(li.map(async i=>{const q=await fetch(`/api/crm-proxy/crm-documentos/itens/${encodeURIComponent(i.id)}/propostas`,{cache:"no-store"}),x=await q.json().catch(()=>[]);return[i.id,(Array.isArray(x)?x:[]).map((z:Registro):Proposta=>({id:texto(z.id),numero:texto(z.numero),valor:num(z.valor),status_documento:texto(z.status_documento||z.status),versao:num(z.versao)}))] as const}));setProps(Object.fromEntries(pares))}catch(e){setErro(e instanceof Error?e.message:"Falha ao carregar propostas.")}finally{setLoading(false)}},[oportunidadeId])
 useEffect(()=>{queueMicrotask(()=>void carregar())},[carregar])
 async function gerar(item:Item){const resp=texto(usuario?.id);if(!resp)return setErro("Vendedor autenticado não identificado.");setProc(item.id);setErro("");try{const r=await fetch(`/api/crm-proxy/crm-documentos/itens/${encodeURIComponent(item.id)}/propostas`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({responsavel_id:resp})}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(texto((p as Registro).detail)||`Falha ${r.status}`);setMsg(`Nova versão preparada para ${item.equipamento}.`);await carregar()}catch(e){setErro(e instanceof Error?e.message:"Falha ao gerar proposta.")}finally{setProc("")}}
 async function revisar(){const resp=texto(usuario?.id);if(!resp)return setErro("Vendedor autenticado não identificado.");setProc("revisar");try{const lista:string[]=[];for(const item of itens){const p=atual(props[item.id]||[]);if(p){lista.push(p.id);continue}const r=await fetch(`/api/crm-proxy/crm-documentos/itens/${encodeURIComponent(item.id)}/propostas`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({responsavel_id:resp})}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(texto((x as Registro).detail)||`Falha ao preparar ${item.equipamento}`);const c=Array.isArray(x)?x[0]:x,id=c&&typeof c==="object"?texto((c as Registro).id):"";if(id)lista.push(id)}setIds(lista);setFinal(true);setMsg(`${lista.length} proposta(s) pronta(s) para revisão e envio.`);await carregar()}catch(e){setErro(e instanceof Error?e.message:"Falha ao preparar propostas.")}finally{setProc("")}}
 async function enviar(){const dest=emails.split(/[;,\n]/).map(x=>x.trim()).filter(Boolean);if(!dest.length)return setErro("Informe ao menos um e-mail.");setProc("enviar");try{const r=await fetch(`/api/crm-proxy/crm-app/oportunidades/${encodeURIComponent(oportunidadeId)}/enviar-propostas-email`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({proposta_ids:ids,destinatarios:dest,mensagem:mensagem||null})}),p=await r.json().catch(()=>({})) as Registro;if(!r.ok)throw new Error(texto(p.detail)||`Falha ${r.status}`);setMsg(`Propostas enviadas${texto(p.message_id)?` · protocolo ${texto(p.message_id)}`:""}.`);setFinal(false);setEmails("");setMensagem("");await carregar()}catch(e){setErro(e instanceof Error?e.message:"Falha ao enviar.")}finally{setProc("")}}
 return <section className="mb-4 rounded-3xl border border-[#16325c] bg-[#07162b] p-5"><div><h2 className="text-lg font-bold">Propostas do processo</h2><p className="text-xs text-slate-400">Uma proposta Carrier por item, dentro da mesma oportunidade.</p></div>{erro&&<div className="mt-3 rounded-xl border border-red-900 bg-red-950/30 p-3 text-sm text-red-200">{erro}</div>}{msg&&<div className="mt-3 rounded-xl border border-emerald-900 bg-emerald-950/30 p-3 text-sm text-emerald-200">{msg}</div>}{loading?<div className="grid min-h-24 place-items-center"><Loader2 className="animate-spin"/></div>:<div className="mt-4 space-y-3">{itens.map((i,n)=>{const p=atual(props[i.id]||[]);return <article key={i.id} className="rounded-2xl border border-[#24466f] bg-[#091a33] p-4"><div className="flex justify-between gap-3"><div><span className="text-[10px] uppercase tracking-[.16em] text-cyan-400">Item {n+1}</span><b className="block">{i.equipamento}</b><span className="text-xs text-slate-400">{i.quantidade} un. · {dinheiro(i.preco_tabela*(1-i.desconto_percentual/100)*i.quantidade)}</span></div><span className="text-xs text-slate-400">{p?.status_documento||"Sem proposta"}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{p?<Link href={`/crm-app/propostas/${encodeURIComponent(p.id)}`} className="rounded-xl border border-cyan-800 px-3 py-2 text-center text-xs font-semibold text-cyan-200">Abrir {p.numero||"proposta"}</Link>:<span/>}<button disabled={proc===i.id} onClick={()=>void gerar(i)} className="flex items-center justify-center gap-2 rounded-xl border border-[#24466f] px-3 py-2 text-xs font-semibold"><FilePlus2 size={14}/>{p?"Gerar nova versão":"Gerar proposta"}</button></div></article>})}<button disabled={!itens.length||proc==="revisar"} onClick={()=>void revisar()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-500 px-4 py-3 font-bold text-slate-950"><CheckCircle2 size={17}/>Concluir e revisar propostas</button></div>}{final&&<div className="mt-4 space-y-3 rounded-2xl border border-emerald-800 bg-emerald-950/15 p-4"><input value={emails} onChange={e=>setEmails(e.target.value)} placeholder="cliente@empresa.com; comprador@empresa.com" className="h-12 w-full rounded-xl border border-[#24466f] bg-[#020817] px-3"/><textarea value={mensagem} onChange={e=>setMensagem(e.target.value)} placeholder="Mensagem opcional" rows={3} className="w-full rounded-xl border border-[#24466f] bg-[#020817] p-3"/><button disabled={proc==="enviar"} onClick={()=>void enviar()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-400 px-4 py-3 font-bold text-slate-950"><Send size={17}/>Salvar e enviar todas</button></div>}</section>
}
