"use client"
import { useCallback,useEffect,useMemo,useState } from "react"
import { Loader2 } from "lucide-react"
import ItemFinanceiroCard from "./ItemFinanceiroCard"
import ItemValorEditor from "./ItemValorEditor"
import NovoItemFinanceiro from "./NovoItemFinanceiro"
import { Item,Registro,dinheiro,num,texto } from "./financeiro"
export default function ResumoFinanceiroOportunidade({oportunidadeId}:{oportunidadeId:string}){
 const[itens,setItens]=useState<Item[]>([]),[edit,setEdit]=useState(""),[loading,setLoading]=useState(true),[erro,setErro]=useState("")
 const carregar=useCallback(async()=>{setLoading(true);setErro("");try{await fetch(`/api/crm-proxy/crm-app/oportunidades/${encodeURIComponent(oportunidadeId)}/sincronizar-resumo`,{method:"POST"}).catch(()=>null);const r=await fetch(`/api/crm-proxy/crm-documentos/oportunidades/${encodeURIComponent(oportunidadeId)}/itens`,{cache:"no-store"});const p=await r.json().catch(()=>[]);if(!r.ok)throw new Error(texto((p as Registro).detail)||`Falha ${r.status}`);setItens((Array.isArray(p)?p:[]).map((x:Registro):Item=>({id:texto(x.id),equipamento:texto(x.nome_comercial||x.equipamento)||"Equipamento",quantidade:num(x.quantidade)||1,preco_tabela:num(x.preco_tabela||x.preco_unitario),preco_unitario:num(x.preco_unitario),desconto_percentual:num(x.desconto_percentual),status:texto(x.status||"EM_NEGOCIACAO"),condicao_pagamento:texto(x.condicao_pagamento),prazo_entrega:texto(x.prazo_entrega),validade_condicao:texto(x.validade_condicao),garantia:texto(x.garantia),opcionais:Array.isArray(x.opcionais)?x.opcionais.map(texto):[],observacoes_comerciais:texto(x.observacoes_comerciais),observacoes_tecnicas:texto(x.observacoes_tecnicas)})).filter(x=>x.id))}catch(e){setErro(e instanceof Error?e.message:"Não foi possível carregar os valores.")}finally{setLoading(false)}},[oportunidadeId])
 useEffect(()=>{queueMicrotask(()=>void carregar())},[carregar])
 const total=useMemo(()=>itens.reduce((s,i)=>s+i.preco_tabela*(1-i.desconto_percentual/100)*i.quantidade,0),[itens])
 return <section className="mb-4 rounded-3xl border border-[#16325c] bg-[#07162b] p-5" id="negociacao"><div><h2 className="text-lg font-bold">Valores da negociação</h2><p className="text-xs text-slate-400">Todos os itens cadastrados e o efeito real de quantidade e desconto.</p></div>{erro&&<div className="mt-3 rounded-xl border border-red-900 bg-red-950/30 p-3 text-sm text-red-200">{erro}</div>}{loading?<div className="grid min-h-24 place-items-center"><Loader2 className="animate-spin text-cyan-300"/></div>:<><div className="mt-4 space-y-3">{itens.map((i,n)=><div key={i.id}><ItemFinanceiroCard item={i} indice={n} onEdit={x=>setEdit(x.id)}/>{edit===i.id&&<ItemValorEditor item={i} onCancel={()=>setEdit("")} onDone={()=>{setEdit("");void carregar()}}/>}</div>)}</div><div className="mt-4 rounded-2xl border border-emerald-900/70 bg-emerald-950/20 p-4"><span className="text-xs text-emerald-100/70">Total negociado da oportunidade</span><strong className="mt-1 block text-xl text-emerald-300">{dinheiro(total)}</strong><span className="text-xs text-slate-400">{itens.length} item(ns) · este total passa a alimentar o cabeçalho, Pipeline e Forecast.</span></div><NovoItemFinanceiro oportunidadeId={oportunidadeId} ordem={itens.length} onDone={()=>void carregar()}/></>}
 </section>
}
