"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { ArrowLeft, CircleAlert, CircleCheck, Clock3, FileText, Loader2, PackageCheck, Search, WalletCards } from "lucide-react"
import { fetchCrmSeguroProxy } from "@/services/crm-secure"
import { useOperationalI18n } from "@/core/i18n/operational"

type Registro = Record<string, unknown>
type FiltroPedido = "TODOS" | "PENDENTES" | "ENVIADOS" | "FALHAS"
type Copy = { proposalsTitle:string;ordersTitle:string;proposalsSub:string;ordersSub:string;orders:string;totalVolume:string;follow:string;awaiting:string;inCycle:string;fromWeb:string;orderValue:string;withFailure:string;noFailures:string;all:string;failures:string;search:string;empty:string;unidentified:string;equipmentTbd:string;sent:string;invoiceSerial:string;installedSerial:string;proposal:string;order:string;loadError:string }
const COPY: Record<"pt-BR"|"en"|"es",Copy> = {
 "pt-BR":{proposalsTitle:"Propostas comerciais",ordersTitle:"Acompanhamento de pedidos",proposalsSub:"Emissão, aceite e conversão em pedido",ordersSub:"Reflexo do ciclo operacional controlado pelo CTI Web: CARRIER, faturamento, entrega, instalação e encerramento",orders:"Pedidos",totalVolume:"volume total",follow:"A acompanhar",awaiting:"aguardando avanço",inCycle:"Em ciclo",fromWeb:"evolução vinda do CTI Web",orderValue:"Valor em pedidos",withFailure:"com falha",noFailures:"sem falhas registradas",all:"Todos",failures:"Falhas",search:"Buscar cliente, equipamento, pedido, série ou status",empty:"Nenhum registro encontrado.",unidentified:"Cliente não identificado",equipmentTbd:"Equipamento a definir",sent:"enviado",invoiceSerial:"Série NF",installedSerial:"Série instalada",proposal:"Proposta",order:"Pedido",loadError:"Não foi possível carregar os documentos."},
 en:{proposalsTitle:"Sales proposals",ordersTitle:"Order tracking",proposalsSub:"Issuance, acceptance and conversion into an order",ordersSub:"Operational cycle reflected from CTI Web: CARRIER, invoicing, delivery, installation and closure",orders:"Orders",totalVolume:"total volume",follow:"Needs follow-up",awaiting:"awaiting progress",inCycle:"In cycle",fromWeb:"progress reflected from CTI Web",orderValue:"Order value",withFailure:"with failure",noFailures:"no failures recorded",all:"All",failures:"Failures",search:"Search account, equipment, order, serial number or status",empty:"No records found.",unidentified:"Unidentified account",equipmentTbd:"Equipment to be defined",sent:"sent",invoiceSerial:"Invoice serial",installedSerial:"Installed serial",proposal:"Proposal",order:"Order",loadError:"We couldn't load the documents."},
 es:{proposalsTitle:"Propuestas comerciales",ordersTitle:"Seguimiento de pedidos",proposalsSub:"Emisión, aceptación y conversión en pedido",ordersSub:"Reflejo del ciclo operativo controlado por CTI Web: CARRIER, facturación, entrega, instalación y cierre",orders:"Pedidos",totalVolume:"volumen total",follow:"Requiere seguimiento",awaiting:"pendiente de avance",inCycle:"En ciclo",fromWeb:"avance reflejado desde CTI Web",orderValue:"Valor en pedidos",withFailure:"con falla",noFailures:"sin fallas registradas",all:"Todos",failures:"Fallas",search:"Buscar cliente, equipo, pedido, serie o estado",empty:"No se encontraron registros.",unidentified:"Cliente no identificado",equipmentTbd:"Equipo por definir",sent:"enviado",invoiceSerial:"Serie factura",installedSerial:"Serie instalada",proposal:"Propuesta",order:"Pedido",loadError:"No fue posible cargar los documentos."}
}
function texto(valor: unknown, padrao = "—") { const resultado = String(valor ?? "").trim(); return resultado || padrao }
function statusPedido(item: Registro) { return texto(item.status_ciclo || item.status_envio_carrier || item.status_envio || item.status, "PEDIDO").toUpperCase() }
function grupoPedido(item: Registro): Exclude<FiltroPedido, "TODOS"> { const status = statusPedido(item); if (["CARRIER","FATURADO","ENTREGUE","INSTALADO","ENCERRADO","ENVIADO","REENVIADO","CONFIRMADO"].includes(status)) return "ENVIADOS"; if (["FALHA","ERRO","REJEITADO"].includes(status)) return "FALHAS"; return "PENDENTES" }

export default function DocumentosComerciaisLista({ tipo }: { tipo: "propostas" | "pedidos" }) {
  const { locale, formatCurrency, formatDate, formatNumber } = useOperationalI18n(); const c=COPY[locale]
  const [registros,setRegistros]=useState<Registro[]>([]),[busca,setBusca]=useState(""),[filtroPedido,setFiltroPedido]=useState<FiltroPedido>("TODOS"),[carregando,setCarregando]=useState(true),[erro,setErro]=useState("")
  const propostas=tipo==="propostas", titulo=propostas?c.proposalsTitle:c.ordersTitle, subtitulo=propostas?c.proposalsSub:c.ordersSub, Icone=propostas?FileText:PackageCheck
  useEffect(()=>{fetchCrmSeguroProxy(`crm-seguro/${tipo}`,{cache:"no-store"}).then(async r=>{const p=await r.json().catch(()=>[]);if(!r.ok)throw new Error(String((p as Registro).detail||`${c.loadError} (${r.status})`));setRegistros(Array.isArray(p)?p:[])}).catch(f=>setErro(f instanceof Error?f.message:c.loadError)).finally(()=>setCarregando(false))},[tipo,c.loadError])
  const resumoPedidos=useMemo(()=>{const enviados=registros.filter(i=>grupoPedido(i)==="ENVIADOS").length,falhas=registros.filter(i=>grupoPedido(i)==="FALHAS").length,pendentes=registros.filter(i=>grupoPedido(i)==="PENDENTES").length,valor=registros.reduce((t,i)=>t+Number(i.valor||0),0);return{total:registros.length,enviados,falhas,pendentes,valor}},[registros])
  const filtrados=useMemo(()=>{const termo=busca.trim().toLocaleLowerCase(locale);return registros.filter(i=>{if(!propostas&&filtroPedido!=="TODOS"&&grupoPedido(i)!==filtroPedido)return false;if(!termo)return true;return `${texto(i.cliente_nome)} ${texto(i.equipamento)} ${texto(i.numero)} ${texto(i.numero_serie_nf)} ${texto(i.numero_serie_instalado)} ${propostas?texto(i.status_documento||i.status):statusPedido(i)}`.toLocaleLowerCase(locale).includes(termo)})},[busca,filtroPedido,propostas,registros,locale])
  const filtros=[{id:"TODOS" as FiltroPedido,label:c.all,valor:resumoPedidos.total},{id:"PENDENTES" as FiltroPedido,label:c.follow,valor:resumoPedidos.pendentes},{id:"ENVIADOS" as FiltroPedido,label:c.inCycle,valor:resumoPedidos.enviados},{id:"FALHAS" as FiltroPedido,label:c.failures,valor:resumoPedidos.falhas}]
  return <main className="min-h-[100dvh] bg-[#020817] px-4 py-5 pb-24 text-white sm:px-6"><div className="mx-auto max-w-6xl">
    <header className="mb-5 flex items-center gap-3"><Link href="/crm-app" className="grid size-11 place-items-center rounded-2xl border border-[#16325c] bg-[#091a33] text-cyan-300"><ArrowLeft size={20}/></Link><div><p className="text-xs uppercase tracking-[.24em] text-cyan-400">CTI CRM</p><h1 className="text-2xl font-bold">{titulo}</h1><p className="text-sm text-slate-400">{subtitulo}</p></div></header>
    {!propostas&&!carregando&&!erro&&<><section className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><Indicador icone={<PackageCheck size={18}/>} label={c.orders} valor={formatNumber(resumoPedidos.total)} detalhe={c.totalVolume}/><Indicador icone={<Clock3 size={18}/>} label={c.follow} valor={formatNumber(resumoPedidos.pendentes)} detalhe={c.awaiting}/><Indicador icone={<CircleCheck size={18}/>} label={c.inCycle} valor={formatNumber(resumoPedidos.enviados)} detalhe={c.fromWeb}/><Indicador icone={<WalletCards size={18}/>} label={c.orderValue} valor={formatCurrency(resumoPedidos.valor)} detalhe={resumoPedidos.falhas?`${formatNumber(resumoPedidos.falhas)} ${c.withFailure}`:c.noFailures}/></section><section className="mb-4 flex flex-wrap gap-2">{filtros.map(f=><button key={f.id} type="button" onClick={()=>setFiltroPedido(f.id)} className={`rounded-full border px-4 py-2 text-sm ${filtroPedido===f.id?"border-cyan-500 bg-cyan-950/50 text-cyan-200":"border-[#24466f] bg-[#07162b] text-slate-400"}`}>{f.label} <strong className="ml-1">{formatNumber(f.valor)}</strong></button>)}</section></>}
    <div className="relative mb-4"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder={c.search} className="h-12 w-full rounded-2xl border border-[#16325c] bg-[#07162b] pl-11 pr-4"/></div>
    {erro&&<div className="rounded-2xl border border-red-900 bg-red-950/40 p-4 text-red-200">{erro}</div>}
    {carregando?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-cyan-300"/></div>:filtrados.length===0?<div className="rounded-3xl border border-dashed border-[#24466f] p-8 text-center text-slate-400">{c.empty}</div>:<div className="space-y-3">{filtrados.map(item=>{const id=texto(item.id,""),status=propostas?texto(item.status_documento||item.status).replaceAll("_"," "):statusPedido(item).replaceAll("_"," "),href=propostas?`/crm-app/propostas/${id}`:`/crm-app/pedidos/${id}`,enviadoEm=!propostas?texto(item.enviado_carrier_em,""):"",falha=!propostas&&grupoPedido(item)==="FALHAS",serieNf=!propostas?texto(item.numero_serie_nf,""):"",serieInstalada=!propostas?texto(item.numero_serie_instalado,""):"";const dataEnvio=enviadoEm?new Date(enviadoEm):null;return <Link key={id} href={href} className="flex items-center gap-4 rounded-3xl border border-[#16325c] bg-[#07162b] p-5 transition hover:border-cyan-700"><span className={`rounded-2xl p-3 ${falha?"bg-red-950/50 text-red-300":"bg-cyan-950/50 text-cyan-300"}`}>{falha?<CircleAlert size={22}/>:<Icone size={22}/>}</span><span className="min-w-0 flex-1"><strong className="block truncate text-lg">{texto(item.cliente_nome,c.unidentified)}</strong><span className="mt-1 block text-sm text-slate-300">{texto(item.equipamento,c.equipmentTbd)}{!propostas&&item.quantidade?` · ${formatNumber(Number(item.quantidade))}`:""}</span><span className="mt-2 block text-xs text-slate-500">{status} · {formatCurrency(Number(item.valor||0))}{dataEnvio&&!Number.isNaN(dataEnvio.getTime())?` · ${c.sent} ${formatDate(dataEnvio)}`:""}</span>{!propostas&&(serieNf||serieInstalada)&&<span className="mt-1 block text-[11px] text-slate-500">{c.invoiceSerial}: {serieNf||"—"} · {c.installedSerial}: {serieInstalada||"—"}</span>}<span className="mt-1 block text-[11px] text-slate-600">{propostas?c.proposal:c.order} {texto(item.numero)}</span></span></Link>})}</div>}
  </div></main>
}
function Indicador({icone,label,valor,detalhe}:{icone:React.ReactNode;label:string;valor:string;detalhe:string}){return <div className="rounded-2xl border border-[#16325c] bg-[#07162b] p-4"><div className="flex items-center gap-2 text-cyan-300">{icone}<span className="text-xs uppercase tracking-[.12em] text-slate-500">{label}</span></div><strong className="mt-3 block text-xl sm:text-2xl">{valor}</strong><span className="mt-1 block text-xs text-slate-500">{detalhe}</span></div>}
