"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { ArrowLeft, CalendarDays, CircleAlert, CircleCheck, Clock3, FileText, Loader2, PackageCheck, Search, UserRound, WalletCards } from "lucide-react"
import { fetchCrmSeguroProxy } from "@/services/crm-secure"
import { useOperationalI18n } from "@/core/i18n/operational"
import { useAuth } from "@/core/auth"
import CrmFiltrosComerciais from "@/components/crm-app/CrmFiltrosComerciais"
import {
  aplicarFiltrosComerciais,
  calcularMetricasPrazo,
  FILTROS_CRM_VAZIOS,
  montarRegistroAnalitico,
  opcoesUnicas,
  type CrmFiltrosComerciais as FiltrosComerciais,
} from "@/lib/crm-analise-comercial"
import { exportarRelatorioCrmPdf } from "@/lib/crm-relatorio-pdf"

type Registro = Record<string, unknown>
type FiltroPedido = "TODOS" | "PENDENTES" | "ENVIADOS" | "FALHAS"
type UsuarioOpcao = { id:string; nome:string }
type Copy = { proposalsTitle:string;ordersTitle:string;proposalsSub:string;ordersSub:string;orders:string;totalVolume:string;follow:string;awaiting:string;inCycle:string;fromWeb:string;orderValue:string;withFailure:string;noFailures:string;all:string;failures:string;search:string;empty:string;unidentified:string;equipmentTbd:string;sent:string;invoiceSerial:string;installedSerial:string;proposal:string;order:string;loadError:string;responsible:string;includedAt:string;forecastAt:string;planned:string;elapsed:string;overdue:string }
const COPY: Record<"pt-BR"|"en"|"es",Copy> = {
 "pt-BR":{proposalsTitle:"Propostas comerciais",ordersTitle:"Acompanhamento de pedidos",proposalsSub:"Emissão, aceite e conversão em pedido",ordersSub:"Reflexo do ciclo operacional controlado pelo CTI Web: CARRIER, faturamento, entrega, instalação e encerramento",orders:"Pedidos",totalVolume:"volume total",follow:"A acompanhar",awaiting:"aguardando avanço",inCycle:"Em ciclo",fromWeb:"evolução vinda do CTI Web",orderValue:"Valor em pedidos",withFailure:"com falha",noFailures:"sem falhas registradas",all:"Todos",failures:"Falhas",search:"Buscar cliente, responsável, linha, equipamento, pedido, série ou status",empty:"Nenhum registro encontrado.",unidentified:"Cliente não identificado",equipmentTbd:"Equipamento a definir",sent:"enviado",invoiceSerial:"Série NF",installedSerial:"Série instalada",proposal:"Proposta",order:"Pedido",loadError:"Não foi possível carregar os documentos.",responsible:"Responsável",includedAt:"Inclusão",forecastAt:"Previsão",planned:"Prazo previsto",elapsed:"Decorrido",overdue:"Atraso"},
 en:{proposalsTitle:"Sales proposals",ordersTitle:"Order tracking",proposalsSub:"Issuance, acceptance and conversion into an order",ordersSub:"Operational cycle reflected from CTI Web: CARRIER, invoicing, delivery, installation and closure",orders:"Orders",totalVolume:"total volume",follow:"Needs follow-up",awaiting:"awaiting progress",inCycle:"In cycle",fromWeb:"progress reflected from CTI Web",orderValue:"Order value",withFailure:"with failure",noFailures:"no failures recorded",all:"All",failures:"Failures",search:"Search account, owner, equipment line, order, serial number or status",empty:"No records found.",unidentified:"Unidentified account",equipmentTbd:"Equipment to be defined",sent:"sent",invoiceSerial:"Invoice serial",installedSerial:"Installed serial",proposal:"Proposal",order:"Order",loadError:"We couldn't load the documents.",responsible:"Owner",includedAt:"Created",forecastAt:"Forecast",planned:"Planned",elapsed:"Elapsed",overdue:"Overdue"},
 es:{proposalsTitle:"Propuestas comerciales",ordersTitle:"Seguimiento de pedidos",proposalsSub:"Emisión, aceptación y conversión en pedido",ordersSub:"Reflejo del ciclo operativo controlado por CTI Web: CARRIER, facturación, entrega, instalación y cierre",orders:"Pedidos",totalVolume:"volumen total",follow:"Requiere seguimiento",awaiting:"pendiente de avance",inCycle:"En ciclo",fromWeb:"avance reflejado desde CTI Web",orderValue:"Valor en pedidos",withFailure:"con falla",noFailures:"sin fallas registradas",all:"Todos",failures:"Fallas",search:"Buscar cliente, responsable, línea, equipo, pedido, serie o estado",empty:"No se encontraron registros.",unidentified:"Cliente no identificado",equipmentTbd:"Equipo por definir",sent:"enviado",invoiceSerial:"Serie factura",installedSerial:"Serie instalada",proposal:"Propuesta",order:"Pedido",loadError:"No fue posible cargar los documentos.",responsible:"Responsable",includedAt:"Inclusión",forecastAt:"Previsión",planned:"Plazo previsto",elapsed:"Transcurrido",overdue:"Atraso"}
}
function texto(valor: unknown, padrao = "—") { const resultado = String(valor ?? "").trim(); return resultado || padrao }
function statusPedido(item: Registro) { return texto(item.status_ciclo || item.status_envio_carrier || item.status_envio || item.status, "PEDIDO").toUpperCase() }
function statusProposta(item: Registro) { return texto(item.status_documento || item.status, "").toUpperCase().replace(/[^A-Z0-9]/g, "") }
function propostaJaVirouPedido(item: Registro) { return statusProposta(item) === "CONVERTIDAPEDIDO" }
function grupoPedido(item: Registro): Exclude<FiltroPedido, "TODOS"> { const status = statusPedido(item); if (["CARRIER","FATURADO","ENTREGUE","INSTALADO","ENCERRADO","ENVIADO","REENVIADO","CONFIRMADO"].includes(status)) return "ENVIADOS"; if (["FALHA","ERRO","REJEITADO"].includes(status)) return "FALHAS"; return "PENDENTES" }
function encerrado(item: Registro){const s=statusPedido(item);return ["ENCERRADO","FATURADO","CONCLUIDO","CONCLUIDA","CANCELADO","CANCELADA"].includes(s)||statusProposta(item)==="CONVERTIDAPEDIDO"}
function dias(valor:number|null){return valor===null?"—":`${valor}d`}
function listaUsuarios(payload:unknown):UsuarioOpcao[]{if(!Array.isArray(payload))return[];return payload.map((item)=>{const r=item as Registro;return{id:texto(r.id,""),nome:texto(r.nome||r.email,"")}}).filter(i=>i.id&&i.nome)}

export default function DocumentosComerciaisLista({ tipo }: { tipo: "propostas" | "pedidos" }) {
  const { usuario } = useAuth()
  const { locale, formatCurrency, formatDate, formatNumber } = useOperationalI18n(); const c=COPY[locale]
  const master=String(usuario?.tipo_usuario||"").toUpperCase()==="ADMIN_MASTER"
  const [registros,setRegistros]=useState<Registro[]>([]),[busca,setBusca]=useState(""),[filtroPedido,setFiltroPedido]=useState<FiltroPedido>("TODOS"),[carregando,setCarregando]=useState(true),[erro,setErro]=useState("")
  const [filtrosComerciais,setFiltrosComerciais]=useState<FiltrosComerciais>(FILTROS_CRM_VAZIOS)
  const [usuarios,setUsuarios]=useState<UsuarioOpcao[]>([])
  const propostas=tipo==="propostas", titulo=propostas?c.proposalsTitle:c.ordersTitle, subtitulo=propostas?c.proposalsSub:c.ordersSub, Icone=propostas?FileText:PackageCheck

  useEffect(()=>{fetchCrmSeguroProxy(`crm-seguro/${tipo}`,{cache:"no-store"}).then(async r=>{const p=await r.json().catch(()=>[]);if(!r.ok)throw new Error(String((p as Registro).detail||`${c.loadError} (${r.status})`));const lista=Array.isArray(p)?p:[];setRegistros(tipo==="propostas"?lista.filter(item=>!propostaJaVirouPedido(item)):lista)}).catch(f=>setErro(f instanceof Error?f.message:c.loadError)).finally(()=>setCarregando(false))},[tipo,c.loadError])
  useEffect(()=>{if(!master){const id=texto(usuario?.id,"");const nome=texto(usuario?.nome||usuario?.email,"");setUsuarios(id&&nome?[{id,nome}]:[]);return}fetch("/api/crm-proxy/governanca/usuarios",{cache:"no-store"}).then(async r=>r.ok?listaUsuarios(await r.json().catch(()=>[])):[]).then(setUsuarios).catch(()=>setUsuarios([]))},[master,usuario?.id,usuario?.nome,usuario?.email])

  const nomesPorId=useMemo(()=>Object.fromEntries(usuarios.map(i=>[i.id,i.nome])),[usuarios])
  const analiticos=useMemo(()=>registros.map(raw=>({raw,...montarRegistroAnalitico(raw,nomesPorId)})),[registros,nomesPorId])
  const linhas=useMemo(()=>opcoesUnicas(analiticos.map(i=>i.linha),"Não informada"),[analiticos])
  const responsaveis=useMemo(()=>{const base=[...usuarios];for(const item of analiticos){if(item.responsavelId&&item.responsavelNome&&!base.some(u=>u.id===item.responsavelId))base.push({id:item.responsavelId,nome:item.responsavelNome})}return base.sort((a,b)=>a.nome.localeCompare(b.nome,locale))},[usuarios,analiticos,locale])
  const escopoComercial=useMemo(()=>aplicarFiltrosComerciais(analiticos,filtrosComerciais,master,texto(usuario?.id,"")),[analiticos,filtrosComerciais,master,usuario?.id])
  const registrosEscopo=useMemo(()=>escopoComercial.map(i=>i.raw),[escopoComercial])

  const resumoPedidos=useMemo(()=>{const enviados=registrosEscopo.filter(i=>grupoPedido(i)==="ENVIADOS").length,falhas=registrosEscopo.filter(i=>grupoPedido(i)==="FALHAS").length,pendentes=registrosEscopo.filter(i=>grupoPedido(i)==="PENDENTES").length,valor=registrosEscopo.reduce((t,i)=>t+Number(i.valor||0),0);return{total:registrosEscopo.length,enviados,falhas,pendentes,valor}},[registrosEscopo])
  const filtrados=useMemo(()=>{const termo=busca.trim().toLocaleLowerCase(locale);return escopoComercial.filter(a=>{const i=a.raw;if(propostas&&propostaJaVirouPedido(i))return false;if(!propostas&&filtroPedido!=="TODOS"&&grupoPedido(i)!==filtroPedido)return false;if(!termo)return true;return `${texto(i.cliente_nome)} ${a.responsavelNome} ${a.linha} ${texto(i.equipamento)} ${texto(i.numero)} ${texto(i.numero_serie_nf)} ${texto(i.numero_serie_instalado)} ${propostas?texto(i.status_documento||i.status):statusPedido(i)}`.toLocaleLowerCase(locale).includes(termo)})},[busca,filtroPedido,propostas,escopoComercial,locale])
  const filtros=[{id:"TODOS" as FiltroPedido,label:c.all,valor:resumoPedidos.total},{id:"PENDENTES" as FiltroPedido,label:c.follow,valor:resumoPedidos.pendentes},{id:"ENVIADOS" as FiltroPedido,label:c.inCycle,valor:resumoPedidos.enviados},{id:"FALHAS" as FiltroPedido,label:c.failures,valor:resumoPedidos.falhas}]

  function exportarPdf(){exportarRelatorioCrmPdf({titulo,subtitulo,colunas:[{chave:"numero",titulo:propostas?c.proposal:c.order},{chave:"cliente",titulo:"Cliente"},{chave:"responsavel",titulo:c.responsible},{chave:"linha",titulo:"Linha de equipamento"},{chave:"equipamento",titulo:"Equipamento"},{chave:"status",titulo:"Status"},{chave:"valor",titulo:"Valor"},{chave:"inclusao",titulo:c.includedAt},{chave:"previsao",titulo:c.forecastAt},{chave:"atraso",titulo:c.overdue}],registros:filtrados.map(a=>{const i=a.raw,m=calcularMetricasPrazo(a.dataInclusao,a.dataPrevista,encerrado(i));return{numero:texto(i.numero),cliente:texto(i.cliente_nome,c.unidentified),responsavel:a.responsavelNome,linha:a.linha,equipamento:texto(i.equipamento,c.equipmentTbd),status:propostas?texto(i.status_documento||i.status):statusPedido(i),valor:formatCurrency(Number(i.valor||0)),inclusao:a.dataInclusao?formatDate(a.dataInclusao):"—",previsao:a.dataPrevista?formatDate(a.dataPrevista):"—",atraso:m.atrasado?`${m.diasAtraso} dias`:"—"}})})}

  return <main className="min-h-[100dvh] bg-[#020817] px-4 py-5 pb-24 text-white sm:px-6"><div className="mx-auto max-w-6xl">
    <header className="mb-5 flex items-center gap-3"><Link href="/crm-app" className="grid size-11 place-items-center rounded-2xl border border-[#16325c] bg-[#091a33] text-cyan-300"><ArrowLeft size={20}/></Link><div><p className="text-xs uppercase tracking-[.24em] text-cyan-400">CTI CRM</p><h1 className="text-2xl font-bold">{titulo}</h1><p className="text-sm text-slate-400">{subtitulo}</p></div></header>
    <CrmFiltrosComerciais filtros={filtrosComerciais} onChange={setFiltrosComerciais} master={master} responsaveis={responsaveis} linhas={linhas} totalFiltrado={filtrados.length} onPdf={exportarPdf}/>
    {!propostas&&!carregando&&!erro&&<><section className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><Indicador icone={<PackageCheck size={18}/>} label={c.orders} valor={formatNumber(resumoPedidos.total)} detalhe={c.totalVolume}/><Indicador icone={<Clock3 size={18}/>} label={c.follow} valor={formatNumber(resumoPedidos.pendentes)} detalhe={c.awaiting}/><Indicador icone={<CircleCheck size={18}/>} label={c.inCycle} valor={formatNumber(resumoPedidos.enviados)} detalhe={c.fromWeb}/><Indicador icone={<WalletCards size={18}/>} label={c.orderValue} valor={formatCurrency(resumoPedidos.valor)} detalhe={resumoPedidos.falhas?`${formatNumber(resumoPedidos.falhas)} ${c.withFailure}`:c.noFailures}/></section><section className="mb-4 flex flex-wrap gap-2">{filtros.map(f=><button key={f.id} type="button" onClick={()=>setFiltroPedido(f.id)} className={`rounded-full border px-4 py-2 text-sm ${filtroPedido===f.id?"border-cyan-500 bg-cyan-950/50 text-cyan-200":"border-[#24466f] bg-[#07162b] text-slate-400"}`}>{f.label} <strong className="ml-1">{formatNumber(f.valor)}</strong></button>)}</section></>}
    <div className="relative mb-4"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder={c.search} className="h-12 w-full rounded-2xl border border-[#16325c] bg-[#07162b] pl-11 pr-4"/></div>
    {erro&&<div className="rounded-2xl border border-red-900 bg-red-950/40 p-4 text-red-200">{erro}</div>}
    {carregando?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-cyan-300"/></div>:filtrados.length===0?<div className="rounded-3xl border border-dashed border-[#24466f] p-8 text-center text-slate-400">{c.empty}</div>:<div className="space-y-3">{filtrados.map(a=>{const item=a.raw,id=texto(item.id,""),status=propostas?texto(item.status_documento||item.status).replaceAll("_"," "):statusPedido(item).replaceAll("_"," "),href=propostas?`/crm-app/propostas/${id}`:`/crm-app/pedidos/${id}`,enviadoEm=!propostas?texto(item.enviado_carrier_em,""):"",falha=!propostas&&grupoPedido(item)==="FALHAS",serieNf=!propostas?texto(item.numero_serie_nf,""):"",serieInstalada=!propostas?texto(item.numero_serie_instalado,""):"";const dataEnvio=enviadoEm?new Date(enviadoEm):null;const metricas=calcularMetricasPrazo(a.dataInclusao,a.dataPrevista,encerrado(item));return <Link key={id} href={href} className="flex items-start gap-4 rounded-3xl border border-[#16325c] bg-[#07162b] p-5 transition hover:border-cyan-700"><span className={`rounded-2xl p-3 ${falha?"bg-red-950/50 text-red-300":"bg-cyan-950/50 text-cyan-300"}`}>{falha?<CircleAlert size={22}/>:<Icone size={22}/>}</span><span className="min-w-0 flex-1"><strong className="block truncate text-lg">{texto(item.cliente_nome,c.unidentified)}</strong><span className="mt-1 block text-sm text-slate-300">{a.linha!=="Não informada"?`${a.linha} · `:""}{texto(item.equipamento,c.equipmentTbd)}{!propostas&&item.quantidade?` · ${formatNumber(Number(item.quantidade))}`:""}</span><span className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-cyan-300"><UserRound size={13}/>{a.responsavelNome}</span><span className="mt-2 block text-xs text-slate-500">{status} · {formatCurrency(Number(item.valor||0))}{dataEnvio&&!Number.isNaN(dataEnvio.getTime())?` · ${c.sent} ${formatDate(dataEnvio)}`:""}</span><span className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-slate-400"><span className="inline-flex items-center gap-1"><CalendarDays size={12}/>{c.includedAt}: {a.dataInclusao?formatDate(a.dataInclusao):"—"}</span><span>{c.forecastAt}: {a.dataPrevista?formatDate(a.dataPrevista):"—"}</span><span>{c.planned}: {dias(metricas.diasPlanejados)}</span><span>{c.elapsed}: {dias(metricas.diasDecorridos)}</span>{metricas.atrasado&&<span className="font-semibold text-amber-300">{c.overdue}: {metricas.diasAtraso}d</span>}</span>{!propostas&&(serieNf||serieInstalada)&&<span className="mt-1 block text-[11px] text-slate-500">{c.invoiceSerial}: {serieNf||"—"} · {c.installedSerial}: {serieInstalada||"—"}</span>}<span className="mt-1 block text-[11px] text-slate-600">{propostas?c.proposal:c.order} {texto(item.numero)}</span></span></Link>})}</div>}
  </div></main>
}
function Indicador({icone,label,valor,detalhe}:{icone:React.ReactNode;label:string;valor:string;detalhe:string}){return <div className="rounded-2xl border border-[#16325c] bg-[#07162b] p-4"><div className="flex items-center gap-2 text-cyan-300">{icone}<span className="text-xs uppercase tracking-[.12em] text-slate-500">{label}</span></div><strong className="mt-3 block text-xl sm:text-2xl">{valor}</strong><span className="mt-1 block text-xs text-slate-500">{detalhe}</span></div>}
