"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { ArrowLeft, CircleAlert, CircleCheck, Clock3, FileText, Loader2, PackageCheck, Search, WalletCards } from "lucide-react"
import { fetchCrmSeguroProxy } from "@/services/crm-secure"

type Registro = Record<string, unknown>
type FiltroPedido = "TODOS" | "PENDENTES" | "ENVIADOS" | "FALHAS"
function texto(valor: unknown, padrao = "—") { const resultado = String(valor ?? "").trim(); return resultado || padrao }
function moeda(valor: unknown) { return Number(valor || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }) }
function dataBr(valor: unknown) { const bruto = texto(valor, ""); if (!bruto) return "—"; const data = new Date(bruto); return Number.isNaN(data.getTime()) ? bruto : data.toLocaleDateString("pt-BR") }
function statusPedido(item: Registro) { return texto(item.status_ciclo || item.status_envio_carrier || item.status_envio || item.status, "PEDIDO").toUpperCase() }
function grupoPedido(item: Registro): Exclude<FiltroPedido, "TODOS"> { const status = statusPedido(item); if (["CARRIER","FATURADO","ENTREGUE","INSTALADO","ENCERRADO","ENVIADO","REENVIADO","CONFIRMADO"].includes(status)) return "ENVIADOS"; if (["FALHA","ERRO","REJEITADO"].includes(status)) return "FALHAS"; return "PENDENTES" }

export default function DocumentosComerciaisLista({ tipo }: { tipo: "propostas" | "pedidos" }) {
  const [registros,setRegistros]=useState<Registro[]>([]),[busca,setBusca]=useState(""),[filtroPedido,setFiltroPedido]=useState<FiltroPedido>("TODOS"),[carregando,setCarregando]=useState(true),[erro,setErro]=useState("")
  const propostas=tipo==="propostas", titulo=propostas?"Propostas comerciais":"Acompanhamento de pedidos", subtitulo=propostas?"Emissão, aceite e conversão em pedido":"Reflexo do ciclo operacional controlado pelo CTI Web: CARRIER, faturamento, entrega, instalação e encerramento", Icone=propostas?FileText:PackageCheck
  useEffect(()=>{fetchCrmSeguroProxy(`crm-seguro/${tipo}`,{cache:"no-store"}).then(async r=>{const p=await r.json().catch(()=>[]);if(!r.ok)throw new Error(String((p as Registro).detail||`Falha ${r.status}`));setRegistros(Array.isArray(p)?p:[])}).catch(f=>setErro(f instanceof Error?f.message:"Não foi possível carregar os documentos.")).finally(()=>setCarregando(false))},[tipo])
  const resumoPedidos=useMemo(()=>{const enviados=registros.filter(i=>grupoPedido(i)==="ENVIADOS").length,falhas=registros.filter(i=>grupoPedido(i)==="FALHAS").length,pendentes=registros.filter(i=>grupoPedido(i)==="PENDENTES").length,valor=registros.reduce((t,i)=>t+Number(i.valor||0),0);return{total:registros.length,enviados,falhas,pendentes,valor}},[registros])
  const filtrados=useMemo(()=>{const termo=busca.trim().toLocaleLowerCase("pt-BR");return registros.filter(i=>{if(!propostas&&filtroPedido!=="TODOS"&&grupoPedido(i)!==filtroPedido)return false;if(!termo)return true;return `${texto(i.cliente_nome)} ${texto(i.equipamento)} ${texto(i.numero)} ${texto(i.numero_serie_nf)} ${texto(i.numero_serie_instalado)} ${propostas?texto(i.status_documento||i.status):statusPedido(i)}`.toLocaleLowerCase("pt-BR").includes(termo)})},[busca,filtroPedido,propostas,registros])
  const filtros=[{id:"TODOS" as FiltroPedido,label:"Todos",valor:resumoPedidos.total},{id:"PENDENTES" as FiltroPedido,label:"A acompanhar",valor:resumoPedidos.pendentes},{id:"ENVIADOS" as FiltroPedido,label:"Em ciclo",valor:resumoPedidos.enviados},{id:"FALHAS" as FiltroPedido,label:"Falhas",valor:resumoPedidos.falhas}]
  return <main className="min-h-[100dvh] bg-[#020817] px-4 py-5 pb-24 text-white sm:px-6"><div className="mx-auto max-w-6xl">
    <header className="mb-5 flex items-center gap-3"><Link href="/crm-app" className="grid size-11 place-items-center rounded-2xl border border-[#16325c] bg-[#091a33] text-cyan-300"><ArrowLeft size={20}/></Link><div><p className="text-xs uppercase tracking-[.24em] text-cyan-400">CTI CRM</p><h1 className="text-2xl font-bold">{titulo}</h1><p className="text-sm text-slate-400">{subtitulo}</p></div></header>
    {!propostas&&!carregando&&!erro&&<><section className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><Indicador icone={<PackageCheck size={18}/>} label="Pedidos" valor={String(resumoPedidos.total)} detalhe="volume total"/><Indicador icone={<Clock3 size={18}/>} label="A acompanhar" valor={String(resumoPedidos.pendentes)} detalhe="aguardando avanço"/><Indicador icone={<CircleCheck size={18}/>} label="Em ciclo" valor={String(resumoPedidos.enviados)} detalhe="evolução vinda do CTI Web"/><Indicador icone={<WalletCards size={18}/>} label="Valor em pedidos" valor={moeda(resumoPedidos.valor)} detalhe={resumoPedidos.falhas?`${resumoPedidos.falhas} com falha`:"sem falhas registradas"}/></section><section className="mb-4 flex flex-wrap gap-2">{filtros.map(f=><button key={f.id} type="button" onClick={()=>setFiltroPedido(f.id)} className={`rounded-full border px-4 py-2 text-sm ${filtroPedido===f.id?"border-cyan-500 bg-cyan-950/50 text-cyan-200":"border-[#24466f] bg-[#07162b] text-slate-400"}`}>{f.label} <strong className="ml-1">{f.valor}</strong></button>)}</section></>}
    <div className="relative mb-4"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar cliente, equipamento, pedido, série ou status" className="h-12 w-full rounded-2xl border border-[#16325c] bg-[#07162b] pl-11 pr-4"/></div>
    {erro&&<div className="rounded-2xl border border-red-900 bg-red-950/40 p-4 text-red-200">{erro}</div>}
    {carregando?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-cyan-300"/></div>:filtrados.length===0?<div className="rounded-3xl border border-dashed border-[#24466f] p-8 text-center text-slate-400">Nenhum registro encontrado.</div>:<div className="space-y-3">{filtrados.map(item=>{const id=texto(item.id,""),status=propostas?texto(item.status_documento||item.status).replaceAll("_"," "):statusPedido(item).replaceAll("_"," "),href=propostas?`/crm-app/propostas/${id}`:`/crm-app/pedidos/${id}`,enviadoEm=!propostas?texto(item.enviado_carrier_em,""):"",falha=!propostas&&grupoPedido(item)==="FALHAS",serieNf=!propostas?texto(item.numero_serie_nf,""):"",serieInstalada=!propostas?texto(item.numero_serie_instalado,""):"";return <Link key={id} href={href} className="flex items-center gap-4 rounded-3xl border border-[#16325c] bg-[#07162b] p-5 transition hover:border-cyan-700"><span className={`rounded-2xl p-3 ${falha?"bg-red-950/50 text-red-300":"bg-cyan-950/50 text-cyan-300"}`}>{falha?<CircleAlert size={22}/>:<Icone size={22}/>}</span><span className="min-w-0 flex-1"><strong className="block truncate text-lg">{texto(item.cliente_nome,"Cliente não identificado")}</strong><span className="mt-1 block text-sm text-slate-300">{texto(item.equipamento,"Equipamento a definir")}{!propostas&&item.quantidade?` · ${texto(item.quantidade)} un.`:""}</span><span className="mt-2 block text-xs text-slate-500">{status} · {moeda(item.valor)}{enviadoEm?` · enviado ${dataBr(enviadoEm)}`:""}</span>{!propostas&&(serieNf||serieInstalada)&&<span className="mt-1 block text-[11px] text-slate-500">Série NF: {serieNf||"—"} · Série instalada: {serieInstalada||"—"}</span>}<span className="mt-1 block text-[11px] text-slate-600">{propostas?"Proposta":"Pedido"} {texto(item.numero)}</span></span></Link>})}</div>}
  </div></main>
}
function Indicador({icone,label,valor,detalhe}:{icone:React.ReactNode;label:string;valor:string;detalhe:string}){return <div className="rounded-2xl border border-[#16325c] bg-[#07162b] p-4"><div className="flex items-center gap-2 text-cyan-300">{icone}<span className="text-xs uppercase tracking-[.12em] text-slate-500">{label}</span></div><strong className="mt-3 block text-xl sm:text-2xl">{valor}</strong><span className="mt-1 block text-xs text-slate-500">{detalhe}</span></div>}