"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { ArrowLeft, Building2, CircleDollarSign, FileCheck2, Loader2, Mail, PackageCheck, Save, Send } from "lucide-react"
import { useParams } from "next/navigation"
import { fetchCrmSeguroProxy } from "@/services/crm-secure"
import { useClosureI18n } from "@/core/i18n/closure"

type Registro=Record<string,unknown>
type Pacote={pedido:Registro;proposta:Registro|null;item:Registro|null;oportunidade:Registro|null;cliente:Registro|null;envio:Registro|null;protocolo_envio:Registro|null;transporte_email:{configurado?:boolean;remetente?:string;reply_to?:string}|null}
type Locale="pt-BR"|"en"|"es"
function texto(valor:unknown,padrao="—"){const v=String(valor??"").trim();return v||padrao}
function separarEmails(valor:string){return valor.split(/[;,\n]+/).map(i=>i.trim()).filter(Boolean)}
const copy={
 "pt-BR":{load:"Não foi possível carregar o pedido.",needTo:"Informe ao menos um endereço no campo Para.",saveFail:"Não foi possível salvar os destinatários.",saved:"Endereçamento do pedido registrado.",sendNeed:"Registre o campo Para antes de enviar o pedido.",confirmSend:"Confirma o envio definitivo deste pedido para {count} destinatário(s) principal(is)?",sendFail:"Não foi possível enviar o pedido.",sent:"Pedido enviado e protocolo registrado no CTI.",confirmSale:"Confirma a conclusão deste pedido como venda? A venda passará a alimentar o painel gerencial do CTI.",saleFail:"Não foi possível registrar a venda.",saleAlready:"Venda já estava registrada no CTI.",saleDone:"Venda registrada. O painel gerencial do CTI foi alimentado.",accountMissing:"Cliente não identificado no cadastro",sourceProposal:"Proposta de origem",deliveryStatus:"ENVIO",noRecipient:"Nenhum destinatário principal registrado. Use o botão Adicionar.",sendNotes:"Observações para o envio",sendingOrder:"Enviando pedido...",transportOk:"Transporte confirmado",transportBlocked:"Envio bloqueado até a confirmação do domínio e da chave de transporte no Render.",deliveryConfirmed:"Envio confirmado",date:"Data",provider:"Provedor",protocol:"Protocolo",sender:"Remetente",dossier:"Dossiê comercial preservado",dossierText:"O pedido mantém vínculo com a proposta aceita, o aceite registrado, a oportunidade, o item comercial, o endereçamento e o protocolo de envio."},
 en:{load:"We couldn't load the order.",needTo:"Enter at least one address in the To field.",saveFail:"We couldn't save the recipients.",saved:"Order recipients saved.",sendNeed:"Save the To field before sending the order.",confirmSend:"Confirm final delivery of this order to {count} primary recipient(s)?",sendFail:"We couldn't send the order.",sent:"Order sent and delivery protocol recorded in CTI.",confirmSale:"Confirm closing this order as a sale? The sale will feed CTI management reporting.",saleFail:"We couldn't record the sale.",saleAlready:"The sale was already recorded in CTI.",saleDone:"Sale recorded. CTI management reporting has been updated.",accountMissing:"Account not identified in master data",sourceProposal:"Source proposal",deliveryStatus:"DELIVERY",noRecipient:"No primary recipient is registered. Use Add to enter one.",sendNotes:"Delivery notes",sendingOrder:"Sending order...",transportOk:"Delivery configured",transportBlocked:"Sending is blocked until the delivery domain and transport key are confirmed in Render.",deliveryConfirmed:"Delivery confirmed",date:"Date",provider:"Provider",protocol:"Protocol",sender:"Sender",dossier:"Commercial dossier preserved",dossierText:"The order remains linked to the accepted proposal, recorded acceptance, opportunity, commercial item, addressing and delivery protocol."},
 es:{load:"No fue posible cargar el pedido.",needTo:"Ingrese al menos una dirección en el campo Para.",saveFail:"No fue posible guardar los destinatarios.",saved:"Destinatarios del pedido registrados.",sendNeed:"Registre el campo Para antes de enviar el pedido.",confirmSend:"¿Confirma el envío definitivo de este pedido a {count} destinatario(s) principal(es)?",sendFail:"No fue posible enviar el pedido.",sent:"Pedido enviado y protocolo registrado en CTI.",confirmSale:"¿Confirma la conclusión de este pedido como venta? La venta alimentará el panel gerencial de CTI.",saleFail:"No fue posible registrar la venta.",saleAlready:"La venta ya estaba registrada en CTI.",saleDone:"Venta registrada. El panel gerencial de CTI fue actualizado.",accountMissing:"Cliente no identificado en los datos maestros",sourceProposal:"Propuesta de origen",deliveryStatus:"ENVÍO",noRecipient:"No hay destinatario principal registrado. Use Agregar para incluir uno.",sendNotes:"Observaciones del envío",sendingOrder:"Enviando pedido...",transportOk:"Transporte confirmado",transportBlocked:"El envío está bloqueado hasta confirmar el dominio y la clave de transporte en Render.",deliveryConfirmed:"Envío confirmado",date:"Fecha",provider:"Proveedor",protocol:"Protocolo",sender:"Remitente",dossier:"Expediente comercial preservado",dossierText:"El pedido mantiene el vínculo con la propuesta aceptada, la aceptación registrada, la oportunidad, el ítem comercial, los destinatarios y el protocolo de envío."}
} satisfies Record<Locale,Record<string,string>>
function fill(s:string,count:number){return s.replace("{count}",String(count))}

export default function PedidoCrmAppPage(){
 const params=useParams<{id:string}>(),id=String(params.id||"");const {locale,tc,formatCurrency,formatDate}=useClosureI18n(),t=copy[locale as Locale]||copy["pt-BR"]
 const[dados,setDados]=useState<Pacote|null>(null),[carregando,setCarregando]=useState(true),[salvando,setSalvando]=useState(false),[enviando,setEnviando]=useState(false),[registrandoVenda,setRegistrandoVenda]=useState(false),[vendaRegistrada,setVendaRegistrada]=useState(false),[tipoVenda,setTipoVenda]=useState("EQUIPAMENTO"),[erro,setErro]=useState(""),[mensagem,setMensagem]=useState(""),[editando,setEditando]=useState(false),[para,setPara]=useState(""),[cc,setCc]=useState(""),[cco,setCco]=useState(""),[observacoes,setObservacoes]=useState("")
 const moeda=(v:unknown)=>formatCurrency(Number(v||0)),data=(v:unknown)=>{const x=texto(v,"");return x?formatDate(x,{dateStyle:"short",timeStyle:"short"}):"—"}
 const carregar=useCallback(async()=>{if(!id)return;setCarregando(true);setErro("");try{const r=await fetchCrmSeguroProxy(`crm-seguro/pedidos/${encodeURIComponent(id)}/pacote`,{cache:"no-store"}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p.detail||t.load));setDados(p);setPara(Array.isArray(p?.envio?.destinatarios)?p.envio.destinatarios.join("\n"):"");setCc(Array.isArray(p?.envio?.cc)?p.envio.cc.join("\n"):"");setCco(Array.isArray(p?.envio?.cco)?p.envio.cco.join("\n"):"");setObservacoes(String(p?.envio?.observacoes_envio||""))}catch(e){setErro(e instanceof Error?e.message:t.load)}finally{setCarregando(false)}},[id,t.load])
 useEffect(()=>{void carregar()},[carregar])
 async function salvarDestinatarios(){const destinatarios=separarEmails(para);if(!destinatarios.length){setErro(t.needTo);return}setSalvando(true);setErro("");setMensagem("");try{const r=await fetchCrmSeguroProxy(`crm-seguro/pedidos/${encodeURIComponent(id)}/destinatarios`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({destinatarios,cc:separarEmails(cc),cco:separarEmails(cco),observacoes_envio:observacoes||null})}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p.detail||t.saveFail));setMensagem(t.saved);setEditando(false);await carregar()}catch(e){setErro(e instanceof Error?e.message:t.saveFail)}finally{setSalvando(false)}}
 async function enviarPedido(){const destinatarios=Array.isArray(dados?.envio?.destinatarios)?dados.envio.destinatarios as string[]:[];if(!destinatarios.length){setErro(t.sendNeed);return}if(!window.confirm(fill(t.confirmSend,destinatarios.length)))return;setEnviando(true);setErro("");setMensagem("");try{const r=await fetchCrmSeguroProxy(`crm-seguro/pedidos/${encodeURIComponent(id)}/enviar`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmar:true})}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p.detail||t.sendFail));setDados(p);setMensagem(t.sent)}catch(e){setErro(e instanceof Error?e.message:t.sendFail)}finally{setEnviando(false)}}
 async function concluirVenda(){if(!window.confirm(t.confirmSale))return;setRegistrandoVenda(true);setErro("");setMensagem("");try{const r=await fetchCrmSeguroProxy(`crm-seguro/pedidos/${encodeURIComponent(id)}/concluir-venda`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmar:true,tipo_venda:tipoVenda})}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p.detail||t.saleFail));setVendaRegistrada(true);setMensagem(p.status==="JA_REGISTRADA"?t.saleAlready:t.saleDone)}catch(e){setErro(e instanceof Error?e.message:t.saleFail)}finally{setRegistrandoVenda(false)}}
 const destinatarios=Array.isArray(dados?.envio?.destinatarios)?dados.envio.destinatarios as string[]:[],copias=Array.isArray(dados?.envio?.cc)?dados.envio.cc as string[]:[],ocultas=Array.isArray(dados?.envio?.cco)?dados.envio.cco as string[]:[],protocolo=dados?.protocolo_envio||null,enviado=texto(protocolo?.status_envio||dados?.envio?.status_envio,"PENDENTE")==="ENVIADO",statusEnvio=enviado?"ENVIADO":texto(dados?.envio?.status_envio,"PENDENTE"),transporteConfigurado=Boolean(dados?.transporte_email?.configurado),cliente=texto(dados?.cliente?.razao_social||dados?.cliente?.nome||dados?.oportunidade?.cliente_nome,t.accountMissing)
 return <main className="min-h-[100dvh] bg-[#020817] px-4 py-5 pb-24 text-white sm:px-6"><div className="mx-auto max-w-4xl">
  <header className="mb-5 flex items-center gap-3"><Link href="/crm-app/pedidos" className="grid size-11 place-items-center rounded-2xl border border-[#16325c] bg-[#091a33] text-cyan-300"><ArrowLeft size={20}/></Link><div><p className="text-xs uppercase tracking-[0.24em] text-cyan-400">CTI CRM</p><h1 className="text-2xl font-bold">{tc("crmOrder.title")}</h1><p className="text-sm text-slate-400">{tc("crmOrder.subtitle")}</p></div></header>
  {carregando&&<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-cyan-300"/></div>}{erro&&<div className="mb-4 rounded-2xl border border-red-900 bg-red-950/40 p-4 text-red-200">{erro}</div>}{mensagem&&<div className="mb-4 rounded-2xl border border-emerald-900 bg-emerald-950/30 p-4 text-emerald-200">{mensagem}</div>}
  {dados&&<div className="space-y-4"><section className="rounded-3xl border border-emerald-800 bg-gradient-to-br from-emerald-950/50 to-[#07162b] p-5"><div className="flex items-start gap-3"><span className="rounded-2xl bg-emerald-900/40 p-3 text-emerald-300"><PackageCheck size={24}/></span><div><p className="text-sm text-slate-400">{tc("crmOrder.commercialOrder")}</p><h2 className="mt-1 text-xl font-bold">{texto(dados.pedido.numero,tc("crmOrder.generated"))}</h2><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded-full border border-emerald-700 px-3 py-1 text-emerald-200">{texto(dados.pedido.status,"ABERTO").replaceAll("_"," ")}</span><span className="rounded-full border border-[#24466f] px-3 py-1">{moeda(dados.pedido.valor)}</span></div></div></div></section>
  <section className="grid gap-3 sm:grid-cols-2"><Info icone={<Building2 size={18}/>} label={tc("crmOrder.account")} valor={cliente}/><Info icone={<PackageCheck size={18}/>} label={tc("proposal.equipment")} valor={texto(dados.item?.equipamento)}/><Info icone={<FileCheck2 size={18}/>} label={t.sourceProposal} valor={texto(dados.proposta?.numero)}/><Info icone={<FileCheck2 size={18}/>} label={tc("crmOrder.createdAt")} valor={data(dados.pedido.created_at)}/></section>
  <section className="rounded-3xl border border-cyan-800 bg-gradient-to-br from-cyan-950/30 to-[#07162b] p-5"><div className="flex items-start gap-3"><span className="rounded-2xl bg-cyan-900/40 p-3 text-cyan-300"><CircleDollarSign size={24}/></span><div className="flex-1"><p className="text-xs uppercase tracking-[0.2em] text-cyan-400">{tc("crmOrder.saleConclusion")}</p><h3 className="mt-1 text-lg font-bold">{tc("crmOrder.orderToSale")}</h3><p className="mt-1 text-sm text-slate-400">{tc("crmOrder.saleDescription")}</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><label className="text-sm text-slate-300">{tc("crmOrder.saleType")}<select value={tipoVenda} onChange={e=>setTipoVenda(e.target.value)} disabled={vendaRegistrada||registrandoVenda} className="mt-2 w-full rounded-xl border border-[#24466f] bg-[#020817] px-3 py-3 text-white"><option value="EQUIPAMENTO">{tc("crmOrder.equipmentSale")}</option><option value="PECA">{tc("crmOrder.partSale")}</option><option value="SERVICO">{tc("crmOrder.serviceSale")}</option><option value="OUTRA">{tc("crmOrder.otherSale")}</option></select></label><button disabled={vendaRegistrada||registrandoVenda} onClick={()=>void concluirVenda()} className="self-end rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{vendaRegistrada?tc("crmOrder.saleRegistered"):registrandoVenda?tc("crmOrder.registering"):tc("crmOrder.completeSale")}</button></div></section>
  <section className="rounded-3xl border border-[#16325c] bg-[#07162b] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">{tc("crmOrder.addressing")}</h3><p className="text-sm text-slate-400">{tc("crmOrder.addressingSub")}</p></div><div className="flex items-center gap-2"><span className={`rounded-full border px-3 py-1 text-xs ${enviado?"border-emerald-700 text-emerald-300":"border-amber-700 text-amber-300"}`}>{t.deliveryStatus} {statusEnvio.replaceAll("_"," ")}</span>{!enviado&&<button type="button" onClick={()=>setEditando(v=>!v)} className="rounded-xl border border-cyan-700 px-3 py-2 text-sm text-cyan-200">{destinatarios.length?tc("crmOrder.edit"):tc("crmOrder.add")}</button>}</div></div>
  {editando?<div className="mt-4 space-y-3"><Campo titulo={tc("crmOrder.to")} valor={para} alterar={setPara}/><Campo titulo={tc("crmOrder.cc")} valor={cc} alterar={setCc}/><Campo titulo={tc("crmOrder.bcc")} valor={cco} alterar={setCco}/><Campo titulo={tc("crmOrder.notes")} valor={observacoes} alterar={setObservacoes}/><button disabled={salvando} onClick={()=>void salvarDestinatarios()} className="w-full rounded-xl bg-cyan-500 px-4 py-3 font-semibold text-slate-950 disabled:opacity-50"><Save className="mr-2 inline" size={18}/>{salvando?tc("common.saving"):tc("crmOrder.saveAddressing")}</button></div>:<div className="mt-4 space-y-3"><GrupoEmails titulo={tc("crmOrder.to")} emails={destinatarios}/>{copias.length>0&&<GrupoEmails titulo="CC" emails={copias}/>} {ocultas.length>0&&<GrupoEmails titulo="BCC" emails={ocultas}/>} {!destinatarios.length&&<p className="rounded-2xl border border-dashed border-[#24466f] p-4 text-sm text-slate-400">{t.noRecipient}</p>}</div>}
  {!editando&&texto(dados.envio?.observacoes_envio,"")&&<div className="mt-4 rounded-2xl bg-[#020817] p-4 text-sm text-slate-300"><strong className="block text-xs text-slate-500">{t.sendNotes}</strong>{texto(dados.envio?.observacoes_envio)}</div>}
  {!enviado&&!editando&&<div className="mt-4"><button disabled={enviando||!destinatarios.length||!transporteConfigurado} onClick={()=>void enviarPedido()} className="w-full rounded-xl bg-emerald-500 px-4 py-3 font-semibold text-slate-950 disabled:opacity-40"><Send className="mr-2 inline" size={18}/>{enviando?t.sendingOrder:tc("crmOrder.sendOrder")}</button><p className={`mt-3 text-xs ${transporteConfigurado?"text-emerald-300":"text-amber-300"}`}>{transporteConfigurado?`${t.transportOk}: ${texto(dados.transporte_email?.remetente)}`:t.transportBlocked}</p></div>}
  {enviado&&protocolo&&<div className="mt-4 rounded-2xl border border-emerald-800 bg-emerald-950/30 p-4"><h4 className="font-semibold text-emerald-200">{t.deliveryConfirmed}</h4><div className="mt-3 grid gap-2 text-sm text-slate-300 sm:grid-cols-2"><p><strong className="text-slate-500">{t.date}:</strong> {data(protocolo.enviado_em)}</p><p><strong className="text-slate-500">{t.provider}:</strong> {texto(protocolo.provider)}</p><p className="sm:col-span-2 break-all"><strong className="text-slate-500">{t.protocol}:</strong> {texto(protocolo.message_id)}</p><p className="sm:col-span-2 break-all"><strong className="text-slate-500">{t.sender}:</strong> {texto(protocolo.remetente)}</p></div></div>}</section>
  <section className="rounded-3xl border border-[#16325c] bg-[#07162b] p-5"><h3 className="font-bold">{t.dossier}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{t.dossierText}</p></section></div>}
 </div></main>
}
function Campo({titulo,valor,alterar}:{titulo:string;valor:string;alterar:(v:string)=>void}){return <label className="block text-sm text-slate-300">{titulo}<textarea value={valor} onChange={e=>alterar(e.target.value)} className="mt-2 min-h-16 w-full rounded-2xl border border-[#24466f] bg-[#020817] p-3 text-white"/></label>}
function GrupoEmails({titulo,emails}:{titulo:string;emails:string[]}){return <div><strong className="mb-2 block text-xs uppercase tracking-[.14em] text-slate-500">{titulo}</strong><div className="space-y-2">{emails.map(email=><div key={`${titulo}:${email}`} className="flex items-center gap-3 rounded-2xl border border-[#16325c] bg-[#091a33] p-3"><Mail size={18} className="text-cyan-300"/><span className="break-all text-sm">{email}</span></div>)}</div></div>}
function Info({icone,label,valor}:{icone:React.ReactNode;label:string;valor:string}){return <div className="rounded-2xl border border-[#16325c] bg-[#091a33] p-4"><div className="flex items-center gap-2 text-cyan-300">{icone}<span className="text-xs text-slate-400">{label}</span></div><strong className="mt-2 block">{valor}</strong></div>}
