"use client"

import { useCallback } from "react"
import { useI18n } from "./I18nContext"

type Params = Record<string, string | number>
type Dict = Record<string, string>

const pt: Dict = {
  "dossier.title":"Dossiê comercial do cliente","dossier.subtitle":"Uma visão única da carteira, histórico e próximos passos","dossier.edit":"Editar cadastro","dossier.scheduleVisit":"Agendar visita","dossier.activity":"Registrar atividade","dossier.newOpportunity":"Nova oportunidade","dossier.deals":"Negócios","dossier.pipeline":"Pipeline","dossier.pending":"Pendências","dossier.overdue":"Atrasadas","dossier.lastVisit":"Última visita","dossier.noVisit":"Nenhuma visita concluída","dossier.noVisitDetail":"O histórico ainda não possui visita realizada.","dossier.nextAction":"Próxima ação","dossier.noAction":"Nenhuma próxima ação","dossier.noActionDetail":"Defina uma atividade para manter o cliente em acompanhamento.","dossier.negotiations":"Negociações","dossier.noDeals":"Nenhuma oportunidade vinculada ao seu escopo comercial para este cliente.","dossier.history":"Histórico comercial do cliente","dossier.noActivities":"Nenhuma atividade do seu escopo registrada para este cliente.","dossier.openDeal":"Abrir negociação →","dossier.loadFailed":"Não foi possível carregar o dossiê comercial.","dossier.activitiesFailed":"Não foi possível carregar as atividades autorizadas ({status}).","dossier.unknownDate":"Não informada","dossier.defaultOpportunity":"Oportunidade comercial","dossier.defaultRecord":"Registro comercial",
  "edit.title":"Editar cliente","edit.subtitle":"Use o CNPJ para conferir e enriquecer os dados cadastrais.","edit.registration":"Dados cadastrais","edit.review":"A consulta apenas preenche a tela; você confirma ao salvar.","edit.checkTaxId":"Buscar / conferir CNPJ","edit.savedTaxId":"CNPJ confirmado no cadastro CTI. Nenhum dado externo foi aplicado automaticamente.","edit.external":"Dados encontrados em {source}. Revise as alterações e toque em Salvar para confirmá-las.","edit.updated":"Cadastro atualizado e disponível em toda a jornada comercial.","edit.save":"Salvar alterações","edit.loadFailed":"Não foi possível carregar o cliente.","edit.taxFailed":"Não foi possível consultar o CNPJ.","edit.duplicate":"Este CNPJ já pertence a {name}.","edit.required":"Preencha razão social, cidade, UF e categoria.","edit.updateFailed":"Não foi possível atualizar o cliente.","edit.otherClient":"outro cliente",
  "field.legalName":"Nome / razão social","field.taxId":"CNPJ","field.stateRegistration":"Inscrição estadual","field.category":"Categoria","field.addressSection":"Endereço","field.address":"Endereço","field.number":"Número","field.complement":"Complemento","field.district":"Bairro","field.city":"Cidade","field.state":"UF","field.postal":"CEP","field.areaCode":"DDD","field.subregion":"Sub-região","field.contactSection":"Contato comercial e fiscal","field.contact":"Contato","field.phone":"Fone","field.email":"E-mail","field.xml":"E-mail para XML","cat.transport":"Transportadora","cat.producer":"Produtor","cat.shipper":"Embarcador","cat.rental":"Locadora","cat.bodybuilder":"Implementadora","cat.distributor":"Distribuidora"
}
const en: Dict = {
  "dossier.title":"Account intelligence file","dossier.subtitle":"One view of the account, relationship history and next moves","dossier.edit":"Edit account","dossier.scheduleVisit":"Schedule visit","dossier.activity":"Log activity","dossier.newOpportunity":"New opportunity","dossier.deals":"Deals","dossier.pipeline":"Pipeline","dossier.pending":"Pending actions","dossier.overdue":"Overdue","dossier.lastVisit":"Last visit","dossier.noVisit":"No completed visit","dossier.noVisitDetail":"No completed visit has been recorded in the relationship history yet.","dossier.nextAction":"Next action","dossier.noAction":"No next action","dossier.noActionDetail":"Schedule an activity to keep this account actively managed.","dossier.negotiations":"Open business","dossier.noDeals":"No opportunity in your commercial scope is linked to this account.","dossier.history":"Account relationship history","dossier.noActivities":"No activity in your scope has been recorded for this account.","dossier.openDeal":"Open deal →","dossier.loadFailed":"We couldn't load the account file.","dossier.activitiesFailed":"We couldn't load the authorized activities ({status}).","dossier.unknownDate":"Not provided","dossier.defaultOpportunity":"Sales opportunity","dossier.defaultRecord":"Commercial activity",
  "edit.title":"Edit account","edit.subtitle":"Use the Brazilian tax ID to verify and enrich company registration data.","edit.registration":"Company registration","edit.review":"The lookup only fills the form; changes are applied only when you save.","edit.checkTaxId":"Retrieve / verify CNPJ","edit.savedTaxId":"CNPJ confirmed in CTI. No external data was applied automatically.","edit.external":"Company data found via {source}. Review the changes and save to confirm them.","edit.updated":"Account updated and available throughout the sales workflow.","edit.save":"Save changes","edit.loadFailed":"We couldn't load the account.","edit.taxFailed":"We couldn't retrieve the CNPJ data.","edit.duplicate":"This CNPJ already belongs to {name}.","edit.required":"Complete legal name, city, state and account type.","edit.updateFailed":"We couldn't update the account.","edit.otherClient":"another account",
  "field.legalName":"Account / legal name","field.taxId":"Tax ID (CNPJ)","field.stateRegistration":"State tax registration","field.category":"Account type","field.addressSection":"Address","field.address":"Street address","field.number":"Number","field.complement":"Additional address","field.district":"District","field.city":"City","field.state":"State","field.postal":"Postal code","field.areaCode":"Area code","field.subregion":"Sub-region","field.contactSection":"Commercial and billing contact","field.contact":"Contact","field.phone":"Phone","field.email":"Email","field.xml":"Invoice XML email","cat.transport":"Carrier / Fleet operator","cat.producer":"Producer","cat.shipper":"Shipper","cat.rental":"Rental company","cat.bodybuilder":"Body builder","cat.distributor":"Distributor"
}
const es: Dict = {
  "dossier.title":"Expediente comercial del cliente","dossier.subtitle":"Una visión única del cliente, su historial comercial y los próximos pasos","dossier.edit":"Editar cliente","dossier.scheduleVisit":"Programar visita","dossier.activity":"Registrar actividad","dossier.newOpportunity":"Nueva oportunidad","dossier.deals":"Negocios","dossier.pipeline":"Pipeline","dossier.pending":"Pendientes","dossier.overdue":"Vencidas","dossier.lastVisit":"Última visita","dossier.noVisit":"Sin visitas realizadas","dossier.noVisitDetail":"El historial aún no registra una visita realizada.","dossier.nextAction":"Próxima acción","dossier.noAction":"Sin próxima acción","dossier.noActionDetail":"Programe una actividad para mantener el seguimiento del cliente.","dossier.negotiations":"Negocios en curso","dossier.noDeals":"No hay oportunidades de su ámbito comercial vinculadas a este cliente.","dossier.history":"Historial comercial del cliente","dossier.noActivities":"No hay actividades de su ámbito registradas para este cliente.","dossier.openDeal":"Abrir negocio →","dossier.loadFailed":"No fue posible cargar el expediente comercial.","dossier.activitiesFailed":"No fue posible cargar las actividades autorizadas ({status}).","dossier.unknownDate":"No informada","dossier.defaultOpportunity":"Oportunidad comercial","dossier.defaultRecord":"Actividad comercial",
  "edit.title":"Editar cliente","edit.subtitle":"Utilice el CNPJ para verificar y enriquecer los datos registrales.","edit.registration":"Datos registrales","edit.review":"La consulta solo completa el formulario; los cambios se confirman al guardar.","edit.checkTaxId":"Buscar / verificar CNPJ","edit.savedTaxId":"CNPJ confirmado en CTI. No se aplicaron datos externos automáticamente.","edit.external":"Datos encontrados en {source}. Revise los cambios y guárdelos para confirmarlos.","edit.updated":"Cliente actualizado y disponible en todo el proceso comercial.","edit.save":"Guardar cambios","edit.loadFailed":"No fue posible cargar el cliente.","edit.taxFailed":"No fue posible consultar el CNPJ.","edit.duplicate":"Este CNPJ ya pertenece a {name}.","edit.required":"Complete razón social, ciudad, estado y categoría.","edit.updateFailed":"No fue posible actualizar el cliente.","edit.otherClient":"otro cliente",
  "field.legalName":"Nombre / razón social","field.taxId":"CNPJ","field.stateRegistration":"Inscripción estatal","field.category":"Categoría","field.addressSection":"Dirección","field.address":"Dirección","field.number":"Número","field.complement":"Complemento","field.district":"Barrio","field.city":"Ciudad","field.state":"Estado","field.postal":"Código postal","field.areaCode":"Código de área","field.subregion":"Subregión","field.contactSection":"Contacto comercial y fiscal","field.contact":"Contacto","field.phone":"Teléfono","field.email":"Correo electrónico","field.xml":"Correo para XML","cat.transport":"Transportista","cat.producer":"Productor","cat.shipper":"Cargador","cat.rental":"Empresa de alquiler","cat.bodybuilder":"Carrocero","cat.distributor":"Distribuidor"
}
const dictionaries={"pt-BR":pt,en,es}
function interpolate(template:string,params?:Params){if(!params)return template;return template.replace(/\{(\w+)\}/g,(_,key:string)=>String(params[key]??`{${key}}`))}
export function useClientsI18n(){const {locale,formatDate,formatNumber,formatCurrency}=useI18n();const tClient=useCallback((key:string,params?:Params)=>{const d=dictionaries[locale]||pt;return interpolate(d[key]||pt[key]||key,params)},[locale]);return{locale,tClient,formatDate,formatNumber,formatCurrency}}
