"use client"

import { useCallback } from "react"
import { useI18n } from "./I18nContext"

type Params = Record<string, string | number>
type Dict = Record<string, string>

const pt: Dict = {
  "common.start": "Início", "common.end": "Fim", "common.search": "Buscar", "common.currentMonth": "Mês atual", "common.action": "Ação", "common.company": "Empresa", "common.value": "Valor", "common.stage": "Etapa", "common.forecast": "Previsão", "common.open": "Abrir", "common.all": "Todas", "common.openFem": "Abertas", "common.loadingData": "Carregando dados",
  "op.eyebrow": "Negócio individual", "op.title": "CRM • Oportunidades", "op.subtitle": "Fonte operacional do negócio: cliente, composição de itens, valor, chance, próxima ação e previsão de fechamento.", "op.report": "Gerar relatório", "op.new": "Nova oportunidade", "op.searchPlaceholder": "Empresa, oportunidade, produto ou etapa", "op.periodRecords": "Registros no período", "op.openCount": "Oportunidades abertas", "op.openValue": "Valor aberto", "op.weightedValue": "Valor ponderado", "op.loading": "Carregando oportunidades...", "op.empty": "Nenhuma oportunidade encontrada no período.", "op.composition": "Composição atual: {count} oportunidade(s) · visão {view}.", "op.opportunity": "Oportunidade", "op.products": "Produtos da oportunidade", "op.chance": "Chance", "op.openDeal": "Abrir negócio", "op.undefined": "A definir", "op.noForecast": "Sem previsão", "op.loadFailed": "Não foi possível carregar as oportunidades do período.",
  "dashboard.eyebrow": "Leitura temporal executiva", "dashboard.title": "Dashboard Executivo", "dashboard.subtitle": "Passado consolidado e negócios atuais, separados para leitura imediata.", "dashboard.activeContext": "Contexto ativo", "dashboard.historyPeriod": "Período histórico", "dashboard.lastUpdate": "Última atualização", "dashboard.filteredHistory": "Registros históricos filtrados", "dashboard.connection": "Conexão temporariamente indisponível. Reconexão automática em andamento; nenhum indicador indisponível será mostrado como zero.", "dashboard.realized": "REALIZADO", "dashboard.realizedSub": "O que já aconteceu.", "dashboard.confirmedHistory": "Histórico confirmado", "dashboard.inProgress": "EM CURSO", "dashboard.inProgressSub": "O que está acontecendo agora.", "dashboard.liveDeals": "Negócios vivos", "dashboard.historicalClients": "Clientes históricos", "dashboard.historicalTicket": "Ticket histórico", "dashboard.states": "Estados atendidos", "dashboard.cities": "Municípios", "dashboard.openPipeline": "Pipeline aberto", "dashboard.activeDeals": "Negociações ativas", "dashboard.currentProposals": "Propostas vigentes", "dashboard.ordersInProgress": "Pedidos em curso", "dashboard.historyChart": "Volume por linha — período atual × anterior", "dashboard.pipelineChart": "Pipeline atual por linha de equipamento", "dashboard.previousPeriod": "Período anterior", "dashboard.selectedPeriod": "Período selecionado", "dashboard.allHistory": "Todo o histórico disponível", "dashboard.customPeriod": "Período personalizado",
  "pipeline.title": "Pipeline Comercial", "activities.title": "Atividades Comerciais", "proposals.title": "Propostas Comerciais", "orders.title": "Pedidos", "sales.title": "Vendas",
  "common.clickDetail": "Clique para detalhar"
}

const en: Dict = {
  "common.start": "Start", "common.end": "End", "common.search": "Search", "common.currentMonth": "Current month", "common.action": "Action", "common.company": "Account", "common.value": "Value", "common.stage": "Stage", "common.forecast": "Expected close", "common.open": "Open", "common.all": "All", "common.openFem": "Open", "common.loadingData": "Loading data",
  "op.eyebrow": "Individual deal", "op.title": "CRM • Opportunities", "op.subtitle": "Operational source of truth for each deal: account, item mix, value, win probability, next action and expected close date.", "op.report": "Generate report", "op.new": "New opportunity", "op.searchPlaceholder": "Account, opportunity, product or stage", "op.periodRecords": "Records in period", "op.openCount": "Open opportunities", "op.openValue": "Open pipeline value", "op.weightedValue": "Weighted pipeline", "op.loading": "Loading opportunities...", "op.empty": "No opportunities found for this period.", "op.composition": "Current view: {count} opportunity(ies) · {view}.", "op.opportunity": "Opportunity", "op.products": "Opportunity products", "op.chance": "Win probability", "op.openDeal": "Open deal", "op.undefined": "To be defined", "op.noForecast": "No expected close", "op.loadFailed": "We couldn't load opportunities for this period.",
  "dashboard.eyebrow": "Executive time view", "dashboard.title": "Executive Dashboard", "dashboard.subtitle": "Confirmed history and current business, separated for immediate reading.", "dashboard.activeContext": "Active context", "dashboard.historyPeriod": "Historical period", "dashboard.lastUpdate": "Last updated", "dashboard.filteredHistory": "Filtered historical records", "dashboard.connection": "Connection temporarily unavailable. Automatic reconnection is in progress; unavailable indicators will never be shown as zero.", "dashboard.realized": "COMPLETED", "dashboard.realizedSub": "What has already happened.", "dashboard.confirmedHistory": "Confirmed history", "dashboard.inProgress": "IN PROGRESS", "dashboard.inProgressSub": "What is happening now.", "dashboard.liveDeals": "Live deals", "dashboard.historicalClients": "Historical accounts", "dashboard.historicalTicket": "Historical average ticket", "dashboard.states": "States served", "dashboard.cities": "Municipalities", "dashboard.openPipeline": "Open pipeline", "dashboard.activeDeals": "Active deals", "dashboard.currentProposals": "Active proposals", "dashboard.ordersInProgress": "Orders in progress", "dashboard.historyChart": "Volume by product line — selected vs previous period", "dashboard.pipelineChart": "Current pipeline by equipment line", "dashboard.previousPeriod": "Previous period", "dashboard.selectedPeriod": "Selected period", "dashboard.allHistory": "All available history", "dashboard.customPeriod": "Custom period",
  "pipeline.title": "Sales Pipeline", "activities.title": "Sales Activities", "proposals.title": "Sales Proposals", "orders.title": "Orders", "sales.title": "Sales",
  "common.clickDetail": "Click to view details"
}

const es: Dict = {
  "common.start": "Inicio", "common.end": "Fin", "common.search": "Buscar", "common.currentMonth": "Mes actual", "common.action": "Acción", "common.company": "Cliente", "common.value": "Valor", "common.stage": "Etapa", "common.forecast": "Cierre previsto", "common.open": "Abrir", "common.all": "Todas", "common.openFem": "Abiertas", "common.loadingData": "Cargando datos",
  "op.eyebrow": "Negocio individual", "op.title": "CRM • Oportunidades", "op.subtitle": "Fuente operativa de cada negocio: cliente, composición de productos, valor, probabilidad de cierre, próxima acción y fecha prevista de cierre.", "op.report": "Generar informe", "op.new": "Nueva oportunidad", "op.searchPlaceholder": "Cliente, oportunidad, producto o etapa", "op.periodRecords": "Registros del período", "op.openCount": "Oportunidades abiertas", "op.openValue": "Valor abierto", "op.weightedValue": "Valor ponderado", "op.loading": "Cargando oportunidades...", "op.empty": "No se encontraron oportunidades en el período.", "op.composition": "Vista actual: {count} oportunidad(es) · {view}.", "op.opportunity": "Oportunidad", "op.products": "Productos de la oportunidad", "op.chance": "Probabilidad", "op.openDeal": "Abrir negocio", "op.undefined": "Por definir", "op.noForecast": "Sin previsión", "op.loadFailed": "No fue posible cargar las oportunidades del período.",
  "dashboard.eyebrow": "Lectura temporal ejecutiva", "dashboard.title": "Panel Ejecutivo", "dashboard.subtitle": "Historial confirmado y negocios actuales, separados para una lectura inmediata.", "dashboard.activeContext": "Contexto activo", "dashboard.historyPeriod": "Período histórico", "dashboard.lastUpdate": "Última actualización", "dashboard.filteredHistory": "Registros históricos filtrados", "dashboard.connection": "Conexión temporalmente no disponible. La reconexión automática está en curso; ningún indicador no disponible se mostrará como cero.", "dashboard.realized": "REALIZADO", "dashboard.realizedSub": "Lo que ya ocurrió.", "dashboard.confirmedHistory": "Historial confirmado", "dashboard.inProgress": "EN CURSO", "dashboard.inProgressSub": "Lo que está ocurriendo ahora.", "dashboard.liveDeals": "Negocios activos", "dashboard.historicalClients": "Clientes históricos", "dashboard.historicalTicket": "Ticket histórico", "dashboard.states": "Estados atendidos", "dashboard.cities": "Municipios", "dashboard.openPipeline": "Pipeline abierto", "dashboard.activeDeals": "Negocios activos", "dashboard.currentProposals": "Propuestas vigentes", "dashboard.ordersInProgress": "Pedidos en curso", "dashboard.historyChart": "Volumen por línea — período seleccionado vs anterior", "dashboard.pipelineChart": "Pipeline actual por línea de equipo", "dashboard.previousPeriod": "Período anterior", "dashboard.selectedPeriod": "Período seleccionado", "dashboard.allHistory": "Todo el historial disponible", "dashboard.customPeriod": "Período personalizado",
  "pipeline.title": "Pipeline Comercial", "activities.title": "Actividades Comerciales", "proposals.title": "Propuestas Comerciales", "orders.title": "Pedidos", "sales.title": "Ventas",
  "common.clickDetail": "Haga clic para ver detalles"
}

const dictionaries = { "pt-BR": pt, en, es }

function interpolate(template: string, params?: Params) {
  if (!params) return template
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(params[key] ?? `{${key}}`))
}

export function useOperationalI18n() {
  const { locale, formatDate, formatNumber, formatCurrency } = useI18n()
  const tOp = useCallback((key: string, params?: Params) => {
    const dictionary = dictionaries[locale] || pt
    return interpolate(dictionary[key] || pt[key] || key, params)
  }, [locale])
  return { locale, tOp, formatDate, formatNumber, formatCurrency }
}
