"use client"

import { useCallback } from "react"
import { useI18n } from "./I18nContext"

type Params = Record<string, string | number>
type Dict = Record<string, string>

const pt: Dict = {
  "common.start": "Início", "common.end": "Fim", "common.search": "Buscar", "common.currentMonth": "Mês atual", "common.action": "Ação", "common.company": "Empresa", "common.value": "Valor", "common.stage": "Etapa", "common.forecast": "Previsão", "common.open": "Abrir", "common.all": "Todas", "common.openFem": "Abertas", "common.loadingData": "Carregando dados", "common.clickDetail": "Clique para detalhar",
  "op.eyebrow": "Negócio individual", "op.title": "CRM • Oportunidades", "op.subtitle": "Fonte operacional do negócio: cliente, composição de itens, valor, chance, próxima ação e previsão de fechamento.", "op.report": "Gerar relatório", "op.new": "Nova oportunidade", "op.searchPlaceholder": "Empresa, oportunidade, produto ou etapa", "op.periodRecords": "Registros no período", "op.openCount": "Oportunidades abertas", "op.openValue": "Valor aberto", "op.weightedValue": "Valor ponderado", "op.loading": "Carregando oportunidades...", "op.empty": "Nenhuma oportunidade encontrada no período.", "op.composition": "Composição atual: {count} oportunidade(s) · visão {view}.", "op.opportunity": "Oportunidade", "op.products": "Produtos da oportunidade", "op.chance": "Chance", "op.openDeal": "Abrir negócio", "op.undefined": "A definir", "op.noForecast": "Sem previsão", "op.loadFailed": "Não foi possível carregar as oportunidades do período.",
  "dashboard.eyebrow": "Leitura temporal executiva", "dashboard.title": "Dashboard Executivo", "dashboard.subtitle": "Passado consolidado e negócios atuais, separados para leitura imediata.", "dashboard.activeContext": "Contexto ativo", "dashboard.historyPeriod": "Período histórico", "dashboard.lastUpdate": "Última atualização", "dashboard.filteredHistory": "Registros históricos filtrados", "dashboard.connection": "Conexão temporariamente indisponível. Reconexão automática em andamento; nenhum indicador indisponível será mostrado como zero.", "dashboard.realized": "REALIZADO", "dashboard.realizedSub": "O que já aconteceu.", "dashboard.confirmedHistory": "Histórico confirmado", "dashboard.inProgress": "EM CURSO", "dashboard.inProgressSub": "O que está acontecendo agora.", "dashboard.liveDeals": "Negócios vivos", "dashboard.historicalClients": "Clientes históricos", "dashboard.historicalTicket": "Ticket histórico", "dashboard.states": "Estados atendidos", "dashboard.cities": "Municípios", "dashboard.openPipeline": "Pipeline aberto", "dashboard.activeDeals": "Negociações ativas", "dashboard.currentProposals": "Propostas vigentes", "dashboard.ordersInProgress": "Pedidos em curso", "dashboard.historyChart": "Volume por linha — período atual × anterior", "dashboard.pipelineChart": "Pipeline atual por linha de equipamento", "dashboard.previousPeriod": "Período anterior", "dashboard.selectedPeriod": "Período selecionado", "dashboard.allHistory": "Todo o histórico disponível", "dashboard.customPeriod": "Período personalizado",
  "pipeline.title": "Pipeline Comercial", "activities.title": "Atividades Comerciais", "proposals.title": "Propostas Comerciais", "orders.title": "Pedidos", "sales.title": "Vendas",
  "clients.portfolio": "Carteira de clientes", "clients.registered": "{count} clientes cadastrados", "clients.new": "Novo cliente", "clients.searchPlaceholder": "Buscar por nome, razão social, fantasia ou CNPJ", "clients.alphaIndex": "Índice alfabético", "clients.alphaHelp": "Escolha uma letra para listar somente os clientes correspondentes.", "clients.clear": "Limpar", "clients.loading": "Carregando carteira comercial...", "clients.selectOrSearch": "Selecione uma letra ou use a busca", "clients.selectOrSearchHelp": "A carteira completa permanece disponível sem carregar centenas de cartões de uma só vez.", "clients.none": "Nenhum cliente encontrado", "clients.create": "Cadastrar novo cliente", "clients.foundOne": "cliente encontrado", "clients.foundMany": "clientes encontrados", "clients.inLetter": "na letra {letter}", "clients.backAlphabet": "Voltar ao alfabeto", "clients.commercialRecord": "Cadastro comercial", "clients.dealOne": "negociação", "clients.dealMany": "negociações", "clients.openDossier": "abrir dossiê", "clients.loadFailed": "Não foi possível carregar a carteira de clientes.",
  "clients.newTitle": "Novo cliente", "clients.newSubtitle": "Informe o CNPJ para buscar e preencher os dados cadastrais.", "clients.registrationData": "Dados cadastrais", "clients.reviewSource": "A busca por CNPJ não substitui sua revisão antes de salvar.", "clients.legalName": "Nome / razão social", "clients.taxId": "CNPJ", "clients.fetchTaxId": "Buscar dados pelo CNPJ", "clients.stateRegistration": "Inscrição estadual", "clients.category": "Categoria", "clients.addressSection": "Endereço", "clients.address": "Endereço", "clients.number": "Número", "clients.complement": "Complemento", "clients.district": "Bairro", "clients.city": "Cidade", "clients.state": "UF", "clients.postalCode": "CEP", "clients.areaCode": "DDD", "clients.subregion": "Sub-região", "clients.contactSection": "Contato comercial e fiscal", "clients.contact": "Contato", "clients.phone": "Fone", "clients.email": "E-mail", "clients.xmlEmail": "E-mail para envio de XML", "clients.save": "Salvar cliente", "clients.required": "Preencha razão social, CNPJ, cidade, UF e categoria.", "clients.saved": "Cliente cadastrado com sucesso e disponível em toda a jornada comercial.", "clients.saveFailed": "Falha ao cadastrar cliente.", "clients.taxLookupFailed": "Falha ao consultar CNPJ.", "clients.existing": "Cliente já cadastrado no CTI: {name}. Abra a ficha existente em vez de criar duplicidade.", "clients.externalData": "Dados cadastrais encontrados em {source}. Revise e complete os dados comerciais antes de salvar.", "clients.duplicate": "Este CNPJ já pertence a {name}. Cadastro duplicado não foi criado.", "clients.cat.transport": "Transportadora", "clients.cat.producer": "Produtor", "clients.cat.shipper": "Embarcador", "clients.cat.rental": "Locadora", "clients.cat.bodybuilder": "Implementadora", "clients.cat.distributor": "Distribuidora"
}

const en: Dict = {
  "common.start": "Start", "common.end": "End", "common.search": "Search", "common.currentMonth": "Current month", "common.action": "Action", "common.company": "Account", "common.value": "Value", "common.stage": "Stage", "common.forecast": "Expected close", "common.open": "Open", "common.all": "All", "common.openFem": "Open", "common.loadingData": "Loading data", "common.clickDetail": "Click to view details",
  "op.eyebrow": "Individual deal", "op.title": "CRM • Opportunities", "op.subtitle": "Operational source of truth for each deal: account, item mix, value, win probability, next action and expected close date.", "op.report": "Generate report", "op.new": "New opportunity", "op.searchPlaceholder": "Account, opportunity, product or stage", "op.periodRecords": "Records in period", "op.openCount": "Open opportunities", "op.openValue": "Open pipeline value", "op.weightedValue": "Weighted pipeline", "op.loading": "Loading opportunities...", "op.empty": "No opportunities found for this period.", "op.composition": "Current view: {count} opportunity(ies) · {view}.", "op.opportunity": "Opportunity", "op.products": "Opportunity products", "op.chance": "Win probability", "op.openDeal": "Open deal", "op.undefined": "To be defined", "op.noForecast": "No expected close", "op.loadFailed": "We couldn't load opportunities for this period.",
  "dashboard.eyebrow": "Executive time view", "dashboard.title": "Executive Dashboard", "dashboard.subtitle": "Confirmed history and current business, separated for immediate reading.", "dashboard.activeContext": "Active context", "dashboard.historyPeriod": "Historical period", "dashboard.lastUpdate": "Last updated", "dashboard.filteredHistory": "Filtered historical records", "dashboard.connection": "Connection temporarily unavailable. Automatic reconnection is in progress; unavailable indicators will never be shown as zero.", "dashboard.realized": "COMPLETED", "dashboard.realizedSub": "What has already happened.", "dashboard.confirmedHistory": "Confirmed history", "dashboard.inProgress": "IN PROGRESS", "dashboard.inProgressSub": "What is happening now.", "dashboard.liveDeals": "Live deals", "dashboard.historicalClients": "Historical accounts", "dashboard.historicalTicket": "Historical average ticket", "dashboard.states": "States served", "dashboard.cities": "Municipalities", "dashboard.openPipeline": "Open pipeline", "dashboard.activeDeals": "Active deals", "dashboard.currentProposals": "Active proposals", "dashboard.ordersInProgress": "Orders in progress", "dashboard.historyChart": "Volume by product line — selected vs previous period", "dashboard.pipelineChart": "Current pipeline by equipment line", "dashboard.previousPeriod": "Previous period", "dashboard.selectedPeriod": "Selected period", "dashboard.allHistory": "All available history", "dashboard.customPeriod": "Custom period",
  "pipeline.title": "Sales Pipeline", "activities.title": "Sales Activities", "proposals.title": "Sales Proposals", "orders.title": "Orders", "sales.title": "Sales",
  "clients.portfolio": "Account portfolio", "clients.registered": "{count} accounts registered", "clients.new": "New account", "clients.searchPlaceholder": "Search by name, legal name, trading name or tax ID", "clients.alphaIndex": "Alphabetical index", "clients.alphaHelp": "Choose a letter to list only matching accounts.", "clients.clear": "Clear", "clients.loading": "Loading account portfolio...", "clients.selectOrSearch": "Choose a letter or use search", "clients.selectOrSearchHelp": "The full portfolio remains available without loading hundreds of cards at once.", "clients.none": "No account found", "clients.create": "Create account", "clients.foundOne": "account found", "clients.foundMany": "accounts found", "clients.inLetter": "under letter {letter}", "clients.backAlphabet": "Back to alphabet", "clients.commercialRecord": "Commercial account", "clients.dealOne": "deal", "clients.dealMany": "deals", "clients.openDossier": "open account file", "clients.loadFailed": "We couldn't load the account portfolio.",
  "clients.newTitle": "New account", "clients.newSubtitle": "Enter the tax ID to retrieve company registration data.", "clients.registrationData": "Company registration", "clients.reviewSource": "Retrieved registration data must still be reviewed before saving.", "clients.legalName": "Account / legal name", "clients.taxId": "Tax ID (CNPJ)", "clients.fetchTaxId": "Retrieve company data", "clients.stateRegistration": "State tax registration", "clients.category": "Account type", "clients.addressSection": "Address", "clients.address": "Street address", "clients.number": "Number", "clients.complement": "Additional address", "clients.district": "District", "clients.city": "City", "clients.state": "State", "clients.postalCode": "Postal code", "clients.areaCode": "Area code", "clients.subregion": "Sub-region", "clients.contactSection": "Commercial and billing contact", "clients.contact": "Contact", "clients.phone": "Phone", "clients.email": "Email", "clients.xmlEmail": "Invoice XML email", "clients.save": "Save account", "clients.required": "Complete legal name, tax ID, city, state and account type.", "clients.saved": "Account created successfully and available throughout the sales workflow.", "clients.saveFailed": "We couldn't create the account.", "clients.taxLookupFailed": "We couldn't retrieve the tax ID data.", "clients.existing": "This account already exists in CTI: {name}. Open the existing account instead of creating a duplicate.", "clients.externalData": "Registration data found via {source}. Review and complete the commercial information before saving.", "clients.duplicate": "This tax ID already belongs to {name}. No duplicate account was created.", "clients.cat.transport": "Carrier / Fleet operator", "clients.cat.producer": "Producer", "clients.cat.shipper": "Shipper", "clients.cat.rental": "Rental company", "clients.cat.bodybuilder": "Body builder", "clients.cat.distributor": "Distributor"
}

const es: Dict = {
  "common.start": "Inicio", "common.end": "Fin", "common.search": "Buscar", "common.currentMonth": "Mes actual", "common.action": "Acción", "common.company": "Cliente", "common.value": "Valor", "common.stage": "Etapa", "common.forecast": "Cierre previsto", "common.open": "Abrir", "common.all": "Todas", "common.openFem": "Abiertas", "common.loadingData": "Cargando datos", "common.clickDetail": "Haga clic para ver detalles",
  "op.eyebrow": "Negocio individual", "op.title": "CRM • Oportunidades", "op.subtitle": "Fuente operativa de cada negocio: cliente, composición de productos, valor, probabilidad de cierre, próxima acción y fecha prevista de cierre.", "op.report": "Generar informe", "op.new": "Nueva oportunidad", "op.searchPlaceholder": "Cliente, oportunidad, producto o etapa", "op.periodRecords": "Registros del período", "op.openCount": "Oportunidades abiertas", "op.openValue": "Valor abierto", "op.weightedValue": "Valor ponderado", "op.loading": "Cargando oportunidades...", "op.empty": "No se encontraron oportunidades en el período.", "op.composition": "Vista actual: {count} oportunidad(es) · {view}.", "op.opportunity": "Oportunidad", "op.products": "Productos de la oportunidad", "op.chance": "Probabilidad", "op.openDeal": "Abrir negocio", "op.undefined": "Por definir", "op.noForecast": "Sin previsión", "op.loadFailed": "No fue posible cargar las oportunidades del período.",
  "dashboard.eyebrow": "Lectura temporal ejecutiva", "dashboard.title": "Panel Ejecutivo", "dashboard.subtitle": "Historial confirmado y negocios actuales, separados para una lectura inmediata.", "dashboard.activeContext": "Contexto activo", "dashboard.historyPeriod": "Período histórico", "dashboard.lastUpdate": "Última actualización", "dashboard.filteredHistory": "Registros históricos filtrados", "dashboard.connection": "Conexión temporalmente no disponible. La reconexión automática está en curso; ningún indicador no disponible se mostrará como cero.", "dashboard.realized": "REALIZADO", "dashboard.realizedSub": "Lo que ya ocurrió.", "dashboard.confirmedHistory": "Historial confirmado", "dashboard.inProgress": "EN CURSO", "dashboard.inProgressSub": "Lo que está ocurriendo ahora.", "dashboard.liveDeals": "Negocios activos", "dashboard.historicalClients": "Clientes históricos", "dashboard.historicalTicket": "Ticket histórico", "dashboard.states": "Estados atendidos", "dashboard.cities": "Municipios", "dashboard.openPipeline": "Pipeline abierto", "dashboard.activeDeals": "Negocios activos", "dashboard.currentProposals": "Propuestas vigentes", "dashboard.ordersInProgress": "Pedidos en curso", "dashboard.historyChart": "Volumen por línea — período seleccionado vs anterior", "dashboard.pipelineChart": "Pipeline actual por línea de equipo", "dashboard.previousPeriod": "Período anterior", "dashboard.selectedPeriod": "Período seleccionado", "dashboard.allHistory": "Todo el historial disponible", "dashboard.customPeriod": "Período personalizado",
  "pipeline.title": "Pipeline Comercial", "activities.title": "Actividades Comerciales", "proposals.title": "Propuestas Comerciales", "orders.title": "Pedidos", "sales.title": "Ventas",
  "clients.portfolio": "Cartera de clientes", "clients.registered": "{count} clientes registrados", "clients.new": "Nuevo cliente", "clients.searchPlaceholder": "Buscar por nombre, razón social, nombre comercial o CNPJ", "clients.alphaIndex": "Índice alfabético", "clients.alphaHelp": "Seleccione una letra para mostrar únicamente los clientes correspondientes.", "clients.clear": "Limpiar", "clients.loading": "Cargando cartera comercial...", "clients.selectOrSearch": "Seleccione una letra o utilice la búsqueda", "clients.selectOrSearchHelp": "La cartera completa sigue disponible sin cargar cientos de tarjetas a la vez.", "clients.none": "No se encontró ningún cliente", "clients.create": "Registrar nuevo cliente", "clients.foundOne": "cliente encontrado", "clients.foundMany": "clientes encontrados", "clients.inLetter": "en la letra {letter}", "clients.backAlphabet": "Volver al alfabeto", "clients.commercialRecord": "Registro comercial", "clients.dealOne": "negocio", "clients.dealMany": "negocios", "clients.openDossier": "abrir expediente", "clients.loadFailed": "No fue posible cargar la cartera de clientes.",
  "clients.newTitle": "Nuevo cliente", "clients.newSubtitle": "Ingrese el CNPJ para recuperar y completar los datos registrales.", "clients.registrationData": "Datos registrales", "clients.reviewSource": "Los datos recuperados por CNPJ deben revisarse antes de guardar.", "clients.legalName": "Nombre / razón social", "clients.taxId": "CNPJ", "clients.fetchTaxId": "Buscar datos por CNPJ", "clients.stateRegistration": "Inscripción estatal", "clients.category": "Categoría", "clients.addressSection": "Dirección", "clients.address": "Dirección", "clients.number": "Número", "clients.complement": "Complemento", "clients.district": "Barrio", "clients.city": "Ciudad", "clients.state": "Estado", "clients.postalCode": "Código postal", "clients.areaCode": "Código de área", "clients.subregion": "Subregión", "clients.contactSection": "Contacto comercial y fiscal", "clients.contact": "Contacto", "clients.phone": "Teléfono", "clients.email": "Correo electrónico", "clients.xmlEmail": "Correo para envío de XML", "clients.save": "Guardar cliente", "clients.required": "Complete razón social, CNPJ, ciudad, estado y categoría.", "clients.saved": "Cliente registrado con éxito y disponible en todo el proceso comercial.", "clients.saveFailed": "No fue posible registrar el cliente.", "clients.taxLookupFailed": "No fue posible consultar el CNPJ.", "clients.existing": "El cliente ya está registrado en CTI: {name}. Abra la ficha existente en lugar de crear un duplicado.", "clients.externalData": "Datos registrales encontrados en {source}. Revise y complete la información comercial antes de guardar.", "clients.duplicate": "Este CNPJ ya pertenece a {name}. No se creó un registro duplicado.", "clients.cat.transport": "Transportista", "clients.cat.producer": "Productor", "clients.cat.shipper": "Cargador", "clients.cat.rental": "Empresa de alquiler", "clients.cat.bodybuilder": "Carrocero", "clients.cat.distributor": "Distribuidor"
}

const dictionaries = { "pt-BR": pt, en, es }

function interpolate(template: string, params?: Params) {
  if (!params) return template
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(params[key] ?? `{${key}}`))
}

export function useOperationalI18n() {
  const { locale, formatDate, formatNumber, formatCurrency } = useI18n()
  const tOp = useCallback((key: string, params?: Params) => {
    const dictionary = dictionaries[locale] || pt
    return interpolate(dictionary[key] || pt[key] || key, params)
  }, [locale])
  return { locale, tOp, formatDate, formatNumber, formatCurrency }
}
