"use client"

import Link from "next/link"
import { FormEvent, useEffect, useMemo, useState } from "react"
import { ArrowLeft, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Loader2, Pencil, Plus, Save, UserRound, Building2 } from "lucide-react"
import { useAuth } from "@/core/auth/AuthContext"
import { useOperationalI18n } from "@/core/i18n/operational"
import { pertenceAoEscopoDoUsuario } from "@/core/rbac/commercial-scope"
import { fetchCrmSeguroProxy } from "@/services/crm-secure"

type Registro=Record<string,unknown>
type Item={id:string;usuarioId:string;titulo:string;tipo:string;status:string;data:string;hora:string;cliente:string;parceiroNome:string;parceiroOrganizacao:string;parceiroTipo:string;oportunidade:string;descricao:string}
type Locale="pt-BR"|"en"|"es"
const textos={
 "pt-BR":{title:"Agenda comercial",subtitle:"Compromissos pendentes, atrasos e próximas ações",new:"Novo compromisso",pending:"compromisso(s) pendente(s)",emptyDay:"Nenhum compromisso pendente neste dia.",selectDay:"Selecione um dia para consultar ou editar.",withWhom:"Com quem",type:"Tipo",deal:"Negociação",edit:"Editar compromisso",complete:"Concluir e enviar ao histórico",editTitle:"Editar compromisso",withWhomFuture:"Com quem será o compromisso",fieldTitle:"Título",date:"Data",time:"Horário",status:"Status",description:"Descrição",cancel:"Cancelar edição",save:"Salvar compromisso",saving:"Salvando",registered:"Cliente cadastrado",external:"Contato externo",unidentified:"Contato não identificado",review:"Revisar cadastro do compromisso",activity:"Atividade comercial",load:"Não foi possível carregar a agenda.",updated:"Compromisso atualizado.",updateFail:"Não foi possível atualizar o compromisso.",completeFail:"Não foi possível concluir o compromisso.",completed:"Compromisso concluído e enviado ao histórico comercial."},
 en:{title:"Sales calendar",subtitle:"Pending commitments, overdue items and next actions",new:"New commitment",pending:"pending commitment(s)",emptyDay:"No pending commitments on this day.",selectDay:"Select a day to review or edit commitments.",withWhom:"With whom",type:"Type",deal:"Deal",edit:"Edit commitment",complete:"Complete and send to history",editTitle:"Edit commitment",withWhomFuture:"Who the commitment is with",fieldTitle:"Title",date:"Date",time:"Time",status:"Status",description:"Description",cancel:"Cancel editing",save:"Save commitment",saving:"Saving",registered:"Registered account",external:"External contact",unidentified:"Unidentified contact",review:"Review commitment record",activity:"Sales activity",load:"We couldn't load the calendar.",updated:"Commitment updated.",updateFail:"We couldn't update the commitment.",completeFail:"We couldn't complete the commitment.",completed:"Commitment completed and sent to sales history."},
 es:{title:"Agenda comercial",subtitle:"Compromisos pendientes, atrasos y próximas acciones",new:"Nuevo compromiso",pending:"compromiso(s) pendiente(s)",emptyDay:"No hay compromisos pendientes en este día.",selectDay:"Seleccione un día para consultar o editar.",withWhom:"Con quién",type:"Tipo",deal:"Negocio",edit:"Editar compromiso",complete:"Completar y enviar al historial",editTitle:"Editar compromiso",withWhomFuture:"Con quién será el compromiso",fieldTitle:"Título",date:"Fecha",time:"Hora",status:"Estado",description:"Descripción",cancel:"Cancelar edición",save:"Guardar compromiso",saving:"Guardando",registered:"Cliente registrado",external:"Contacto externo",unidentified:"Contacto no identificado",review:"Revisar registro del compromiso",activity:"Actividad comercial",load:"No fue posible cargar la agenda.",updated:"Compromiso actualizado.",updateFail:"No fue posible actualizar el compromiso.",completeFail:"No fue posible completar el compromiso.",completed:"Compromiso completado y enviado al historial comercial."}
} satisfies Record<Locale,Record<string,string>>
const dias:Record<Locale,string[]>={"pt-BR":["D","S","T","Q","Q","S","S"],en:["S","M","T","W","T","F","S"],es:["D","L","M","X","J","V","S"]}
function lista(p:unknown):Registro[]{if(Array.isArray(p))return p as Registro[];if(p&&typeof p==="object"){const o=p as Registro;for(const k of["itens","dados","resultado","atividades"])if(Array.isArray(o[k]))return o[k] as Registro[]}return[]}
function texto(v:unknown){return String(v||"").trim()}
function chaveMes(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function statusLegivel(v:string,l:Locale){const m:Record<Locale,Record<string,string>>={"pt-BR":{PENDENTE:"Pendente",CONCLUIDA:"Concluída",CANCELADA:"Cancelada"},en:{PENDENTE:"Pending",CONCLUIDA:"Completed",CANCELADA:"Cancelled"},es:{PENDENTE:"Pendiente",CONCLUIDA:"Completada",CANCELADA:"Cancelada"}};return m[l][v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase()]||v}
function tipoLegivel(v:string,l:Locale){const m:Record<Locale,Record<string,string>>={"pt-BR":{VISITA_PRESENCIAL:"Visita presencial",VISITA_REMOTA:"Visita remota",LIGACAO:"Ligação",REUNIAO:"Reunião",APRESENTACAO:"Apresentação",PROSPECCAO:"Prospecção",POS_VENDA:"Pós-venda",FOLLOW_UP:"Follow-up",EMAIL:"E-mail",WHATSAPP:"WhatsApp",ATIVIDADE:"Atividade"},en:{VISITA_PRESENCIAL:"On-site visit",VISITA_REMOTA:"Remote visit",LIGACAO:"Phone call",REUNIAO:"Meeting",APRESENTACAO:"Presentation",PROSPECCAO:"Prospecting",POS_VENDA:"After-sales",FOLLOW_UP:"Follow-up",EMAIL:"Email",WHATSAPP:"WhatsApp",ATIVIDADE:"Activity"},es:{VISITA_PRESENCIAL:"Visita presencial",VISITA_REMOTA:"Visita remota",LIGACAO:"Llamada",REUNIAO:"Reunión",APRESENTACAO:"Presentación",PROSPECCAO:"Prospección",POS_VENDA:"Posventa",FOLLOW_UP:"Seguimiento",EMAIL:"Correo electrónico",WHATSAPP:"WhatsApp",ATIVIDADE:"Actividad"}};return m[l][v]||v.replaceAll("_"," ")}
export default function Agenda(){
 const {usuario}=useAuth();const {locale,formatDate}=useOperationalI18n();const idioma=locale as Locale;const t=textos[idioma]||textos["pt-BR"]
 const[mes,setMes]=useState(()=>new Date()),[itens,setItens]=useState<Item[]>([]),[selecionado,setSelecionado]=useState<Item|null>(null),[dia,setDia]=useState(""),[carregando,setCarregando]=useState(true),[salvando,setSalvando]=useState(false),[erro,setErro]=useState(""),[sucesso,setSucesso]=useState("")
 function contexto(i:Item){if(i.cliente)return{pessoa:i.cliente,organizacao:t.registered};if(i.parceiroNome)return{pessoa:i.parceiroNome,organizacao:i.parceiroOrganizacao||tipoLegivel(i.parceiroTipo,idioma)||t.external};return{pessoa:t.unidentified,organizacao:t.review}}
 async function carregar(){setCarregando(true);setErro("");try{const r=await fetchCrmSeguroProxy("crm-seguro/agenda",{cache:"no-store"}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String((p as Registro).detail||`HTTP ${r.status}`));setItens(lista(p).map(i=>({id:texto(i.id||i.atividade_id),usuarioId:texto(i.usuario_id||i.responsavel_id),titulo:texto(i.titulo||i.assunto||i.descricao)||t.activity,tipo:texto(i.tipo||i.tipo_atividade).toUpperCase()||"ATIVIDADE",status:texto(i.status).toUpperCase()||"PENDENTE",data:texto(i.data||i.data_atividade||i.inicio).slice(0,10),hora:texto(i.hora||i.horario||i.inicio).slice(11,16),cliente:texto(i.cliente_nome||i.cliente),parceiroNome:texto(i.parceiro_nome),parceiroOrganizacao:texto(i.parceiro_organizacao),parceiroTipo:texto(i.parceiro_tipo),oportunidade:texto(i.oportunidade_titulo),descricao:texto(i.descricao)})).filter(i=>i.data&&!["CONCLUIDA","CONCLUÍDA","CANCELADA"].includes(i.status)))}catch(e){setErro(e instanceof Error?e.message:t.load)}finally{setCarregando(false)}}
 useEffect(()=>{void carregar()},[t.activity,t.load])
 const escopados=useMemo(()=>itens.filter(i=>pertenceAoEscopoDoUsuario(i.usuarioId,usuario)),[itens,usuario]),doMes=useMemo(()=>escopados.filter(i=>i.data.startsWith(chaveMes(mes))).sort((a,b)=>`${a.data}${a.hora}`.localeCompare(`${b.data}${b.hora}`)),[escopados,mes]),titulo=mes.toLocaleDateString(locale,{month:"long",year:"numeric"}),primeiro=new Date(mes.getFullYear(),mes.getMonth(),1),totalDias=new Date(mes.getFullYear(),mes.getMonth()+1,0).getDate(),inicio=primeiro.getDay(),celulas=Array.from({length:inicio+totalDias},(_,i)=>i<inicio?null:i-inicio+1),filtrados=dia?doMes.filter(i=>i.data===dia):doMes
 function mover(n:number){setMes(a=>new Date(a.getFullYear(),a.getMonth()+n,1));setDia("");setSelecionado(null)}
 async function salvar(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selecionado||!pertenceAoEscopoDoUsuario(selecionado.usuarioId,usuario))return;setSalvando(true);setErro("");setSucesso("");const f=new FormData(e.currentTarget),payload={titulo:texto(f.get("titulo")),tipo:texto(f.get("tipo")),data:texto(f.get("data")),horario:texto(f.get("horario")),descricao:texto(f.get("descricao"))||null,status:texto(f.get("status"))};try{const r=await fetchCrmSeguroProxy(`crm-seguro/atividades/${encodeURIComponent(selecionado.id)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String((p as Registro).detail||`HTTP ${r.status}`));setSucesso(t.updated);setSelecionado(null);await carregar()}catch(x){setErro(x instanceof Error?x.message:t.updateFail)}finally{setSalvando(false)}}
 async function concluir(id:string){const i=escopados.find(x=>x.id===id);if(!i)return;const r=await fetchCrmSeguroProxy(`crm-seguro/atividades/${encodeURIComponent(id)}/concluir`,{method:"PUT"});if(!r.ok)setErro(t.completeFail);else{setSucesso(t.completed);await carregar()}}
 return <main className="min-h-[100dvh] bg-[#020817] px-4 py-5 pb-24 text-white sm:px-6"><div className="mx-auto max-w-5xl"><header className="mb-5 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Link href="/crm-app" className="grid size-11 place-items-center rounded-2xl border border-[#16325c] bg-[#091a33] text-cyan-300"><ArrowLeft size={20}/></Link><div><p className="text-xs uppercase tracking-[.24em] text-cyan-400">CTI CRM</p><h1 className="text-2xl font-bold">{t.title}</h1><p className="text-sm text-slate-400">{t.subtitle}</p></div></div><Link href="/crm-app/atividades/nova" className="flex items-center gap-2 rounded-2xl bg-cyan-500 px-4 py-3 font-bold text-slate-950"><Plus size={18}/>{t.new}</Link></header>
 {erro&&<div className="mb-4 rounded-2xl border border-red-900 bg-red-950/40 p-4 text-red-200">{erro}</div>}{sucesso&&<div className="mb-4 rounded-2xl border border-emerald-900 bg-emerald-950/40 p-4 text-emerald-200">{sucesso}</div>}
 <section className="mb-4 rounded-3xl border border-[#16325c] bg-[#07162b] p-4"><div className="mb-4 flex items-center justify-between"><button onClick={()=>mover(-1)} className="rounded-xl border border-[#24466f] p-2 text-cyan-300"><ChevronLeft/></button><div className="text-center"><CalendarDays className="mx-auto text-cyan-300"/><h2 className="mt-1 font-bold capitalize">{titulo}</h2><p className="text-xs text-slate-400">{doMes.length} {t.pending}</p></div><button onClick={()=>mover(1)} className="rounded-xl border border-[#24466f] p-2 text-cyan-300"><ChevronRight/></button></div><div className="grid grid-cols-7 gap-1 text-center text-xs text-slate-400">{dias[idioma].map((d,i)=><div key={`${d}-${i}`} className="py-2 font-semibold">{d}</div>)}{celulas.map((n,i)=>n===null?<div key={`v-${i}`}/>:<button key={n} onClick={()=>setDia(`${chaveMes(mes)}-${String(n).padStart(2,"0")}`)} className={`min-h-14 rounded-xl border p-2 ${dia===`${chaveMes(mes)}-${String(n).padStart(2,"0")}`?"border-cyan-400 bg-cyan-950/50":"border-[#16325c] bg-[#091a33]"}`}><span className="block font-semibold text-white">{n}</span>{doMes.some(x=>Number(x.data.slice(8,10))===n)&&<span className="mx-auto mt-1 block size-2 rounded-full bg-cyan-400"/>}</button>)}</div></section>
 {carregando?<div className="grid min-h-40 place-items-center"><Loader2 className="animate-spin text-cyan-300"/></div>:filtrados.length===0?<div className="rounded-3xl border border-dashed border-[#24466f] p-8 text-center text-slate-400">{dia?t.emptyDay:t.selectDay}</div>:<div className="space-y-3">{filtrados.map(i=>{const c=contexto(i);return <article key={i.id} className="rounded-3xl border border-[#16325c] bg-[#07162b] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs text-cyan-300">{formatDate(i.data)}</p><h3 className="mt-1 font-bold">{i.titulo}</h3><div className="mt-3 rounded-2xl border border-cyan-900/70 bg-cyan-950/20 p-3"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-cyan-400">{t.withWhom}</p><p className="mt-1 flex items-center gap-2 font-semibold text-white"><UserRound size={16} className="text-cyan-300"/>{c.pessoa}</p><p className="mt-1 flex items-center gap-2 text-sm text-slate-400"><Building2 size={15}/>{c.organizacao}</p></div><p className="mt-3 text-xs text-slate-400"><span className="font-semibold text-slate-300">{t.type}:</span> {tipoLegivel(i.tipo,idioma)}</p>{i.oportunidade&&<p className="mt-1 text-xs text-slate-400"><span className="font-semibold text-slate-300">{t.deal}:</span> {i.oportunidade}</p>}{i.hora&&<p className="mt-2 inline-flex items-center gap-1 text-xs text-slate-400"><Clock3 size={14}/>{i.hora}</p>}</div><span className="rounded-full border border-[#24466f] px-3 py-1 text-xs">{statusLegivel(i.status,idioma)}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><button onClick={()=>setSelecionado(i)} className="flex items-center justify-center gap-2 rounded-xl border border-cyan-800 px-3 py-3 text-sm font-semibold text-cyan-200"><Pencil size={16}/>{t.edit}</button><button onClick={()=>void concluir(i.id)} className="flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-3 py-3 text-sm font-bold"><CheckCircle2 size={16}/>{t.complete}</button></div></article>})}</div>}
 {selecionado&&<form onSubmit={salvar} className="mt-4 grid gap-4 rounded-3xl border border-cyan-800 bg-[#07162b] p-5 sm:grid-cols-2"><h2 className="text-xl font-bold sm:col-span-2">{t.editTitle}</h2><div className="sm:col-span-2 rounded-2xl border border-[#24466f] bg-[#020817]/60 p-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-cyan-400">{t.withWhomFuture}</p><p className="mt-2 font-semibold text-white">{contexto(selecionado).pessoa}</p><p className="text-sm text-slate-400">{contexto(selecionado).organizacao}</p></div><Campo name="titulo" label={t.fieldTitle} valor={selecionado.titulo}/><Campo name="tipo" label={t.type} valor={selecionado.tipo}/><Campo name="data" label={t.date} type="date" valor={selecionado.data}/><Campo name="horario" label={t.time} type="time" valor={selecionado.hora}/><label><span className="mb-2 block text-sm text-slate-300">{t.status}</span><select name="status" defaultValue={selecionado.status.normalize("NFD").replace(/[\u0300-\u036f]/g,"")} className="h-12 w-full rounded-2xl border border-[#24466f] bg-[#020817] px-4"><option value="PENDENTE">{statusLegivel("PENDENTE",idioma)}</option><option value="CONCLUIDA">{statusLegivel("CONCLUIDA",idioma)}</option><option value="CANCELADA">{statusLegivel("CANCELADA",idioma)}</option></select></label><label className="sm:col-span-2"><span className="mb-2 block text-sm text-slate-300">{t.description}</span><textarea name="descricao" defaultValue={selecionado.descricao} rows={4} className="w-full rounded-2xl border border-[#24466f] bg-[#020817] px-4 py-3"/></label><div className="grid gap-2 sm:col-span-2 sm:grid-cols-2"><button type="button" onClick={()=>setSelecionado(null)} className="rounded-2xl border border-[#24466f] py-3">{t.cancel}</button><button disabled={salvando} className="flex items-center justify-center gap-2 rounded-2xl bg-cyan-500 py-3 font-bold text-slate-950">{salvando?<Loader2 className="animate-spin"/>:<Save size={18}/>} {salvando?t.saving:t.save}</button></div></form>}
 </div></main>
}
function Campo({name,label,valor,type="text"}:{name:string;label:string;valor:string;type?:string}){return <label><span className="mb-2 block text-sm text-slate-300">{label}</span><input name={name} type={type} defaultValue={valor} className="h-12 w-full rounded-2xl border border-[#24466f] bg-[#020817] px-4"/></label>}
