"use client"

import { useEffect, useMemo, useState } from "react"
import { ArrowLeft, FileText, Printer } from "lucide-react"
import Link from "next/link"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import { useI18n } from "@/core/i18n"

type Segmento = { segmento:string; mercado:number; carrier:number; carrier_percentual_observado:number; tk:number; nacional:number; sem_contato:number; nao_participou:number; q2_vs_q1_percentual:number|null }
type Mensal = { mes:string; trailer:number; diesel_truck:number; direct_drive:number; total:number }
type Territorio = { ddd:string; mercado:number; trailer:number; diesel_truck:number; direct_drive:number; responsavel:string }
type Prioridade = { prioridade:string; cliente:string; score_transparente:number; mercado:number; nao_carrier:number; carrier:number; nao_participou:number; sem_contato:number; tk:number; nacional:number; preco:number; relacionamento:number; gap_tecnico:number; leitura_sugerida:string }
type Implementadora = { implementadora:string; mercado_elegivel:number; trailer:number; diesel_truck:number; direct_drive:number; leitura:string }
type Tema = { tema:string; ocorrencias:number; clientes_unicos:number; observacoes_unicas:number; leitura_comercial:string; uso_no_cti:string }
type Payload = {
 metadata:{competencia:string}
 inteligencia_viena:{mercado_elegivel:number;carrier_observada:number;carrier_presenca_percentual:number;sem_contato:number;nao_participamos_proposta:number;dados_status_a_qualificar:number;q1:number;q2:number;q2_vs_q1_percentual:number|null;segmentos:Segmento[];mensal:Mensal[];territorio:Territorio[];leituras_estrategicas:string[]}
 oportunidades_prioritarias:Prioridade[]
 implementadoras_mercado:Implementadora[]
 inteligencia_observacoes:{temas:Tema[];registros_elegiveis:number;com_observacao_util:number;cobertura_observacoes_percentual:number;sem_observacao_util:number;regra:string}
}
type Camada = "viena"|"prioridades"|"implementadoras"|"observacoes"

const textos = {
 "pt-BR": { title:"Relatório ANFIR 2026 · Viena", back:"Voltar ao Dashboard", print:"Imprimir / Salvar PDF", layers:"Camadas do relatório", all:"Todas", viena:"Inteligência Viena", priorities:"Oportunidades Prioritárias", builders:"Implementadoras Mercado", notes:"Inteligência Observações", loading:"Carregando relatório ANFIR 2026...", error:"Não foi possível carregar o relatório ANFIR 2026.", generated:"Relatório gerado a partir do contrato auditado Carrier/JOV. A competência permanece fixa em 2026.", market:"Mercado elegível", carrier:"Presença Carrier observada", noContact:"Sem contato", noParticipation:"Não participamos da proposta", qualify:"Status a qualificar", trend:"Q2 vs Q1", segment:"Segmento", month:"Mês", territory:"Território por DDD", owner:"Responsável", readings:"Leituras estratégicas", priority:"Prioridade", account:"Cliente", score:"Score", nonCarrier:"Não Carrier", price:"Preço", relationship:"Relacionamento", technical:"Gap técnico", reading:"Leitura sugerida", builder:"Implementadora", observations:"Ocorrências", clients:"Clientes únicos", uniqueNotes:"Observações únicas", commercialReading:"Leitura comercial", use:"Uso no CTI", useful:"Com observação útil", coverage:"Cobertura de observações", without:"Sem observação útil", rule:"Regra", empty:"Selecione ao menos uma camada para gerar o documento." },
 en: { title:"ANFIR 2026 Report · Viena", back:"Back to Dashboard", print:"Print / Save PDF", layers:"Report layers", all:"All", viena:"Viena Intelligence", priorities:"Priority Accounts", builders:"Body Builder Market", notes:"Notes Intelligence", loading:"Loading ANFIR 2026 report...", error:"ANFIR 2026 report could not be loaded.", generated:"Report generated from the audited Carrier/JOV contract. The reporting period remains fixed to 2026.", market:"Eligible market", carrier:"Observed Carrier presence", noContact:"No contact", noParticipation:"No participation", qualify:"Status to qualify", trend:"Q2 vs Q1", segment:"Segment", month:"Month", territory:"Territory by area code", owner:"Owner", readings:"Strategic readings", priority:"Priority", account:"Account", score:"Score", nonCarrier:"Non Carrier", price:"Price", relationship:"Relationship", technical:"Technical gap", reading:"Suggested reading", builder:"Body builder", observations:"Occurrences", clients:"Unique accounts", uniqueNotes:"Unique notes", commercialReading:"Commercial reading", use:"Use in CTI", useful:"With useful note", coverage:"Notes coverage", without:"Without useful note", rule:"Rule", empty:"Select at least one layer to generate the document." },
 es: { title:"Informe ANFIR 2026 · Viena", back:"Volver al Dashboard", print:"Imprimir / Guardar PDF", layers:"Capas del informe", all:"Todas", viena:"Inteligencia Viena", priorities:"Cuentas Prioritarias", builders:"Mercado de Carroceros", notes:"Inteligencia de Observaciones", loading:"Cargando informe ANFIR 2026...", error:"No fue posible cargar el informe ANFIR 2026.", generated:"Informe generado desde el contrato auditado Carrier/JOV. La competencia permanece fija en 2026.", market:"Mercado elegible", carrier:"Presencia Carrier observada", noContact:"Sin contacto", noParticipation:"Sin participación", qualify:"Status a calificar", trend:"Q2 vs Q1", segment:"Segmento", month:"Mes", territory:"Territorio por DDD", owner:"Responsable", readings:"Lecturas estratégicas", priority:"Prioridad", account:"Cliente", score:"Score", nonCarrier:"No Carrier", price:"Precio", relationship:"Relación", technical:"Gap técnico", reading:"Lectura sugerida", builder:"Carrocero", observations:"Ocurrencias", clients:"Clientes únicos", uniqueNotes:"Observaciones únicas", commercialReading:"Lectura comercial", use:"Uso en CTI", useful:"Con observación útil", coverage:"Cobertura de observaciones", without:"Sin observación útil", rule:"Regla", empty:"Seleccione al menos una capa para generar el documento." }
} as const

export default function AnfirRelatorioPage(){
 const { locale, formatNumber } = useI18n(); const tx = textos[locale]
 const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false)
 const [camadas,setCamadas]=useState<Camada[]>(["viena","prioridades","implementadoras","observacoes"])
 useEffect(()=>{let active=true;fetch("/api/cti/analytics/anfir-workbook-2026",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error(String(r.status));return r.json() as Promise<Payload>}).then(p=>{if(active)setData(p)}).catch(()=>{if(active)setError(true)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 const selecionadas=useMemo(()=>new Set(camadas),[camadas])
 function toggle(c:Camada){setCamadas(atual=>atual.includes(c)?atual.filter(x=>x!==c):[...atual,c])}
 const opts:[Camada,string][]=[["viena",tx.viena],["prioridades",tx.priorities],["implementadoras",tx.builders],["observacoes",tx.notes]]
 if(loading)return <div className="min-h-screen bg-[#020817] p-8 text-slate-300">{tx.loading}</div>
 if(error||!data)return <div className="min-h-screen bg-[#020817] p-8 text-amber-200">{tx.error}</div>
 const v=data.inteligencia_viena,o=data.inteligencia_observacoes
 return <main className="flex min-h-screen bg-[#020817] text-white print:block print:bg-white print:text-black">
  <div className="print:hidden"><Sidebar/></div>
  <section className="min-w-0 flex-1">
   <div className="print:hidden"><Topbar/></div>
   <div className="space-y-5 p-4 sm:p-6 lg:p-8 print:p-0">
    <header className="rounded-3xl border border-[#17304d] bg-[#071226] p-6 print:rounded-none print:border-0 print:bg-white print:p-0">
     <Link href="/dashboard" className="mb-4 inline-flex items-center gap-2 rounded-xl border border-[#17304d] px-4 py-2 text-sm text-cyan-200 print:hidden"><ArrowLeft size={16}/>{tx.back}</Link>
     <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-400 print:text-black">{data.metadata.competencia} · Carrier/JOV</p><h1 className="mt-2 text-3xl font-bold">{tx.title}</h1><p className="mt-2 max-w-4xl text-sm text-slate-400 print:text-gray-700">{tx.generated}</p></div><button onClick={()=>window.print()} disabled={camadas.length===0} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-5 py-3 font-semibold text-slate-950 disabled:opacity-40 print:hidden"><Printer size={17}/>{tx.print}</button></div>
    </header>
    <section className="rounded-2xl border border-[#17304d] bg-[#071226] p-5 print:hidden"><p className="mb-3 text-sm font-semibold text-slate-200">{tx.layers}</p><div className="flex flex-wrap gap-2"><button onClick={()=>setCamadas(camadas.length===4?[]:["viena","prioridades","implementadoras","observacoes"])} className="rounded-xl border border-[#29456f] px-4 py-2 text-sm">{tx.all}</button>{opts.map(([c,label])=><button key={c} onClick={()=>toggle(c)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${selecionadas.has(c)?"bg-cyan-400 text-slate-950":"border border-[#29456f] bg-[#09182e] text-slate-300"}`}>{label}</button>)}</div></section>
    {camadas.length===0&&<div className="rounded-xl border border-amber-700/50 p-5 text-amber-200 print:hidden">{tx.empty}</div>}
    {selecionadas.has("viena")&&<ReportSection title={tx.viena}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6 print:grid-cols-3"><Metric title={tx.market} value={formatNumber(v.mercado_elegivel)}/><Metric title={tx.carrier} value={`${formatNumber(v.carrier_observada)} · ${v.carrier_presenca_percentual.toFixed(1)}%`}/><Metric title={tx.noContact} value={formatNumber(v.sem_contato)}/><Metric title={tx.noParticipation} value={formatNumber(v.nao_participamos_proposta)}/><Metric title={tx.qualify} value={formatNumber(v.dados_status_a_qualificar)}/><Metric title={tx.trend} value={`${v.q2_vs_q1_percentual&&v.q2_vs_q1_percentual>0?"+":""}${Number(v.q2_vs_q1_percentual||0).toFixed(1)}%`}/></div><Table headers={[tx.segment,tx.market,"Carrier","Carrier %","TK","Nacional",tx.noContact,tx.noParticipation,tx.trend]} rows={v.segmentos.map(s=>[s.segmento,formatNumber(s.mercado),formatNumber(s.carrier),`${s.carrier_percentual_observado.toFixed(1)}%`,formatNumber(s.tk),formatNumber(s.nacional),formatNumber(s.sem_contato),formatNumber(s.nao_participou),s.q2_vs_q1_percentual===null?"—":`${s.q2_vs_q1_percentual>0?"+":""}${s.q2_vs_q1_percentual.toFixed(1)}%`])}/><h3 className="mt-5 mb-2 font-semibold">{tx.month}</h3><Table headers={[tx.month,"Trailer","Diesel Truck","Direct Drive","Total"]} rows={v.mensal.map(m=>[m.mes,formatNumber(m.trailer),formatNumber(m.diesel_truck),formatNumber(m.direct_drive),formatNumber(m.total)])}/><h3 className="mt-5 mb-2 font-semibold">{tx.territory}</h3><Table headers={["DDD",tx.market,"Trailer","Diesel Truck","Direct Drive",tx.owner]} rows={v.territorio.map(d=>[d.ddd,formatNumber(d.mercado),formatNumber(d.trailer),formatNumber(d.diesel_truck),formatNumber(d.direct_drive),d.responsavel])}/><div className="mt-5"><h3 className="mb-2 font-semibold">{tx.readings}</h3><ol className="list-decimal space-y-1 pl-5 text-sm text-slate-300 print:text-black">{v.leituras_estrategicas.map(r=><li key={r}>{r}</li>)}</ol></div></ReportSection>}
    {selecionadas.has("prioridades")&&<ReportSection title={tx.priorities}><Table headers={[tx.priority,tx.account,tx.score,tx.market,tx.nonCarrier,"Carrier",tx.noParticipation,tx.noContact,"TK","Nacional",tx.price,tx.relationship,tx.technical,tx.reading]} rows={data.oportunidades_prioritarias.map(r=>[r.prioridade,r.cliente,formatNumber(r.score_transparente),formatNumber(r.mercado),formatNumber(r.nao_carrier),formatNumber(r.carrier),formatNumber(r.nao_participou),formatNumber(r.sem_contato),formatNumber(r.tk),formatNumber(r.nacional),formatNumber(r.preco),formatNumber(r.relacionamento),formatNumber(r.gap_tecnico),r.leitura_sugerida])}/></ReportSection>}
    {selecionadas.has("implementadoras")&&<ReportSection title={tx.builders}><Table headers={[tx.builder,tx.market,"Trailer","Diesel Truck","Direct Drive",tx.reading]} rows={data.implementadoras_mercado.map(r=>[r.implementadora,formatNumber(r.mercado_elegivel),formatNumber(r.trailer),formatNumber(r.diesel_truck),formatNumber(r.direct_drive),r.leitura])}/></ReportSection>}
    {selecionadas.has("observacoes")&&<ReportSection title={tx.notes}><div className="grid gap-3 sm:grid-cols-4 print:grid-cols-4"><Metric title={tx.market} value={formatNumber(o.registros_elegiveis)}/><Metric title={tx.useful} value={formatNumber(o.com_observacao_util)}/><Metric title={tx.coverage} value={`${o.cobertura_observacoes_percentual.toFixed(1)}%`}/><Metric title={tx.without} value={formatNumber(o.sem_observacao_util)}/></div><Table headers={["Tema",tx.observations,tx.clients,tx.uniqueNotes,tx.commercialReading,tx.use]} rows={o.temas.map(r=>[r.tema,formatNumber(r.ocorrencias),formatNumber(r.clientes_unicos),formatNumber(r.observacoes_unicas),r.leitura_comercial,r.uso_no_cti])}/><p className="mt-4 text-xs text-slate-400 print:text-black"><strong>{tx.rule}:</strong> {o.regra}</p></ReportSection>}
    {camadas.length>0&&<footer className="hidden border-t border-gray-300 pt-3 text-xs text-gray-600 print:block"><FileText size={14} className="inline"/> CTI · ANFIR 2026 · Carrier/JOV · {new Date().toLocaleString(locale==="pt-BR"?"pt-BR":locale==="en"?"en-US":"es-419")}</footer>}
   </div>
  </section>
 </main>
}
function ReportSection({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-4 rounded-2xl border border-[#17304d] bg-[#071226] p-5 print:break-inside-auto print:rounded-none print:border-0 print:bg-white print:p-0 print:pb-6"><h2 className="text-xl font-bold text-cyan-300 print:text-black">{title}</h2>{children}</section>}
function Metric({title,value}:{title:string;value:string}){return <div className="rounded-xl border border-[#193354] bg-[#08162d] p-4 print:border-gray-300 print:bg-white"><p className="text-[10px] uppercase text-slate-500 print:text-gray-600">{title}</p><p className="mt-1 text-lg font-bold text-cyan-300 print:text-black">{value}</p></div>}
function Table({headers,rows}:{headers:string[];rows:string[][]}){return <div className="overflow-x-auto print:overflow-visible"><table className="min-w-full border-collapse text-xs"><thead><tr className="border-b border-[#24466f] print:border-gray-400">{headers.map(h=><th key={h} className="px-2 py-2 text-left uppercase text-slate-500 print:text-black">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={`${i}-${row[0]}`} className="border-b border-[#13203f] print:border-gray-200">{row.map((cell,j)=><td key={`${j}-${cell}`} className="px-2 py-2 align-top text-slate-300 print:text-black">{cell}</td>)}</tr>)}</tbody></table></div>}
