/* eslint-disable react-hooks/set-state-in-effect */
"use client"

import { useEffect, useMemo, useState } from "react"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import JornadaComercialNav from "@/components/crm/JornadaComercialNav"
import { useAuth } from "@/core/auth/AuthContext"
import { useOperationalI18n } from "@/core/i18n/operational"
import { pertenceAoEscopoDoUsuario, possuiEscopoProprio } from "@/core/rbac/commercial-scope"
import { API_URL } from "@/lib/api"

type Venda={id?:string;cliente_id?:string;cliente_nome?:string;equipamento_id?:string;equipamento_codigo?:string;equipamento_nome?:string;implementador_id?:string;implementadora_id?:string;implementadora_nome?:string;pedido_id?:string;pedido_numero?:string;tipo_venda?:string;valor?:number;data_venda?:string;observacao?:string}
type LinhaNucleo={responsavel_id?:string|null;pedido_id?:string|null}

const textos={
 "pt-BR":{eyebrow:"Realizado comercial",title:"Vendas",subtitle:"Histórico do que efetivamente foi concluído no CRM App. Esta tela não cria novas negociações nem novos pedidos.",registered:"Vendas registradas",soldValue:"Valor vendido",averageTicket:"Ticket médio",saleTypes:"Tipos de venda",history:"Histórico de vendas",historySub:"Espelho gerencial do realizado, originado dos pedidos concluídos no CRM App. Sem busca ativa, esta tabela é a composição exata dos três indicadores navegáveis acima.",search:"Buscar cliente, equipamento, pedido, tipo ou observação",loading:"Carregando vendas...",empty:"Nenhuma venda registrada na base atual.",date:"Data",client:"Cliente",order:"Pedido",equipment:"Equipamento",bodyBuilder:"Implementadora",type:"Tipo",value:"Valor",defaultSale:"VENDA",click:"Clique para detalhar",load:"Não foi possível carregar as vendas.",unexpected:"A API de vendas retornou um formato inesperado.",loadFail:"Falha ao carregar vendas."},
 en:{eyebrow:"Completed business",title:"Sales",subtitle:"History of business effectively completed in the CRM App. This screen does not create new deals or new orders.",registered:"Recorded sales",soldValue:"Sales value",averageTicket:"Average ticket",saleTypes:"Sale types",history:"Sales history",historySub:"Management view of completed business originating from orders closed in the CRM App. With no active search, this table is the exact composition of the three navigable indicators above.",search:"Search account, equipment, order, sale type or notes",loading:"Loading sales...",empty:"No sales recorded in the current data set.",date:"Date",client:"Account",order:"Order",equipment:"Equipment",bodyBuilder:"Body Builder",type:"Type",value:"Value",defaultSale:"SALE",click:"Click to view details",load:"We couldn't load sales.",unexpected:"The sales API returned an unexpected format.",loadFail:"We couldn't load sales."},
 es:{eyebrow:"Realizado comercial",title:"Ventas",subtitle:"Historial de lo que efectivamente se completó en la App CRM. Esta pantalla no crea nuevas negociaciones ni nuevos pedidos.",registered:"Ventas registradas",soldValue:"Valor vendido",averageTicket:"Ticket medio",saleTypes:"Tipos de venta",history:"Historial de ventas",historySub:"Vista gerencial de lo realizado, originada en pedidos concluidos en la App CRM. Sin búsqueda activa, esta tabla es la composición exacta de los tres indicadores navegables anteriores.",search:"Buscar cliente, equipo, pedido, tipo u observación",loading:"Cargando ventas...",empty:"No hay ventas registradas en la base actual.",date:"Fecha",client:"Cliente",order:"Pedido",equipment:"Equipo",bodyBuilder:"Carrocero",type:"Tipo",value:"Valor",defaultSale:"VENTA",click:"Haga clic para ver detalles",load:"No fue posible cargar las ventas.",unexpected:"La API de ventas devolvió un formato inesperado.",loadFail:"No fue posible cargar las ventas."}
} as const

export default function VendasPage(){
 const { usuario } = useAuth()
 const { locale, formatCurrency, formatDate, formatNumber }=useOperationalI18n()
 const tx=textos[locale]
 const[dados,setDados]=useState<Venda[]>([]),[busca,setBusca]=useState(""),[loading,setLoading]=useState(true),[erro,setErro]=useState("")
 useEffect(()=>{let ativo=true;setLoading(true);setErro("");Promise.all([fetch(`${API_URL}/vendas`,{cache:"no-store"}),fetch(`${API_URL}/crm/nucleo-comercial`,{cache:"no-store"})]).then(async([rv,rn])=>{const vendas=await rv.json().catch(()=>null),nucleo=await rn.json().catch(()=>[]);if(!rv.ok)throw new Error(vendas?.detail||tx.load);if(!Array.isArray(vendas))throw new Error(tx.unexpected);if(!possuiEscopoProprio(usuario)){if(ativo)setDados(vendas as Venda[]);return}const pedidosPermitidos=new Set((rn.ok&&Array.isArray(nucleo)?nucleo:[]).filter((item:LinhaNucleo)=>pertenceAoEscopoDoUsuario(item.responsavel_id,usuario)).map((item:LinhaNucleo)=>String(item.pedido_id||"")).filter(Boolean));if(ativo)setDados((vendas as Venda[]).filter(item=>Boolean(item.pedido_id)&&pedidosPermitidos.has(String(item.pedido_id))))}).catch(falha=>{if(ativo)setErro(falha instanceof Error?falha.message:tx.loadFail)}).finally(()=>{if(ativo)setLoading(false)});return()=>{ativo=false}},[tx.load,tx.loadFail,tx.unexpected,usuario])
 const filtrados=useMemo(()=>{const loc=locale==="pt-BR"?"pt-BR":locale==="es"?"es":"en";const termo=busca.trim().toLocaleLowerCase(loc);if(!termo)return dados;return dados.filter(item=>JSON.stringify(item).toLocaleLowerCase(loc).includes(termo))},[busca,dados,locale])
 const valorTotal=dados.reduce((total,item)=>total+Number(item.valor||0),0),ticketMedio=dados.length?valorTotal/dados.length:0,tipos=new Set(dados.map(item=>String(item.tipo_venda||"").trim()).filter(Boolean)).size
 const dataLocal=(valor?:string)=>{if(!valor)return"-";return formatDate(`${valor}T12:00:00`)}
 function abrirRealizado(){setBusca("");window.setTimeout(()=>document.getElementById("historico-vendas")?.scrollIntoView({behavior:"smooth",block:"start"}),0)}
 return <main className="flex min-h-screen bg-[#020817] text-white"><Sidebar/><section className="min-w-0 flex-1"><Topbar/><div className="space-y-6 p-4 sm:p-6 lg:p-8">
  <header className="rounded-3xl border border-[#13203f] bg-[#091a33] p-6"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400">{tx.eyebrow}</p><h1 className="mt-2 text-3xl font-bold">{tx.title}</h1><p className="mt-2 text-sm text-slate-400">{tx.subtitle}</p></header>
  <JornadaComercialNav/>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi titulo={tx.registered} valor={formatNumber(dados.length)} onOpen={abrirRealizado} click={tx.click}/><Kpi titulo={tx.soldValue} valor={formatCurrency(valorTotal)} onOpen={abrirRealizado} click={tx.click}/><Kpi titulo={tx.averageTicket} valor={formatCurrency(ticketMedio)} onOpen={abrirRealizado} click={tx.click}/><Kpi titulo={tx.saleTypes} valor={formatNumber(tipos)} click={tx.click}/></section>
  <section id="historico-vendas" className="scroll-mt-24 rounded-3xl border border-[#13203f] bg-[#071427] p-6"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h2 className="text-xl font-bold">{tx.history}</h2><p className="mt-1 text-sm text-slate-400">{tx.historySub}</p></div><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder={tx.search} className="w-full rounded-xl border border-[#24466f] bg-[#020817] px-4 py-3 text-sm text-white md:max-w-md"/></div>
   {erro&&<div className="mt-5 rounded-xl border border-red-900 bg-red-950/30 p-4 text-sm text-red-200">{erro}</div>}
   {loading?<p className="mt-6 text-slate-400">{tx.loading}</p>:filtrados.length===0?<div className="mt-6 rounded-2xl border border-dashed border-[#24466f] p-8 text-center text-slate-400">{tx.empty}</div>:<div className="mt-6 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b border-[#16325c] text-left text-slate-400"><th className="p-3">{tx.date}</th><th className="p-3">{tx.client}</th><th className="p-3">{tx.order}</th><th className="p-3">{tx.equipment}</th><th className="p-3">{tx.bodyBuilder}</th><th className="p-3">{tx.type}</th><th className="p-3">{tx.value}</th></tr></thead><tbody>{filtrados.map((item,index)=><tr key={item.id||`${item.cliente_id}-${item.data_venda}-${index}`} className="border-b border-[#13203f] align-top"><td className="p-3">{dataLocal(item.data_venda)}</td><td className="p-3 font-semibold text-white">{item.cliente_nome||item.cliente_id||"-"}</td><td className="p-3 text-cyan-300">{item.pedido_numero||"-"}</td><td className="p-3">{item.equipamento_nome||item.equipamento_codigo||item.equipamento_id||"-"}</td><td className="p-3">{item.implementadora_nome||"-"}</td><td className="p-3"><span className="rounded-full border border-cyan-800 px-3 py-1 text-xs text-cyan-200">{item.tipo_venda||tx.defaultSale}</span></td><td className="p-3 font-semibold text-emerald-300">{formatCurrency(Number(item.valor||0))}</td></tr>)}</tbody></table></div>}
  </section>
 </div></section></main>
}
function Kpi({titulo,valor,onOpen,click}:{titulo:string;valor:string;onOpen?:()=>void;click:string}){const body=<><p className="text-sm text-slate-400">{titulo}</p><p className="mt-2 text-2xl font-bold text-cyan-300">{valor}</p>{onOpen&&<p className="mt-2 text-[11px] text-cyan-400">{click}</p>}</>;return onOpen?<button type="button" onClick={onOpen} className="rounded-2xl border border-[#13203f] bg-[#091a33] p-5 text-left transition hover:border-cyan-500/70 hover:bg-[#0b1d38]">{body}</button>:<div className="rounded-2xl border border-[#13203f] bg-[#091a33] p-5">{body}</div>}
