/* eslint-disable react-hooks/set-state-in-effect */
"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import JornadaComercialNav from "@/components/crm/JornadaComercialNav"
import { useAuth } from "@/core/auth/AuthContext"
import { pertenceAoEscopoDoUsuario } from "@/core/rbac/commercial-scope"
import { useOperationalI18n } from "@/core/i18n/operational"
import { API_URL } from "@/lib/api"

type LinhaNucleo = { oportunidade_id:string; titulo:string; cliente_nome:string; responsavel_id?:string|null; etapa:string; valor:number; probabilidade:number; valor_ponderado:number; data_fechamento_prevista?:string|null; encerrada:boolean; pedido_id?:string|null }
type CicloPedido = { id:string; status_ciclo?:string; instalado_em?:string|null; encerrado_em?:string|null }
const ETAPAS_PIPELINE=["OPORTUNIDADE","ATIVIDADE","PROPOSTA","ACEITE","PEDIDO","CARRIER","FATURADO","ENTREGUE","INSTALADO","ENCERRADO"]
function percentual(valor:number){return `${Math.round(Number(valor||0)*100)}%`}
function inicioMesAtual(){const agora=new Date();return `${agora.getFullYear()}-${String(agora.getMonth()+1).padStart(2,"0")}-01`}
function fimMesAtual(){const agora=new Date();return new Date(agora.getFullYear(),agora.getMonth()+1,0).toISOString().slice(0,10)}
function dataIsoValida(valor?:string|null){return Boolean(valor&&/^\d{4}-\d{2}-\d{2}$/.test(valor)&&!Number.isNaN(new Date(`${valor}T12:00:00`).getTime()))}

const texto = {
 "pt-BR": { eyebrow:"Movimento do negócio", subtitle:"O pipeline acompanha o negócio até CARRIER, faturamento, entrega, instalação e encerramento. O ciclo não termina na entrega.", periodDeals:"Negociações no período", total:"Pipeline total", weighted:"Pipeline ponderado", visual:"Leitura visual do ciclo completo", valueByStage:"Valor por estágio", postOrder:"As etapas pós-pedido passam a ser alimentadas pelo acompanhamento operacional real do pedido.", loading:"Carregando pipeline...", empty:"Nenhuma negociação encontrada no período.", tableTitle:"Negociações por estágio", tableSubtitle:"Esta tabela é a composição exata dos três indicadores acima. A etapa pós-pedido reflete as confirmações manuais de CARRIER, NF, entrega e instalação.", client:"Cliente", opportunity:"Oportunidade", chance:"Chance", noClient:"Cliente não identificado", genericOpportunity:"Oportunidade comercial", followCycle:"Acompanhar ciclo", openDeal:"Abrir negócio", noForecast:"Sem previsão", composition:"Clique para ver a composição" },
 en: { eyebrow:"Deal progression", subtitle:"The pipeline follows each deal through CARRIER processing, invoicing, delivery, installation and closure. The cycle does not end at delivery.", periodDeals:"Deals in period", total:"Total pipeline", weighted:"Weighted pipeline", visual:"Full-cycle visual", valueByStage:"Value by stage", postOrder:"Post-order stages are driven by the order's real operational follow-up.", loading:"Loading pipeline...", empty:"No deals found for this period.", tableTitle:"Deals by stage", tableSubtitle:"This table is the exact composition of the three indicators above. Post-order stages reflect manual confirmations for CARRIER, invoice, delivery and installation.", client:"Account", opportunity:"Opportunity", chance:"Win probability", noClient:"Account not identified", genericOpportunity:"Commercial opportunity", followCycle:"Track cycle", openDeal:"Open deal", noForecast:"No expected close", composition:"Click to view composition" },
 es: { eyebrow:"Evolución del negocio", subtitle:"El pipeline acompaña cada negocio hasta CARRIER, facturación, entrega, instalación y cierre. El ciclo no termina con la entrega.", periodDeals:"Negocios del período", total:"Pipeline total", weighted:"Pipeline ponderado", visual:"Lectura visual del ciclo completo", valueByStage:"Valor por etapa", postOrder:"Las etapas posteriores al pedido se alimentan del seguimiento operativo real del pedido.", loading:"Cargando pipeline...", empty:"No se encontraron negocios en el período.", tableTitle:"Negocios por etapa", tableSubtitle:"Esta tabla muestra la composición exacta de los tres indicadores anteriores. Las etapas posteriores al pedido reflejan las confirmaciones manuales de CARRIER, factura, entrega e instalación.", client:"Cliente", opportunity:"Oportunidad", chance:"Probabilidad", noClient:"Cliente no identificado", genericOpportunity:"Oportunidad comercial", followCycle:"Acompañar ciclo", openDeal:"Abrir negocio", noForecast:"Sin previsión", composition:"Haga clic para ver la composición" }
}

export default function PipelinePage(){
 const { usuario } = useAuth()
 const { locale, tOp, formatCurrency, formatDate, formatNumber } = useOperationalI18n()
 const tx=texto[locale]
 const[dados,setDados]=useState<LinhaNucleo[]>([]),[ciclos,setCiclos]=useState<CicloPedido[]>([]),[inicio,setInicio]=useState(inicioMesAtual),[fim,setFim]=useState(fimMesAtual),[loading,setLoading]=useState(true),[erro,setErro]=useState("")
 useEffect(()=>{let ativo=true;setLoading(true);setErro("");Promise.all([fetch(`${API_URL}/crm/nucleo-comercial`,{cache:"no-store"}),fetch(`${API_URL}/carrier-operacional/ciclos`,{cache:"no-store"})]).then(async([rn,rc])=>{const pn=await rn.json().catch(()=>[]),pc=await rc.json().catch(()=>[]);if(!rn.ok)throw new Error(pn?.detail||"Falha ao carregar núcleo comercial");if(ativo){setDados(Array.isArray(pn)?pn:[]);setCiclos(rc.ok&&Array.isArray(pc)?pc:[])}}).catch(e=>{if(ativo)setErro(e instanceof Error?e.message:tx.loading)}).finally(()=>{if(ativo)setLoading(false)});return()=>{ativo=false}},[tx.loading])
 const cicloPorPedido=useMemo(()=>new Map(ciclos.map(c=>[String(c.id),c])),[ciclos])
 const dadosEscopados=useMemo(()=>dados.filter(item=>pertenceAoEscopoDoUsuario(item.responsavel_id,usuario)),[dados,usuario])
 const consolidados=useMemo(()=>dadosEscopados.map(item=>{const ciclo=item.pedido_id?cicloPorPedido.get(String(item.pedido_id)):undefined;const etapaCiclo=String(ciclo?.status_ciclo||"").toUpperCase();return etapaCiclo&&ETAPAS_PIPELINE.includes(etapaCiclo)?{...item,etapa:etapaCiclo,encerrada:etapaCiclo==="ENCERRADO"}:item}),[dadosEscopados,cicloPorPedido])
 const filtrados=useMemo(()=>consolidados.filter(item=>{const data=dataIsoValida(item.data_fechamento_prevista)?String(item.data_fechamento_prevista):"";if(!data)return true;return data>=inicio&&data<=fim}),[consolidados,fim,inicio])
 const valorTotal=filtrados.reduce((t,i)=>t+Number(i.valor||0),0),valorPonderado=filtrados.reduce((t,i)=>t+Number(i.valor_ponderado||0),0)
 const grafico=useMemo(()=>ETAPAS_PIPELINE.map(etapa=>{const itens=filtrados.filter(item=>item.etapa===etapa);return{etapa:etapa.replaceAll("_"," "),valor:itens.reduce((t,i)=>t+Number(i.valor||0),0),negociacoes:itens.length}}),[filtrados])
 const dataPrevista=(valor?:string|null)=>dataIsoValida(valor)?formatDate(`${valor}T12:00:00`):tx.noForecast
 return <main className="flex min-h-screen bg-[#020817] text-white"><Sidebar/><section className="min-w-0 flex-1"><Topbar/><div className="space-y-6 p-4 sm:p-6 lg:p-8">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400">{tx.eyebrow}</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">CRM • {tOp("pipeline.title")}</h1><p className="mt-2 text-gray-400">{tx.subtitle}</p></div><Link href="/crm-app/oportunidades/nova" className="rounded-xl bg-cyan-500 px-5 py-3 text-center font-semibold text-slate-950">{tOp("op.new")}</Link></div>
  <JornadaComercialNav/>
  <section className="grid gap-4 rounded-2xl border border-[#13203f] bg-[#071226] p-5 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_auto]"><CampoData label={tOp("common.start")} value={inicio} onChange={setInicio}/><CampoData label={tOp("common.end")} value={fim} onChange={setFim}/><button type="button" onClick={()=>{setInicio(inicioMesAtual());setFim(fimMesAtual())}} className="self-end rounded-xl border border-cyan-700 px-4 py-3 text-cyan-300">{tOp("common.currentMonth")}</button></section>
  {erro&&<div className="rounded-xl border border-red-500 p-4 text-red-300">{erro}</div>}
  <section className="grid grid-cols-1 gap-4 md:grid-cols-3"><Kpi titulo={tx.periodDeals} valor={formatNumber(filtrados.length)} href="#negociacoes-pipeline" detalhe={tx.composition}/><Kpi titulo={tx.total} valor={formatCurrency(valorTotal)} href="#negociacoes-pipeline" detalhe={tx.composition}/><Kpi titulo={tx.weighted} valor={formatCurrency(valorPonderado)} href="#negociacoes-pipeline" detalhe={tx.composition}/></section>
  {!loading&&filtrados.length>0&&<section className="rounded-3xl border border-[#13203f] bg-gradient-to-b from-[#081a33] to-[#050d1d] p-5 shadow-[0_18px_45px_rgba(0,0,0,.35)]"><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-400">{tx.visual}</p><h2 className="mt-1 text-xl font-bold">{tx.valueByStage}</h2><p className="mt-1 text-sm text-slate-400">{tx.postOrder}</p></div><div className="h-[300px] w-full [perspective:1000px]"><div className="h-full rounded-2xl border border-[#17365f] bg-[#04101f] p-2 shadow-[0_16px_30px_rgba(6,182,212,.08)] [transform:rotateX(1.5deg)]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={grafico} margin={{top:18,right:20,left:8,bottom:8}}><defs><linearGradient id="pipelineArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22d3ee" stopOpacity={.55}/><stop offset="78%" stopColor="#0891b2" stopOpacity={.12}/><stop offset="100%" stopColor="#020817" stopOpacity={0}/></linearGradient><filter id="linhaGlow"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><CartesianGrid stroke="#15304f" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="etapa" stroke="#7890ab" tick={{fontSize:10}} interval={0}/><YAxis stroke="#7890ab" tick={{fontSize:11}} tickFormatter={v=>formatCurrency(Number(v),"BRL").replace(/\s/g,"").replace(/,00$/,"")}/><Tooltip contentStyle={{backgroundColor:"#061126",border:"1px solid #24507a",borderRadius:"14px",color:"#fff"}} formatter={(v)=>[formatCurrency(Number(v)),tOp("common.value")]}/><Area type="monotone" dataKey="valor" stroke="#22d3ee" strokeWidth={4} fill="url(#pipelineArea)" filter="url(#linhaGlow)" dot={{r:4,fill:"#22d3ee",stroke:"#0e7490",strokeWidth:2}} activeDot={{r:6}}/></AreaChart></ResponsiveContainer></div></div></section>}
  {loading?<Aviso>{tx.loading}</Aviso>:filtrados.length===0?<Aviso>{tx.empty}</Aviso>:<section id="negociacoes-pipeline" className="scroll-mt-24 overflow-hidden rounded-3xl border border-[#13203f] bg-[#071427]"><div className="border-b border-[#13203f] p-5"><h2 className="text-xl font-bold">{tx.tableTitle}</h2><p className="mt-1 text-sm text-slate-400">{tx.tableSubtitle}</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b border-[#16325c] text-left text-slate-400"><Th>{tx.client}</Th><Th>{tx.opportunity}</Th><Th>{tOp("common.stage")}</Th><Th>{tOp("common.value")}</Th><Th>{tx.chance}</Th><Th>{tOp("common.forecast")}</Th><Th>{tOp("common.action")}</Th></tr></thead><tbody>{filtrados.map(item=><tr key={item.oportunidade_id} className="border-b border-[#13203f] hover:bg-[#091a33]/60"><Td forte>{item.cliente_nome||tx.noClient}</Td><Td>{item.titulo||tx.genericOpportunity}</Td><td className="p-4"><span className="rounded-full border border-cyan-800 bg-cyan-950/30 px-3 py-1 text-xs text-cyan-300">{item.etapa.replaceAll("_"," ")}</span></td><td className="p-4 font-semibold text-emerald-300">{formatCurrency(item.valor)}</td><Td>{percentual(item.probabilidade)}</Td><Td>{dataPrevista(item.data_fechamento_prevista)}</Td><td className="p-4"><Link href={item.pedido_id?`/pedidos/${item.pedido_id}/ciclo`:`/oportunidades/${item.oportunidade_id}`} className="rounded-lg border border-cyan-700 px-3 py-2 text-xs font-semibold text-cyan-300">{item.pedido_id?tx.followCycle:tx.openDeal}</Link></td></tr>)}</tbody></table></div></section>}
 </div></section></main>
}
function CampoData({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="text-sm text-slate-300">{label}<input type="date" value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-[#24466f] bg-[#020817] px-4 py-3"/></label>}
function Kpi({titulo,valor,href,detalhe}:{titulo:string;valor:string;href?:string;detalhe:string}){const body=<><p className="text-sm text-gray-400">{titulo}</p><p className="mt-2 text-3xl font-bold text-cyan-400">{valor}</p>{href&&<p className="mt-2 text-[11px] text-cyan-400">{detalhe}</p>}</>;return href?<Link href={href} className="rounded-2xl border border-[#13203f] bg-[#091a33] p-6 transition hover:border-cyan-500/70 hover:bg-[#0b1d38]">{body}</Link>:<div className="rounded-2xl border border-[#13203f] bg-[#091a33] p-6">{body}</div>}
function Aviso({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-[#13203f] bg-[#091a33] p-10 text-gray-300">{children}</div>}
function Th({children}:{children:React.ReactNode}){return <th className="p-4 font-medium">{children}</th>}
function Td({children,forte=false}:{children:React.ReactNode;forte?:boolean}){return <td className={`p-4 ${forte?"font-semibold text-cyan-300":"text-slate-200"}`}>{children}</td>}
