"use client"

import { useEffect, useMemo, useState } from "react"

const API_URL = process.env.NEXT_PUBLIC_API_URL || "https://cti-backend-5ugf.onrender.com"
const dims = ["regiao", "uf", "dealer", "implementadora", "cliente", "linha", "familia", "produto"] as const
type Dim = (typeof dims)[number]
type Filters = Record<Dim, string> & { contexto: string; segmento: string; periodo: string; comparacao: string; inicio: string; fim: string }
type Option = { valor: string; contagem: number }
type Rank = { nome: string; quantidade: number; valor: number }
type Serie = { periodo: string; volume: number; valor: number; ticket_medio: number }
type Data = {
  metadata: { contexto_operacional: string; segmento: string; ultima_atualizacao: string; origem: string; natureza_dados?: string }
  kpis: { volume: number; valor: number; ticket_medio: number; comparacoes: Record<string, { percentual: number; direcao: string }> }
  resumo?: { clientes_unicos?: number }
  rankings: Record<string, Rank[]>; serie_temporal: Serie[]
  clientes_sem_registro_recente?: Array<{ nome: string; dias_sem_registro: number | null }>
  heatmap: Array<{ regiao: string; uf: string }>; drilldown: Record<string, Rank[]>; empty_state: string | null
}

const initial: Filters = { contexto: "brasil", segmento: "GERAL", periodo: "ULTIMOS_90_DIAS", comparacao: "PERIODO_ANTERIOR", inicio: "", fim: "", regiao: "", uf: "", dealer: "", implementadora: "", cliente: "", linha: "", familia: "", produto: "" }
const periods = [["HOJE","Hoje"],["ULTIMOS_7_DIAS","Últimos 7 dias"],["ULTIMOS_30_DIAS","Últimos 30 dias"],["ULTIMOS_90_DIAS","Últimos 90 dias"],["MES_ATUAL","Mês atual"],["TRIMESTRE_ATUAL","Trimestre atual"],["ANO_ATUAL","Ano atual"],["PERSONALIZADO","Personalizado"]]
function qs(filters: Filters, extra: Record<string,string> = {}) { const p = new URLSearchParams(); Object.entries({...filters,...extra}).forEach(([k,v]) => { if (v) p.set(k,v) }); return p.toString() }
function moeda(valor:number){return Number(valor||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function Card({title,value,compare}:{title:string;value:string;compare?:{percentual:number;direcao:string}}){return <div className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-2xl font-semibold">{value}</p>{compare&&<p className="mt-2 text-xs text-slate-500">{compare.percentual>0?"+":""}{compare.percentual}% vs. comparação</p>}</div>}
function Bars({items}:{items:Rank[]}){const max=Math.max(1,...items.map(i=>i.quantidade));return <div className="space-y-3">{items.slice(0,10).map(i=><div key={i.nome}><div className="flex justify-between text-xs"><span className="truncate pr-2">{i.nome}</span><strong>{i.quantidade}</strong></div><div className="mt-1 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-blue-600" style={{width:`${Math.max(3,i.quantidade/max*100)}%`}}/></div></div>)}</div>}

export default function InteligenciaPage(){
  const [edit,setEdit]=useState<Filters>(initial),[filters,setFilters]=useState<Filters>(initial),[data,setData]=useState<Data|null>(null)
  const [options,setOptions]=useState<Record<string,Option[]>>({}),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
  const query=useMemo(()=>qs(filters),[filters])
  useEffect(()=>{const c=new AbortController();Promise.all([fetch(`${API_URL}/analytics/intelligence?${query}`,{cache:"no-store",signal:c.signal}),fetch(`${API_URL}/analytics/intelligence/filter-options?${query}`,{cache:"no-store",signal:c.signal})]).then(async([a,b])=>{if(!a.ok||!b.ok)throw new Error(`Backend respondeu ${a.status}/${b.status}`);const[d,o]=await Promise.all([a.json(),b.json()]);setData(d);setOptions(o.opcoes||{});setError(null)}).catch((e:unknown)=>{if(e instanceof DOMException&&e.name==="AbortError")return;setError(e instanceof Error?e.message:"Falha ao carregar")}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[query])
  function change(k:keyof Filters,v:string){const n={...edit,[k]:v};if(k==="linha"){n.familia="";n.produto=""}if(k==="familia")n.produto="";setEdit(n)}
  function apply(){setLoading(true);setFilters(edit)}
  function clear(){setLoading(true);setEdit(initial);setFilters(initial)}
  function exportFile(format:"csv"|"xlsx"){window.open(`${API_URL}/analytics/intelligence/export?${qs(filters,{formato:format})}`,"_blank")}
  const heat=useMemo(()=>{const m=new Map<string,number>();data?.heatmap.forEach(i=>{const k=`${i.regiao} / ${i.uf}`;m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1])},[data])
  return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header><p className="text-sm font-medium uppercase tracking-wide text-blue-700">CTI · mercado realizado</p><h1 className="text-3xl font-bold">Inteligência de Mercado</h1><p className="mt-2 text-slate-600">ANFIR e fatos históricos já ocorridos. Este painel não representa Funil, pipeline, conversão do CRM ou oportunidades abertas.</p></header>
    <section className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><strong>Separação obrigatória:</strong> ANFIR = realizado. CRM = operação comercial. Funil = ciclo das oportunidades. Entre eles existe correlação analítica, nunca fusão de registros.</section>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
      <label className="text-sm">Contexto<select className="mt-1 w-full rounded-lg border p-2" value={edit.contexto} onChange={e=>change("contexto",e.target.value)}><option value="brasil">Brasil</option><option value="viena-sp">VIENA SP</option><option value="outros-dealers">Outros Dealers</option></select></label>
      <label className="text-sm">Segmento<select className="mt-1 w-full rounded-lg border p-2" value={edit.segmento} onChange={e=>change("segmento",e.target.value)}>{["GERAL","TR","DT","DD","UNKNOWN"].map(v=><option key={v}>{v}</option>)}</select></label>
      <label className="text-sm">Período<select className="mt-1 w-full rounded-lg border p-2" value={edit.periodo} onChange={e=>change("periodo",e.target.value)}>{periods.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>
      <label className="text-sm">Comparação<select className="mt-1 w-full rounded-lg border p-2" value={edit.comparacao} onChange={e=>change("comparacao",e.target.value)}><option value="SEM_COMPARACAO">Sem comparação</option><option value="PERIODO_ANTERIOR">Período anterior</option><option value="ANO_ANTERIOR">Ano anterior</option></select></label>
      {edit.periodo==="PERSONALIZADO"&&<><label className="text-sm">Início<input type="date" className="mt-1 w-full rounded-lg border p-2" value={edit.inicio} onChange={e=>change("inicio",e.target.value)}/></label><label className="text-sm">Fim<input type="date" className="mt-1 w-full rounded-lg border p-2" value={edit.fim} onChange={e=>change("fim",e.target.value)}/></label></>}
      {dims.map(d=><label className="text-sm capitalize" key={d}>{d}<select className="mt-1 w-full rounded-lg border p-2" value={edit[d]} onChange={e=>change(d,e.target.value)}><option value="">Todos</option>{(options[d]||[]).map(o=><option key={o.valor} value={o.valor}>{o.valor} ({o.contagem})</option>)}</select></label>)}
    </div><div className="mt-4 flex flex-wrap gap-2"><button onClick={apply} className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-medium text-white">Aplicar filtros</button><button onClick={clear} className="rounded-lg bg-slate-200 px-4 py-2 text-sm font-medium">Limpar</button><button onClick={()=>exportFile("csv")} className="rounded-lg border px-4 py-2 text-sm">Exportar CSV</button><button onClick={()=>exportFile("xlsx")} className="rounded-lg border px-4 py-2 text-sm">Exportar XLSX</button></div></section>
    {loading&&<div className="rounded-xl border bg-white p-10 text-center">Carregando inteligência de mercado...</div>}{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-6 text-red-800">{error}</div>}{!loading&&data?.empty_state&&<div className="rounded-xl border bg-white p-10 text-center">{data.empty_state}</div>}
    {!loading&&data&&!data.empty_state&&<><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card title="Registros realizados" value={data.kpis.volume.toLocaleString("pt-BR")} compare={data.kpis.comparacoes.volume}/><Card title="Valor registrado" value={moeda(data.kpis.valor)} compare={data.kpis.comparacoes.valor}/><Card title="Ticket médio histórico" value={moeda(data.kpis.ticket_medio)} compare={data.kpis.comparacoes.ticket_medio}/><Card title="Clientes históricos" value={String(data.resumo?.clientes_unicos??0)} /></section>
      <section className="grid gap-6 lg:grid-cols-3"><div className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Evolução do mercado realizado</h2><div className="mt-4 space-y-2 text-sm">{data.serie_temporal.slice(-12).map(i=><div key={i.periodo} className="grid grid-cols-3 gap-2 border-b pb-2"><span>{i.periodo}</span><span>{i.volume} registro(s)</span><span>{moeda(i.valor)}</span></div>)}</div></div><div className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Distribuição por UF</h2><div className="mt-4"><Bars items={data.rankings.uf||[]}/></div></div><div className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Distribuição por produto</h2><div className="mt-4"><Bars items={data.rankings.produto||[]}/></div></div></section>
      <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Recorrência histórica</h2><p className="mt-2 text-sm text-slate-500">Dias desde o último registro realizado encontrado. Não significa oportunidade perdida nem ausência de compra no CRM.</p><div className="mt-4 max-h-64 overflow-auto text-sm">{(data.clientes_sem_registro_recente||[]).map(c=><div key={c.nome} className="flex justify-between border-b py-2"><span>{c.nome}</span><strong>{c.dias_sem_registro??0} dias</strong></div>)}</div></div><div className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Heat map do mercado realizado</h2><div className="mt-4 space-y-2 text-sm">{heat.map(([k,v])=><div key={k} className="flex justify-between rounded bg-slate-100 p-2"><span>{k}</span><strong>{v}</strong></div>)}</div></div></section>
      <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Drill-down de mercado</h2><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{dims.map(d=><div key={d}><h3 className="mb-2 text-sm font-medium capitalize">{d}</h3><div className="max-h-52 overflow-auto text-xs">{(data.drilldown[d]||[]).slice(0,15).map(i=><div key={i.nome} className="flex justify-between border-b py-2"><span className="truncate pr-2">{i.nome}</span><strong>{i.quantidade}</strong></div>)}</div></div>)}</div></section>
      <section className="rounded-xl border bg-white p-4 text-sm text-slate-600">Origem: {data.metadata.origem} · Natureza: {data.metadata.natureza_dados||"FATO_MERCADO_REALIZADO"} · Contexto: {data.metadata.contexto_operacional} · Atualização: {new Date(data.metadata.ultima_atualizacao).toLocaleString("pt-BR")}</section></>}
  </div></main>
}
