"use client"

import Link from "next/link"
import { useCallback, useEffect, useState } from "react"
import { Bar, BarChart, CartesianGrid, LabelList, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import { useAuth } from "@/core/auth/AuthContext"
import { useOperationalI18n } from "@/core/i18n/operational"
import { pertenceAoEscopoDoUsuario } from "@/core/rbac/commercial-scope"
import { useOperationalContext } from "@/context/OperationalContext"
import { getDashboardExecutivoContextual } from "@/services/cti-api"
import { API_URL } from "@/lib/api"

type DashboardContextual={total_clientes?:number;total_estados?:number;total_municipios?:number;ticket_medio?:number;metadata?:{total_registros_filtrados?:number}}
type NucleoComercial={oportunidade_id:string;responsavel_id?:string|null;valor?:number;proposta_id?:string|null;pedido_id?:string|null;encerrada?:boolean}
type OportunidadeCRM={id:string;linha_equipamentos?:string|null;equipamento?:string|null;descricao?:string|null}
type LinhaProduto={codigo:"TR"|"DT"|"DD";nome:string;atual:number;anterior:number;variacao:number;disponivel:boolean}
type ProductLinesMetadata={descricao?:string;total_registros_periodo?:number;registros_classificados_periodo?:number;cobertura_classificacao_percentual?:number}
type ProductLinesResponse={metadata?:ProductLinesMetadata;linhas?:Array<{codigo:"TR"|"DT"|"DD";nome:string;atual:number;anterior:number;variacao:number}>}
type LinhaEmCurso={codigo:"TR"|"DT"|"DD";nome:string;negociacoes:number;valor:number}

const LINHAS=[{codigo:"TR" as const,nome:"Trailer"},{codigo:"DT" as const,nome:"Diesel Truck"},{codigo:"DD" as const,nome:"Direct Drive"}]
const RETRY_MS=5_000,REFRESH_MS=60_000

const textos={
 "pt-BR":{contextNational:"Visão consolidada nacional",contextViena:"Registros do autorizado Viena",contextUf:"Registros da unidade federativa {value}",contextDdd:"Território autorizado Viena no DDD {value}",lastLoading:"Carregando dados",historyRecordsTitle:"Dashboard Executivo · Registros históricos filtrados",historyRecordsSub:"Registros individualizados do realizado no contexto selecionado",liveDealsTitle:"Dashboard Executivo · Negócios em curso",liveDealsSub:"Oportunidades abertas que formam o indicador operacional",historyCoverage:"Cobertura da classificação histórica",unclassified:"{count} negócio(s) em curso sem classificação recuperável.",allClassified:"Todos os negócios em curso estão classificados por linha.",reconnecting:"Dados em curso reconectando.",deals:"negócio(s)",pipeline:"Pipeline",chartUnavailable:"Dados temporariamente indisponíveis. Reconexão automática em andamento.",click:"Clique para detalhar",period30:"Últimos 30 dias",period90:"Últimos 90 dias",year:"Ano atual",until:"até"},
 en:{contextNational:"National consolidated view",contextViena:"Viena authorized records",contextUf:"Records for state {value}",contextDdd:"Viena authorized territory in area code {value}",lastLoading:"Loading data",historyRecordsTitle:"Executive Dashboard · Filtered historical records",historyRecordsSub:"Individual completed-business records for the selected context",liveDealsTitle:"Executive Dashboard · Live deals",liveDealsSub:"Open opportunities that compose the operational indicator",historyCoverage:"Historical classification coverage",unclassified:"{count} live deal(s) without a recoverable product-line classification.",allClassified:"All live deals are classified by product line.",reconnecting:"Live data reconnecting.",deals:"deal(s)",pipeline:"Pipeline",chartUnavailable:"Data temporarily unavailable. Automatic reconnection is in progress.",click:"Click to view details",period30:"Last 30 days",period90:"Last 90 days",year:"Current year",until:"to"},
 es:{contextNational:"Vista consolidada nacional",contextViena:"Registros autorizados de Viena",contextUf:"Registros del estado {value}",contextDdd:"Territorio autorizado de Viena en el DDD {value}",lastLoading:"Cargando datos",historyRecordsTitle:"Panel Ejecutivo · Registros históricos filtrados",historyRecordsSub:"Registros individualizados de lo realizado en el contexto seleccionado",liveDealsTitle:"Panel Ejecutivo · Negocios en curso",liveDealsSub:"Oportunidades abiertas que componen el indicador operativo",historyCoverage:"Cobertura de la clasificación histórica",unclassified:"{count} negocio(s) en curso sin clasificación de línea recuperable.",allClassified:"Todos los negocios en curso están clasificados por línea.",reconnecting:"Datos en curso reconectando.",deals:"negocio(s)",pipeline:"Pipeline",chartUnavailable:"Datos temporalmente no disponibles. La reconexión automática está en curso.",click:"Haga clic para ver detalles",period30:"Últimos 30 días",period90:"Últimos 90 días",year:"Año actual",until:"a"}
} as const
function interp(text:string,values:Record<string,string|number>){return text.replace(/\{(\w+)\}/g,(_,key)=>String(values[key]??`{${key}}`))}

export default function DashboardHub(){
 const{usuario}=useAuth();const{locale,tOp,formatDate,formatNumber,formatCurrency}=useOperationalI18n();const tx=textos[locale]
 const{contexto,contextoAtual,periodo,dataInicio,dataFim,queryString}=useOperationalContext()
 const[historico,setHistorico]=useState<DashboardContextual|null>(null),[nucleo,setNucleo]=useState<NucleoComercial[]|null>(null),[oportunidadesCrm,setOportunidadesCrm]=useState<OportunidadeCRM[]|null>(null),[linhasProduto,setLinhasProduto]=useState<LinhaProduto[]|null>(null),[metadataLinhas,setMetadataLinhas]=useState<ProductLinesMetadata>({}),[ultimaAtualizacao,setUltimaAtualizacao]=useState<Date|null>(null),[loadingHistorico,setLoadingHistorico]=useState(true),[loadingOperacional,setLoadingOperacional]=useState(true),[falhaHistorico,setFalhaHistorico]=useState(false),[falhaLinhas,setFalhaLinhas]=useState(false),[falhaNucleo,setFalhaNucleo]=useState(false),[falhaOportunidades,setFalhaOportunidades]=useState(false)
 const carregarOperacional=useCallback(async()=>{const[dadosNucleo,dadosOportunidades]=await Promise.all([tentar<NucleoComercial[]>(()=>buscarJson(`${API_URL}/crm/nucleo-comercial`),2),tentar<OportunidadeCRM[]>(()=>buscarJson(`${API_URL}/crm/oportunidades`),2)]),nucleoOk=dadosNucleo!==null,oportunidadesOk=dadosOportunidades!==null;if(nucleoOk)setNucleo(dadosNucleo);if(oportunidadesOk)setOportunidadesCrm(dadosOportunidades);setFalhaNucleo(!nucleoOk);setFalhaOportunidades(!oportunidadesOk);setLoadingOperacional(false);if(nucleoOk||oportunidadesOk)setUltimaAtualizacao(new Date());return nucleoOk&&oportunidadesOk},[])
 const carregarHistorico=useCallback(async()=>{const[dadosHistoricos,dadosLinhas]=await Promise.all([tentar<DashboardContextual>(()=>getDashboardExecutivoContextual(queryString),2),tentar<ProductLinesResponse>(()=>buscarJson(`${API_URL}/analytics/product-lines?${queryString}`),2)]),historicoOk=dadosHistoricos!==null,linhasOk=Boolean(dadosLinhas?.linhas?.length===3);if(historicoOk)setHistorico(dadosHistoricos);if(linhasOk&&dadosLinhas){setLinhasProduto((dadosLinhas.linhas??[]).map(linha=>({...linha,disponivel:true})));setMetadataLinhas(dadosLinhas.metadata??{})}setFalhaHistorico(!historicoOk);setFalhaLinhas(!linhasOk);setLoadingHistorico(false);if(historicoOk||linhasOk)setUltimaAtualizacao(new Date());return historicoOk&&linhasOk},[queryString])
 useEffect(()=>{let ativo=true,timer:number|undefined;const executar=async()=>{const ok=await carregarOperacional();if(!ativo)return;timer=window.setTimeout(()=>void executar(),ok?REFRESH_MS:RETRY_MS)};queueMicrotask(()=>{if(!ativo)return;setLoadingOperacional(true);void executar()});const aoReconectar=()=>void carregarOperacional();window.addEventListener("online",aoReconectar);return()=>{ativo=false;if(timer)window.clearTimeout(timer);window.removeEventListener("online",aoReconectar)}},[carregarOperacional])
 useEffect(()=>{let ativo=true,timer:number|undefined;const executar=async()=>{const ok=await carregarHistorico();if(!ativo)return;timer=window.setTimeout(()=>void executar(),ok?REFRESH_MS:RETRY_MS)};queueMicrotask(()=>{if(!ativo)return;setHistorico(null);setLinhasProduto(null);setMetadataLinhas({});setLoadingHistorico(true);void executar()});const aoReconectar=()=>void carregarHistorico();window.addEventListener("online",aoReconectar);return()=>{ativo=false;if(timer)window.clearTimeout(timer);window.removeEventListener("online",aoReconectar)}},[carregarHistorico])
 const periodoExibido=periodo==="TODO_HISTORICO"?tOp("dashboard.allHistory"):periodo==="PERSONALIZADO"?(dataInicio&&dataFim?`${formatDate(`${dataInicio}T12:00:00`)} ${tx.until} ${formatDate(`${dataFim}T12:00:00`)}`:tOp("dashboard.customPeriod")):periodo==="ULTIMOS_30_DIAS"?tx.period30:periodo==="ULTIMOS_90_DIAS"?tx.period90:tx.year
 const contextoDescricao=contexto==="brasil"?tx.contextNational:contexto==="viena-sp"?tx.contextViena:contexto.startsWith("uf-")?interp(tx.contextUf,{value:contexto.slice(3).toUpperCase()}):contexto.startsWith("ddd-")?interp(tx.contextDdd,{value:contexto.slice(4)}):contextoAtual.description
 const historicoDisponivel=historico!==null,linhasDisponiveis=linhasProduto!==null,nucleoDisponivel=nucleo!==null,oportunidadesDisponiveis=oportunidadesCrm!==null,operacionalDisponivel=nucleoDisponivel&&oportunidadesDisponiveis
 const abertos=(nucleo??[]).filter(item=>!item.encerrada&&pertenceAoEscopoDoUsuario(item.responsavel_id,usuario)),pipelineAberto=abertos.reduce((t,i)=>t+Number(i.valor||0),0),propostasAbertas=abertos.filter(i=>Boolean(i.proposta_id)).length,pedidosAbertos=abertos.filter(i=>Boolean(i.pedido_id)).length,totalPeriodo=metadataLinhas.total_registros_periodo??0,totalClassificado=metadataLinhas.registros_classificados_periodo??(linhasProduto??[]).reduce((s,l)=>s+l.atual,0),cobertura=totalPeriodo>0?(totalClassificado/totalPeriodo)*100:0
 const oportunidadePorId=new Map((oportunidadesCrm??[]).map(item=>[String(item.id),item])),linhasEmCurso:LinhaEmCurso[]=LINHAS.map(linha=>{const itens=abertos.filter(item=>classificarLinha(oportunidadePorId.get(String(item.oportunidade_id)))===linha.codigo);return{codigo:linha.codigo,nome:linha.nome,negociacoes:itens.length,valor:itens.reduce((t,i)=>t+Number(i.valor||0),0)}}),classificadosEmCurso=linhasEmCurso.reduce((t,i)=>t+i.negociacoes,0),semLinhaEmCurso=Math.max(abertos.length-classificadosEmCurso,0)
 const graficoHistorico=LINHAS.map(def=>{const linha=(linhasProduto??[]).find(i=>i.codigo===def.codigo);return{linha:def.codigo,nome:def.nome,atual:linha?.atual??0,anterior:linha?.anterior??0}}),graficoPipeline=linhasEmCurso.map(linha=>({linha:linha.codigo,nome:linha.nome,valor:linha.valor,negociacoes:linha.negociacoes})),falhaTemporaria=falhaHistorico||falhaLinhas||falhaNucleo||falhaOportunidades
 const registrosHistoricosHref=drilldown("anfir",tx.historyRecordsTitle,tx.historyRecordsSub,queryString),negociosEmCursoHref=drilldown("crm",tx.liveDealsTitle,tx.liveDealsSub)
 const ultima=ultimaAtualizacao?formatDate(ultimaAtualizacao,{dateStyle:"short",timeStyle:"medium"}):tx.lastLoading
 const money=(value?:number)=>formatCurrency(Number(value??0)),shortMoney=(value:number)=>abreviarMoeda(value,locale)
 return <main className="flex min-h-screen bg-[#020817] text-white"><Sidebar/><section className="min-w-0 flex-1 overflow-hidden"><Topbar/><div className="space-y-6 p-4 sm:p-6 lg:p-8">
  <header><p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400">{tOp("dashboard.eyebrow")}</p><h1 className="mt-2 text-3xl font-bold">{tOp("dashboard.title")}</h1><p className="mt-2 max-w-4xl text-sm text-slate-400">{tOp("dashboard.subtitle")}</p><p className="mt-2 text-sm text-cyan-300">{tOp("dashboard.activeContext")}: {contextoAtual.label} — {contextoDescricao}</p></header>
  <section className="grid gap-3 md:grid-cols-3"><Info titulo={tOp("dashboard.historyPeriod")} valor={periodoExibido} click={tx.click}/><Info titulo={tOp("dashboard.lastUpdate")} valor={ultima} click={tx.click}/><Info titulo={tOp("dashboard.filteredHistory")} valor={loadingHistorico?"...":historicoDisponivel?formatNumber(historico.metadata?.total_registros_filtrados??0):"—"} href={historicoDisponivel?registrosHistoricosHref:undefined} click={tx.click}/></section>
  {falhaTemporaria&&<div className="rounded-2xl border border-amber-700 bg-amber-950/20 p-4 text-sm text-amber-200">{tOp("dashboard.connection")}</div>}
  <section className="grid gap-5 xl:grid-cols-2"><PainelTempo titulo={tOp("dashboard.realized")} subtitulo={tOp("dashboard.realizedSub")} destaque={tOp("dashboard.confirmedHistory")}><div className="grid gap-3 sm:grid-cols-2"><Kpi titulo={tOp("dashboard.historicalClients")} valor={loadingHistorico?"...":historicoDisponivel?formatNumber(historico.total_clientes??0):"—"} click={tx.click}/><Kpi titulo={tOp("dashboard.historicalTicket")} valor={loadingHistorico?"...":historicoDisponivel?money(historico.ticket_medio):"—"} click={tx.click}/><Kpi titulo={tOp("dashboard.states")} valor={loadingHistorico?"...":historicoDisponivel?formatNumber(historico.total_estados??0):"—"} click={tx.click}/><Kpi titulo={tOp("dashboard.cities")} valor={loadingHistorico?"...":historicoDisponivel?formatNumber(historico.total_municipios??0):"—"} click={tx.click}/></div></PainelTempo>
   <PainelTempo titulo={tOp("dashboard.inProgress")} subtitulo={tOp("dashboard.inProgressSub")} destaque={tOp("dashboard.liveDeals")}><div className="grid gap-3 sm:grid-cols-2"><Kpi titulo={tOp("dashboard.openPipeline")} valor={loadingOperacional?"...":nucleoDisponivel?money(pipelineAberto):"—"} href={nucleoDisponivel?negociosEmCursoHref:undefined} click={tx.click}/><Kpi titulo={tOp("dashboard.activeDeals")} valor={loadingOperacional?"...":nucleoDisponivel?formatNumber(abertos.length):"—"} href={nucleoDisponivel?negociosEmCursoHref:undefined} click={tx.click}/><Kpi titulo={tOp("dashboard.currentProposals")} valor={loadingOperacional?"...":nucleoDisponivel?formatNumber(propostasAbertas):"—"} click={tx.click}/><Kpi titulo={tOp("dashboard.ordersInProgress")} valor={loadingOperacional?"...":nucleoDisponivel?formatNumber(pedidosAbertos):"—"} click={tx.click}/></div></PainelTempo></section>
  <section className="grid gap-5 2xl:grid-cols-2"><GraficoPainel titulo={tOp("dashboard.realized")} subtitulo={tOp("dashboard.historyChart")}>
   {linhasDisponiveis?<ResponsiveContainer width="100%" height="100%"><BarChart data={graficoHistorico} margin={{top:30,right:16,left:0,bottom:0}}><CartesianGrid stroke="#17304d" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="linha" stroke="#8294ad"/><YAxis stroke="#8294ad"/><Tooltip contentStyle={tooltipStyle} labelFormatter={label=>nomeLinha(String(label))}/><Legend/><Bar dataKey="anterior" name={tOp("dashboard.previousPeriod")} fill="#52657d" radius={[7,7,0,0]}><LabelList dataKey="anterior" position="top" fill="#94a3b8" fontSize={12}/></Bar><Bar dataKey="atual" name={tOp("dashboard.selectedPeriod")} fill="#22d3ee" radius={[7,7,0,0]}><LabelList dataKey="atual" position="top" fill="#67e8f9" fontSize={12}/></Bar></BarChart></ResponsiveContainer>:<GraficoIndisponivel texto={tx.chartUnavailable}/>}</GraficoPainel>
   <GraficoPainel titulo={tOp("dashboard.inProgress")} subtitulo={tOp("dashboard.pipelineChart")}>
    {operacionalDisponivel?<><ResponsiveContainer width="100%" height="100%"><BarChart data={graficoPipeline} margin={{top:34,right:16,left:8,bottom:0}}><CartesianGrid stroke="#17304d" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="linha" stroke="#8294ad"/><YAxis stroke="#8294ad" tickFormatter={valor=>shortMoney(Number(valor))}/><Tooltip contentStyle={tooltipStyle} labelFormatter={label=>nomeLinha(String(label))} formatter={(valor,nome)=>nome===tx.pipeline?[money(Number(valor)),nome]:[valor,nome]}/><Legend/><Bar dataKey="valor" name={tx.pipeline} fill="#34d399" radius={[7,7,0,0]}><LabelList dataKey="valor" position="top" fill="#6ee7b7" fontSize={12} formatter={valor=>shortMoney(Number(valor))}/></Bar></BarChart></ResponsiveContainer><div className="mt-3 grid grid-cols-3 gap-2">{linhasEmCurso.map(linha=><Mini key={linha.codigo} titulo={linha.codigo} valor={`${formatNumber(linha.negociacoes)} ${tx.deals} · ${shortMoney(linha.valor)}`}/>)}</div></>:<GraficoIndisponivel texto={tx.chartUnavailable}/>}</GraficoPainel></section>
  <section className="flex flex-col gap-2 rounded-2xl border border-[#13203f] bg-[#071226] px-5 py-4 text-xs text-slate-500 md:flex-row md:items-center md:justify-between"><span>{tx.historyCoverage}: {loadingHistorico?"...":linhasDisponiveis?`${formatNumber(cobertura,{maximumFractionDigits:1})}%`:"—"}.</span>{operacionalDisponivel?(semLinhaEmCurso>0?<span className="text-amber-300">{interp(tx.unclassified,{count:formatNumber(semLinhaEmCurso)})}</span>:<span className="text-emerald-300">{tx.allClassified}</span>):<span className="text-amber-300">{tx.reconnecting}</span>}</section>
 </div></section></main>
}

const tooltipStyle={backgroundColor:"#061126",border:"1px solid #24507a",borderRadius:"14px",color:"#fff"}
async function buscarJson<T>(url:string):Promise<T>{const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error(`${response.status} ${url}`);return response.json() as Promise<T>}
async function tentar<T>(executar:()=>Promise<T>,tentativas=1):Promise<T|null>{for(let tentativa=0;tentativa<tentativas;tentativa+=1){try{return await executar()}catch{if(tentativa+1<tentativas)await new Promise(resolve=>setTimeout(resolve,700))}}return null}
function normalizar(valor?:string|null){return String(valor||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[-_/]+/g," ").replace(/\s+/g," ").trim()}
function valorContexto(descricao:string|null|undefined,chave:string){const texto=String(descricao||""),match=texto.match(new RegExp(`(?:^|\\n)${chave}\\s*:\\s*([^\\n]+)`,"i"));return match?.[1]?.trim()||""}
function classificarLinha(item?:OportunidadeCRM){if(!item)return null;const linhaEstruturada=normalizar(item.linha_equipamentos),linhaContexto=normalizar(valorContexto(item.descricao,"linhas?")),linha=linhaEstruturada||linhaContexto;if(["TR","TRAILER","LINHA TRAILER"].includes(linha))return"TR";if(["DT","DIESEL TRUCK","LINHA DIESEL TRUCK"].includes(linha))return"DT";if(["DD","DIRECT DRIVE","LINHA DIRECT DRIVE"].includes(linha))return"DD";const equipamentoEstruturado=normalizar(item.equipamento),equipamentoContexto=normalizar(valorContexto(item.descricao,"equipamentos?")),equipamento=equipamentoEstruturado||equipamentoContexto;if(/\b(X4 7500|X4 7700|VECTOR 8500|VECTOR HE19|HE19)\b/.test(equipamento))return"TR";if(/\b(SUPRA 750|SUPRA 850|SUPRA 1150|A500)\b/.test(equipamento))return"DT";if(/\b(CM 280|CM280|CM 400|CM400|CM 500|CM500|CM 600|CM600|D6|D7|S8|S9|XARIOS 350|XARIOS 600)\b/.test(equipamento))return"DD";return null}
function drilldown(camada:"anfir"|"crm",titulo:string,subtitulo:string,queryString=""){const query=new URLSearchParams(queryString);query.set("camada",camada);query.set("titulo",titulo);query.set("subtitulo",subtitulo);return`/detalhamento?${query.toString()}`}
function nomeLinha(codigo:string){return LINHAS.find(linha=>linha.codigo===codigo)?.nome??codigo}
function abreviarMoeda(valor:number,locale:"pt-BR"|"en"|"es"){const prefix=locale==="en"?"R$":locale==="es"?"R$":"R$";if(Math.abs(valor)>=1_000_000)return`${prefix} ${(valor/1_000_000).toLocaleString(locale==="en"?"en-US":locale==="es"?"es-419":"pt-BR",{maximumFractionDigits:1})}M`;if(Math.abs(valor)>=1_000)return`${prefix} ${(valor/1_000).toLocaleString(locale==="en"?"en-US":locale==="es"?"es-419":"pt-BR",{maximumFractionDigits:0})}k`;return`${prefix} ${valor.toLocaleString(locale==="en"?"en-US":locale==="es"?"es-419":"pt-BR")}`}
function PainelTempo({titulo,subtitulo,destaque,children}:{titulo:string;subtitulo:string;destaque:string;children:React.ReactNode}){return <section className="rounded-3xl border border-[#13203f] bg-[#071427] p-5 sm:p-6"><div className="mb-5 flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">{titulo}</p><h2 className="mt-1 text-xl font-bold">{subtitulo}</h2></div><span className="shrink-0 rounded-full border border-[#24466f] px-3 py-1 text-xs text-slate-300">{destaque}</span></div>{children}</section>}
function Info({titulo,valor,href,click}:{titulo:string;valor:string;href?:string;click:string}){const body=<><p className="text-xs uppercase tracking-wide text-slate-500">{titulo}</p><p className="mt-1 text-sm font-semibold text-cyan-200">{valor}</p>{href&&<p className="mt-2 text-[11px] text-cyan-400">{click}</p>}</>;return href?<Link href={href} className="rounded-2xl border border-[#13203f] bg-[#071226] p-4 transition hover:border-cyan-500/70 hover:bg-[#0a1a31]">{body}</Link>:<div className="rounded-2xl border border-[#13203f] bg-[#071226] p-4">{body}</div>}
function Kpi({titulo,valor,href,click}:{titulo:string;valor:string|number;href?:string;click:string}){const body=<><p className="text-sm text-slate-400">{titulo}</p><p className="mt-2 text-2xl font-bold text-cyan-300">{valor}</p>{href&&<p className="mt-2 text-[11px] text-cyan-400">{click}</p>}</>;return href?<Link href={href} className="rounded-2xl border border-[#16325c] bg-[#091a33] p-4 transition hover:border-cyan-500/70 hover:bg-[#0b1d38]">{body}</Link>:<div className="rounded-2xl border border-[#16325c] bg-[#091a33] p-4">{body}</div>}
function GraficoPainel({titulo,subtitulo,children}:{titulo:string;subtitulo:string;children:React.ReactNode}){return <section className="rounded-3xl border border-[#13203f] bg-[#071427] p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-400">{titulo}</p><h2 className="mt-1 text-xl font-bold">{subtitulo}</h2><div className="mt-5 h-[300px]">{children}</div></section>}
function GraficoIndisponivel({texto}:{texto:string}){return <div className="grid h-full place-items-center rounded-2xl border border-dashed border-amber-700/60 bg-amber-950/10 px-6 text-center text-sm text-amber-200">{texto}</div>}
function Mini({titulo,valor}:{titulo:string;valor:string}){return <div className="rounded-xl border border-[#16325c] bg-[#091a33] p-3"><p className="text-xs font-bold text-cyan-300">{titulo}</p><p className="mt-1 text-xs text-slate-400">{valor}</p></div>}
