"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import Sidebar from "@/components/ui/Sidebar"
import Topbar from "@/components/ui/Topbar"
import { useStrategicI18n } from "@/core/i18n/strategic"
import { getHistoricoResumo, type HistoricoResumo, type RankingItem } from "@/services/modulos-api"

const source={file:"funil de vendas 2026(20260814-104652).xlsx",sha256:"54bb20087d96013e5a814a1d378f37315987c56b4a617631bd9603725ebb4583"}
export default function HistoricoComercialPage(){
 const {locale,t,formatNumber,formatCurrency}=useStrategicI18n(); const[resumo,setResumo]=useState<HistoricoResumo|null>(null),[loading,setLoading]=useState(true),[erro,setErro]=useState("")
 useEffect(()=>{let ativo=true;queueMicrotask(()=>{if(!ativo)return;getHistoricoResumo().then(r=>{if(ativo)setResumo(r)}).catch(e=>{if(ativo)setErro(e instanceof Error?e.message:t("history.loadError"))}).finally(()=>{if(ativo)setLoading(false)})});return()=>{ativo=false}},[t])
 const drill=(titulo:string,campo?:string,valor?:string)=>{const q=new URLSearchParams({camada:"historico",titulo,subtitulo:t("history.drillSub")});if(campo)q.set("campo",campo);if(valor)q.set("valor",valor);return `/detalhamento?${q.toString()}`}
 const money=(v:number)=>formatCurrency(v,{maximumFractionDigits:0}), nome=(key:string)=>t(key)
 return <main className="flex min-h-screen bg-[#020817] text-white"><Sidebar/><section className="min-w-0 flex-1 overflow-x-hidden"><Topbar/><div className="space-y-6 p-4 sm:p-6 lg:p-8"><header><div className="flex flex-wrap items-center gap-3"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400">{t("history.eyebrow")}</p><span className="rounded-full border border-amber-500/40 bg-amber-500/10 px-3 py-1 text-xs font-semibold text-amber-200">{t("history.readOnly")}</span></div><h1 className="mt-3 text-3xl font-bold">{t("history.title")}</h1><p className="mt-2 max-w-5xl text-sm text-slate-400">{t("history.subtitle")}</p></header>
 {erro&&<div className="rounded-xl border border-red-500/50 bg-red-950/20 p-4 text-red-200">{erro}</div>}{loading&&<div className="rounded-2xl border border-[#17304d] bg-[#071226] p-6 text-slate-400">{t("history.loading")}</div>}
 {!loading&&resumo&&<><section className="grid gap-3 sm:grid-cols-2 min-[1800px]:grid-cols-4"><Kpi title={t("common.records")} value={formatNumber(resumo.total_registros)} note={t("history.approvedSource")} href={drill(`${t("history.title")} · ${t("common.records")}`)}/><Kpi title={t("history.nominalUnits")} value={formatNumber(resumo.total_unidades)} note={t("history.auditMeasure")} href={drill(`${t("history.title")} · ${t("history.nominalUnits")}`)}/><Kpi title={t("history.nominalValue")} value={money(resumo.valor_nominal)} note={t("history.notRevenue")} href={drill(`${t("history.title")} · ${t("history.nominalValue")}`)}/><Kpi title={t("history.truthSource")} value={t("history.unique")} note={t("history.sameRecords")} tone="good"/></section>
 <section className="rounded-2xl border border-[#17304d] bg-[#071226] p-5"><div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center"><div className="min-w-0"><h2 className="text-lg font-semibold">{t("history.traceability")}</h2><p className="mt-2 break-words text-sm text-slate-400">{source.file}</p><p className="mt-1 break-all font-mono text-xs text-slate-500">SHA-256: {source.sha256}</p></div><Link href={drill(t("history.immutable",{count:formatNumber(resumo.total_registros)}))} className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-200 transition hover:border-emerald-400">{t("history.immutable",{count:formatNumber(resumo.total_registros)})}</Link></div></section>
 <section className="grid gap-5 xl:grid-cols-3"><Panel title={t("history.sheetOrigin")}><Rows items={resumo.abas} total={resumo.total_registros} campo="aba" titulo={t("history.sheetOrigin")} drill={drill} formatNumber={formatNumber} click={t("history.click")}/></Panel><Panel title={t("history.yearDistribution")}><Rows items={ordenarNome(resumo.anos,locale)} total={resumo.total_registros} campo="ano" titulo={t("history.yearDistribution")} drill={drill} formatNumber={formatNumber} click={t("history.click")}/></Panel><Panel title={t("history.salesChannel")}><Rows items={resumo.canais} total={resumo.total_registros} campo="canal" titulo={t("history.salesChannel")} drill={drill} formatNumber={formatNumber} click={t("history.click")}/></Panel></section>
 <section className="grid gap-5 xl:grid-cols-2"><Panel title={t("history.responsibility")}><Rows items={resumo.representantes} total={resumo.total_registros} campo="representante" titulo={t("history.responsibility")} drill={drill} formatNumber={formatNumber} click={t("history.click")}/><div className="mt-4 rounded-xl border border-cyan-500/30 bg-cyan-500/10 p-3 text-sm text-cyan-100">{t("history.authorship")}</div></Panel><Panel title={t("history.auditStatus")}><Rows items={resumo.status} total={resumo.total_registros} campo="status" titulo={t("history.auditStatus")} drill={drill} formatNumber={formatNumber} click={t("history.click")}/></Panel></section>
 <section className="grid gap-5 xl:grid-cols-2"><Panel title={t("history.topEquipment")}><Rows items={resumo.equipamentos} total={resumo.total_registros} campo="equipamento" titulo={t("history.topEquipment")} compact drill={drill} formatNumber={formatNumber} click={t("history.click")}/></Panel><Panel title={t("history.bodyBuilders")}><Rows items={resumo.implementadoras} total={somar(resumo.implementadoras)} campo="implementadora" titulo={t("history.bodyBuilders")} compact drill={drill} formatNumber={formatNumber} click={t("history.click")}/></Panel></section>
 <section className="grid gap-5 xl:grid-cols-2"><Panel title={t("history.lossReasons")}><Rows items={resumo.motivos_perda} total={somar(resumo.motivos_perda)} campo="motivo_perda" titulo={t("history.lossReasons")} drill={drill} formatNumber={formatNumber} click={t("history.click")}/></Panel><Panel title={t("history.rules")}>{["history.rule1","history.rule2","history.rule3","history.rule4","history.rule5","history.rule6","history.rule7"].map(k=><Checklist key={k} label={nome(k)}/>)}</Panel></section>
 <section className="rounded-2xl border border-cyan-500/30 bg-cyan-950/20 p-5"><h2 className="font-semibold text-cyan-100">{t("history.how")}</h2><p className="mt-2 text-sm text-cyan-100/80">{t("history.howText")}</p></section></>}</div></section></main>
}
function Kpi({title,value,note,tone,href}:{title:string;value:string;note:string;tone?:"good";href?:string}){const body=<><p className="text-xs uppercase tracking-wider text-slate-500">{title}</p><p className={`mt-2 break-words text-[clamp(1.5rem,2.35vw,1.875rem)] font-bold leading-tight ${tone==="good"?"text-emerald-300":"text-white"}`}>{value}</p><p className="mt-2 text-xs text-slate-500">{note}</p></>;return href?<Link href={href} className="min-w-0 rounded-2xl border border-[#17304d] bg-[#071226] p-5 transition hover:border-cyan-500/70 hover:bg-[#0a1a31]">{body}</Link>:<div className="min-w-0 rounded-2xl border border-[#17304d] bg-[#071226] p-5">{body}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="min-w-0 rounded-2xl border border-[#17304d] bg-[#071226] p-5"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section>}
function Rows({items,total,compact=false,campo,titulo,drill,formatNumber,click}:{items:RankingItem[];total:number;compact?:boolean;campo:string;titulo:string;drill:(t:string,c?:string,v?:string)=>string;formatNumber:(v:number,o?:Intl.NumberFormatOptions)=>string;click:string}){return <div className={compact?"grid gap-2 sm:grid-cols-2":"space-y-2"}>{items.map(item=>{const value=item.quantidade_registros,pct=total?value/total*100:0;return <Link href={drill(`${titulo} · ${item.nome}`,campo,item.nome)} key={item.nome} className="block min-w-0 rounded-xl border border-[#13203f] bg-[#08162d] p-3 transition hover:border-cyan-500/60 hover:bg-[#0b1d38]"><div className="flex items-center justify-between gap-3 text-sm"><span className="min-w-0 truncate text-slate-300">{item.nome}</span><strong className="text-cyan-200">{formatNumber(value)}</strong></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#13203f]"><div className="h-full rounded-full bg-cyan-400" style={{width:`${Math.max(2,Math.min(100,pct))}%`}}/></div><p className="mt-1 text-right text-[11px] text-slate-500">{formatNumber(pct,{maximumFractionDigits:1})}% · {click}</p></Link>})}</div>}
function Checklist({label}:{label:string}){return <div className="mb-2 flex items-center gap-3 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-3 text-sm text-emerald-100"><span className="text-emerald-400">✓</span><span>{label}</span></div>}
function somar(itens:RankingItem[]){return itens.reduce((total,item)=>total+item.quantidade_registros,0)}
function ordenarNome(itens:RankingItem[],locale:string){return [...itens].sort((a,b)=>a.nome.localeCompare(b.nome,locale))}
